class PB_TestDummy : Actor {
	override int TakeSpecialDamage(Actor inflictor, Actor source, int damage, Name damagetype) {
		console.printf("%i, type: "..damagetype, damage);
		TriggerPainChance(damagetype, true);
		return 0;
	}

	Default {
        //$Title Test Dummy
        //$Category Project Brutality
        //$Sprite PL4YA0
		Height 56;
		Radius 16;
		PainChance 256;
		+SHOOTABLE
		+SOLID
		+DONTTHRUST
	}
	
	States {
		Spawn:
			PL4Y A 10;
			Loop;
		Pain:
			PL4Y G 8;
			Goto Spawn;
	}
}