Class PB_RiotShieldGuy : PB_ShotgunGuyHelmet
{
	actor shieldActor;
	
	Default
	{
		//$Title Riot Shield Sergeant
		//$Category Project Brutality - Monsters/Former Humans/Sergeants
		//$Sprite RPSZA1
		DropItem "RiotShieldDrop";
		DropItem "PB_ShotgunGuyDrop2";
		PB_Monster.CanIRoll false;
		PB_Monster.CanIFallback false;
		Health 100;

		PB_Monster.TailPitch 0.8;
	}
	
	override void PostBeginPlay()
	{
		Super.PostBeginPlay(); // call the super function for virtual functions so we don't break shit if GZdoom update.
		SpawnShieldBox();
	}
		
	void SpawnShieldBox()
	{
		shieldActor = Spawn("RiotShieldPhysics");
		shieldActor.master = self;
	}
	
	void KillShieldBox()
	{
		if(shieldActor)
		{
			shieldActor.Destroy();
		}
	}
	
	override void Tick()
	{
		Super.Tick();
		
		// Update recognition if crouching
		if(IsInState (Self, "MissileContinue") || IsInState (Self,"DeployShield"))
			self.Height = 44;
		else {
			self.Height = 56;
			//Handle Hitbox system when monster is not shielded
			//HitboxerHandlerRiot();
		}
		
		if(shieldActor)
		{
			shieldActor.SetOrigin((Vec2Angle(20,angle),pos.z),false);
		}
	}
	
	override void Die(Actor source, Actor inflictor, int dmgflags, Name MeansOfDeath)
	{
		if(shieldActor) {
			shieldActor.Destroy();
		}
		Super.Die(source,inflictor,dmgflags,MeansOfDeath);
	}
	
	States
	{
		Death.Execution:
			TNT1 A 0 
			{
	// 			A_Stop;
				A_Stopsound();
				A_FaceTarget();
				A_NoBlocking(false);
			}
			RPSZ D 8;
			TNT1 A 0 A_Pain();
			RHGM C 21;
			TNT1 A 0 A_Recoil(4);
			Goto Death.SSG;
		
		Death.KillMe:
		Death.Taunt:
		Death.Avoid:
			TNT1 A 0;
			TNT1 A 0 {bTHRUACTORS = true;}
			TNT1 A 0 {bCOUNTKILL = false;}
			TNT1 A 0 A_SpawnItemEx ("PB_RiotShieldGuy",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION |SXF_TRANSFERSPECIAL| SXF_TRANSFERAMBUSHFLAG ,0);
			Stop;
		
		Spawn:
			RPSZ A 1;
			TNT1 A 0 {
				A_GiveInventory("ZombieManAmmo", random(1,4));
				A_GiveInventory("SKShotgunGuy", 1);
				A_GiveInventory("TypeSergeant", 1);
			}
		Stand:
			RPSZ A 8 A_Look();
			Loop;
		See:
			TNT1 A 0 {
				A_TakeInventory("SKShotgunGuy", 1);
				EnemyLastSighted = Level.MapTime;
			}
		SeeContinue:
			RPSZ A 1 A_SmartChase("Missile", "Melee", 0);
			RPSZ AA 1 A_SmartChase(null, null, CHF_DONTTURN);
			RPSZ A 1 A_SmartChase("Missile", "Melee", 0);
			RPSZ AA 1 A_SmartChase(null, null, CHF_DONTTURN);
			RPSZ B 1 A_SmartChase("Missile", "Melee", 0);
			RPSZ BB 1 A_SmartChase(null, null, CHF_DONTTURN);
			RPSZ B 1 A_SmartChase("Missile", "Melee", 0);
			RPSZ BB 1 A_SmartChase(null, null, CHF_DONTTURN);
			TNT1 A 0 A_StartSound("humans/step");
			RPSZ C 1 A_SmartChase("Missile", "Melee", 0);
			RPSZ CC 1 A_SmartChase(null, null, CHF_DONTTURN);
			RPSZ C 1 A_SmartChase("Missile", "Melee", 0);
			RPSZ CC 1 A_SmartChase(null, null, CHF_DONTTURN);
			RPSZ D 1 A_SmartChase("Missile", "Melee", 0);
			RPSZ DD 1 A_SmartChase(null, null, CHF_DONTTURN);
			RPSZ D 1 A_SmartChase("Missile", "Melee", 0);
			RPSZ DD 1 A_SmartChase(null, null, CHF_DONTTURN);
			TNT1 A 0 A_StartSound("humans/step");
			TNT1 A 0 A_JumpIf(CountInv("Wandering") == 71 && !OnPatrol,"LookAround");
			Loop;
		LookAround:
			TNT1 A 0 A_ClearTarget();
			TNT1 A 0 A_TakeInventory("Wandering", 71);
			TNT1 A 0 A_Jump(200, 2);
			TNT1 A 0 A_StartSound("monsters/zombie/searching", CHAN_AUTO);
			RPSZ AAAA 2 A_Look();
			Goto See;
		
		
		////////////////
		//Attack Logic// 
		////////////////
		Melee:
			TNT1 A 0 A_KillChildren("DestroyShield", 0 , "RiotShieldPhysics");
			RHGM A 4 A_FaceTarget();
			RHGM A 4;
			TNT1 A 0 {
				A_StartSound("skeleton/swing");
				A_CustomMeleeAttack(10, "AxeHit", "", "Normal");
			}
			//TNT1 A 0 A_SpawnProjectile("ZombieBashAttack",10,0,0,0);
			RHGM B 6 A_FaceTarget();
			TNT1 A 0 A_StartSound("barrel/pain");
			RHGM C 6;
			Goto See;
		DialogueCheck:
			TNT1 A 0 A_Jump(240, "MissileContinue");
			TNT1 A 0 A_CombatDialogueHandler();
			Goto MissileContinue;
		Missile:
			TNT1 A 0 A_JumpIfInTargetInventory("IsPlayer",1, "DialogueCheck");
			
		MissileContinue:
			TNT1 A 0 A_Jump(64,"Magdump");
			RPSZ E 4 A_FaceTarget();
			RPSZ F 2 BRIGHT {
				A_StartSound("revolver/fire",CHAN_WEAPON,pitch:frandom(0.95, 1.05));
				PB_DynamicTailMonster("pistol", "shotgun");
				A_SpawnProjectile("OrangeLensFlareAlt", 34, 10, 15, 0);
				A_SpawnProjectile("PB_MagnumBullet",28,10,random(-6,6),0,random(-4,4));
			}
			RPSZ E 4 {
				A_FaceTarget();
				A_GiveInventory("ZombieManAmmo", 1);
				return A_JumpIfInventory("ZombieManAmmo", 6, "Reload");
			}
			RPSZ E 4 A_FaceTarget();
			RPSZ F 2 BRIGHT {
				A_StartSound("revolver/fire",CHAN_WEAPON,pitch:frandom(0.95, 1.05));
				PB_DynamicTailMonster("pistol", "shotgun");
				A_SpawnProjectile("OrangeLensFlareAlt", 34, 10, 15, 0);
				A_SpawnProjectile("PB_MagnumBullet",28,10,random(-6,6),0,random(-4,4));
			}
			RPSZ E 4 {
				A_FaceTarget();
				A_GiveInventory("ZombieManAmmo", 1);
				return A_JumpIfInventory("ZombieManAmmo", 6, "Reload");
			}
			Goto See;
		Magdump:
			RPSZ E 4 A_FaceTarget();
			RPSZ F 2 BRIGHT {
				A_StartSound("revolver/fire",CHAN_WEAPON,pitch:frandom(0.95, 1.05));
				PB_DynamicTailMonster("pistol", "shotgun");
				A_SpawnProjectile("OrangeLensFlareAlt", 34, 10, 15, 0);
				A_SpawnProjectile("PB_MagnumBullet",28,10,random(-6,6),0,random(-4,4));
			}
			RPSZ E 4 {
				A_FaceTarget();
				A_GiveInventory("ZombieManAmmo", 1);
				return A_JumpIfInventory("ZombieManAmmo", 6, "Reload");
			}
			RPSZ E 4 A_FaceTarget();
		FanRevolver:
			RPSZ F 2 BRIGHT {
				A_StartSound("revolver/fire",CHAN_WEAPON,pitch:frandom(0.95, 1.05));
				PB_DynamicTailMonster("pistol", "shotgun");
				A_SpawnProjectile("OrangeLensFlareAlt", 34, 10, 15, 0);
				A_SpawnProjectile("PB_MagnumBullet",28,10,random(-9,9),0,random(-6,6));
			}
			RPSZ E 5 {
				A_FaceTarget();
				A_GiveInventory("ZombieManAmmo", 1);
				return A_JumpIfInventory("ZombieManAmmo", 6, "Reload");
			}
			Loop;
		Reload:
			RPSZ A 6 {
				A_StartSound("monsters/zombie/reload",CHAN_AUTO);
				A_TakeInventory("ZombieManAmmo", 6);
			}
			TNT1 A 0 A_StartSound("Weapons/Revolver/Open",10,CHANF_OVERLAP);
			RSP6 C 10 KillShieldBox();
			TNT1 A 0 {
				A_StartSound("Weapons/Revolver/Click2",10,CHANF_OVERLAP);
				A_SpawnProjectile("EmptyBrassMagnum",frandom(-5,5),0,0,-30);
				A_SpawnProjectile("EmptyBrassMagnum",frandom(-5,5),0,0,-30);
				A_SpawnProjectile("EmptyBrassMagnum",frandom(-5,5),0,0,-30);
				A_SpawnProjectile("EmptyBrassMagnum",frandom(-5,5),0,0,-30);
				A_SpawnProjectile("EmptyBrassMagnum",frandom(-5,5),0,0,-30);
				A_SpawnProjectile("EmptyBrassMagnum",frandom(-5,5),0,0,-30);
			}
			RSP6 A 4;
			RSP6 B 3;
			TNT1 A 0 A_StartSound("Weapons/Revolver/Load",10,CHANF_OVERLAP);
			RSP6 C 3;
			TNT1 A 0 A_StartSound("CYLNSPIN",10,CHANF_OVERLAP);
			RSP6 C 3;
			TNT1 A 0 A_StartSound("Weapons/Revolver/Close",10,CHANF_OVERLAP);
			RPSZ A 3 SpawnShieldBox();
			Goto See;
			
		
		////////////////
		//Pain Logic// 
		////////////////
		NormalKick:
			TNT1 A 0 A_JumpIfInventory ("IsDown", 1, "Pain");
			SPO4 U 1 {
					{bNODROPOFF = False;}
					{bFORCEXYBILLBOARD = True;}
					A_TakeInventory("SKShotgunGuy", 1);
					A_GiveInventory("IsDown", 1);
					A_Pain();
					A_facetarget();
					ThrustThingZ(0,30,0,1);
			}
			SPO4 U 2 A_facetarget();
			SPO4 U 1 A_Recoil(15);
			SPO4 UVWXY 3;
			Goto FallingAfterImpact;
			
		GetUp:
			TNT1 A 0 A_JumpIfInventory ("FallingHeight", 16, "FallingDie");
			TNT1 A 0 {
				A_TakeInventory("FallingHeight", 100);
				A_Stop();
				A_StartSound("BODYF",6);
			}
			ID11 SSSSSSSSS 5 A_JumpIf(Vel.Z < 0, "FallingAfterImpact");
			ID11 T 10 {
				A_FaceTarget();
				A_TakeInventory("IsDown", 1);
				A_TakeInventory("RiotShieldStop", 1);
				bFORCEXYBILLBOARD = false;
			}
			TNT1 A 0 A_JumpIfInTargetInventory("IsPlayer",1, "See");
			
			TNT1 A 0 A_StartSound("monsters/zombie/infight",CHAN_AUTO);
			Goto See;
		Pain.Melee:
		Pain.Kick:
		Pain.ExtremePunches:
		Pain.ExplosiveImpact:
		Pain.Explosive:
		Pain.DestroyShield:
			TNT1 A 0 A_JumpIfInventory ("RiotShieldStop", 1, "NormalKick");
			TNT1 A 0 KillShieldBox();
			TNT1 A 0 A_GiveInventory("RiotShieldStop", 1);
			RHGM C 1 A_FaceTarget();
			RHGM C 5 A_Pain();
			RHGM C 24;
			TNT1 A 0 {
				A_TakeInventory("RiotShieldStop", 1);
				SpawnShieldBox();
			}
			Goto See;
		Pain:
		Pain.Head:
		Pain.Avoid:
		Roll:
			TNT1 A 0 A_JumpIfInventory ("IsDown", 1, "Downed");
			TNT1 A 0 A_TakeInventory("RiotShieldStop", 1);
			RHGM C 1 A_FaceTarget();
			RPSZ D 6 A_Pain();
			TNT1 A 0 A_JumpIf(random(0,3) == 3 && target && CheckSight(target),"Missile");
		DeployShield:
			RPSZ G 8 A_FaceTarget();
			RPSZ G 8 A_FaceTarget();
			RPSZ G 8;
			Goto See;
		Possession:
			TNT1 A 0 A_SetInvulnerable();
			RPSZ A 3;
			RPSZ A 3 A_Pain();
			"####" "#" 35 ACS_NamedExecuteAlways("Pos - Flicker effect");
			TNT1 A 0 A_UnSetInvulnerable();
			Goto See;
		
	Pain.Stun:
		TNT1 A 0 A_SpawnItemEx ("StunElectrocute", random (-4, 4), random (-4, 4),  random (16, 32), 0, 0);
		RPSZ D 1 A_Pain();
		RPSZ DDDDDDDDDD 3 A_SpawnItemEx ("StunElectrocute", random (-12, 12), random (-12, 12),  random (16, 52), 0, 0);
		RPSZ D 1 A_Pain();
		RPSZ DDDDDDDDDD 3 A_SpawnItemEx ("StunElectrocute", random (-12, 12), random (-12, 12),  random (16, 52), 0, 0);
		RPSZ D 1 A_Pain();
		RPSZ DDDDDDDDDD 3 A_SpawnItemEx ("StunElectrocute", random (-12, 12), random (-12, 12),  random (16, 52), 0, 0);
		RPSZ D 1 A_Pain();
		RPSZ DDDDDDDDDD 3 A_SpawnItemEx ("StunElectrocute", random (-12, 12), random (-12, 12),  random (16, 52), 0, 0);
		RPSZ D 1 A_Pain();
		RPSZ DDDDDDDDDD 3 A_SpawnItemEx ("StunElectrocute", random (-12, 12), random (-12, 12),  random (16, 52), 0, 0);
		RPSZ D 1 A_Pain();
		Goto See;
	
	Pain.Siphon:
		TNT1 AAA 0 A_SpawnItemEx ("RedLightning_Small", random (-12, 12), random (-12, 12), random (16, 52), 0, 0);
		RPSZ D 1 
		{
			A_FaceTarget();
			A_GiveToTarget("HealthBonus",4);
		}
		RPSZ D 5 A_Pain();
		Goto See;

	Death.Ice:
	Death.IceExplosion:
	Death.Freeze:
	Death.Frost:
			TNT1 A 0 {
				bSHOOTABLE = false;
				bSOLID = false;
				A_SpawnItem("FrozenRiotShieldGuy");
			}
		Stop;
	
	Death.Fatality:
				TNT1 A 0 A_Pain();
				TNT1 A 0 A_NoBlocking();
				TNT1 A 0 A_JumpIfIntargetInventory("FistsSelected", 1, 1);
				Goto Death.ExplosiveImpact;
				TNT1 A 0 A_GiveToTarget("GoFatality", 1);
				TNT1 A 0 A_Jump(256,"Death.Fatality1");
				Goto Death.Fatality1;
	Death.Fatality1:
		TNT1 A 0 A_GiveToTarget("RiotSergeantFatality1", 1);
		Stop;
			
	}
}


class RiotShieldPhysics : Actor
{
	Default
	{
		Radius 20;
		Height 44;
		PainChance 256;
		RipLevelMin 1;
		+NODAMAGE
		+NOGRAVITY
		+SHOOTABLE
		+NOTELEPORT
		+NODAMAGETHRUST
		+NOBLOOD
	}
	States
	{
		Spawn:
			TNT1 A 1;
			Loop;
		Pain:
			TNT1 A 1 A_PlaySound ("barrel/pain");
			Goto Spawn;
		Pain.Plasma:
		Pain.Greenfire:
				TNT1 A 0 A_Playsound("Sparks/Spawn");
				TNT1 AA 1 BRIGHT A_SpawnItem("BlueFlare",0,43);
				TNT1 AAA 0 A_CustomMissile ("BigPlasmaParticleX", 30, 0, random (0, 360), 0, random (0, 360));
				TNT1 AAA 0 A_CustomMissile ("PlasmaParticleX", 48, 0, random (0, 360), 0, random (0, 360));
				TNT1 AAA 0 A_CustomMissile ("BigPlasmaParticleX", 42, 0, random (0, 360), 0, random (0, 360));
				TNT1 AAA 2 BRIGHT A_SpawnItem("BlueFlare",0,43);
		Pain.Kick:
		Pain.ExtremePunches:
			TNT1 A 0
			{
				if(master)
				{
					master.TriggerPainChance("DestroyShield",true);
				}
			}
			Stop;

	}
}
