Class PB_ShotgunGuyHelmet : PB_ShotgunGuy
{
		Default
		{
			//$Title Zombie Helmet Sergeant
			//$Category Project Brutality - Monsters/Former Humans/Sergeants
			//$Sprite SIV1A1
			damagefactor "Head", 0.6;
		}
		
		
		States
		{
		//Emergency manuever in case the monster gets killed by an "alerter" actor
		Death.KillMe:
		Death.Taunt:
		Death.Avoid:
			TNT1 A 0;
			TNT1 A 0 {bTHRUACTORS = true;}
			TNT1 A 0 {bCOUNTKILL = false;}
			TNT1 A 0 A_SpawnItemEx ("PB_ShotgunGuyHelmet",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION |SXF_TRANSFERSPECIAL| SXF_TRANSFERAMBUSHFLAG ,0);
			Stop;
		
		Spawn:
			SIV1 A 1;
			TNT1 A 0 {
				A_GiveInventory("SergeantAmmo", random(1,5));
				A_GiveInventory("SKShotgunGuy", 1);
				A_GiveInventory("TypeSergeant", 1);
			}
		Stand:
			SIV1 AABB 10 A_Look();
			TNT1 A 0 A_Jump(32, "Stand2");
			Loop;
		Stand2:
			SIV1 CADA 10 A_Look();
			Goto Stand;
		See:
			TNT1 A 0 {
				A_TakeInventory("SKShotgunGuy", 1);
				EnemyLastSighted = Level.MapTime;
			}
		SeeContinue:
			SMV1 AABB 2 A_SmartChase();
			TNT1 A 0 A_StartSound("humans/step");
			SMV1 CCDD 2 A_SmartChase();
			TNT1 A 0 A_StartSound("humans/step");
			TNT1 A 0 A_JumpIfInventory("Wandering",16,"LookAround");
			Loop;
		LookAround:
			TNT1 A 0 A_ClearTarget();
			TNT1 A 0 A_TakeInventory("Wandering", 36);
			TNT1 A 0 A_Jump(200, 2);
			TNT1 A 0 A_StartSound("monsters/zombie/searching", CHAN_AUTO);
			5HID ABACAD 10 A_Look();
			Goto See;
		FallBack:
			SMV1 D 4 {
				A_FaceTarget();
				A_Recoil(2);
				A_StartSound("humans/step",3);
				return A_Jump(64,"Missile");
			}
			SMV1 C 4 {
				A_FaceTarget();
				A_Recoil(2);
				return A_Jump(64,"Missile");
			}
			SMV1 B 4 {
				A_FaceTarget();
				A_Recoil(2);
				A_StartSound("humans/step",3);
				return A_Jump(64,"Missile");
			}
			SMV1 A 2 {
				A_FaceTarget();
				A_Recoil(2);
				return A_Jump(64,"Missile");
			}
			SMV1 D 4 {
				A_FaceTarget();
				A_Recoil(2);
				A_StartSound("humans/step",3);
				return A_Jump(64,"Missile");
			}
			SMV1 C 4 {
				A_FaceTarget();
				A_Recoil(2);
				return A_Jump(64,"Missile");
			}
			SMV1 B 4 {
				A_FaceTarget();
				A_Recoil(2);
				A_StartSound("humans/step",3);
				return A_Jump(64,"Missile");
			}
			SMV1 A 4 {
				A_FaceTarget();
				A_Recoil(2);
			}
			Goto Missile;
		
		////////////////
		//Attack Logic// 
		////////////////
		Melee:
			5HGM A 6 A_FaceTarget();
			TNT1 A 0 A_StartSound("skeleton/swing");
			TNT1 A 0 A_SpawnProjectile("ZombieBashAttack",10,0,0,0);
			5HGM B 6 A_FaceTarget();
			5HGM A 6;
			Goto See;
		DialogueCheck:
			TNT1 A 0 A_Jump(240, "MissileContinue");
			TNT1 A 0 A_CombatDialogueHandler();
			Goto MissileContinue;
		Missile:
			TNT1 A 0 A_JumpIfInTargetInventory("IsPlayer",1, "DialogueCheck");
			TNT1 A 0 A_JumpIfInTargetInventory("TargetIsAMarine",1, "DialogueCheck");
			Goto AttackHandler;
		MissileContinue:
			SSV1 E 5 {
				A_FaceTarget();
				return A_CheckLOF("AttackHandler");
				}
			Goto See;
		AttackHandler:
			TNT1 A 0 {
				A_FaceTarget();
				int chance = (random(1,256));
				
				if((chance > 232) && (CountInv("ZombieManGrenadeCount") < 3)) {return A_Jump(256, "Grenade");}
				if(chance > 192) {return A_Jump(256, "Attack3");}
				return A_Jump(256, "Attack1", "Attack2", "Attack4");
			}
			
		//Standard, 1 pump attack
		Attack1:
			SSV1 E 5 A_FaceTarget();
			SSV1 F 5 BRIGHT FireProjStanding;
			TNT1 A 0 A_StartSound("ShotgunDistantGunshot", 3);
			SSV1 E 1 {
				A_FaceTarget();
				A_GiveInventory("SergeantAmmo", 1);
				return A_JumpIfInventory("SergeantAmmo", 8, "Reload");
				}
			SSV1 C 5;
			SSV1 A 5 A_FaceTarget();
			SSV1 B 5 A_StartSound("weapons/sgmvpump", 2);
			TNT1 A 0 A_SpawnItem ("ShotCaseSpawn", 0, 30,0);
			SSV1 A 5 A_StartSound("weapons/sgpump", 3);
			SSV1 C 5;
			Goto See;
		
		// Two Pump Combo Attack
		Attack2:
			SSV1 E 5 A_FaceTarget();
			SSV1 F 5 BRIGHT FireProjStanding;
			TNT1 A 0 A_StartSound("ShotgunDistantGunshot", 3);
			SSV1 E 1 {
				A_FaceTarget();
				A_GiveInventory("SergeantAmmo", 1);
				return A_JumpIfInventory("SergeantAmmo", 8, "Reload");
				}
			SSV1 C 4;
			SSV1 A 5 A_FaceTarget();
			SSV1 B 5 A_StartSound("weapons/sgmvpump", 2);
			TNT1 A 0 A_SpawnItem ("ShotCaseSpawn", 0, 30,0);
			SSV1 A 5 A_StartSound("weapons/sgpump", 3);
			SSV1 C 4;
			SSV1 E 5 A_FaceTarget();
			SSV1 F 5 BRIGHT FireProjStanding;
			TNT1 A 0 A_StartSound("ShotgunDistantGunshot", 3);
			SSV1 E 1 {
				A_FaceTarget();
				A_GiveInventory("SergeantAmmo", 1);
				return A_JumpIfInventory("SergeantAmmo", 8, "Reload");
				}
			SSV1 C 4;
			SSV1 A 5 A_FaceTarget();
			SSV1 B 5 A_StartSound("weapons/sgmvpump", 2);
			TNT1 A 0 A_SpawnItem ("ShotCaseSpawn", 0, 30,0);
			SSV1 A 5 A_StartSound("weapons/sgpump", 3);
			SSV1 C 5;
			Goto See;
		
		// Aimed, Three Pump Combo
		Attack3:
			SZL2 A 5;
			SZL2 C 4 BRIGHT FireProjAimed;
			TNT1 A 0 A_StartSound("ShotgunDistantGunshot", 3);
			SZL2 A 4;
			SZL2 B 5 A_StartSound("weapons/sgmvpump", 2);
			TNT1 A 0 A_SpawnItem ("ShotCaseSpawn", 0, 35,0);
			SZL2 A 5 A_StartSound("weapons/sgpump", 3);
			SZL2 A 3 {
				A_FaceTarget();
				A_GiveInventory("SergeantAmmo", 1);
				return A_JumpIfInventory("SergeantAmmo", 8, "Reload");
			}
			SZL2 C 4 BRIGHT FireProjAimed;
			TNT1 A 0 A_StartSound("ShotgunDistantGunshot", 3);
			SZL2 A 4;
			SZL2 B 5 A_StartSound("weapons/sgmvpump", 2);
			TNT1 A 0 A_SpawnItem ("ShotCaseSpawn", 0, 35,0);
			SZL2 A 5 A_StartSound("weapons/sgpump", 3);
			SZL2 A 3 {
				A_FaceTarget();
				A_GiveInventory("SergeantAmmo", 1);
				return A_JumpIfInventory("SergeantAmmo", 8, "Reload");
			}
			SZL2 C 4 BRIGHT FireProjAimed;
			TNT1 A 0 A_StartSound("ShotgunDistantGunshot", 3);
			SZL2 A 4;
			SZL2 B 5 A_StartSound("weapons/sgmvpump", 2);
			TNT1 A 0 A_SpawnItem ("ShotCaseSpawn", 0, 35,0);
			SZL2 A 5 A_StartSound("weapons/sgpump", 3);
			SZL2 A 3 {
				A_FaceTarget();
				A_GiveInventory("SergeantAmmo", 1);
				return A_JumpIfInventory("SergeantAmmo", 8, "Reload");
			}
			Goto See;
		
		// Crouched, Standard Attack
		Attack4:
			SSV1 E 4 A_FaceTarget();
			Crouching:
			SP1C A 5 A_FaceTarget();
			TNT1 A 0 A_Jump(90 * !pb_disable_sergent_prone, "GoProne"); //has a 90 in 256 chance, but only if the pb_disable_sergent_prone cvar is unset
			SP1C B 5 BRIGHT FireProjCrouched;
			SP1C A 5 A_FaceTarget();
			DoneCrouching:
			SSV1 E 5 {
				A_FaceTarget();
				A_GiveInventory("SergeantAmmo", 1);
				return A_JumpIfInventory("SergeantAmmo", 8, "Reload");
			}
			SSV1 E 5 A_FaceTarget();
			SSV1 C 4;
			SSV1 A 5 A_FaceTarget();
			SSV1 B 5 A_StartSound("weapons/sgmvpump", 2);
			TNT1 A 0 A_SpawnItem ("ShotCaseSpawn", 0, 30,0);
			SSV1 A 5 A_StartSound("weapons/sgpump", 3);
			Goto See;
			
		GoProne:
			ZDE7 D 4 A_FaceTarget();
			TNT1 A 0 A_StartSound("BODYF",6);
		Prone:
			TNT1 A 0 A_GiveInventory("IsProning", 1);
			ZDE7 E 6 A_FaceTarget();
			ZDE7 F 5 BRIGHT FireProjProne;
			TNT1 A 0 A_StartSound("ShotgunDistantGunshot", 3);
			ZDE7 E 4 {
				A_FaceTarget();
				A_GiveInventory("SergeantAmmo", 1);
				return A_JumpIfInventory("SergeantAmmo", 8, "DoneProne");
			}
			ZDE7 G 5 {
				A_FaceTarget();
				A_StartSound("weapons/sgmvpump", 2);
			}
			TNT1 A 0 A_SpawnItem ("ShotCaseSpawn", 0, 5,0);
			ZDE7 E 5 {
				A_FaceTarget();
				A_StartSound("weapons/sgpump", 3);
			}
			ZDE7 F 5 BRIGHT FireProjProne;
			TNT1 A 0 A_StartSound("ShotgunDistantGunshot", 3);
			ZDE7 E 4 {
				A_FaceTarget();
				A_GiveInventory("SergeantAmmo", 1);
				return A_JumpIfInventory("SergeantAmmo", 8, "DoneProne");
			}
			ZDE7 G 5 {
				A_FaceTarget();
				A_StartSound("weapons/sgmvpump", 2);
			}
			TNT1 A 0 A_SpawnItem ("ShotCaseSpawn", 0, 5,0);
			ZDE7 E 5 {
				A_FaceTarget();
				A_StartSound("weapons/sgpump", 3);
			}
			ZDE7 F 5 BRIGHT FireProjProne;
			TNT1 A 0 A_StartSound("ShotgunDistantGunshot", 3);
			ZDE7 E 4 {
				A_FaceTarget();
				A_GiveInventory("SergeantAmmo", 1);
				return A_JumpIfInventory("SergeantAmmo", 8, "DoneProne");
			}
			ZDE7 G 5 {
				A_FaceTarget();
				A_StartSound("weapons/sgmvpump", 2);
			}
			TNT1 A 0 A_SpawnItem ("ShotCaseSpawn", 0, 5,0);
			ZDE7 E 5 {
				A_FaceTarget();
				A_StartSound("weapons/sgpump", 3);
			}
			ZDE7 C 4 A_FaceTarget();
		DoneProne:
			TNT1 A 0 {bNOPAIN = True;}
			TNT1 A 0 A_TakeInventory("IsProning", 1);
			ZDE7 D 4 A_FaceTarget();
			SP1C A 4 A_FaceTarget();
			SSV1 E 4 {
				A_FaceTarget();
				A_GiveInventory("SergeantAmmo", 1);
				bNOPAIN = False;
				return A_JumpIfInventory("SergeantAmmo", 8, "Reload");
			}
			Goto See;
			
		Grenade:
			TNT1 A 0 A_JumpIfCloser(500, 1);
			Goto Attack1;
			TNT1 A 0 A_JumpIfCloser(90, "Attack1");
		ThrowGrenade:
			TNT1 A 0 A_StartSound("monsters/zombie/special",CHAN_AUTO);
			SP0G A 6 {
				A_FaceTarget(90,45);
				A_StartSound("OPNGRN", 1);
			}
			SP0G BC 6 A_FaceTarget(90,45);
			SP0G D 6 {
				A_FaceTarget(90,45);
				A_DropAdjust("EnemyThrownGrenade","EnemyThrownGrenade",0,18,28);
				A_GiveInventory("ZombieManGrenadeCount", 1);
				A_StartSound("THRGRN", 1);
			}
			SP0G E 6;
			Goto See;
		
		Reload:
			TNT1 A 0 A_StartSound("monsters/zombie/reload",CHAN_AUTO);
			SSV1 ABC 5;
		Reloading:
			IDR2 EF 3;
			IDR2 G 3 {
				A_StartSound("insertshell");
				A_TakeInventory("SergeantAmmo", 1);
			}
			TNT1 A 0 A_JumpIfInventory("SergeantAmmo", 1, "Reloading");
			SSV1 A 8 A_StartSound("weapons/sgmvpump", CHAN_AUTO);
			SSV1 B 8 A_StartSound("weapons/sgpump", CHAN_AUTO);
			SSV1 AC 6;
			Goto See;
			
		
		////////////////
		//Pain Logic// 
		////////////////
		Pain.Melee:
			TNT1 A 0 A_JumpIfInventory ("SKShotgunGuy", 1, "StealthKill");
		Pain:
			TNT1 A 0 A_JumpIfInventory("IsProning",1, "PainProne");
			TNT1 A 0 A_JumpIfInventory ("IsDown", 1, "Downed");
			SPV1 A 6 A_Pain();
			TNT1 A 0 A_JumpIfInTargetInventory("IsPlayer",1, "See");
			TNT1 A 0 A_JumpIfInTargetInventory("TargetIsAMarine",1, "See");
			TNT1 A 0 A_Jump(180, "See");
			TNT1 A 0 A_StartSound("monsters/zombie/infight",CHAN_AUTO);
			Goto See;
		Pain.Head:
			TNT1 A 0 A_JumpIfInventory ("SKShotgunGuy", 1, "StealthKill");
			TNT1 A 0 A_JumpIfInventory("IsProning",1, "PainProne");
			TNT1 A 0 A_JumpIfInventory ("IsDown", 1, "Downed");
			SPV1 A 5 A_Pain();
			SPV1 BA 5; 
			TNT1 A 0 A_JumpIfInTargetInventory("IsPlayer",1, "See");
			TNT1 A 0 A_JumpIfInTargetInventory("TargetIsAMarine",1, "See");
			TNT1 A 0 A_Jump(180, "See");
			TNT1 A 0 A_StartSound("monsters/zombie/infight",CHAN_AUTO);
			Goto See;
		StealthKill:
			TNT1 A 0 A_TakeInventory("SKShotgunGuy", 1);
			SPV1 A 1 A_FaceTarget();
			TNT1 A 0 A_JumpIfInTargetInventory("FistsSelected", 1, 2);
			SPV1 A 1;
			Goto Pain;
			TNT1 A 0 A_GiveToTarget("GoFatality", 1);
			TNT1 A 0 A_GiveToTarget("SKShotgunGuy2", 1);
			TNT1 A 0 A_NoBlocking();
			TNT1 A 0 A_Die("Stealthy");
			TNT1 A 1;
			Stop;
			
		Death.Stealthy:
			TNT1 A 0;
			Stop;
		
		PainProne:
			TNT1 A 0 A_TakeInventory("IsProning", 1);
			ZDE7 C 6 A_Pain();
			ZDE7 C 2;
			Goto DoneProne;
			
        Downed:
			1D11 S 6 A_Pain();
			Goto GetUp;
		Pain.Kick:
		Pain.ExtremePunches:
			TNT1 A 0 A_TakeInventory("IsProning", 1);
			TNT1 A 0 A_JumpIfInventory ("IsDown", 1, "Pain");
			SP14 U 1 {
					{bNODROPOFF = False;}
					{bFORCEXYBILLBOARD = True;}
					A_TakeInventory("SKShotgunGuy", 1);
					A_GiveInventory("IsDown", 1);
					A_Pain();
					A_facetarget();
					ThrustThingZ(0,30,0,1);
			}
			SP14 U 2 A_facetarget();
			SP14 U 1 A_Recoil(15);
			SP14 VWX 3;
			SPO4 XY 3;
			Goto FallingAfterImpact;
		
		Pain.ExplosiveImpact:
		Pain.Explosive:
			TNT1 A 0 A_TakeInventory("IsProning", 1);
			TNT1 A 0 A_JumpIfInventory ("IsDown", 1, "Pain");
			SP14 U 1 {
					{bNODROPOFF = False;}
					{bFORCEXYBILLBOARD = True;}
					A_TakeInventory("SKShotgunGuy", 1);
					A_GiveInventory("IsDown", 1);
					A_Pain();
					ThrustThingZ(0,30,0,1);
			}
			SP14 U 2 A_facetarget();
			SP14 U 1 A_Recoil(5);
			SP14 VWX 3;
			SPO4 XY 3;
			Goto FallingAfterImpact;
		FallingAfterImpact:
			ID32 B 1 {
				A_GiveInventory ("FallingHeight", 1);
				A_CheckFloor ("GetUp");
			}
			NULL A 0 A_JumpIf (Vel.Z == 0, "GetUp");
			Loop;
		
		
		GetUp:
			TNT1 A 0 A_SpawnItem("LargeMassWaterImpact");
			TNT1 A 0 A_JumpIfInventory ("FallingHeight", 16, "FallingDie");
			TNT1 A 0 {
				A_TakeInventory("FallingHeight", 100);
				A_Stop();
				A_StartSound("BODYF",6);
			}
			1D11 SSSSSSSSS 5 A_JumpIf(Vel.Z < 0, "FallingAfterImpact");
			1D11 T 10 {
				A_FaceTarget();
				A_TakeInventory("IsDown", 1);
				bFORCEXYBILLBOARD = false;
			}
			TNT1 A 0 A_JumpIfInTargetInventory("IsPlayer",1, "See");
			TNT1 A 0 A_JumpIfInTargetInventory("TargetIsAMarine",1, "See");
			TNT1 A 0 A_StartSound("monsters/zombie/infight",CHAN_AUTO);
			Goto See;
		 
		FallingDie:
			TNT1 A 0 {
				bCOUNTKILL = false;
				bSHOOTABLE = false;
				A_SpawnItem("SplatteredSmall");
			}
			TNT1 A 0 A_JumpIfInventory ("FallingHeight", 32, "Death.Stomp");
			TNT1 A 0 A_JumpIfInventory ("FallingHeight", 25, "FallingSuperDeath");
			TNT1 A 0 A_JumpIfInventory ("FallingHeight", 16, "FallingDeath");
		FallingDeath:
			TNT1 A 0 {
				A_Scream();
				A_SpawnProjectile ("PB_XDeath1", 32, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH  , random (50, 130));
				A_SpawnProjectile ("PB_XDeath1", 32, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH  , random (50, 130));
				A_SpawnProjectile ("PB_XDeath1", 32, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH  , random (50, 130));
				A_SpawnProjectile ("PB_XDeath1", 32, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH  , random (50, 130));
				}
			ID11 E 2;
			ID11 F 2 {
				A_StartSound("BODYF",6);
				A_SpawnItem ("GrowingBloodPool");
				A_SpawnItem ("DeadShotgunguy1");
			}
			Stop;
		FallingSuperDeath:
			TNT1 A 0 A_XScream();
			Goto Death.ExplosiveImpact+1;
				
		Pain.Taunt:
			TNT1 A 0 A_TakeInventory("IsProning", 1);
			TNT1 A 0 A_JumpIfInventory("Enraged", 1, "Missile");
			SMV1 B 1 {
				A_Pain();
				bMISSILEMORE = true;
				bMISSILEEVENMORE = true;
				A_StartSound("grunt/sight");
				A_FaceTarget();
				A_GiveInventory("Enraged", 1);
				}
			SMV1 B 9;
			Goto Missile;
		Pain.Siphon:
			TNT1 A 0 A_TakeInventory("IsProning", 1);
			SPV1 A 1 {
				A_SpawnItemEx("RedLightning_Small", random (-12, 12), random (-12, 12), random (16, 52), 0, 0);
				A_SpawnItemEx("RedLightning_Small", random (-12, 12), random (-12, 12), random (16, 52), 0, 0);
				A_SpawnItemEx("RedLightning_Small", random (-12, 12), random (-12, 12), random (16, 52), 0, 0);
				A_FaceTarget();
				A_GiveToTarget("HealthBonus",4);
			}
			SPV1 A 5 {
				A_FaceTarget();
				A_Pain();
				}
			Goto See;
		Possession:
			TNT1 A 0 A_TakeInventory("IsProning", 1);
			SPV1 A 3 {
				A_SetInvulnerable();
				A_Pain();
				}
			"####" "#" 35 ACS_NamedExecuteAlways("Pos - Flicker effect");
			TNT1 A 0 A_UnSetInvulnerable();
			Goto See;
	
		Pain.Stun:
			TNT1 A 0 A_TakeInventory("IsProning", 1);
			SPV1 A 1 A_Pain();
			SPV1 AAAAAAAAAA 3 A_SpawnItemEx ("StunElectrocute", random (-12, 12), random (-12, 12),  random (16, 52), 0, 0);
			SPV1 A 1 A_Pain();
			SPV1 AAAAAAAAAA 3 A_SpawnItemEx ("StunElectrocute", random (-12, 12), random (-12, 12),  random (16, 52), 0, 0);
			SPV1 A 1 A_Pain();
			SPV1 AAAAAAAAAA 3 A_SpawnItemEx ("StunElectrocute", random (-12, 12), random (-12, 12),  random (16, 52), 0, 0);
			SPV1 A 1 A_Pain();
			SPV1 AAAAAAAAAA 3 A_SpawnItemEx ("StunElectrocute", random (-12, 12), random (-12, 12),  random (16, 52), 0, 0);
			SPV1 A 1 A_Pain();
			SPV1 AAAAAAAAAA 3 A_SpawnItemEx ("StunElectrocute", random (-12, 12), random (-12, 12),  random (16, 52), 0, 0);
			SPV1 A 1 A_Pain();
			Goto See;
			
		PlayerActionDialogue:
			TNT1 A 0 {
				if (A_JumpIfInTargetInventory("PlayerIsThrowingAGrenade",1, 1)) {
					A_StartSound("monsters/zombie/player_grenade", CHAN_AUTO);
				}
			}
			Goto Avoid;
		
		//New Evade Animation
		DiveLeft:
			SSV1 A 1 A_FaceTarget();
			SSV1 A 1 A_SetAngle(angle+90, SPF_INTERPOLATE);
			Goto DivingBegin;
		DiveRight:
			SSV1 A 1 A_FaceTarget();
			SSV1 A 1 A_SetAngle(angle-90, SPF_INTERPOLATE);
			Goto DivingBegin;
		DiveBack:
			SSV1 A 1 A_FaceTarget();
			SSV1 A 1 A_SetAngle(angle-180, SPF_INTERPOLATE);
			Goto DivingBegin;
		DiveFront:
			SSV1 A 1 A_FaceTarget();
			Goto DivingBegin;
		DivingBegin:
			ZDE7 A 5 A_SetAngle(angle, SPF_INTERPOLATE);
			TNT1 A 0 {
				ThrustThingZ(0,30,0,0);
				ThrustThing(angle, 15, 0, 0);
			}
			ZDE7 B 8 A_SetAngle(angle, SPF_INTERPOLATE);
		DivingLoop:
			ZDE7 B 1 A_CheckFloor ("DiveStop");
			ZDE7 B 1 A_JumpIf (Vel.Z == 0, "DiveStop");
			Loop;
		DiveStop:
			TNT1 A 0 A_StartSound("BODYF", CHAN_AUTO);
			ZDE7 C 25 A_Stop();
			ZDE7 D 6;
			SP1C A 6;
			SSV1 E 6;
			Goto Missile;
		
		//Avoid damage
		Pain.Avoid:
			TNT1 A 0 A_TakeInventory("IsProning", 1);
			TNT1 A 0 A_JumpIfInTargetInventory("IsPlayer",1, "PlayerActionDialogue");
		Avoid:
			TNT1 A 0 A_Jump(256, "DiveLeft", "DiveRight", "DiveLeft", "DiveRight", "DiveFront");
			Goto DiveFront;
			
	   //If the monster is hit by the "Killme" damage (which is "exploded" by the captured marine), automatically start firing at the target.
		Pain.KillMe:
			TNT1 A 0 A_TakeInventory("IsProning", 1);
			TNT1 A 0;
			Goto Missile;
					
		Death:
			TNT1 A 0 A_JumpIfInventory("IsProning",1, "DeathProne");
			TNT1 A 0 A_Jump(32, "Death.Arm");
			TNT1 A 0 A_Jump(132, "Death2", "Death3");
			S1V1 Q 5 A_Scream();
			S1V1 R 5;
			S1V1 T 5 A_NoBlocking();
			S1V1 VX 5;
			TNT1 A 0 A_SpawnItem ("GrowingBloodPool");
			TNT1 A 0 A_StartSound("BODYF",6);
			TNT1 A 0 A_SpawnItem ("DeadHelmetShotgunguy1");
			Stop;
			
		DeathProne:
			TNT1 A 0 A_Stop();
			TNT1 A 0 A_Scream();
			TNT1 A 0 A_NoBlocking();
			TNT1 A 0 A_SpawnItem ("GrowingBloodPool");
			TNT1 A 0 A_StartSound("BODYF",6);
			TNT1 A 0 A_SpawnItem ("DeadShotgunguyS2V1E");
			Stop;
		
		Death2:
			TNT1 A 0 A_Stop();
			S2V1 A 6 A_Scream();
			S2V1 B 6;
			S2V1 C 6 A_NoBlocking();
			S2V1 D 6;
			TNT1 A 0 A_SpawnItem ("GrowingBloodPool");
			TNT1 A 0 A_StartSound("BODYF",6);
			TNT1 A 0 A_SpawnItem ("DeadShotgunguyS2V1E");
			Stop;
			
		Death3:
			PS25 A 6 A_Scream();
			PS25 B 6;
			PS25 C 6 A_NoBlocking();
			PS25 D 6;
			TNT1 A 0 A_SpawnItem ("GrowingBloodPool");
			TNT1 A 0 A_StartSound("BODYF",6);
			TNT1 A 0 A_SpawnItem ("DeadShotgunGuyPS23");
			Stop;

		Death.Arm:
			TNT1 A 0 {
				A_SpawnProjectile ("PB_XDeathArm1", 35, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH  , random (0, 160));
				A_SpawnProjectile ("PB_SmallGib", 35, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH  , random (0, 160));
				A_SpawnProjectile ("PB_SmallGib", 35, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH  , random (0, 160));
				A_SpawnProjectile ("PB_MuchBlood2", 35, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH  , random (0, 160));
				A_NoBlocking();
				A_Scream();
				}
			HZD2 A 10;
			TNT1 A 0 A_SpawnItemEx ("DyingHelmetSergeant",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
			Stop;
			
        Death.Saw:
		Death.Cut:
			TNT1 A 0 A_Jump(132, "DeathSaw2");
			TNT1 O 0 A_NoBlocking();
			SXD2 AAABBBCCCDDD 1  A_SpawnProjectile ("Brutal_LiquidBlood2", random(28, 34), 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH  , random (30, 60));
			TNT1 A 0 A_SpawnProjectile ("PB_MuchBlood2", 35, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH  , random (0, 160));
			TNT1 A 0 A_SpawnProjectile ("XDeathHalfHelmetSergeant2", 30, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH  , random (0, 160));
			TNT1 AAAA 0 A_SpawnProjectile("PB_Intestine", 24, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH  , random (0, 160));
			TNT1 AAA 0 A_SpawnProjectile ("PB_XDeath1", 42, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH  , random (0, 160));
			TNT1 AAA 0 A_SpawnProjectile ("PB_SmallGib", 42, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH  , random (0, 160));
			TNT1 AAA 0 A_SpawnProjectile ("BloodMistBig", 40, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH  , random (30, 90));
			SXD1 E 6 A_XScream();
			SXD1 FGHI 6;
			TNT1 A 0 A_SpawnItem ("GrowingBloodPool");
			SXD1 IIIIIIIIIII 3 A_SpawnProjectile ("Brutal_LiquidBlood2", 26, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH  , random (30, 60));
			TNT1 A 0 A_SpawnItem("DeadShotgunguySXD1I");
			Stop;
			
		DeathSaw2:
			TNT1 O 0 A_NoBlocking();
			TNT1 AAAAA 0 A_SpawnProjectile ("BloodMistBig", 30, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH  , random (30, 90));
			TNT1 A 0 A_SpawnProjectile ("PB_XDeathHalfHelmetSergeant1", 30, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH  , random (0, 160));
			TNT1 AAAA 0 A_SpawnProjectile ("PB_XDeath1", 32, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH  , random (0, 160));
			TNT1 AAAA 0 A_SpawnProjectile ("PB_SmallGib", 32, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH  , random (0, 160));
			SZD1 EEEEEEEEEEEEEEE 1 {
				A_SpawnProjectile ("Brutal_LiquidBlood2", random(28, 34), 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH  , random (30, 60));
				A_SpawnItemEx("NashGoreBloodSpurt",
				frandom(-5, 5), frandom(-5, 5), frandom(30, 32),
				frandom(-2, 2), frandom(-2, 2), frandom(4, 8),
				frandom(0, 360));
			}
			SZD1 FGH 6;
			TNT1 A 0 A_SpawnItem ("GrowingBloodPool");
			TNT1 A 0 A_StartSound("BODYF",6);
			TNT1 A 0 A_SpawnItem ("DeadShotgunguyJustLegsAreLeft");
			Stop;
				
		 Death.cutless:
			TNT1 A 0 A_JumpIfInventory ("IsDown", 1, "Death.Down");
			TNT1 A 0 A_Jump(32, "Death.Saw");
			Goto Death.Minigun;
			
		 Death.Minigun:
			TNT1 A 0 A_FaceTarget();
			TNT1 A 0 A_Scream();
			TNT1 O 0 A_NoBlocking();
			TNT1 A 0 A_SpawnItem ("BrutalizedHelmetSergeant1", 1);
			Stop;
			
		 Death.LegMassacre:
			TNT1 A 0 A_SpawnProjectile ("PB_MuchBlood2", 15, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH  , random (0, 160));
			TNT1 A 0 A_Scream();
			TNT1 A 0 A_NoBlocking();
			TNT1 A 0 A_SpawnItem ("BrutalizedSergeantLeg");
			Stop;

		Death.Tear:
			TNT1 A 0 A_XScream();
			TNT1 O 0 A_NoBlocking();
			TNT1 A 0 A_SpawnProjectile ("PB_MuchBlood", 1, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH  , random (0, 160));
			SP2X AA 8;
			TNT1 AAAA 0 A_SpawnProjectile ("BloodMist", random (30, 40), 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH  , random (0, 160));
			TNT1 A 0 A_SpawnProjectile ("PB_XDeath4", 40, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH  , random (0, 160));
			TNT1 AAA 0 A_SpawnProjectile ("PB_SmallGib", 42, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH  , random (0, 160));
			TNT1 A 0 A_SpawnProjectile ("RipHelmetSergeant", 0, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH  , random (0, 160));
			SP2X BBBB 2 A_SpawnProjectile ("PB_SquirtingBloodTrail", 32, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH  , random (30, 60));
			SP2X CCCC 2 A_SpawnProjectile ("PB_SquirtingBloodTrail", 20, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH  , random (30, 60));
			SP2X DDDD 2 A_SpawnProjectile ("PB_SquirtingBloodTrail", 12, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH  , random (30, 60));
			TNT1 A 0 A_SpawnItem ("GrowingBloodPool");
			TNT1 A 0 A_StartSound("BODYF",6);
			SP2X EEEEEEEEEEEEEEEE 2 A_SpawnProjectile ("PB_SquirtingBloodTrail", 12, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH  , random (30, 60));
			TNT1 A 0 A_SpawnItem ("DeadShotgunguySP2XE");
			Stop;

		Death.Head:
			TNT1 A 0 A_FaceTarget();
			TNT1 A 0 A_JumpIfInTargetInventory("HasIncendiaryWeapon",1,"Death.Incinerate");
			TNT1 A 0 A_JumpIfInTargetInventory("HasPlasmaWeapon", 1, "Death.Plasma");
			TNT1 A 0 A_JumpIfInventory("IsProning",1, "DeathProneHead");
			TNT1 A 0 A_JumpIfInTargetInventory("HasCutingWeapon", 1, "Death.Decapitate");
			TNT1 A 0 A_JumpIfInTargetInventory("RandomHeadExploder", 1, "HeadExplode");
			TNT1 A 0 A_JumpIfHealthLower(-600, "HeavyHead");
			TNT1 A 0 A_JumpIfHealthLower(-90, "HeadExplode");
		HeadMinor:
			TNT1 A 0 A_StartSound("MinorHeadshot");
			TNT1 A 0 A_Jump (256, "DeathMinorhead1", "DeathMinorhead2", "DeathMinorhead3");
		DeathMinorHead1:
			TNT1 A 0 A_StartSound("MinorHeadshot", 0);
			TNT1 A 0 A_FaceTarget();
			TNT1 A 0 A_StartSound("misc/xdeath4");
			TNT1 A 0 A_Jump(32, "DeathMinorHead1_Long");
			TNT1 AAAA 0 A_SpawnProjectile ("PB_BloodMist", 50, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH  , random (0, 360));
			TNT1 AA 0 A_SpawnProjectile ("SmallBrainPiece", 50, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH  , random (0, 160));
			TNT1 A 0 A_SpawnProjectile ("XDeath1", 40, 0, random (100, 130), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH  , random (0, 160));
			TNT1 A 0 A_SpawnProjectile ("Brains3", 50, 0, random (90, 110), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH  , random (0, 160));
			TNT1 A 0 A_SpawnProjectile ("Brains5", 50, 0, random (100, 130), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH  , random (0, 160));
			14DG SSTTUU 2 A_SpawnProjectile ("PB_SquirtingBloodTrail", 40, 0, 120, 2, random (0, 60));
			14DG VVV 2 A_SpawnProjectile ("PB_SquirtingBloodTrail", 30, 0, 120, 2, random (60, 120));
			TNT1 A 0 A_NoBlocking();
			14DG XXXYYY 2 A_SpawnProjectile ("PB_SquirtingBloodTrail", 20, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH  , random (60, 120));
			TNT1 A 0 A_SpawnItem ("GrowingBloodPool");
			TNT1 A 0 A_StartSound("BODYF",6);
			TNT1 A 0 A_SpawnItem ("DeadHelmetShotgunguy14DGZ");
			Stop;
		DeathMinorHead1_Long:
			TNT1 A 0 A_NoBlocking();
			TNT1 A 0 A_SpawnItem("DyingHelmetShotgunguyHitInEye");
			Stop;
		DeathMinorHead2:
			TNT1 AAAA 0 A_SpawnProjectile ("PB_BloodMist", 50, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH  , random (0, 360));
			TNT1 AA 0 A_SpawnProjectile ("SmallBrainPiece", 50, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH  , random (0, 160));
			TNT1 A 0 A_SpawnProjectile ("XDeath1", 40, 0, random (100, 130), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH  , random (0, 160));
			TNT1 A 0 A_SpawnProjectile ("Brains3", 50, 0, random (90, 110), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH  , random (0, 160));
			TNT1 A 0 A_SpawnProjectile ("Brains5", 50, 0, random (100, 130), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH  , random (0, 160));
			14DG SSTT 2 A_SpawnProjectile ("PB_SquirtingBloodTrail", 40, 0, 120, 2, random (0, 60));
			TNT1 A 0 A_Jump(32, "DeathMinorHead2_Long");
			SP1S UUVVV 2 A_SpawnProjectile ("PB_SquirtingBloodTrail", 30, 0, 120, 2, random (60, 120));
			TNT1 A 0 A_NoBlocking();
			SP1S XXXYYY 2 A_SpawnProjectile ("PB_SquirtingBloodTrail", 20, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH  , random (60, 120));
			TNT1 A 0 A_SpawnItem ("GrowingBloodPool");
			TNT1 A 0 A_StartSound("BODYF",6);
			TNT1 A 0 A_SpawnItem ("DeadShotgunguySP1SZ");
			Stop;
		DeathMinorHead2_Long:
			TNT1 A 0 A_NoBlocking();
			TNT1 A 0 A_SpawnItem("DyingHelmetShotgunguyHitInEye2");
			Stop;
				
		DeathMinorhead3:
			TNT1 A 0 A_NoBlocking();
			SP2S A 5 A_SpawnProjectile ("PB_MuchBlood2", 40, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH  , random (0, 160));
			SP2S B 5;
			TNT1 A 0 A_SpawnProjectile ("Brains2", random (45, 55), random (5, -5), random (170, 190), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH  , random (-10, 10));
			TNT1 A 0 A_SpawnProjectile ("Brains4", random (45, 55), random (5, -5), random (170, 190), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH  , random (-10, 10));
			TNT1 A 0 A_SpawnProjectile ("SmallBrainPiece", 50, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH  , random (0, 160));
			TNT1 AAA 0 A_SpawnProjectile ("Teeth", 50, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH  , random (0, 160));
			TNT1 AAA 0 A_SpawnProjectile ("PB_SquirtingBloodTrail", 40, 0, 120, 2, random (0, 60));
			TNT1 A 0 A_SpawnProjectile ("SuperWallRedBlood", 46, 0, random (170, 190), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH  , random (0, 40));
			SP2S CDEF 5;
			TNT1 A 0 A_StartSound("BODYF",6);
			TNT1 A 0 A_SpawnItem ("GrowingBloodPool");
			TNT1 A 0 A_SpawnItem ("DeadShotgunguySP2SF");
			Stop;
		
		Death.Decapitate:
			TNT1 A 0 {
				A_Stop();
				A_FaceTarget();
				A_NoBlocking();
				A_SpawnProjectile ("XDeathHFQSZHead", 50, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH  , random (40, 90));
				A_SpawnProjectile ("PB_MuchBlood", 40, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH  , random (0, 160));
			}
			SPDH AAAAABBBBBBBBBBBBBBBBBCCCCC 2 {
				A_SpawnProjectile ("PB_SquirtingBloodTrail", 30, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH  , random (60, 120));
				A_SpawnItemEx("NashGoreBloodSpurt",
				frandom(-5, 5), frandom(-5, 5), frandom(30, 32),
				frandom(-2, 2), frandom(-2, 2), frandom(4, 8),
				frandom(0, 360));
			}
			TNT1 A 0 {
				A_SpawnItem("GrowingBloodPool");
				A_StartSound("BODYF",CHAN_AUTO);
			}
			SPDH DDDDEEEEEEEEEEEEEEEE 2 A_SpawnProjectile ("PB_SquirtingBloodTrail", 10, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH  , random (10, 40));
			TNT1 A 0 A_SpawnItem ("DeadShotgunguySPDHE");
			Stop;
				
		 Death.Leg:
			TNT1 A 0 A_JumpIfHealthLower(-120,"DoubleLegRemove");
			TNT1 A 0 {
				A_SpawnProjectile ("PB_MuchBlood2", 15, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH  , random (0, 160));
				A_SpawnProjectile ("PB_XDeath1", 15, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH  , random (0, 160));
				A_SpawnProjectile ("XDeathSargeLeg1", 35, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH  , random (0, 160));
				A_SpawnProjectile ("PB_SmallGib", 15, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH  , random (0, 160));
				A_SpawnProjectile ("PB_SmallGib", 15, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH  , random (0, 160));
				A_SpawnItem ("GrowingBloodPool");
				A_NoBlocking();
				A_Scream();
			}
			U6M5 AB 6;
			U6M5 C 6 ;
			TNT1 A 0 {
				A_StartSound("BODYF",6);
				A_SpawnItem("DyingHelmetSergeantLegBlewedOff");
				}
			Stop;
		DoubleLegRemove:
			TNT1 A 0 {
				A_Scream();
				A_NoBlocking();
				A_SpawnProjectile ("XDeathSargeLeg1", 15, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH  , random (0, 160));
				A_SpawnProjectile ("XDeathSargeLeg1", 15, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH  , random (0, 160));
				A_SpawnProjectile ("PB_XDeath1", 15, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH  , random (0, 160));
				A_SpawnProjectile ("PB_SmallGib", 15, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH  , random (0, 160));
				A_SpawnProjectile ("PB_SmallGib", 15, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH  , random (0, 160));
				A_SpawnProjectile ("PB_SmallGib", 15, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH  , random (0, 160));
				A_SpawnProjectile ("PB_XDeath1", 15, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH  , random (0, 160));
				ThrustThingZ(0,50,0,1);
			}
			PS27 ABC 3;
			PS24 D 4;
			TNT1 A 0 {
				A_SpawnItem ("GrowingBloodPool");
				A_StartSound("BODYF",6);
				A_SpawnItem ("DeadSergeant_NoLegBoth");
			}
			Stop;
			
		Death.Incinerate:
			TNT1 A 0 {
				A_Stop();
				A_NoBlocking();
				A_StartSound("MELT");
			}
			TNT1 AAAA 0 A_SpawnProjectile ("ExplosionParticleHeavy", 32, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH  , random (0, 360));
			TNT1 AAAA 0 A_SpawnProjectile ("ExplosionParticleVeryFast", 32, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH  , random (0, 360));
			TNT1 A 0 A_SpawnItemEx ("ExplosionFlareSpawner",0,0,32,0,0,0,0,SXF_NOCHECKPOSITION,0);
			TNT1 A 0 A_SpawnItemEx("TinyBurningPiece", random (-15, 15), random (-15, 15));
			TNT1 A 0 A_SpawnItemEx("TinyBurningPiece2", random (-35, 35), random (-35, 35));
			TNT1 A 0 A_SpawnItemEx("TinyBurningPiece3", random (-45, 45), random (-45, 35));
			TNT1 A 0 A_SpawnItemEx ("RealisticFireSparks1",random(-2,2),random(-2,2),32,0,0,0,0,SXF_NOCHECKPOSITION  ,0);
			Z8RN KKKKK 1 BRIGHT Light("IncinerationGlow") A_SpawnProjectile ("BurningEmberParticlesFloating_Bigger", 36, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH  , random (0, 160));
			TNT1 A 0 A_SpawnItemEx ("RealisticFireSparks1",random(-2,2),random(-2,2),28,0,0,0,0,SXF_NOCHECKPOSITION  ,0);
			Z8RN LLLLL 1 BRIGHT Light("IncinerationGlow") A_SpawnProjectile ("BurningEmberParticlesFloating_Bigger", 28, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH  , random (0, 160));
			TNT1 A 0 A_SpawnItemEx ("RealisticFireSparks1",random(-2,2),random(-2,2),24,0,0,0,0,SXF_NOCHECKPOSITION  ,0);
			Z8RN CCCCC 1 BRIGHT Light("IncinerationGlow") A_SpawnProjectile ("BurningEmberParticlesFloating_Bigger", 36, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH  , random (0, 160));
			TNT1 A 0 A_StartSound("SZZLL", 3);
			TNT1 A 0 A_SpawnItemEx ("RealisticFireSparks1",random(-2,2),random(-2,2),20,0,0,0,0,SXF_NOCHECKPOSITION  ,0);
			Z8RN DDDDD 1 BRIGHT Light("IncinerationGlow") A_SpawnProjectile ("BurningEmberParticlesFloating_Bigger", 20, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH  , random (0, 160));
			TNT1 A 0 A_SpawnItemEx ("RealisticFireSparks1",random(-2,2),random(-2,2),16,0,0,0,0,SXF_NOCHECKPOSITION  ,0);
			Z8RN EEEEE 1 BRIGHT Light("IncinerationGlow") A_SpawnProjectile ("BurningEmberParticlesFloating_Bigger", 12, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH  , random (0, 160));
			TNT1 A 0 A_SpawnItemEx ("RealisticFireSparks1",random(-2,2),random(-2,2),12,0,0,0,0,SXF_NOCHECKPOSITION  ,0);
			Z8RN FFFFF 1 BRIGHT Light("IncinerationGlow") A_SpawnProjectile ("BurningEmberParticlesFloating_Bigger", 10, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH  , random (0, 160));
			TNT1 A 0 A_SpawnItemEx ("RealisticFireSparks1",random(-2,2),random(-2,2),8,0,0,0,0,SXF_NOCHECKPOSITION  ,0);
			TNT1 A 0 A_SpawnItem("BarrelExplosionSmokeColumn");
			Z8RN GGGG 2 Light("IncinerationGlow");
			TNT1 A 0 A_SpawnItemEx ("RealisticFireSparks1",random(-2,2),random(-2,2),8,0,0,0,0,SXF_NOCHECKPOSITION  ,0);
			Z8RN HHHH 2 Light("IncinerationGlow") A_SpawnProjectile ("PlasmaSmoke", 14, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH  , random (0, 160));
			TNT1 A 0 A_SpawnItemEx ("RealisticFireSparks1",random(-2,2),random(-2,2),8,0,0,0,0,SXF_NOCHECKPOSITION  ,0);
			Z8RN HHHHHH 12 A_SpawnProjectile ("PlasmaSmoke", 14, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH  , random (0, 160));
			Z8RN H -1;
			Stop;
			
		Death.Shrink:
			TNT1 A 1 {
				A_StartSound("Shrink", 3);
				A_SpawnItemEx ("SergeantShrinkFX1", 0, 0,  5, 0, 0);
				}
			TNT1 A 1 A_SpawnItemEx ("SergeantShrinkFX1", 0, 0, 5, 0, 0);
			TNT1 A 1 A_SpawnItemEx ("SergeantShrinkFX3", 0, 0, 5, 0, 0);
			TNT1 A 1 A_SpawnItemEx ("SergeantShrinkFX4", 0, 0, 5, 0, 0);
			TNT1 A 1 A_SpawnItemEx ("SergeantShrinkFX5", 0, 0, 5, 0, 0);
			TNT1 A 1 A_SpawnItemEx ("SergeantShrinkFX6", 0, 0, 5, 0, 0);
			TNT1 A 1 A_SpawnItemEx ("SergeantShrinkFX7", 0, 0, 5, 0, 0);
			TNT1 A 1 A_SpawnItemEx ("LilSergeant", 1);
			stop;
			
		Death.Melee:
			TNT1 A 0 A_JumpIfInventory ("IsDown", 1, "Death.Down");
			TNT1 A 0 A_JumpIfInventory ("SKShotgunGuy", 1, "StealthKill");
        Death.Kick:
			TNT1 A 0 {
				bNODROPOFF = False;
				bSLIDESONWALLS = true;
				ThrustThingZ(0,30,0,1);
				A_Scream();
				A_NoBlocking();
				A_FaceTarget();
				A_Recoil (10);
			}
			S1V1 QRTVX 5;
			TNT1 A 0 A_StartSound("BODYF");
			TNT1 A 0 A_SpawnItem("DeadHelmetShotgunguy1");
			Stop;
		StealthKill:
			TNT1 A 0 A_JumpIfInTargetInventory("FistsSelected", 1, 1);
			Goto Death;
			TNT1 A 0 {
				A_GiveToTarget("GoFatality", 1);
				A_GiveToTarget("SKShotgunGuy2", 1);
				A_NoBlocking();
				A_Die("Stealthy");
			}
			Stop;
			
		Death.Shotgun:
			TNT1 A 0 A_Jump(42, "Death.Shotgunontheface");
			TNT1 A 0 A_JumpIfCloser(80, "Death.Blast");
			TNT1 A 0 A_JumpIfCloser(320, "Death.Shotgunontheface");
			Goto Death;
			
		Death.Shotgunontheface:	
			TNT1 A 0 {
				{bSLIDESONWALLS = True;}
				{bNOBLOCKMONST = True;}
			}
			TNT1 A 0 A_Jump(160, "DeathShotgunFly");
			
			S1V1 H 1 {
				A_FaceTarget();
				A_Stop();
				A_Pain();
				A_Recoil(13);
				ThrustThingZ(0,20,0,1);
				}
			TNT1 A 0 A_JumpIf(Vel.Y == 0, "DeathShotgunFly");
			TNT1 A 0 A_Jump(128, "DeathShotgunontheface2");
			TNT1 A 0 {
				A_Scream();
				A_SpawnProjectile ("PB_XDeath1", 35, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH  , random (0, 160));
				A_SpawnProjectile ("PB_XDeath1", 35, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH  , random (0, 160));
				A_NoBlocking();
				}
			SPV4 AAAABBBBCCCCDDDD 1 A_SpawnProjectile ("PB_SquirtingBloodTrail", 15, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH  , random (0, 40));
			SPV4 EFGHIJ 4 A_JumpIf((Vel.Y == 0), "DSFStop");
			Goto DSFStop;
		DSFStop:
			TNT1 A 0{
				A_Stop();
				A_SpawnItem ("GrowingBloodPool");
				A_SpawnProjectile ("PB_SuperWallRedBlood", 2, 0, random (170, 190), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH  , random (0, 0));
				A_StartSound("BODYF",6);
				A_SpawnItem("DeadShotgunguySPV4J");
				}
			Stop;
		DeathShotgunontheface2:	
			TNT1 A 0 {
				A_Scream();
				A_SpawnProjectile ("PB_XDeath1", 35, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH  , random (0, 160));
				A_SpawnProjectile ("PB_XDeath1", 35, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH  , random (0, 160));
				A_NoBlocking();
				}
			SPV4 KKKKLLLLMMMMNNNN 1 A_SpawnProjectile ("PB_SquirtingBloodTrail", 15, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH  , random (0, 40));
			SPV4 OPQRST 4 A_JumpIf((Vel.Y == 0), "DSFStop2");
			Goto DSFStop2;
			
		DSFStop2:
			TNT1 A 0 {
				A_Stop();
				A_SpawnItem ("GrowingBloodPool");
				A_SpawnProjectile ("PB_SuperWallRedBlood", 2, 0, random (170, 190), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH  , random (0, 0));
				A_StartSound("BODYF",6);
				A_SpawnItem("DeadShotgunguySPV4T");
			}
			Stop;
		
		
		DeathShotgunFly:
			TNT1 A 0 {
				{bNODROPOFF = False;}
				{bSLIDESONWALLS = True;}
				ThrustThingZ(0,30,0,1);
				A_Scream();
				A_NoBlocking();
				A_FaceTarget();
				A_Recoil (6);
			}
			SP14 U 5 A_SpawnProjectile ("PB_SquirtingBloodTrail", 15, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH  , random (0, 40));
			TNT1 A 0 A_JumpIf((Vel.Y == 0), "TakeASit");
			SP14 U 5 A_SpawnProjectile ("PB_SquirtingBloodTrail", 15, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH  , random (0, 40));
			TNT1 A 0 A_JumpIf((Vel.Y == 0), "TakeASit");
			SP14 V 5 A_SpawnProjectile ("PB_SquirtingBloodTrail", 15, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH  , random (0, 40));
			TNT1 A 0 A_JumpIf((Vel.Y == 0), "TakeASit");
			SP14 W 5 A_SpawnProjectile ("PB_SquirtingBloodTrail", 15, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH  , random (0, 40));
			SP14 X 5 A_SpawnProjectile ("PB_SquirtingBloodTrail", 15, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH  , random (0, 40));
			SPO4 XY 5 A_SpawnProjectile ("PB_SquirtingBloodTrail", 15, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH  , random (0, 40));
			TNT1 A 0 A_StartSound("BODYF",6);
			TNT1 A 0 A_SpawnItem("GrowingBloodPool");
			TNT1 A 0 A_SpawnItem("DeadHelmetShotgunguy1");
			Stop;
		TakeASit:
			TNT1 AAAA 0 A_SpawnProjectile ("PB_SuperWallRedBlood", 6, 0, random (170, 190), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH  , random (0, 40));
			TNT1 A 0 A_StartSound("BODYF",6);
			SP14 U 5;
			TNT1 A 0 A_SpawnItem("GrowingBloodPool");
			TNT1 A 0 A_SpawnItemEx("DeadHelmetShotgunguy_Slumped", 10);
			Stop;
	
		Death.Nailgun:
			TNT1 A 0 A_Jump(256,
				"Naildeath1", "Naildeath1",
				"Naildeath2", "Naildeath2",
				"NailDeath3", "NailDeath3",
				"Death.Blast", "Death.Blast2");
		Naildeath1:
			TNT1 A 0 {
				{bNODROPOFF = False;}
				{bSLIDESONWALLS = True;}
				ThrustThingZ(0,random(20,30),0,1);
				A_Scream();
				A_NoBlocking();
				A_FaceTarget();
				A_Recoil(30);
			}
			SP14 U 5 A_SpawnProjectile ("PB_SquirtingBloodTrail", 15, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH  , random (0, 40));
			TNT1 A 0 A_JumpIf((Vel.Y == 0), "PinToWall");
			SP14 U 5 A_SpawnProjectile ("PB_SquirtingBloodTrail", 15, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH  , random (0, 40));
			TNT1 A 0 A_JumpIf((Vel.Y == 0), "PinToWall");
			SP14 V 5 A_SpawnProjectile ("PB_SquirtingBloodTrail", 15, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH  , random (0, 40));
			TNT1 A 0 A_JumpIf((Vel.Y == 0), "PinToWall");
			SP14 W 5 A_SpawnProjectile ("PB_SquirtingBloodTrail", 15, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH  , random (0, 40));
			SP14 X 5 A_SpawnProjectile ("PB_SquirtingBloodTrail", 15, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH  , random (0, 40));
			SPO4 XY 5 A_SpawnProjectile ("PB_SquirtingBloodTrail", 15, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH  , random (0, 40));
			TNT1 A 0 A_StartSound("BODYF",6);
			TNT1 A 0 A_SpawnItem("GrowingBloodPool");
			TNT1 A 0 A_SpawnItem("DeadHelmetShotgunguy1");
			Stop;
		PinToWall:
			TNT1 A 0 A_SpawnProjectile ("PB_MuchBlood2", 35, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH  , random (0, 160));
			TNT1 AA 0 A_SpawnProjectile ("PB_XDeath1", 35, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH  , random (0, 160));
			TNT1 AAAA 0 A_SpawnProjectile ("PB_SuperWallRedBlood", 6, 0, random (170, 190), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH  , random (0, 40));
			TNT1 A 0 A_StartSound("Weapons/NailHitBleed");
			PIN7 A 5;
			TNT1 A 0 A_SpawnItem("GrowingBloodPool");
			TNT1 A 0 A_SpawnItemEx("PinnedHelmetShotgunguy", 10);
			Stop;
			
		Naildeath2:
			TNT1 A 0 A_XScream();
			TNT1 A 0 A_NoBlocking();
			TNT1 A 0 A_FaceTarget();
			TNT1 AAA 0 A_SpawnProjectile ("PB_Intestine", 32, 0, random (150, 210), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH  , random (0, 40));
			TNT1 AAA 0 A_SpawnProjectile ("PB_XDeath1", 32, 0, random (150, 210), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH  , random (0, 40));
			TNT1 AAA 0 A_SpawnProjectile ("PB_Xdeath3", 16, 0, random (170, 190), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH  , random (0, 40));
			TNT1 AA 0 A_SpawnProjectile ("PB_Xdeath2", 16, 0, random (130, 210), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH  , random (0, 40));
			TNT1 AAAA 0 A_SpawnProjectile ("NashGoreBloodSpurt", 32, 0, random (170, 190), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH  , random (0, 40));
			TNT1 AAAA 0 A_SpawnProjectile ("PB_SuperWallRedBlood", 32, 0, random (170, 190), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH  , random (0, 40));
			TNT1 AAAA 0 A_SpawnProjectile ("PB_BloodMistBig", 40, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH  , random (30, 90));
			TNT1 A 0 A_SpawnProjectile ("PinnedHelmetShotgunGuyTorso", 32, 0, 180, 2, random (-2, 2));
			
			SZD1 EEEEEEEEEEEEEEE 1 {
				A_SpawnProjectile ("Brutal_LiquidBlood2", random(28, 34), 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH  , random (30, 60));
				A_SpawnItemEx("NashGoreBloodSpurt",
				frandom(-5, 5), frandom(-5, 5), frandom(30, 32),
				frandom(-2, 2), frandom(-2, 2), frandom(4, 8),
				frandom(0, 360));
			}
			SZD1 FGH 6;
			TNT1 A 0 A_SpawnItem ("GrowingBloodPool");
			TNT1 A 0 A_StartSound("BODYF",6);
			TNT1 A 0 A_SpawnItem ("DeadShotgunguyJustLegsAreLeft");
			Stop;
			
		NailDeath3:
			TNT1 A 0 A_XScream();
			TNT1 A 0 A_NoBlocking();
			TNT1 A 0 A_FaceTarget();
			TNT1 AAA 0 A_SpawnProjectile ("PB_XDeath1", 32, 0, random (150, 210), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH  , random (0, 40));
			TNT1 AA 0 A_SpawnProjectile ("PB_Xdeath2", 16, 0, random (130, 210), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH  , random (0, 40));
			TNT1 AAAA 0 A_SpawnProjectile ("NashGoreBloodSpurt", 32, 0, random (170, 190), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH  , random (0, 40));
			TNT1 AAAA 0 A_SpawnProjectile ("PB_SuperWallRedBlood", 32, 0, random (170, 190), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH  , random (0, 40));
			TNT1 AAAA 0 A_SpawnProjectile ("PB_BloodMistBig", 40, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH  , random (30, 90));
			SP2X A 6;
			TNT1 A 0 A_SpawnProjectile ("PinnedHelmetShotgunGuyTorso2", 32, 0, 180, 2, random (-2, 2));
			SP2X BCD 6 A_SpawnProjectile ("PB_SquirtingBloodTrail", 30, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH  , random (0, 40));
			TNT1 A 0 A_SpawnItem ("GrowingBloodPool");
			TNT1 A 0 A_StartSound("BODYF",6);
			SP2X EEEEEEEEEEEEEEEEEEEE 2 A_SpawnProjectile("PB_SquirtingBloodTrail", 15, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH  , random (0, 90));
			TNT1 A 0 A_SpawnItem("DeadShotgunguySP2XE");
			Stop;
		
	Death.Railgun:
			TNT1 A 0 A_Jump(96, "Death.SSG");
		Death.Blast:
		TNT1 A 0 A_FaceTarget();
		TNT1 A 0 A_Jump(12, "Death.Arm");
		TNT1 A 0 A_NoBlocking();
		TNT1 A 0 A_Jump(128, "Death.Blast2");
		TNT1 A 0 {
			A_SpawnProjectile ("PB_Intestine", 32, 0, random (150, 210), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH  , random (0, 40));
			A_SpawnProjectile ("PB_Intestine", 32, 0, random (150, 210), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH  , random (0, 40));
			A_SpawnProjectile ("PB_Intestine", 32, 0, random (150, 210), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH  , random (0, 40));
			A_SpawnProjectile ("PB_XDeath1", 32, 0, random (150, 210), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH  , random (0, 40));
			A_SpawnProjectile ("PB_SmallGib", 32, 0, random (150, 210), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH  , random (0, 40));
			A_SpawnProjectile ("PB_XDeath1", 32, 0, random (150, 210), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH  , random (0, 40));
			A_SpawnProjectile ("PB_XDeath3", 16, 0, random (170, 190), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH  , random (0, 40));
			A_SpawnProjectile ("PB_SmallGib", 16, 0, random (170, 190), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH  , random (0, 40));
			A_SpawnProjectile ("PB_XDeath3", 16, 0, random (170, 190), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH  , random (0, 40));
			A_SpawnProjectile ("NashGoreBloodSpurt", 32, 0, random (170, 190), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH  , random (0, 40));
			A_SpawnProjectile ("NashGoreBloodSpurt", 32, 0, random (170, 190), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH  , random (0, 40));
			A_SpawnProjectile ("NashGoreBloodSpurt", 32, 0, random (170, 190), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH  , random (0, 40));
			A_SpawnProjectile ("NashGoreBloodSpurt", 32, 0, random (170, 190), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH  , random (0, 40));
			A_SpawnProjectile ("PB_SuperWallRedBlood", 32, 0, random (170, 190), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH  , random (0, 40));
			A_SpawnProjectile ("PB_SuperWallRedBlood", 32, 0, random (170, 190), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH  , random (0, 40));
			A_SpawnProjectile ("PB_SuperWallRedBlood", 32, 0, random (170, 190), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH  , random (0, 40));
			A_SpawnProjectile ("PB_SuperWallRedBlood", 32, 0, random (170, 190), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH  , random (0, 40));
			A_SpawnProjectile ("PB_BloodmistLarge", 40, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH  , random (30, 90));
			A_SpawnProjectile ("PB_BloodmistLarge", 40, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH  , random (30, 90));
			A_SpawnProjectile ("PB_BloodmistLarge", 40, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH  , random (30, 90));
			}
		Z1Z7 A 6 {
			A_Stop();
			A_SpawnItem ("GrowingBloodPool");
			}
		Z1Z7 BBBBBBBBBB 3 A_SpawnProjectile ("PB_SquirtingBloodTrail", 26, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH  , random (30, 60));
		Z1Z7 CCC 3 A_SpawnProjectile ("PB_SquirtingBloodTrail", 26, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH  , random (10, 40));
		Z1Z7 DD 3 A_SpawnProjectile ("PB_SquirtingBloodTrail", 6, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH  , random (30, 60));
		TNT1 A 0 A_StartSound("BODYF");
		TNT1 A 0 A_SpawnItem("DeadShotgunguyZ1Z7E");
	    Stop;
		
	Death.Blast2:
	    TNT1 A 0 {
			A_XScream();
			NashGoreGibs.SpawnGibs(self);
			A_SpawnProjectile ("PB_XDeathArm1", 42, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH  , random (0, 40));
			A_SpawnProjectile ("PB_Intestine", 32, 0, random (150, 210), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH  , random (0, 40));
			A_SpawnProjectile ("PB_Intestine", 32, 0, random (150, 210), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH  , random (0, 40));
			A_SpawnProjectile ("PB_Intestine", 32, 0, random (150, 210), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH  , random (0, 40));
			A_SpawnProjectile ("PB_XDeath1", 32, 0, random (150, 210), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH  , random (0, 40));
			A_SpawnProjectile ("PB_XDeath1", 32, 0, random (150, 210), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH  , random (0, 40));
			A_SpawnProjectile ("PB_SmallGib", 32, 0, random (150, 210), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH  , random (0, 40));
			A_SpawnProjectile ("PB_XDeath3", 16, 0, random (170, 190), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH  , random (0, 40));
			A_SpawnProjectile ("PB_SmallGib", 16, 0, random (170, 190), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH  , random (0, 40));
			A_SpawnProjectile ("PB_XDeath2", 16, 0, random (130, 210), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH  , random (0, 40));
			A_SpawnProjectile ("PB_SmallGib", 16, 0, random (130, 210), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH  , random (0, 40));
			A_SpawnProjectile ("NashGoreBloodSpurt", 32, 0, random (170, 190), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH  , random (0, 40));
			A_SpawnProjectile ("NashGoreBloodSpurt", 32, 0, random (170, 190), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH  , random (0, 40));
			A_SpawnProjectile ("NashGoreBloodSpurt", 32, 0, random (170, 190), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH  , random (0, 40));
			A_SpawnProjectile ("NashGoreBloodSpurt", 32, 0, random (170, 190), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH  , random (0, 40));
			A_SpawnProjectile ("PB_SuperWallRedBlood", 32, 0, random (170, 190), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH  , random (0, 40));
			A_SpawnProjectile ("PB_SuperWallRedBlood", 32, 0, random (170, 190), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH  , random (0, 40));
			A_SpawnProjectile ("PB_SuperWallRedBlood", 32, 0, random (170, 190), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH  , random (0, 40));
			A_SpawnProjectile ("PB_SuperWallRedBlood", 32, 0, random (170, 190), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH  , random (0, 40));
			A_SpawnProjectile ("PB_BloodmistLarge", 40, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH  , random (30, 90));
			A_SpawnProjectile ("PB_BloodmistLarge", 40, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH  , random (30, 90));
			A_SpawnProjectile ("PB_BloodmistLarge", 40, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH  , random (30, 90));
			A_SpawnProjectile ("PB_BloodmistLarge", 40, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH  , random (30, 90));
		}
		ZXZ6 A 6 {
			A_Stop();
			A_SpawnItem ("GrowingBloodPool");
			}
		ZXZ6 BBBBBBBBBBBBBBBBBBB 3 A_SpawnProjectile ("PB_SquirtingBloodTrail", 26, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH  , random (30, 60));
		ZXZ6 CCC 3 A_SpawnProjectile ("PB_SquirtingBloodTrail", 26, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH  , random (10, 40));
		ZXZ6 DD 3 A_SpawnProjectile ("PB_SquirtingBloodTrail", 6, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH  , random (30, 60));
		TNT1 A 0 {
			A_StartSound("BODYF");
			A_SpawnItem("DeadShotgunguyZXZ6E");
			}
	    Stop;
	
	Death.SSG:
	    ZZD1 E 1 {
				A_Recoil(-20);
				A_FaceTarget();
				NashGoreGibs.SpawnGibs(self);
				for (int i = 0; i < 5; i++) {	
					A_SpawnProjectile ("PB_BloodmistLarge", 32, 0, random (170, 190), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH  , random (0, 40));
					A_SpawnProjectile ("PB_SuperWallRedBlood", 32, 0, random (170, 190), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH  , random (0, 40));
				}
				
				A_SpawnProjectile ("PB_Intestine", 32, 0, random (150, 210), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH  , random (0, 40));
				A_SpawnProjectile ("PB_Intestine", 32, 0, random (150, 210), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH  , random (0, 40));
				A_SpawnProjectile ("PB_Intestine", 32, 0, random (150, 210), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH  , random (0, 40));
				A_SpawnProjectile ("PB_SuperWallRedBlood", 32, 0, random (170, 190), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH  , random (0, 40));
				A_SpawnProjectile ("PB_XDeathArm1", 32, 0, random (180, 190), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH  , random (0, 80));
				A_SpawnProjectile ("PB_XDeathArm1", 32, 0, random (160, 170), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH  , random (0, 80));
				A_SpawnProjectile ("XDeathHFQSZHead", 32, 0, random (170, 190), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH  , random (0, 80));
				A_XScream();
				A_NoBlocking();
			}
        SZD1 EEFFGH 6;
		SZD1 H 1 A_StartSound("BODYF");
		SZD1 HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH 2 {
			A_SpawnItemEx("PB_SquirtingBloodTrail", 
			0, 0, frandom(3, 4),
			frandom(-3, 3), frandom(-3, 3), frandom(3, 6),
			frandom(0.0, 360));
		}
		TNT1 A 0 {
			A_SpawnItem ("GrowingBloodPool");
			A_SpawnItem("DeadShotgunguyJustLegsAreLeft");
		}
        Stop;
		
	XDeath:
		TNT1 A 0 A_JumpIfInTargetInventory("SSGSelected", 1, "Death.SSG");
		TNT1 A 0 { 
			NashGoreGibs.SpawnGibs(self);
			A_SpawnProjectile ("PB_XDeath1", 42, 0, random (0, 290), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH  , random (10, 60));
			A_SpawnProjectile ("PB_XDeath3", 42, 0, random (0, 290), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH  , random (10, 60));
			A_SpawnProjectile ("PB_XDeath3", 42, 0, random (0, 290), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH  , random (10, 60));
			A_SpawnProjectile ("PB_XDeath3", 42, 0, random (0, 290), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH  , random (10, 60));
			A_SpawnProjectile ("PB_XDeath2", 42, 0, random (0, 190), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH  , random (10, 60));
			A_SpawnProjectile ("PB_XDeath4", 42, 0, random (0, 190), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH  , random (10, 60));
			}
		TNT1 AAAAAA 0 A_SpawnProjectile ("PB_BloodmistLarge", 40, 0, random (0, 360), 2, random (30, 90));
        TNT1 A 1 {
			A_SpawnItemEx("sargexdeath",0,0,2,Vel.X,Vel.Y,Vel.Z,angle,SXF_ABSOLUTEVELOCITY|SXF_ABSOLUTEANGLE|SXF_NOCHECKPOSITION,0);
			A_Recoil(2);
			A_XScream();
			A_NoBlocking();
		}
		Stop;
		
		Raise:
			SPOS KJIH 5;
			Goto See;
		
		Death.IceBeam:
			TNT1 A 0 {
				bSHOOTABLE = false;
				bSOLID = false;
				A_SpawnItem("FrozenHelmetShotgunGuy");
				A_SpawnItem("IceCrystalGround");
				A_SpawnItem("IceCrystalGround");
			}
			Stop;
		
		Death.Ice:
		Death.Freeze:
		Death.Frost:
			TNT1 A 0 {
				bSHOOTABLE = false;
				bSOLID = false;
				A_SpawnItem("FrozenHelmetShotgunguy");
			}
			Stop;
		
		Death.Fatality:
				TNT1 A 0 A_Pain();
				TNT1 A 0 A_NoBlocking();
				TNT1 A 0 A_JumpIfIntargetInventory("FistsSelected", 1, 1);
				Goto Death.ExplosiveImpact;
				TNT1 A 0 A_GiveToTarget("GoFatality", 1);
				TNT1 A 0 A_Jump(256,"Death.Fatality1", "Death.Fatality2", "Death.Fatality3");
				Goto Death.Fatality1;

		Death.Fatality1:
			TNT1 A 0 A_GiveToTarget("HelmetSergeantFatality1", 1);
			Stop;
		Death.Fatality2:
			TNT1 A 0 A_GiveToTarget("HelmetSergeantFatality2", 1);
			Stop;
		Death.Fatality3:
			TNT1 A 0 A_GiveToTarget("HelmetSergeantFatality3", 1);
			Stop;
			
		Death.HelperMarineFatallity:
			TNT1 A 1 {
				A_Pain();
				A_NoBlocking();
				A_GiveToTarget("SergeantFatality", 1);
			}
			Stop;
		
		
		Death.Eat:
			TNT1 A 0;
			TNT1 A 0 A_NoBlocking();
			TNT1 A 0 A_GiveToTarget("SergeantFatality",1);
			Stop;
			
		 Crush:
		 Death.Crush:
		 Death.Crusher:
			TNT1 A 0 A_NoBlocking();
			SPOS IJK 2;
			TNT1 A 1 A_XScream();
			TNT1 A 0 {
				NashGoreGibs.SpawnGibs(self);
			}
			TNT1 AAAAAAAAAAAAAAAAAAAAAAAAA 0 A_SpawnProjectile ("PB_SquirtingBloodTrail", 0, 0, random (0, 360), 2, random (0, 360));
			TNT1 AAAAAA 0 bright A_SpawnProjectile ("PB_XDeath1", 5, 0, random (0, 360), 2, random (30, 180));
			TNT1 AA 0 bright A_SpawnProjectile ("PB_SmallGib", 55, 0, random (0, 360), 2, random (30, 180));
			TNT1 AAA 0 A_SpawnItemEx("NashGoreSquishyGibs", flags: SXF_TRANSFERTRANSLATION);
			TNT1 A 0 A_SpawnItem ("PB_CrushedRemains");
			Stop;
			
		
		 Death.Stomp:
		//	TNT1 A 0 A_Scream();
			TNT1 A 0 A_NoBlocking();
			//POSS IJK 2;
			TNT1 A 1 A_XScream();
			TNT1 A 0 {
				NashGoreGibs.SpawnGibs(self);
			}
			TNT1 AAAAAAAAAAAAAAAAAAAAAAAAA 0 A_SpawnProjectile ("PB_SquirtingBloodTrail", 0, 0, random (0, 360), 2, random (0, 360));
			TNT1 AAAAAA 0 bright A_SpawnProjectile ("PB_XDeath1", 5, 0, random (0, 360), 2, random (30, 180));
			TNT1 AAAAA 0 bright A_SpawnProjectile ("PB_SmallGib", 55, 0, random (0, 360), 2, random (30, 180));
			TNT1 A 0 A_SpawnItem ("PB_CrushedRemains");
			Stop;
			
		Death.BHFT:
		Death.RVFT:
			TNT1 A 1 {
				A_Pain();
				A_Scream();
				A_NoBlocking();
				A_GiveToTarget("SergeantFatality", 1);
			}
			Stop;
	}
}
