class PB_GibBase : Actor 
{
	Default 
	{
		Radius 10;
		Height 10;
		//+CLIENTSIDEONLY;
		+NOTELEPORT;
		+MOVEWITHSECTOR;
		+DONTSPLASH;
		+NOBLOCKMONST;
		-NOBLOCKMAP
		+GHOST;
		+THRUACTORS;
		+FLOORCLIP;
		+SLIDESONWALLS;
		+FORCEXYBILLBOARD;
		+NOTAUTOAIMED;
		-SOLID;
		+SHOOTABLE;
		DamageFactor "CauseObjectsToSplash", 0.0;
		DamageFactor "GibRemoving", 0.5;
		damagefactor "Crush", 50.0;
		damagefactor "Shrapnel", 100.0;
		damagefactor "Plasma", 20.0;
		damagefactor "Fire", 0.0;
		damagefactor "TeleportRemover", 1000.0;
		damagefactor "Blood", 0.0; 
		damagefactor "GreenBlood", 0.0; 
		damagefactor "BlueBlood", 0.0; 
		damagefactor "Taunt", 0.0; 
		damagefactor "KillMe", 0.0;
		damagefactor "Avoid", 0.0; 
		damagefactor "Taunt", 0.0;
		damagefactor "Trample", 5000.0;
		painchance 255;
		Mass 1000;
		Health 100;
		BloodType "NashGoreBlood", "NashGoreBlood", "NashGoreBlood";
	}
	
	override void BeginPlay(void)
	{
		ChangeStatNum(STAT_NashGore_Gore);
		NashGoreStatics.QueueGore();
		NashGoreStatics.RandomXFlip(self);
		Super.BeginPlay();
	}

	override void PostBeginPlay(void)
	{
		if (random() < (255 - nashgore_gibamount)) { Destroy(); return; }
		Super.PostBeginPlay();
	}

	override void Tick(void)
	{
		Super.Tick();
		if (!bNoTimeFreeze && (isFrozen() || Level.isFrozen())) return;
		if (NashGoreStatics.CheckSky(self)) { Destroy(); return; }
	}
	
    States
    {
		Spawn:
			TNT1 A 0 A_SpawnItem("NashGoreBloodSpot",0,0,0,1);
			Stop;
		Death:
			TNT1 AAAAAAA 0 A_SpawnProjectile ("PB_XDeathSkinPiece2", 5, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH, random (0, 160));
			TNT1 AAAA 0 A_SpawnProjectile ("PB_XDeathSkinPiece1", 5, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH, random (0, 160));
			TNT1 AAAA 0 A_SpawnProjectile ("PB_SmallGib", 10, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH, random (10, 170));
			TNT1 AA 0 A_SpawnProjectile ("NashGoreBlood", 10, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH, random (30, 90));
			TNT1 AA 0 A_SpawnProjectile ("PB_XDeath1", 0, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH, random (0, 160));
			Stop;
		Death.plasma:
			TNT1 A 0;
			TNT1 A 0 A_XScream();
			TNT1 A 0 A_NoBlocking();
			TNT1 AAA 0 A_SpawnProjectile ("NashGoreBloodParticle_Large", 50, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH, random (0, 160));
			TNT1 A 0 A_SpawnProjectile ("PB_XDeathBurnedMeat", 32, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH, random (0, 160));
			TNT1 A 0 A_SpawnProjectile ("PB_XDeathBurnedMeat3", 32, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH, random (0, 160));
			EXPL AAA 0 A_SpawnProjectile ("ExplosionSmoke", 32, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH, random (0, 360));
			TNT1 A 0;
			Stop;
		Death.Trample:
		Death.Crush:
		Death.Stomp:
		Death.SuperPunch:
		Death.ExtremePunches:
			 TNT1 AAA 0 A_SpawnProjectile ("PB_XDeath1", 5, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH, random (0, 30));
			 TNT1 AAAA 0 A_SpawnProjectile ("NashGoreBlood", 5, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH, random (0, 30));
			 TNT1 AAAAAAA 0 A_SpawnProjectile ("PB_XDeathSkinPiece2", 5, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH, random (10, 30));
			 TNT1 AAAA 0 A_SpawnProjectile ("PB_XDeathSkinPiece1", 5, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH, random (10, 130));
			 TNT1 AAAA 0 A_SpawnProjectile ("PB_SmallGib", 10, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH, random (10, 30));
			 XME2 L 1;
			 XME2 L -1;
			 Stop;
		Death.GibRemoving:
		Death.TeleportRemover:
			TNT1 A 0 {
				bNOCLIP = True;
				bSHOOTABLE = False;
				A_ChangeLinkFlags(True);
				A_NoBlocking();
			}
			Stop;	 
		Death.Disintegrate:
			TNT1 A 0;
			TNT1 AAAA 0 A_SpawnProjectile ("NashGoreClassicBloodTrail", 0, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH, random (0, 90));
			TNT1 AA 0 A_SpawnProjectile ("PB_XDeath1", 0, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH, random (0, 160));
			TNT1 AA 0 A_SpawnProjectile ("NashGoreBlood", 10, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH, random (30, 90));
			Stop;
		
    }
}

class PB_TinyGibBase : Actor
{
	Default
	{
		Radius 2;
		Height 8;
		Speed 6;
		Mass 1;
		gravity 0.5;
		Scale 0.8;
		Decal "BrutalBloodSplat";
		+MOVEWITHSECTOR;
		//+CLIENTSIDEONLY;
		+NOBLOCKMAP;
		+NOTELEPORT;
		+MISSILE;
		+FORCEXYBILLBOARD;
		+DONTSPLASH;
		+NOBLOCKMONST;
		seesound "nashgore/gibsmall";
		deathsound "nashgore/gibsmall";
		BloodType "NashGoreBlood", "NashGoreBlood", "NashGoreBlood";
	}
	
	override void BeginPlay(void)
	{
		ChangeStatNum(STAT_NashGore_Gore);
		NashGoreStatics.QueueGore();
		NashGoreStatics.RandomXFlip(self);
		Super.BeginPlay();
	}

	override void PostBeginPlay(void)
	{
		if (random() < (255 - nashgore_gibamount)) { Destroy(); return; }
		Super.PostBeginPlay();
	}

	override void Tick(void)
	{
		Super.Tick();
		if (!bNoTimeFreeze && (isFrozen() || Level.isFrozen())) return;
		if (NashGoreStatics.CheckSky(self)) { Destroy(); return; }
	}
	
    States
    {
    Spawn:
        TNT1 A 1;
		Loop;
    }
}

class PB_LimbBase: PB_GibBase
{   
	Default
	{
		Radius 6;
		Height 10;
		Mass 1000;
		Painchance 256;
		Health 35;
		+FORCEXYBILLBOARD;
		+DONTSPLASH;
		+SHOOTABLE;
		+NOBLOCKMONST;
		+THRUACTORS;
		+FLOORCLIP;
		BloodType "NashGoreBlood", "NashGoreBlood", "NashGoreBlood";
		damagefactor "Crush", 50.0;
		DeathSound "misc/xdeath4";
		damagefactor "Blood", 0.0;
		damagefactor "GreenBlood", 0.0;
		damagefactor "BlueBlood", 0.0;
		damagefactor "Taunt", 0.0;
		damagefactor "KillMe", 0.0;
		damagefactor "Avoid", 0.0;
		damagefactor "Taunt", 0.0;
		damagefactor "Trample", 2.0;
		damagefactor "Kick", 9.0;
		damagefactor "Explosive", 0.1;
		damagefactor "ExplosiveImpact", 9.1;
		damagefactor "Shrapnel", 100.0;
		damagefactor "Melee", 9.0;
		damagefactor "SuperPunch", 9.0;
		damagefactor "Plasma", 20.0;
		painchance 255;
	}
	States    
	{
		Spawn:
			TNT1 A 1900 A_SpawnItem("NashGoreBloodSpot",0,0,0,1);
			Loop ;
		Death:
			TNT1 AAAAAAA 0 A_SpawnProjectile ("NashGoreClassicBloodTrail", 0, 0, random (0, 180), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH, random (0, 180));
			TNT1 A 0 A_SpawnItem("NashGoreBloodSpot",0,0,0,1);
			XDT3 BCDEFGH 3;
			Stop;
		Death.Crush:
			 TNT1 A 1 A_SpawnProjectile ("PB_XDeath1", 5, 5, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH, random (0, 160));
			 TNT1 A 0 A_SpawnProjectile ("PB_XDeath2", 5, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH, random (0, 160));
			 TNT1 A 0 A_SpawnProjectile ("PB_XDeath3", 5, -5, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH, random (0, 160));
			 CRSB A 9009;
			 Stop;
	}
}


class FlyingGibBase : PB_LimbBase
{}

class PB_XDeath1 : Actor
{
	Default
	{
		Radius 8;
		Height 8;
		Speed 10;
		Scale 1.2;
		Mass 1;
		+NOBLOCKMAP;
		+MISSILE;
		+NOTELEPORT;
		+MOVEWITHSECTOR;
		//+CLIENTSIDEONLY;
		+RIPPER;
		+BLOODLESSIMPACT ;
		-DONTSPLASH;
		+THRUGHOST;
		+THRUACTORS;
		+FLOORCLIP;
		damagetype "Blood";
		SeeSound "misc/xdeath4";
		DeathSound "misc/xdeath1";
		Decal "BrutalBloodSuper";
	}
	
	
	override void BeginPlay(void)
	{
		ChangeStatNum(STAT_NashGore_Gore);
		NashGoreStatics.QueueGore();
		NashGoreStatics.RandomXFlip(self);
		Super.BeginPlay();
	}

	override void PostBeginPlay(void)
	{
		if (random() < (255 - nashgore_gibamount)) { Destroy(); return; }
		Super.PostBeginPlay();
	}

	override void Tick(void)
	{
		Super.Tick();
		if (!bNoTimeFreeze && (isFrozen() || Level.isFrozen())) return;
		if (NashGoreStatics.CheckSky(self)) { Destroy(); return; }
	}
	
    States
    {
		Spawn:
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Underwater");
			BLOD A 4 A_SpawnProjectile ("NashGoreClassicBloodTrail", 0, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH, random (0, 360));
			Loop;
		Death:
			TNT1 A 0 A_SpawnItem ("NashGoreBloodSpot", 0, 1);
			
			XDT1 EF 3;			
			XDT1 GHIJKL 3;
			
			Stop;
		 Underwater:
		 Splash:
			TNT1 A 0 ThrustThingZ (0,35,1,0);
			XDT1 AB 3 A_SpawnProjectile ("NashGoreClassicBloodTrail", 0, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH, random (0, 360));
			TNT1 A 0 ThrustThingZ (0,35,1,0);
			XDT1 CD 3 A_SpawnProjectile ("NashGoreClassicBloodTrail", 0, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH, random (0, 360));
			Loop;
			
		IsOverLiquid:
		SpawnOnWater:
			TNT1 A 1 A_SpawnItem ("WaterBloodSpot", 5);
			Stop;
    }
}


class PB_XDeath2: PB_XDeath1
{
	Default
	{
		Speed 10;
		Gravity 0.4;
		Scale 1.1;
		DeathSound "misc/xdeath2";
		Decal "BrutalBloodSuper";
		//+CLIENTSIDEONLY;
		+DONTSPLASH;
	}
    States
    {
    Spawn:
	    TNT1 A 0 A_JumpIf(waterlevel > 1, "Splash");
        XME1 ABCD 3 A_SpawnProjectile ("NashGoreClassicBloodTrail", 0, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH, random (0, 360));
        Loop;
    Death:
        TNT1 AAAAAAA 0 A_SpawnProjectile ("NashGoreClassicBloodTrail", 0, 0, random (0, 180), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH, random (0, 180));
	    TNT1 A 0 {
			A_CheckFloor("SpawnFloor");
			//A_SpawnItemEx ("DetectCeilBloodSimplerLarge",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
			A_SpawnItemEx ("PB_DetectCeilXDeath2",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
		}
		Stop;
	SpawnFloor:
		XME1 E 0 {
			class<Actor> cls;
			if (nashgore_bloodtype == 0)		cls = "NashGoreBloodSpot";
			else if (nashgore_bloodtype == 1)	cls = "NashGoreBloodSpotClassic";
			A_SpawnItemEx(cls, flags: (NashGoreBloodBase.BLOOD_FLAGS | SXF_TRANSFERPOINTERS) & ~SXF_NOCHECKPOSITION, 150);
		}
		XME1 EEEEEEEEEE 1 {
			A_SpawnItemEx("NashGoreBloodFloorSplashSpawner",
				0, 0, 0,
				frandom(-4.0, 4.0), frandom(-4.0, 4.0), frandom(1.0, 4.0),
				frandom(0, 360), NashGoreBlood.BLOOD_FLAGS, 175);
		}
		XME1 E -1;
		Stop;
    }
}

class PB_XDeath3: PB_XDeath2
{
	Default
	{
		SeeSound "misc/xdeath4";
		DeathSound "misc/xdeath3";
		Decal "BrutalBloodSuper";
		Scale 1.1;
		Speed 10;
		Gravity 1.2;
	}
    States
    {
    Spawn:
	    TNT1 A 0 A_JumpIf(waterlevel > 1, "Splash");
        XME2 ABCD 3 A_SpawnProjectile ("NashGoreClassicBloodTrail", 0, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH, random (0, 360));
        Loop;
    Death:
        TNT1 AAAAAAA 0 A_SpawnProjectile ("NashGoreClassicBloodTrail", 0, 0, random (0, 180), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH, random (0, 180));
	    TNT1 A 0 {
			A_CheckFloor("SpawnFloor");
			//A_SpawnItemEx ("DetectCeilBloodSimplerLarge",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
			A_SpawnItemEx ("PB_DetectCeilXDeath2",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
		}
		Stop;
	SpawnFloor:
		XME2 E 0 {
			class<Actor> cls;
			if (nashgore_bloodtype == 0)		cls = "NashGoreBloodSpot";
			else if (nashgore_bloodtype == 1)	cls = "NashGoreBloodSpotClassic";
			A_SpawnItemEx(cls, flags: (NashGoreBloodBase.BLOOD_FLAGS | SXF_TRANSFERPOINTERS) & ~SXF_NOCHECKPOSITION, 150);
		}
		XME2 EEEEEEEEEE 1 {
			A_SpawnItemEx("NashGoreBloodFloorSplashSpawner",
				0, 0, 0,
				frandom(-4.0, 4.0), frandom(-4.0, 4.0), frandom(1.0, 4.0),
				frandom(0, 360), NashGoreBlood.BLOOD_FLAGS, 175);
		}
		XME2 E -1;
		Stop;
    }
}

class PB_XDeath4: PB_XDeath2
{
	Default
	{
		SeeSound "misc/xdeath4";
		DeathSound "misc/xdeath3";
		Scale 1.1;
		+DOOMBOUNCE;
		BounceFactor 0.3;
	}
	
    States
    {
		Spawn:
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Splash");
			XME3 ABCDEFGH 3 A_SpawnProjectile ("NashGoreClassicBloodTrail", 0, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH, random (0, 360));
			Loop;
		Death:
			TNT1 A 0 A_SpawnItem("NashGoreBloodSpot",0,0,0,1);
			TNT1 A 0 A_Jump(255, "Death1", "Death2");
			GOto Death1;
		
		Death1:
			XME3 GH 3;
			XME3 A -1;
			Stop;
		Death2:
			XME3 I 1;
			XME3 I -1;
			Stop;
    }
}

// Smaller Gibs from Nash's base giblets
class PB_SmallGib : PB_XDeath1
{
	Default
	{
		Radius 8;
		Height 4;
		Gravity 0.875;
		BounceType 'Doom';
		BounceFactor 0.5;
		BounceSound "misc/xdeath1";
		SeeSound "misc/xdeath4";
		+MISSILE
		+NOBLOCKMAP
		+THRUACTORS
		+NOTELEPORT
		+CANBOUNCEWATER
		+FLOORCLIP
		+MOVEWITHSECTOR
		+FORCEXYBILLBOARD
		-SOLID
	}

	States
	{
		Spawn:
			TNT1 A 0 NoDelay A_Jump(256, "Gib2", "Gib3", "Gib7", "Gib8", "Gib9");
			Stop;
		Gib2:
			GIB2 A 0;
			Goto SpawnLoop;
		Gib3:
			GIB3 A 0;
			Goto SpawnLoop;
		Gib7:
			GIB7 A 0;
			Goto SpawnLoop;
		Gib8:
			GIB8 A 0;
			Goto SpawnLoop;
		Gib9:
			GIB9 A 0;
			Goto SpawnLoop;
		SpawnLoop:
			"####" ABCD 3;
			Loop;
		Death:
			"####" E 0 {
				class<Actor> cls;
				if (nashgore_bloodtype == 0)		cls = "NashGoreBloodSpot";
				else if (nashgore_bloodtype == 1)	cls = "NashGoreBloodSpotClassic";
				A_SpawnItemEx(cls, flags: (NashGoreBloodBase.BLOOD_FLAGS | SXF_TRANSFERPOINTERS) & ~SXF_NOCHECKPOSITION, 150);
			}
			"####" EEEEEEEEEE 1 {
				A_SpawnItemEx("NashGoreBloodFloorSplashSpawner",
					0, 0, 0,
					frandom(-4.0, 4.0), frandom(-4.0, 4.0), frandom(1.0, 4.0),
					frandom(0, 360), NashGoreBlood.BLOOD_FLAGS, 175);
			}
			"####" E -1;
			Stop;
	}
}


class PB_XDeathOrgan1: PB_XDeath1
{
	Default
	{
		SeeSound "misc/xdeath4";
		DeathSound "misc/xdeath3";
		Scale 0.9;
		Speed 4;
	}
    States
    {
		Spawn:
			XME8 A 4 A_SpawnProjectile ("NashGoreClassicBloodTrail", 0, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH, random (0, 360));
			Loop;
		Death:
			XME8 A -1;
			Stop;
    }
}

class PB_XDeathOrgan1b: PB_XDeathOrgan1
{
	Default
	{
		XScale -0.7;
		YScale 0.5;
	}
}

class PB_XDeathOrgan2: PB_XDeathOrgan1
{
	States
	{
		Spawn:
			XME8 B 4 A_SpawnProjectile ("NashGoreClassicBloodTrail", 0, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH, random (0, 360));
			Loop;
		Death:
			XME8 B -1;
			Stop;
	}
}

class PB_XDeathGuts: PB_XDeath1
{
	Default
	{
		Scale 1.1;
		SeeSound "misc/xdeath4";
		DeathSound "misc/xdeath3";
	}
    States
    {
    Spawn:
	    TNT1 A 0 A_JumpIf(waterlevel > 1, "Splash");
        XME4 AAAABBBBCCCCDDDD 2;
        Loop;
    Death:
        TNT1 AAA 0 A_SpawnProjectile ("NashGoreClassicBloodTrail", 0, 0, random (0, 180), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH, random (0, 180));
        XME4 E -1;
        Stop;
    }
}

class PB_XDeathSkinPiece1: PB_XDeath1
{
	Default
	{
		Radius 2;
		Height 2;
		Speed 10;
		Scale 1.0;
		Mass 1;
		SeeSound "none";
		DeathSound "none";
		Mass 1;
	}
	
    States
    {
		Spawn:
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
			XSKI A 4;
			Loop;
		Death:
			XSKI B 0 {
				A_QueueCorpse();
				class<Actor> cls;
				if (nashgore_bloodtype == 0)		cls = "NashGoreBloodSpot";
				else if (nashgore_bloodtype == 1)	cls = "NashGoreBloodSpotClassic";
				A_SpawnItemEx(cls, flags: (NashGoreBloodBase.BLOOD_FLAGS | SXF_TRANSFERPOINTERS) & ~SXF_NOCHECKPOSITION, 150);
			}
			XSKI B 1 {
				A_SpawnItemEx("NashGoreBloodFloorSplashSpawner",
					0, 0, 0,
					frandom(-4.0, 4.0), frandom(-4.0, 4.0), frandom(1.0, 4.0),
					frandom(0, 360), NashGoreBlood.BLOOD_FLAGS, 175);
			}
			XSKI B -1;
			Stop;
    }
}	


class PB_XDeathSkinPiece2: PB_XDeath1
{
	Default
	{
		Radius 2;
		Height 2;
		Speed 10;
		Scale 1.0;
		Mass 1;
		SeeSound "none";
		DeathSound "none";
		Mass 1;
	}
    States
    {
		Spawn:
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
			XSKI C 4;
			Loop;
		Death:
			XSKI D 0 {
				A_QueueCorpse();
				class<Actor> cls;
				if (nashgore_bloodtype == 0)		cls = "NashGoreBloodSpot";
				else if (nashgore_bloodtype == 1)	cls = "NashGoreBloodSpotClassic";
				A_SpawnItemEx(cls, flags: (NashGoreBloodBase.BLOOD_FLAGS | SXF_TRANSFERPOINTERS) & ~SXF_NOCHECKPOSITION, 150);
			}
			XSKI D 1 {
				A_SpawnItemEx("NashGoreBloodFloorSplashSpawner",
					0, 0, 0,
					frandom(-4.0, 4.0), frandom(-4.0, 4.0), frandom(1.0, 4.0),
					frandom(0, 360), NashGoreBlood.BLOOD_FLAGS, 175);
			}
			XSKI D -1;
			Stop;
	}
}

class PB_XDeathBurnedMeat : Actor
{
	Default
	{
		Radius 8;
		Height 8;
		Speed 5;
		Mass 6;
		BounceFactor 0.5;
		+DOOMBOUNCE;
		+NOBLOCKMAP;
		+MISSILE;
		+NOTELEPORT;
		+DONTSPLASH;
		+MOVEWITHSECTOR;
	}
	
	override void BeginPlay(void)
	{
		ChangeStatNum(STAT_NashGore_Gore);
		NashGoreStatics.QueueGore();
		NashGoreStatics.RandomXFlip(self);
		Super.BeginPlay();
	}

	override void PostBeginPlay(void)
	{
		if (random() < (255 - nashgore_gibamount)) { Destroy(); return; }
		Super.PostBeginPlay();
	}

	override void Tick(void)
	{
		Super.Tick();
		if (!bNoTimeFreeze && (isFrozen() || Level.isFrozen())) return;
		if (NashGoreStatics.CheckSky(self)) { Destroy(); return; }
	}
	
    States
    {
		Spawn:
			CARB A 10 A_SpawnProjectile("PlasmaSmoke",0,0,180,2);
			Loop;
		Death:
			CARB A 1 A_SpawnItem ("MicroSmokeColumnWide", 0, 1);
			CARB A -1;
			Stop;
    }
}

class PB_XDeathBurnedMeatGreen : PB_XDeathBurnedMeat
{
    Default
	{
		translation "16:47=114:127", "179:191=116:127";
	}
}

class PB_XDeathBurnedMeat2 : PB_XDeathBurnedMeat
{
    States
    {
		Spawn:
			CARB B 10 A_SpawnProjectile("PlasmaSmoke",0,0,180,2);
			Loop;
		Death:
			CARB B 1 A_SpawnItem ("MicroSmokeColumnWide", 0, 1);
			CARB B -1;
			Stop;
    }
}

class PB_XDeathBurnedMeat2Green : PB_XDeathBurnedMeat2
{
    Default
	{
		translation "16:47=114:127", "174:191=115:127";
	}
}

class PB_XDeathBurnedMeat3 : PB_XDeathBurnedMeat
{
    States
    {
		Spawn:
			CARB C 10 A_SpawnProjectile("PlasmaSmoke",0,0,180,2);
			Loop;
		Death:
			CARB C 1 A_SpawnItem ("MicroSmokeColumnWide", 0, 1);
			CARB C -1;
			Stop;
    }
}

class PB_XDeathBurnedMeat3Green : PB_XDeathBurnedMeat3
{
	Default
	{
		translation "16:47=114:125", "179:191=116:127";
	}
}


class PB_XDeathBurnedArm : PB_XDeathBurnedMeat
{
    States
    {
		Spawn:
			CARB D 10 A_SpawnProjectile("PlasmaSmoke",0,0,180,2);
			Loop;
		Death:
			CARB D 1 A_SpawnItem ("MicroSmokeColumnWide", 0, 1);
			CARB D -1;
			Stop;
    }
}

class PB_XDeathBurnedLeg : PB_XDeathBurnedMeat
{
    States
    {
		Spawn:
			CARB E 10 A_SpawnProjectile("PlasmaSmoke",0,0,180,2);
			Loop;
		Death:
			CARB E 1 A_SpawnItem ("MicroSmokeColumnWide", 0, 1);
			CARB E -1;
			Stop;
    }
}

class PB_XDeathBurnedSkull : PB_XDeathBurnedMeat
{
    States
    {
		Spawn:
			BURN B 10 A_SpawnProjectile("PlasmaSmoke",0,0,180,2);
			Loop;
		Death:
			BURN B 1 A_SpawnItem ("MicroSmokeColumnWide", 0, 1);
			BURN B -1;
			Stop;
    }
}


/////////////////
//ARMS
/////////////////


class PB_XDeathArm1 : FlyingGibBase
{
	Default
	{
		Radius 8;
		Height 8;
		Scale 1.2;
		Speed 8;
		Mass 1;
		gravity 0.5;
		Decal "BrutalBloodSplat";
		BounceFactor 0.4;
		BounceCount 3;
		+DOOMBOUNCE;
		+MOVEWITHSECTOR;
		//+CLIENTSIDEONLY;
		+NOBLOCKMAP;
		+NOTELEPORT;
		+MISSILE;
		+EXPLODEONWATER;
		+SKYEXPLODE;
		-DONTSPLASH;
		seesound "bloood";
		deathsound "bloood";
	}
	
	override void BeginPlay(void)
	{
		ChangeStatNum(STAT_NashGore_Gore);
		NashGoreStatics.QueueGore();
		NashGoreStatics.RandomXFlip(self);
		Super.BeginPlay();
	}

	override void PostBeginPlay(void)
	{
		if (random() < (255 - nashgore_gibamount)) { Destroy(); return; }
		Super.PostBeginPlay();
	}

	override void Tick(void)
	{
		Super.Tick();
		if (!bNoTimeFreeze && (isFrozen() || Level.isFrozen())) return;
		if (NashGoreStatics.CheckSky(self)) { Destroy(); return; }
	}
	
    States
    {
		Spawn:
			TNT1 A 0 A_SpawnItem("NashGoreBloodSpot",0,0,0,1);
		Fly:
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
			XARM AEBCFDG 5 A_SpawnProjectile ("NashGoreClassicBloodTrail", 0, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH, random (0, 360));
			Loop;
		Death:
			XDT5 I 1 {
				A_SpawnItem("NashGoreBloodSpot",0,0,0,1);
				A_SpawnItem("PB_GibArm");
			}
			Stop;
    }
}

class PB_XDeathArm1Kicked: PB_XDeathArm1
{
	Default
	{
		+ACTIVATEMCROSS;
		+ACTIVATEIMPACT;
		+CANUSEWALLS;
	}
    States
    {
		Spawn:
			TNT1 A 0 {bNOCLIP = True;}
			XARM A 2 {
				bNOCLIP = False;
				A_SpawnItem("NashGoreBloodSpot",0,0,0,1);
			}
		Flying:
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
			XARM ABCD 6 A_SpawnProjectile ("NashGoreClassicBloodTrail", 0, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH, random (0, 360));
			Loop;
	}
}

class PB_GibArm: PB_LimbBase
{
	Default
	{
		Scale 1.2;
	}
    States
    {
		Spawn:
			XDT5 I 1 A_SpawnItem ("NashGoreBloodSpot", 0, 1);
		Rest:
			XDT5 I -1;
			Stop;
		Death.plasma: 
		Death.Burn: 
		Death.Flames:	    
			TNT1 A 0 A_SpawnItemEx("TinyBurningPiece2", random (-15, 15), random (-15, 15));
			TNT1 A 0 A_SpawnItemEx("TinyBurningPiece3", random (-15, 15), random (-15, 15));
			TNT1 A 0 A_SpawnProjectile ("PB_XDeathBurnedArm", 2, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH, 270);  
			Stop;
		Death:    
			TNT1 AAAA 0 A_SpawnProjectile ("NashGoreClassicBloodTrail", 0, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH, random (0, 360));
			TNT1 A 0 A_SpawnProjectile ("PB_GibHand", 0, 0, random (0, 180), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH, random (0, 180));
			TNT1 A 0 A_SpawnProjectile ("PB_GibArmPart", 0, 0, random (0, 180), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH, random (0, 180));
			Stop;
		Death.Kick:
		Death.Melee:
		Death.SuperPunch:
			XDT5 II 1 A_FaceTarget();
			TNT1 A 0 A_SpawnProjectile ("PB_XDeathArm1Kicked", 5, 0, random (170, 190), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH, random (20, 40));
			Stop;
		Pain:
			TNT1 A 0 ThrustThingZ(0,20,0,1);
			XARM ABCD 3;
			Goto Spawn;
	
		Death.ExplosiveImpact:
			TNT1 A 0 {	
				A_ChangeLinkFlags(False);
				ThrustThingZ(0,50,0,1);
			}
			XARM A 6;
			XARM ABCDABCDABCD 6 A_CheckFloor("Landz");
			Goto Landz;
		Landz:
			XDT5 I 0 A_SpawnItem("PB_GibArm");
			Stop;
	}
}

class PB_GibArmPart: PB_TinyGibBase
{
	Default
	{
		Scale 1.0;
    }
	States
    {
		Spawn:
			XDT5 Z 1;
		Death:
			XDT5 Z -1;
			Stop;
	}
}

class PB_GibHand: PB_TinyGibBase
{
	Default
	{
		Scale 1.0;
    }
	States
    {
		Spawn:
			XDT5 Y 1;
		Death:
			XDT5 Y -1;
			Stop;
	}
}

// Nazi Arm
class PB_NaziArm : PB_XDeathArm1
{
	Default
	{
		+ROLLSPRITE;
	}
	States
    {
		Spawn:
			TNT1 A 0 A_setroll(0);
			TNT1 A 0 A_SpawnItem("NashGoreBloodSpot",0,0,0,1);
		Fly:
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
			NZA1 A 3 {
			A_SetRoll(roll+30);
			A_SpawnProjectile ("NashGoreClassicBloodTrail", 0, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH, random (0, 360));
			}
			Loop;
		Death:
			NZA1 B 1 {
				A_SetRoll(0);
				A_SpawnItem("NashGoreBloodSpot",0,0,0,1);
				A_SpawnItem("PB_GibNaziArm");
			}
			Stop;
    }
}
class PB_GibNaziArm: PB_GibArm
{
	Default
	{
		+RollSprite;
	}
    States
    {
		Spawn:
			TNT1 A 0 A_setroll(0);
			NZA1 B 1 A_SpawnItem ("NashGoreBloodSpot", 0, 1);
		Rest:
			NZA1 B -1;
			Stop;
		Death.plasma: 
		Death.Burn: 
		Death.Flames:	    
			TNT1 A 0 A_SpawnItemEx("TinyBurningPiece2", random (-15, 15), random (-15, 15));
			TNT1 A 0 A_SpawnItemEx("TinyBurningPiece3", random (-15, 15), random (-15, 15));
			TNT1 A 0 A_SpawnProjectile ("PB_XDeathBurnedArm", 2, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH, 270);  
			Stop;
		Death:    
			TNT1 AAAA 0 A_SpawnProjectile ("NashGoreClassicBloodTrail", 0, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH, random (0, 360));
			TNT1 A 0 A_SpawnProjectile ("PB_GibHand", 0, 0, random (0, 180), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH, random (0, 180));
			TNT1 A 0 A_SpawnProjectile ("PB_GibNaziArmPart", 0, 0, random (0, 180), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH, random (0, 180));
			Stop;
		Death.Kick:
		Death.Melee:
		Death.SuperPunch:
			NZA1 BB 1 A_FaceTarget();
			TNT1 A 0 A_SpawnProjectile ("PB_NaziArmKicked", 5, 0, random (170, 190), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH, random (20, 40));
			Stop;
		Pain:
			TNT1 A 0 ThrustThingZ(0,20,0,1);
			NZA1 AAA 3 {
			A_setroll(roll+30);
			}
			Goto Spawn;
	
		Death.ExplosiveImpact:
			TNT1 A 0 {	
				A_ChangeLinkFlags(False);
				ThrustThingZ(0,50,0,1);
			}
			NZA1 A 6;
			NZA1 A 3 {
			A_setroll(roll+30);
			A_CheckFloor("Landz");
			}
			Goto Landz;
		Landz:
			TNT1 A 0 A_setroll(0);
			XDT5 I 0 A_SpawnItem("PB_GibNaziArm");
			Stop;
	}
}

class PB_NaziArmKicked: PB_NaziArm
{
	Default
	{
		+ROLLSPRITE;
	}
    States
    {
		Spawn:
			TNT1 A 0 {bNOCLIP = True;}
			NZA1 A 2 {
				bNOCLIP = False;
				A_SpawnItem("NashGoreBloodSpot",0,0,0,1);
			}
		Flying:
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
			NZA1 A 3 {
				A_SetRoll(roll+30);
				A_SpawnProjectile ("NashGoreClassicBloodTrail", 0, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH, random (0, 360));
			}
			Loop;
	}
}

class PB_GibNaziArmPart: PB_GibArmPart
{
	States
    {
		Spawn:
			NZT1 Z 1;
		Death:
			NZT1 Z -1;
			Stop;
	}
}

/////////////////////
//LEGS
/////////////////////

class PB_XDeathZombieLeg: PB_XDeathArm1
{
	Default
	{
		Scale 1.1;
		Speed 8;
		Gravity 0.4;
		BounceFactor 0.4;
	}
    States
    {
		Spawn:
			TNT1 A 0 A_SpawnItem("NashGoreBloodSpot",0,0,0,1);
		Fly:
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
			LEG1 ABCDEFGH 5 A_SpawnProjectile ("NashGoreClassicBloodTrail", 0, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH, random (0, 360));
			Loop;
		Death:
			LEG1 I 1 A_SpawnItem("PB_GibZombieLeg1");
			Stop;
    }
}



class PB_XDeathPlasmaZombieLeg: PB_XDeathArm1
{
	Default
	{
		Scale 1.1;
		Speed 8;
		Gravity 0.4;
		BounceFactor 0.4;
		+RollSprite;
	}
    States
    {
		Spawn:
			TNT1 A 0 A_SpawnItem("NashGoreBloodSpot",0,0,0,1);
		Fly:
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
			PZ13 A 4 {
				A_SetRoll(roll+30);
				A_SpawnProjectile ("NashGoreClassicBloodTrail", 0, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH, random (0, 360));
			}
			Loop;
		Death:
			PZ13 B 0 {
				A_SetRoll(0);
				A_SpawnItem("PB_GibPlasmaZombieLeg1");
			}
			Stop;
    }
}

class PB_GibZombieLeg1: PB_LimbBase
{
	Default
	{
		Scale 1.1;
		+RollSprite;
	}
    States
    {
		Spawn:
			TNT1 A 0 A_Jump(128, "Spawn1");
			LEG1 I 1 A_SpawnItem("NashGoreBloodSpot",0,0,0,1);
			LEG1 I -1;
			Stop;
		Spawn1:
			LEG1 J 1 A_SpawnItem("NashGoreBloodSpot",0,0,0,1);
			LEG1 J -1;
			Stop;
		Death.plasma:	    
			TNT1 A 0 A_SpawnProjectile ("PB_XDeathBurnedLeg", 32, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH, random (0, 160));   
			Stop;
		Death:    
			TNT1 AAA 0 A_SpawnProjectile ("NashGoreClassicBloodTrail", 0, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH, random (0, 360));
			TNT1 A 0 A_SpawnProjectile ("PB_GibZombieLegPart", 0, 0, random (0, 180), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH, random (0, 180));
			TNT1 A 0 A_SpawnProjectile ("PB_GibZombieBoot", 0, 0, random (0, 180), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH, random (0, 180));
			Stop;
		Death.Kick:
		Death.Melee:
		Death.SuperPunch:
			LEG1 E 1 {
				A_FaceTarget();
				A_SpawnProjectile ("PB_XDeathZombieLeg", 5, 0, random (170, 190), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH, random (20, 40));
				}
			Stop;
		
		Pain:
			TNT1 A 0 ThrustThingZ(0,20,0,1);
			LEG1 ABCDEFGH 2;
			Goto Spawn;
		
		Death.ExplosiveImpact:
			TNT1 A 0 {A_ChangeLinkFlags(False);}
			TNT1 A 0 ThrustThingZ(0,50,0,1);
			LEG1 A 5;
			LEG1 ABCDEFGHABCDEFGHABCDEFGH 5 A_CheckFloor("Landz");
			Goto Landz;
		Landz:
			XDT5 I 0 A_SpawnItem("PB_GibZombieLeg1");
			Stop;
	}
}

class PB_GibPlasmaZombieLeg1: PB_GibZombieLeg1
{
    States
    {
		Spawn:
			TNT1 A 0 A_Jump(128, "Spawn1");
			PZ13 B 1 A_SpawnItem("NashGoreBloodSpot",0,0,0,1);
			PZ13 B -1;
			Stop;
		Spawn1:
			PZ13 E 1 A_SpawnItem("NashGoreBloodSpot",0,0,0,1);
			PZ13 E -1;
			Stop;
		Death.plasma:	    
			TNT1 A 0 A_SpawnProjectile ("PB_XDeathBurnedLeg", 32, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH, random (0, 160));   
			Stop;
		Death:    
			TNT1 AAA 0 A_SpawnProjectile ("NashGoreClassicBloodTrail", 0, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH, random (0, 360));
			TNT1 A 0 A_SpawnProjectile ("PB_GibPlasmaZombieLegPart", 0, 0, random (0, 180), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH, random (0, 180));
			TNT1 A 0 A_SpawnProjectile ("PB_GibPlasmaZombieBoot", 0, 0, random (0, 180), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH, random (0, 180));
			Stop;
		Death.Kick:
		Death.Melee:
		Death.SuperPunch:
			PZ13 A 1 {
				A_FaceTarget();
				A_SpawnProjectile ("PB_XDeathPlasmaZombieLeg", 5, 0, random (170, 190), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH, random (20, 40));
				}
			Stop;
		
		Pain:
			TNT1 A 0 ThrustThingZ(0,20,0,1);
			PZ13 AAAAAAAA 2 A_SetRoll(roll+30);
			TNT1 A 0 A_SetRoll(0);
			Goto Spawn;
		
		Death.ExplosiveImpact:
			TNT1 A 0 {A_ChangeLinkFlags(False);}
			TNT1 A 0 ThrustThingZ(0,50,0,1);
			PZ13 A 5;
			PZ13 ABCDEFGHABCDEFGHABCDEFGH 5 A_CheckFloor("Landz");
			PZ13 AAAAAAAAAAAAAAAAAAAAAAAA 4 {
				A_SetRoll(roll+30);
				A_CheckFloor("Landz");
			}
			Goto Landz;
		Landz:
			TNT1 A 0 A_SpawnItem("PB_GibPlasmaZombieLeg1");
			Stop;
	}
}

class PB_GibZombieLegPart: PB_TinyGibBase
{
	Default
	{
		Scale 1.1;
    }
	States
    {
		Spawn:
			LEG1 Z 1;
		Death:
			LEG1 Z -1;
			Stop;
	}
}

class PB_GibZombieBoot: PB_TinyGibBase
{
	Default
	{
		Scale 1.1;
    }
	States
    {
		Spawn:
			LEG1 Y 1;
		Death:
			LEG1 Y -1;
			Stop;
	}
}

class PB_GibPlasmaZombieLegPart: PB_TinyGibBase
{
	Default
	{
		Scale 1.1;
    }
	States
    {
		Spawn:
			PZ13 C 1;
		Death:
			PZ13 C -1;
			Stop;
	}
}

class PB_GibPlasmaZombieBoot: PB_TinyGibBase
{
	Default
	{
		Scale 1.1;
    }
	States
    {
		Spawn:
			PZ13 D 1;
		Death:
			PZ13 D -1;
			Stop;
	}
}

// Nazi Legs
class PB_NaziLeg: PB_XDeathPlasmaZombieLeg
{
	Default
	{
		Scale 1.1;
		Speed 8;
		Gravity 0.4;
		BounceFactor 0.4;
		+RollSprite;
	}
    States
    {
		Spawn:
			TNT1 A 0 A_SpawnItem("NashGoreBloodSpot",0,0,0,1);
		Fly:
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
			NZL3 A 4 {
				A_SetRoll(roll+30);
				A_SpawnProjectile ("NashGoreClassicBloodTrail", 0, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH, random (0, 360));
			}
			Loop;
		Death:
			NZL3 B 0 {
				A_SetRoll(0);
				A_SpawnItem("PB_GibNaziLeg");
			}
			Stop;
    }
}

class PB_GibNaziLeg: PB_GibPlasmaZombieLeg1
{
    States
    {
		Spawn:
			TNT1 A 0 A_SetRoll(0);
			TNT1 A 0 A_Jump(128, "Spawn1");
			NZL3 B 1 A_SpawnItem("NashGoreBloodSpot",0,0,0,1);
			NZL3 B -1;
			Stop;
		Spawn1:
			NZL3 E 1 A_SpawnItem("NashGoreBloodSpot",0,0,0,1);
			NZL3 E -1;
			Stop;
		Death.plasma:	    
			TNT1 A 0 A_SpawnProjectile ("PB_XDeathBurnedLeg", 32, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH, random (0, 160));   
			Stop;
		Death:    
			TNT1 AAA 0 A_SpawnProjectile ("NashGoreClassicBloodTrail", 0, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH, random (0, 360));
			TNT1 A 0 A_SpawnProjectile ("PB_GibNaziLegPart", 0, 0, random (0, 180), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH, random (0, 180));
			TNT1 A 0 A_SpawnProjectile ("PB_GibNaziBoot", 0, 0, random (0, 180), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH, random (0, 180));
			Stop;
		Death.Kick:
		Death.Melee:
		Death.SuperPunch:
			NZL3 A 1 {
				A_FaceTarget();
				A_SpawnProjectile ("PB_NaziLeg", 5, 0, random (170, 190), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH, random (20, 40));
				}
			Stop;
		
		Pain:
			TNT1 A 0 ThrustThingZ(0,20,0,1);
			NZL3 AAAAAAAA 2 A_SetRoll(roll+30);
			Goto Spawn;
		
		Death.ExplosiveImpact:
			TNT1 A 0 {A_ChangeLinkFlags(False);}
			TNT1 A 0 ThrustThingZ(0,50,0,1);
			NZL3 A 5;
			NZL3 AAA 4 {
				A_SetRoll(roll+30);
				A_CheckFloor("Landz");
			}
			Goto Landz;
		Landz:
			TNT1 A 0 A_SpawnItem("PB_GibNaziLeg");
			Stop;
	}
}

class PB_GibNaziLegPart: PB_TinyGibBase
{
	Default
	{
		Scale 1.1;
    }
	States
    {
		Spawn:
			NZL3 C 1;
		Death:
			NZL3 C -1;
			Stop;
	}
}

class PB_GibNaziBoot: PB_TinyGibBase
{
	Default
	{
		Scale 1.1;
    }
	States
    {
		Spawn:
			NZL3 D 1;
		Death:
			NZL3 D -1;
			Stop;
	}
}

class PB_SmallBrainPiece : PB_TinyGibBase
{
	Default
	{
		Radius 2;
		Height 2;
		Speed 10;
		Mass 1;
		Scale 0.5;
		Decal "BrutalBloodSuper";
		+MISSILE;
		+NOBLOCKMAP;
		+NOTELEPORT;
		+THRUGHOST;
		+THRUACTORS;
		//+CLIENTSIDEONLY;
		+DONTSPLASH;
		+MOVEWITHSECTOR;
		-DONTSPLASH;
		+FORCEXYBILLBOARD;
		+FLOORCLIP;
	}
    States
    {
		Spawn:
			TNT1 A 0;
			TNT1 A 0 A_Jump(32, "DoNothing");
			TNT1 A 0 {bNOGRAVITY = False;}
		See:
			XDB5 ABCD 3;
			Loop;
		Death:
			TNT1 A 0;
			TNT1 A 0 A_CheckFloor("Rest");
			TNT1 A 0 A_SpawnItem("PB_DetectCeilBrain");
			TNT1 A 2;
			Stop;
		
		Rest:
			TNT1 A 0 A_Jump(255, "Rest1", "Rest2");
		Rest1:
			XDT5 B -1;
			Stop;
		Rest2:
			XDT5 O -1;
			Stop;
    }
}

class PB_SmallBrainPieceGreen : PB_SmallBrainPiece
{
	Default
	{
		translation "16:31=152:159", "168:191=12:12", "32:47=9:12";
		Decal "GreenBloodSplat";
	}
    States
    {
		Spawn:
			TNT1 A 0;
			TNT1 A 0 A_Jump(32, "DoNothing");
			TNT1 A 0 {bNOGRAVITY = False;}
		See:
			XDB5 ABCD 3;
			Loop;
		Death:
			TNT1 A 0;
			TNT1 A 0 A_CheckFloor("Rest");
			TNT1 A 0 A_SpawnItem("PB_DetectCeilBrainGreen");
			TNT1 A 2;
			Stop;
		
		Rest:
			TNT1 A 0 A_Jump(255, "Rest1", "Rest2");
		Rest1:
			XDT5 B -1;
			Stop;
		Rest2:
			XDT5 O -1;
			Stop;
    }
}


class PB_SmallBrainPieceFast : PB_SmallBrainPiece
{
	Default
	{
		Speed 16;
		Scale 0.65;
	}
}


Class PB_DetectCeilBrain : PB_TinyGibBase
{
	Default
	{
		scale 0.4;
		speed 0;
		health 1;
		radius 1;
		height 1;
		Gravity 0.0;
		damage 0;
		Renderstyle "Translucent";
		Alpha 0.95;
		DamageType "Blood";
		+MISSILE;
		//+CLIENTSIDEONLY;
		+NOTELEPORT;
		+NOBLOCKMAP;
		+FORCEXYBILLBOARD;
		+NODAMAGETHRUST;
		-DONTSPLASH;
		+NOGRAVITY;
   }
	States
	{
		Spawn:
			TNT1 A 0 ThrustThingZ(0,35,0,1);
			TNT1 A 2;
			TNT1 A 0 A_SpawnItem("PB_SmearingBrain");
			Stop;
		Death:
			TNT1 A 0 A_SpawnProjectile ("PB_SmallBrainPieceGreen", -15, 0, 90, 2, 90);
			Stop;
    }
}


Class PB_DetectCeilBrainGreen : PB_DetectCeilBrain
{
	Default
	{
		translation "16:31=152:159", "168:191=12:12", "32:47=9:12";
	}
	States
	{
		Spawn:
			TNT1 A 0 ThrustThingZ(0,35,0,1);
			TNT1 A 2;
			TNT1 A 0 A_SpawnItem("PB_SmearingBrainGreen");
			Stop;
		Death:
			TNT1 A 0 A_SpawnProjectile ("PB_SmallBrainPieceGreen", -15, 0, 90, 2, 90);
			Stop;
    }
}



Class PB_SmearingBrain : PB_TinyGibBase
{
	Default
	{
		Radius 2;
		Height 2;
		Speed 10;
		Mass 1;
		Scale 0.5;
		Gravity 0.25;
		+NOBLOCKMAP;
		+NOTELEPORT;
		+THRUGHOST;
		//+CLIENTSIDEONLY;
		+DONTSPLASH;
		+MOVEWITHSECTOR;
		-DONTSPLASH;
		+FORCEXYBILLBOARD;
	}
    States
    {
	Spawn:
		TNT1 A 0 {bNOGRAVITY = True;}
		TNT1 A 0 A_Jump(255, "Spawn1", "Spawn2", "Spawn3", "Spawn4");
	Spawn1:
		XDB5 AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA 1 A_CheckFloor("Rest");
		Goto Death;
	Spawn2:
		XDB5 BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB 1 A_CheckFloor("Rest");
		Goto Death;
	
	Spawn3:
		XDB5 CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC 1 A_CheckFloor("Rest");
		Goto Death;
	
	Spawn4:
		XDB5 DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD 1 A_CheckFloor("Rest");
		Goto Death;
	
	Death:
	Rest:
		TNT1 A 0 { Gravity = 1.0; }
		XDB5 A 2 ThrustThingZ(0,-2,0,1);
		TNT1 A 0 A_CheckFloor("Sleep");
		Loop;
	Sleep:	
	    XDT5 BBBBBBBBBBBBBBBBBB 2 ThrustThingZ(0,-2,0,1);
        XDT5 B -1;
        Stop;
    }
}

Class PB_SmearingBrainGreen : PB_SmearingBrain
{
	Default
	{
		translation "16:31=152:159", "168:191=12:12", "32:47=9:12";
	}
}

class PB_Brains1 : PB_TinyGIbBase//Random bloody piece
{
	Default
	{
		Radius 2;
		Height 2;
		Speed 6;
		Mass 1;
		BounceFactor 0.4;
		Scale 0.5;
		+MISSILE;
		+NOBLOCKMAP;
		+NOTELEPORT;
		//+CLIENTSIDEONLY;
		+DONTSPLASH;
		+MOVEWITHSECTOR;
		+FLOORCLIP;
	}
    States
    {
		Spawn:
			XDB5 DCBA 4;
			Loop;
		Death:
			XDT5 C -1;
			Stop;
    }
}

class PB_Brains2 : PB_TinyGIbBase
{
	Default
	{
		Radius 2;
		Height 2;
		Speed 6;
		Mass 1;
		Decal "BrutalBloodSplat";
		//+CLIENTSIDEONLY;
		BounceFactor 0.4;
		Scale 0.9;
		+DOOMBOUNCE;
		+MISSILE;
		+NOBLOCKMAP;
		+NOTELEPORT;
		+DONTSPLASH;
		+MOVEWITHSECTOR;
		+FLOORCLIP;
	}
    States
    {
		Spawn:
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
			TNT1 A 0 A_SpawnProjectile ("NashGoreClassicBloodTrail", 0, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH, random (0, 360));
			BRIB ABCD 4;
			Loop;
		Death:
		Rest:
			TNT1 A 0 A_Jump(255, "Rest1", "Rest2");
		Rest1:
			BRIB A -1;
			Stop;
		Rest2:
			BRIB C -1;
			Stop;
    }
}

class PB_Brains3 : PB_TinyGibBase //Eyeballs
{
	Default
	{
		Radius 2;
		Height 2;
		Speed 6;
		Mass 1;
		Decal "BrutalBloodSplat";
		//+CLIENTSIDEONLY;
		BounceFactor 0.5;
		+DOOMBOUNCE;
		+MISSILE;
		+NOBLOCKMAP;
		+NOTELEPORT;
		+DONTSPLASH;
		+MOVEWITHSECTOR;
		+FLOORCLIP;
		Scale 0.8;
	}
    States
    {
		Spawn:
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
			BRIB EFGH 4;
			Loop;
		Death:
			BRIB E 1 A_Jump(255, "Rest1", "Rest2", "Rest3", "Rest4");
		Rest1:
			BRIB E -1;
			Stop;
		Rest2:
			BRIB F -1;
			Stop;
		Rest3:
			BRIB G -1;
			Stop;
		Rest4:
			BRIB H -1;
			Stop;
    }
}

class PB_Brains4 : PB_TinyGibBase //White skinned piece 1
{
	Default
	{
		Radius 2;
		Height 2;
		Speed 6;
		Mass 1;
		Scale 0.9;
		Decal "BrutalBloodSplat";
		//+CLIENTSIDEONLY;
		BounceFactor 0.2;
		+DOOMBOUNCE;
		+NOBLOCKMAP;
		+MISSILE;
		+NOTELEPORT;
		+DONTSPLASH;
		+MOVEWITHSECTOR;
		+FLOORCLIP;
	}
	
    States
    {
		Spawn:
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
			TNT1 A 0 A_SpawnProjectile ("NashGoreClassicBloodTrail", 0, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH, random (0, 360));
			BRIB IJKL 4;
			Loop;
		Death:
			BRIN D -1;
			Stop;
    }
}

class PB_Brains4Blonde: PB_Brains4 //White skinned piece 1
{
    States
    {
		Spawn:
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
			TNT1 A 0 A_SpawnProjectile ("NashGoreClassicBloodTrail", 0, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH, random (0, 360));
			BR8B IJKL 4;
			Loop;
		Death:
			BR8B I -1;
			Stop;
    }
}

class PB_Brains4BlondeBig: PB_Brains4 //White skinned piece 1
{
    States
    {
		Spawn:
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
			TNT1 A 0 A_SpawnProjectile ("NashGoreClassicBloodTrail", 0, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH, random (0, 360));
			BR8B ABCD 4;
			Loop;
		Death:
			BR8B A -1;
			Stop;
    }
}

class PB_Brains5: PB_Brains4 //White skinned piece 2
{
    States
    {
		Spawn:
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
			TNT1 A 0 A_SpawnProjectile ("NashGoreClassicBloodTrail", 0, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH, random (0, 360));
			BRIB IJKL 4;
			Loop;
		Death:
			BRIN E -1;
			Stop;
    }
}

class PB_Brains6: PB_Brains4 //White skinned piece 2
{
    States
    {
		Spawn:
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
			TNT1 A 0 A_SpawnProjectile ("NashGoreClassicBloodTrail", 0, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH, random (0, 360));
			BRIB MNOP 4;
			Loop;
		Death:
			BRIN F -1;
			Stop;
    }
}

class PB_Brains6Big: PB_Brains6 //White skinned piece 2
{
	Default
	{
		Scale 1.8;
	}
}

class PB_Brains7: PB_Brains4 //White skinned piece 2
{
    States
    {
		Spawn:
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
			TNT1 A 0 A_SpawnProjectile ("NashGoreClassicBloodTrail", 0, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH, random (0, 360));
			BRIB QRST 4;
			Loop;
		Death:
			BRIN G -1;
			Stop;
    }
}

class PB_Brains7Big: PB_Brains7 //White skinned piece 2
{
	Default
	{
		Scale 1.8;
	}
}

class PB_Brains4BrownHair: PB_Brains4 //White skinned piece 1
{
	Default
	{
		+RollSprite
	}
    States
    {
		Spawn:
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
			TNT1 A 0 A_SpawnProjectile ("NashGoreClassicBloodTrail", 0, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH, random (0, 360));
			LCE0 C 4 A_SetRoll(roll+45);
			Loop;
		Death:
			LCE0 C 1 A_SetRoll(0);
			LCE0 C -1;
			Stop;
    }
}

class PB_Brains4BrownHairBig: PB_Brains4 //White skinned piece 1
{
	Default
	{
		+RollSprite
	}
    States
    {
		Spawn:
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
			TNT1 A 0 A_SpawnProjectile ("NashGoreClassicBloodTrail", 0, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH, random (0, 360));
			LCE0 B 4 A_SetRoll(roll+45);
			Loop;
		Death:
			LCE0 B 1 A_SetRoll(0);
			LCE0 B -1;
			Stop;
    }
}

class PB_Brains4Green: PB_Brains4 //White skinned piece 1
{
    States
    {
		Spawn:
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
			TNT1 A 0 A_SpawnProjectile ("NashGoreClassicBloodTrail", 0, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH, random (0, 360));
			BR7B IJKL 4;
			Loop;
		Death:
			BR7N D -1;
			Stop;
    }
}

class PB_Brains4GreenBig: PB_Brains4 //White skinned piece 1
{
    States
    {
		Spawn:
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
			TNT1 A 0 A_SpawnProjectile ("NashGoreClassicBloodTrail", 0, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH, random (0, 360));
			BR7B ABCD 4;
			Loop;
		Death:
			BR7B A -1;
			Stop;
    }
}

class PB_Brains4Blue: PB_Brains4 //White skinned piece 1
{
    States
    {
		Spawn:
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
			TNT1 A 0 A_SpawnProjectile ("NashGoreClassicBloodTrail", 0, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH, random (0, 360));
			BR9B IJKL 4;
			Loop;
		Death:
			BR9B I -1;
			Stop;
    }
}

class PB_Brains4BlueBig: PB_Brains4 //White skinned piece 1
{
    States
    {
		Spawn:
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
			TNT1 A 0 A_SpawnProjectile ("NashGoreClassicBloodTrail", 0, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH, random (0, 360));
			BR9B ABCD 4;
			Loop;
		Death:
			BR9B A -1;
			Stop;
    }
}

class PB_Brains4Orange: PB_Brains4
{
    States
    {
		Spawn:
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
			TNT1 A 0 A_SpawnProjectile ("NashGoreClassicBloodTrail", 0, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH, random (0, 360));
			BR0B IJKL 4;
			Loop;
		Death:
			BR0B I -1;
			Stop;
    }
}

class PB_Brains4OrangeBig: PB_Brains4 //White skinned piece 1
{
    States
    {
		Spawn:
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
			TNT1 A 0 A_SpawnProjectile ("NashGoreClassicBloodTrail", 0, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH, random (0, 360));
			BR0B ABCD 4;
			Loop;
		Death:
			BR0B A -1;
			Stop;
    }
}

class PB_BrainsSergeantHeadPiece: PB_Brains4 //White skinned piece 1
{
	Default
	{
		Scale 1.0;
	}
    States
    {
		Spawn:
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
			TNT1 A 0 A_SpawnProjectile ("NashGoreClassicBloodTrail", 0, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH, random (0, 360));
			BR7B EFGH 4;
			Loop;
		Death:
			BR7B E -1;
			Stop;
    }
}

class PB_BrainsImpHeadPiece: PB_Brains4 //White skinned piece 1
{
	Default
	{
		Speed 2;
		-DOOMBOUNCE;
		Scale 1.0;
	}
    States
    {
    Spawn:
	    TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
		TNT1 A 0 A_SpawnProjectile ("NashGoreClassicBloodTrail", 0, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH, random (0, 360));
		BR7N E 4;
		Loop;
	Death:
        BR7N E -1;
        Stop;
    }
}

class PB_BrainsSavageImpHeadPiece: PB_BrainsImpHeadPiece //White skinned piece 1
{
    States
    {
		Spawn:
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
			1HED AA 4 A_SpawnProjectile ("NashGoreClassicBloodTrail", 0, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH, random (0, 360));
			Loop;
		Death:
			1HED A -1;
			Stop;
    }
}

class PB_XDeathZombieManHead: PB_XDeathArm1
{
	Default
	{
		Radius 10;
		Scale 1.0;
	}
    States
    {
		Spawn:
		Spawn1:
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
			TNT1 A 0 A_JumpIf(Vel.Z == 0, "Death");
			TNT1 A 0 {bTHRUSPECIES = False;}
			XHE2 ABCDEFGH 3 A_SpawnProjectile ("NashGoreClassicBloodTrail", 0, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH, random (0, 360));
			Loop;
		Death:
			XHE2 E 1;
			XHE2 E 1 A_SpawnItem("PB_ZombieManHead",0,0,0,1);
			Stop;
	}
}

class PB_ZombiemanHead: PB_LimbBase
{
	default
	{
		damagefactor "Kick", 99.0;
		damagefactor "Melee", 99.0;
		damagefactor "SuperPunch", 99.0;
		damagefactor "Crush", 50.0;
		Radius 10;
		Mass 12;
		Health 40;
		Scale 1.1;
		+SHOOTABLE;
		+THRUACTORS;
	}
    States
    {
		Spawn:
			TNT1 A 0;
			TNT1 A 0 A_Jump(256, "Spawn1", "Spawn2", "Spawn3");
		Spawn1:
			XHE2 C -1;
			Stop;
		Spawn2:
			XHE2 G -1;
			Stop;
		Spawn3:
			XHE2 H -1;
			Stop;
	
		Death.Trample:
		Death.Stomp:
			TNT1 A 0; //A_GiveToTarget("BootsSmearedWithRedBlood", 6)
			Goto Death;
		Death:
			TNT1 A 0;
			TNT1 A 0 A_SpawnItem("ZombiemanHeadExplode");
			Stop;
		Crush:
			TNT1 AAAAAAAA 0 A_SpawnProjectile ("NashGoreClassicBloodTrail", 0, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH, random (60, 140));
			TNT1 A 0 A_StartSound("misc/xdeath4");
			CRS1 B 5;
			CRS1 B -1;
			Stop;
		Death.plasma:
			TNT1 A 0 A_SpawnProjectile ("PB_XDeathBurnedSkull", 32, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH, random (0, 160));
			EXPL A 0 A_SpawnProjectile ("ExplosionSmoke", 32, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH, random (0, 360));
			Stop;
		Death.Melee:
		Death.SuperPunch:
		Death.Kick:
			XHE2 EE 1 A_FaceTarget();
			TNT1 AAAA 0 A_SpawnItemEx("NashGoreBlood", 0, 0, 10);
			TNT1 A 0 A_SpawnProjectile ("PB_XDeathZombieManHeadKicked", 5, 0, random (170, 190), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH, random (20, 30));
			TNT1 A 0 A_StartSound("misc/xdeath4", 1);
			TNT1 A 0 A_StartSound("player/cyborg/fist", 3);
			TNT1 A 20;
			Stop;
		
		Pain:
			TNT1 A 0;
			TNT1 A 0 ThrustThingZ(0,20,0,1);
			XHE2 ABCDEFGH 2;
			Goto Spawn;
		
		Death.ExplosiveImpact:
			TNT1 A 0;
			TNT1 A 0 {A_ChangeLinkFlags(False);}
			TNT1 A 0 ThrustThingZ(0,50,0,1);
			XHE2 ABCD 6;
			XDT5 I 0 A_SpawnItem("PB_ZombiemanHead");
			Stop;
	}
}

class PB_XDeathZombiemanHeadOnXDeath: PB_XDeathZombieManHead
{
	States
	{
		Spawn:
			TNT1 A 1 A_jump(96, "ExplodeOnAir");
			Goto Spawn1;
		ExplodeOnAir:
			TNT1 A 0 A_SpawnItem("PB_ZombiemanHeadExplode");
			Stop;
	}
}

class PB_XDeathHelmetZombiemanHeadOnXDeath: PB_XDeathHelmetZombieHead
{
	States
	{
		Spawn:
			TNT1 A 1 A_jump(96, "ExplodeOnAir");
			Goto Spawn1;
		ExplodeOnAir:
			TNT1 A 0 A_SpawnItem("PB_ZombiemanHeadExplode");
			Stop;
	}
}



class PB_XDeathARZombiemanHeadOnXDeath: PB_XDeathARZombieManHead
{
	States
	{
		Spawn:
			TNT1 A 1 A_jump(96, "ExplodeOnAir");
			Goto Spawn1;
		ExplodeOnAir:
			TNT1 A 0 A_SpawnItem("ShotgunGuyHeadExplode");
			Stop;
	}
}

class PB_XDeathZombiemanHeadKicked: PB_XDeathZombieManHead
{
	Default
	{
		Speed 9;
	}
}


// NAZI GORE

class PB_XDeathNaziHelmet: PB_XDeathZombieManHead //White skinned piece 1
{
	Default 
	{
		+NOBLOOD;
		Scale 1.1;
		Decal "None";
		seesound "nazi/helmet";
		deathsound "nazi/helmet";
		BounceCount 3;
	}
    States
    {
		Spawn:
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
			GERH ABCD 4;
			Loop;
		Death:
			GERH A 1 A_SpawnItem("PB_NaziHelmetResting");
			Stop;
    }
}

class PB_NaziHelmetResting: PB_ZombiemanHead
{
	default
	{
		damagefactor "Kick", 99.0;
		damagefactor "Melee", 99.0;
		damagefactor "SuperPunch", 99.0;
		damagefactor "Crush", 0.0;
		damagefactor "Trample",0.0;
		damagefactor "Stomp", 0.0;
		damagefactor "Plasma", 0.0;
		Radius 10;
		Mass 12;
		Scale 1.1;
		Health 99999999;
		+SHOOTABLE;
		+THRUACTORS;
		+NOBLOOD;
	}
    States
    {
		Spawn:
			TNT1 A 0;
		Spawn1:
			BR8B I 0 A_Jump(128, "Spawn2");
			GERH A -1;
			Stop;
		Spawn2:
			GERH C -1;
			Stop;
	
		Death.Trample:
		Death.Stomp:
			TNT1 A 0; //A_GiveToTarget("BootsSmearedWithRedBlood", 6)
			Goto Death;
		Death:
		Crush:
			TNT1 A 0;
			TNT1 A 0 A_SpawnItem("PB_NaziHelmetResting");
			Stop;
		
		Pain.Kick:
		Pain.Melee:
		Pain.SuperPunch:
		Pain.Plasma:
		Death.Melee:
		Death.SuperPunch:
		Death.Kick:
		Death.Plasma:
			GERH AA 1 A_FaceTarget();
			TNT1 A 0 A_SpawnProjectile ("PB_XDeathNaziHelmet", 5, 0, random (170, 190), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH, random (20, 30));
			TNT1 A 0 A_StartSound("BLANKSND");
			TNT1 A 20;
			Stop;
		Pain:
			TNT1 A 0;
			Goto Spawn;
		
		Death.ExplosiveImpact:
		Pain.ExplosiveImpact:
			TNT1 A 0;
			TNT1 A 0 {A_ChangeLinkFlags(False);}
			TNT1 A 0 ThrustThingZ(0,50,0,1);
			GERH ABCD 6;
			XDT5 I 0 A_SpawnItem("PB_NaziHelmetResting");
			Stop;
	}
}


class PB_XDeathNaziHead: PB_XDeathChainsawZombieHead
{
    States
    {
		Spawn:
		Spawn1:
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
			TNT1 A 0 A_JumpIf(Vel.Z == 0, "Death");
			TNT1 A 0 {bTHRUSPECIES = False;}
			XZE1 A 3 {
				A_SpawnProjectile ("NashGoreClassicBloodTrail", 0, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH, random (0, 360));
				A_SetRoll(roll+30);
			}
			Loop;
		Death:
			XZE1 E 1 A_SETROLL(0);
			XZE1 E 1 A_SpawnItem("PB_NaziHead",0,0,0,1);
			Stop;
	}
}

class PB_NaziHead: PB_ZombiemanHead
{
	DEFAULT 
	{
		+ROLLCENTER;
	}
    States
    {
		Spawn:
			TNT1 A 0 {bROLLSPRITE = FALSE;}
			TNT1 A 0 A_Jump(256, "Spawn1", "Spawn2", "Spawn3", "Spawn4");
		Spawn1:
			XZE1 A -1;
			Stop;
		Spawn2:
			XZE1 B -1;
			Stop;
		Spawn3:
			XZE1 A -1 {bYFLIP = true;}
			Stop;
		Spawn4:
			XZE1 B -1{bXFLIP = true;}
			Stop;
	
		Death.Trample:
		Death.Stomp:
			TNT1 A 0; //A_GiveToTarget("BootsSmearedWithRedBlood", 6)
			Goto Death;
		Death:
			TNT1 A 0;
			TNT1 A 0 {
				bYFLIP = false;
				bXFLIP = false;
			}
			TNT1 A 0 A_SpawnItem("NaziHeadExplode");
			Stop;
		Crush:
			TNT1 A 0 {
				bYFLIP = false;
				bXFLIP = false;
			}
			TNT1 AAAAAAAA 0 A_SpawnProjectile ("NashGoreClassicBloodTrail", 0, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH, random (60, 140));
			TNT1 A 0 A_StartSound("misc/xdeath4");
			CRS1 B 5;
			CRS1 B -1;
			Stop;
		Death.plasma:
			TNT1 A 0 {
				bYFLIP = false;
				bXFLIP = false;
			}
			TNT1 A 0 A_SpawnProjectile ("PB_XDeathBurnedSkull", 32, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH, random (0, 160));
			EXPL A 0 A_SpawnProjectile ("ExplosionSmoke", 32, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH, random (0, 360));
			Stop;
		Death.Melee:
		Death.SuperPunch:
		Death.Kick:
			TNT1 A 0 {
				bYFLIP = false;
				bXFLIP = false;
			}
			XZE1 AA 1 A_FaceTarget();
			TNT1 AAAA 0 A_SpawnItemEx("NashGoreBlood", 0, 0, 10);
			TNT1 A 0 A_SpawnProjectile ("PB_XDeathNaziHeadKicked", 5, 0, random (170, 190), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH, random (20, 30));
			TNT1 A 0 A_StartSound("misc/xdeath4", 1);
			TNT1 A 0 A_StartSound("player/cyborg/fist", 3);
			TNT1 A 20;
			Stop;
		
		Pain:
			TNT1 A 0;
			TNT1 A 0 {
				bYFLIP = false;
				bXFLIP = false;
				bROLLSPRITE = TRUE;
			}
			TNT1 A 0 ThrustThingZ(0,20,0,1);
			XZE1 AAAAAAAA 2 {
			A_SetRoll(roll-30);
			}
			Goto Spawn;
		
		Death.ExplosiveImpact:
			TNT1 A 0;
			TNT1 A 0 {
				bYFLIP = false;
				bXFLIP = false;
				bROLLSPRITE = TRUE;
			}
			TNT1 A 0 {A_ChangeLinkFlags(False);}
			TNT1 A 0 ThrustThingZ(0,50,0,1);
			XZE1 AAAA 2 {
			A_SetRoll(roll-30);
			}
			XDT5 I 0 A_SpawnItem("PB_NaziHead");
			Stop;
	}
}

class PB_XDeathNaziHeadKicked: PB_XDeathNaziHead
{
	Default
	{
		Speed 9;
	}
}

class PB_XDeathNaziHeadOnXDeath: PB_XDeathNaziHead
{
	States
	{
		Spawn:
			TNT1 A 1 A_jump(96, "ExplodeOnAir");
			Goto Spawn1;
		ExplodeOnAir:
			TNT1 A 0 A_SpawnItem("NaziHeadExplode");
			Stop;
	}
}


class PB_XDeathHelmetZombieHead: PB_XDeathArm1
{
	Default
	{
		Radius 10;
		Scale 1.0;
	}
    States
    {
		Spawn:
		Spawn1:
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
			TNT1 A 0 A_JumpIf(Vel.Z == 0, "Death");
			TNT1 A 0 {bTHRUSPECIES = False;}
			XHEQ ABCD 3 A_SpawnProjectile ("NashGoreClassicBloodTrail", 0, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH, random (0, 360));
			Loop;
		Death:
			QHED A 1 A_SpawnItem("PB_HelmetZombieHead",0,0,0,1);
			Stop;
	}
}

class PB_XDeathHelmetZombieHeadKicked: PB_XDeathHelmetZombieHead
{
	Default
	{
		Speed 9;
	}
}

class PB_HelmetZombieHead: PB_ZombiemanHead
{
    States
    {
		Spawn:
			QHED A -1;
			Stop;
	
		Death.Trample:
		Death.Stomp:
			TNT1 A 0; //A_GiveToTarget("BootsSmearedWithRedBlood", 6)
			Goto Death;
		Death:
			TNT1 A 0 A_SpawnItem("ZombiemanHeadExplode");
			HEDQ A -1;
			Stop;
		Crush:
			TNT1 AAAAAAAA 0 A_SpawnProjectile ("NashGoreClassicBloodTrail", 0, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH, random (60, 140));
			TNT1 A 0 A_StartSound("misc/xdeath4");
			CRS1 B 5;
			CRS1 B -1;
			Stop;
		Death.plasma:
			TNT1 A 0 A_SpawnProjectile ("PB_XDeathBurnedSkull", 32, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH, random (0, 160));
			EXPL A 0 A_SpawnProjectile ("ExplosionSmoke", 32, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH, random (0, 360));
			Stop;
		Death.Melee:
		Death.SuperPunch:
		Death.Kick:
			QHED A 1 A_FaceTarget();
			TNT1 AAAA 0 A_SpawnItemEx("NashGoreBlood", 0, 0, 10);
			TNT1 A 0 A_SpawnProjectile ("PB_XDeathHelmetZombieHeadKicked", 5, 0, random (170, 190), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH, random (20, 30));
			TNT1 A 0 A_StartSound("misc/xdeath4", 1);
			TNT1 A 0 A_StartSound("player/cyborg/fist", 3);
			TNT1 A 20;
			Stop;
		
		Pain:
			TNT1 A 0 ThrustThingZ(0,20,0,1);
			XHEQ ABCDABCD 2;
			Goto Spawn;
		
		Death.ExplosiveImpact:
			TNT1 A 0;
			TNT1 A 0 {A_ChangeLinkFlags(False);}
			TNT1 A 0 ThrustThingZ(0,50,0,1);
			XHEQ ABCD 6;
			TNT1 A 0 A_SpawnItem("PB_HelmetZombieHead");
			Stop;
	}
}

class PB_XDeathARZombieManHead: PB_XDeathArm1
{
	Default
	{
		Radius 10;
		Scale 1.0;
	}
    States
    {
		Spawn:
		Spawn1:
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
			TNT1 A 0 A_JumpIf(Vel.Z == 0, "Death");
			TNT1 A 0 {bTHRUSPECIES = False;}
			RHE2 ABCDEFGH 3 A_SpawnProjectile ("NashGoreClassicBloodTrail", 0, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH, random (0, 360));
			Loop;
		Death:
			RHE2 E 1;
			RHE2 E 1 A_SpawnItem("PB_ARZombieManHead",0,0,0,1);
			Stop;
	}
}

class PB_ARZombiemanHead: PB_LimbBase
{
	default
	{
		damagefactor "Kick", 99.0;
		damagefactor "Melee", 99.0;
		damagefactor "SuperPunch", 99.0;
		damagefactor "Crush", 50.0;
		Radius 10;
		Mass 12;
		Health 40;
		Scale 1.1;
		+SHOOTABLE;
		+THRUACTORS;
	}
    States
    {
		Spawn:
			TNT1 A 0;
			TNT1 A 0 A_Jump(256, "Spawn1", "Spawn2");
		Spawn1:
			RHE2 I -1;
			Stop;
		Spawn2:
			RHE2 J -1;
			Stop;
	
		Death.Trample:
		Death.Stomp:
			TNT1 A 0; //A_GiveToTarget("BootsSmearedWithRedBlood", 6)
			Goto Death;
		Death:
			TNT1 A 0;
			TNT1 A 0 A_SpawnItem("ShotgunGuyHeadExplode");
			Stop;
		Crush:
			TNT1 AAAAAAAA 0 A_SpawnProjectile ("NashGoreClassicBloodTrail", 0, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH, random (60, 140));
			TNT1 A 0 A_StartSound("misc/xdeath4");
			CRS1 B 5;
			CRS1 B -1;
			Stop;
		Death.plasma:
			TNT1 A 0 A_SpawnProjectile ("PB_XDeathBurnedSkull", 32, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH, random (0, 160));
			EXPL A 0 A_SpawnProjectile ("ExplosionSmoke", 32, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH, random (0, 360));
			Stop;
		Death.Melee:
		Death.SuperPunch:
		Death.Kick:
			RHE2 EE 1 A_FaceTarget();
			TNT1 AAAA 0 A_SpawnItemEx("NashGoreBlood", 0, 0, 10);
			TNT1 A 0 A_SpawnProjectile ("PB_ARXDeathZombieManHeadKicked", 5, 0, random (170, 190), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH, random (20, 30));
			TNT1 A 0 A_StartSound("misc/xdeath4", 1);
			TNT1 A 0 A_StartSound("player/cyborg/fist", 3);
			TNT1 A 20;
			Stop;
		
		Pain:
			TNT1 A 0;
			TNT1 A 0 ThrustThingZ(0,20,0,1);
			RHE2 ABCDEFGH 2;
			Goto Spawn;
		
		Death.ExplosiveImpact:
			TNT1 A 0;
			TNT1 A 0 {A_ChangeLinkFlags(False);}
			TNT1 A 0 ThrustThingZ(0,50,0,1);
			RHE2 ABCD 6;
			XDT5 I 0 A_SpawnItem("PB_ARZombiemanHead");
			Stop;
	}
}

class PB_ARXDeathZombieManHeadKicked: PB_ARZombiemanHead
{
	Default
	{
		Speed 9;
	}
}

class PB_XDeathChainsawZombieHead: PB_XDeathArm1
{
	Default
	{
		Radius 10;
		Scale 1.0;
		+ROLLSPRITE;
		+ROLLCENTER;
	}
    States
    {
		Spawn:
		Spawn1:
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
			TNT1 A 0 A_JumpIf(Vel.Z == 0, "Death");
			TNT1 A 0 {bTHRUSPECIES = False;}
			LCE0 A 3 {
				A_SpawnProjectile ("NashGoreClassicBloodTrail", 0, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH, random (0, 360));
				A_SetRoll(roll+45);
			}
			Loop;
		Death:
			LCE0 E 0 A_SpawnItem("PB_ChainsawZombieHead",0,0,0,1);
			Stop;
	}
}

class PB_ChainsawZombieHead: PB_LimbBase
{
	default
	{
		damagefactor "Kick", 99.0;
		damagefactor "Melee", 99.0;
		damagefactor "SuperPunch", 99.0;
		damagefactor "Crush", 50.0;
		Radius 10;
		Mass 12;
		Health 40;
		Scale 1.1;
		+SHOOTABLE;
		+THRUACTORS;
		+RollSprite;
	}
    States
    {
		Spawn:
			TNT1 A 0;
			TNT1 A 0 A_SetRoll(0);
			TNT1 A 0 A_Jump(256, "Spawn1", "Spawn2");
		Spawn1:
			LCE0 E -1;
			Stop;
		Spawn2:
			LCE0 F -1;
			Stop;
	
		Death.Trample:
		Death.Stomp:
			TNT1 A 0; //A_GiveToTarget("BootsSmearedWithRedBlood", 6)
			Goto Death;
		Death:
			TNT1 A 0;
			TNT1 A 0 A_SpawnItem("ShotgunGuyHeadExplode");
			Stop;
		Crush:
			TNT1 AAAAAAAA 0 A_SpawnProjectile ("NashGoreClassicBloodTrail", 0, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH, random (60, 140));
			TNT1 A 0 A_StartSound("misc/xdeath4");
			CRS1 B 5;
			CRS1 B -1;
			Stop;
		Death.plasma:
			TNT1 A 0 A_SpawnProjectile ("PB_XDeathBurnedSkull", 32, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH, random (0, 160));
			EXPL A 0 A_SpawnProjectile ("ExplosionSmoke", 32, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH, random (0, 360));
			Stop;
		Death.Melee:
		Death.SuperPunch:
		Death.Kick:
			TNT1 A 0 ThrustThingZ(0,35,0,1);
			LCE0 AA 1 A_FaceTarget();
			TNT1 AAAA 0 A_SpawnItemEx("NashGoreBlood", 0, 0, 10);
			TNT1 A 0 A_SpawnProjectile ("PB_XDeathChainsawZombieHeadKicked", 5, 0, random (170, 190), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH, random (20, 30));
			TNT1 A 0 A_StartSound("misc/xdeath4", 1);
			TNT1 A 0 A_StartSound("player/cyborg/fist", 3);
			TNT1 A 20;
			Stop;
		
		Pain:
			TNT1 A 0;
			TNT1 A 0 ThrustThingZ(0,20,0,1);
			LCE0 AAAAAAAA 2 A_SetRoll(roll+45);
			Goto Spawn;
		
		Death.ExplosiveImpact:
			TNT1 A 0;
			TNT1 A 0 {A_ChangeLinkFlags(False);}
			TNT1 A 0 ThrustThingZ(0,50,0,1);
			LCE0 AAAAAAAA 2 A_SetRoll(roll+45);
			XDT5 I 0 A_SpawnItem("PB_ChainsawZombieHead");
			Stop;
	}
}

class PB_XDeathChainsawZombieHeadKicked: PB_XDeathChainsawZombieHead
{
	Default
	{
		Speed 9;
	}
}

class PB_XDeathHellTrooperHead: PB_XDeathChainsawZombieHead
{
    States
    {
		Spawn:
		Spawn1:
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
			TNT1 A 0 A_JumpIf(Vel.Z == 0, "Death");
			TNT1 A 0 {bTHRUSPECIES = False;}
			HTHD A 3 {
				A_SpawnProjectile ("NashGoreClassicBloodTrail", 0, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH, random (0, 360));
				A_SetRoll(roll+30);
			}
			Loop;
		Death:
			HTHD A 1 A_SETROLL(0);
			HTHD A 1 A_SpawnItem("PB_HellTrooperHead",0,0,0,1);
			Stop;
	}
}

class PB_HellTrooperHead: PB_ZombiemanHead
{
	DEFAULT 
	{
		+ROLLCENTER;
	}
    States
    {
		Spawn:
			TNT1 A 0 {bROLLSPRITE = FALSE;}
			TNT1 A 0 A_Jump(256, "Spawn1", "Spawn2", "Spawn3", "Spawn4");
		Spawn1:
			HTHD A -1;
			Stop;
		Spawn2:
			HTHD B -1;
			Stop;
		Spawn3:
			HTHD A -1{bYFLIP = true;}
			Stop;
		Spawn4:
			HTHD B -1{bXFLIP = true;}
			Stop;
	
		Death.Trample:
		Death.Stomp:
			TNT1 A 0; //A_GiveToTarget("BootsSmearedWithRedBlood", 6)
			Goto Death;
		Death:
			TNT1 A 0;
			TNT1 A 0 {
				bYFLIP = false;
				bXFLIP = false;
			}
			TNT1 A 0 A_SpawnItem("ShotgunguyHeadExplode");
			Stop;
		Crush:
			TNT1 A 0 {
				bYFLIP = false;
				bXFLIP = false;
			}
			TNT1 AAAAAAAA 0 A_SpawnProjectile ("NashGoreClassicBloodTrail", 0, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH, random (60, 140));
			TNT1 A 0 A_StartSound("misc/xdeath4");
			CRS1 B 5;
			CRS1 B -1;
			Stop;
		Death.plasma:
			TNT1 A 0 {
				bYFLIP = false;
				bXFLIP = false;
			}
			TNT1 A 0 A_SpawnProjectile ("PB_XDeathBurnedSkull", 32, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH, random (0, 160));
			EXPL A 0 A_SpawnProjectile ("ExplosionSmoke", 32, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH, random (0, 360));
			Stop;
		Death.Melee:
		Death.SuperPunch:
		Death.Kick:
			TNT1 A 0 {
				bYFLIP = false;
				bXFLIP = false;
			}
			HTHD AA 1 A_FaceTarget();
			TNT1 AAAA 0 A_SpawnItemEx("NashGoreBlood", 0, 0, 10);
			TNT1 A 0 A_SpawnProjectile ("PB_XDeathHellTrooperHeadKicked", 5, 0, random (170, 190), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH, random (20, 30));
			TNT1 A 0 A_StartSound("misc/xdeath4", 1);
			TNT1 A 20;
			Stop;
		
		Pain:
			TNT1 A 0;
			TNT1 A 0 {
				bYFLIP = false;
				bXFLIP = false;
				bROLLSPRITE = TRUE;
			}
			TNT1 A 0 ThrustThingZ(0,20,0,1);
			HTHD AAAAAAAA 2 {
			A_SetRoll(roll-30);
			}
			Goto Spawn;
		
		Death.ExplosiveImpact:
			TNT1 A 0;
			TNT1 A 0 {
				bYFLIP = false;
				bXFLIP = false;
				bROLLSPRITE = TRUE;
			}
			TNT1 A 0 {A_ChangeLinkFlags(False);}
			TNT1 A 0 ThrustThingZ(0,50,0,1);
			HTHD AAAA 2 {
			A_SetRoll(roll-30);
			}
			XDT5 I 0 A_SpawnItem("PB_NaziHead");
			Stop;
	}
}

class PB_XDeathHellTrooperHeadKicked: PB_XDeathHellTrooperHead
{
	Default
	{
		Speed 9;
	}
}

class PB_XDeathHellTrooperHeadOnXDeath: PB_XDeathHellTrooperHead
{
	States
	{
		Spawn:
			TNT1 A 1 A_jump(96, "ExplodeOnAir");
			Goto Spawn1;
		ExplodeOnAir:
			TNT1 A 0 A_SpawnItem("ShotgunguyHeadExplode");
			Stop;
	}
}


class PB_Teeth : PB_TinyGibBase
{
	Default
	{
		Height 2;
		Radius 2;
		Speed 6;
		Scale 0.15;
		+DOOMBOUNCE;
		-NOGRAVITY;
		+WINDTHRUST;
		//+CLIENTSIDEONLY;
		+MOVEWITHSECTOR;
		+MISSILE;
		+NOBLOCKMAP;
		-DROPOFF;
		+NOTELEPORT;
		+FORCEXYBILLBOARD;
		+NOTDMATCH;
		+THRUACTORS;
		+GHOST;
   }
   States
   {
	   Spawn:
		  XTET ABCDEFGHABCDEFGHABCDEFGHABCDEFGHABCDEFGHABCDEFGH 3;
		  Stop;
	   Death:
			LCPJ A 0 A_Jump(256,"Rest1","Rest2");
			Goto Rest1;
		Rest1:
			XTET C -1;
			Stop;
		Rest2:
			XTET G -1;
			Stop;
   }
}


class PB_TeethNoBounce: PB_Teeth
{
	Default
	{
		-DOOMBOUNCE;
	}
}


Class PB_Intestine : PB_TinyGibBase
{
	Default
	{
		Radius 8;
		Height 12;
		Speed 9;
		Mass 5;
		Renderstyle "Translucent";
		Alpha 0.9;
		Gravity 0.5;
		+NOBLOCKMAP;
		+MISSILE;
		+NOTELEPORT;
		+MOVEWITHSECTOR;
		//+CLIENTSIDEONLY;
		+FORCEXYBILLBOARD;
		+RollSprite;
		-EXPLODEONWATER;
		DeathSound "misc/xdeath2";
		Decal "BrutalBloodSplat";
		Scale 0.8;
	}
    States
    {
		Spawn:
			TNT1 A 0;
			GUTS A 1 A_Jump(256, "Spawn1", "Spawn2");
		Spawn1:
			TNT1 A 0 A_SetScale(frandom(0.55,0.85),frandom(0.85,0.85));
			GUTS ABCDEFGHIJ 1 A_SetRoll(roll+10,SPF_INTERPOLATE);
		Spawn1_Flying:
			GUTS J 3 A_SetRoll(roll+10,SPF_INTERPOLATE);
			Loop;
		Spawn2:
			TNT1 A 0 A_SetScale(frandom(0.35,1.15),frandom(0.85,1.25));
			GUTS ABCDEFGHIJ 1 A_SetRoll(roll-10,SPF_INTERPOLATE);
		Spawn2_Flying:
			GUTS J 3 A_SetRoll(roll-10,SPF_INTERPOLATE);
			Loop;
			
	
		Death:
			"####" "#" 0 A_JumpIf(waterlevel > 1, "Water");
			"####" "#" 2 A_CheckFloor("Rest");
			Loop;
		Rest:
			TNT1 A 0 A_SetRoll(0);
			TNT1 A 0 A_Jump(255, "Rest1", "Rest2");
		Rest1:
			GUTS K -1;
			Stop;
		Rest2:
			GUTS L -1;
			Stop;
		Rest3:
			GUTS K 1 {bSPRITEFLIP = true;}
			GUTS K -1;
			Stop;
		Rest4:
			GUTS L 1 {bSPRITEFLIP = true;}
			GUTS L -1;
			Stop;
		
		Water:
			TNT1 A 0 A_Jump(128, "Water2");
		Water1:
			GUTS GH 10 A_SetRoll(roll+20);
			Loop;
		Water2:
			GUTS IJ 10 A_SetRoll(roll-20);
			Loop;
    }
}

class PB_Intestine2: PB_Intestine
{
	Default
	{
		Speed 12;
	}
}

class PB_XDeathHalfZombieman : PB_GibBase
{
	Default
	{
		Radius 8;
		Height 8;
		Scale 1.0;
		Speed 6;
		Mass 4;
		Decal "BrutalBloodSplat";
		BounceFactor 0.2;
		+DOOMBOUNCE;
		+MISSILE;
		+MOVEWITHSECTOR;
		//+CLIENTSIDEONLY;
		+NOBLOCKMAP;
		+NOTELEPORT;
	}
    States
    {
		Spawn:
			TNT1 A 0 A_SpawnItem("NashgoreBloodSpot",0,0,0,1);
			POSX P 12;
			Loop;
		Death:
			TNT1 A 0 A_SpawnItem("NashgoreBloodSpot",0,0,0,1);
			POSX F 1 A_SpawnItem("PB_Gib_HalfZombieMan",0,0,0,1);
			Stop;
    }
}


class PB_XDeathHalfPlasmaZombie : PB_GibBase
{
	Default
	{
		Radius 8;
		Height 8;
		Scale 1.0;
		Speed 6;
		Mass 4;
		Decal "BrutalBloodSplat";
		BounceFactor 0.2;
		+DOOMBOUNCE;
		+MISSILE;
		+MOVEWITHSECTOR;
		//+CLIENTSIDEONLY;
		+NOBLOCKMAP;
		+NOTELEPORT;
	}
    States
    {
		Spawn:
			TNT1 A 0 A_SpawnItem("NashgoreBloodSpot",0,0,0,1);
			PZ07 F 12;
			Loop;
		Death:
			TNT1 A 0 A_SpawnItem("NashgoreBloodSpot",0,0,0,1);
			PZ07 F 1 A_SpawnItem("PB_Gib_HalfPlasmaZombie",0,0,0,1);
			Stop;
    }
}

class PB_XDeathHalfPlasmaZombie2 : PB_GibBase
{
	Default
	{
		Radius 8;
		Height 8;
		Scale 1.0;
		Speed 6;
		Mass 4;
		Decal "BrutalBloodSplat";
		BounceFactor 0.2;
		+DOOMBOUNCE;
		+MISSILE;
		+MOVEWITHSECTOR;
		//+CLIENTSIDEONLY;
		+NOBLOCKMAP;
		+NOTELEPORT;
	}
    States
    {
		Spawn:
			TNT1 A 0 A_SpawnItem("NashgoreBloodSpot",0,0,0,1);
			PZ06 A 12;
			Loop;
		Death:
			TNT1 A 0 A_SpawnItem("NashgoreBloodSpot",0,0,0,1);
			PZ06 A 1 A_SpawnItem("PB_Gib_HalfPlasmaZombie2",0,0,0,1);
			Stop;
    }
}

class PB_XDeathHalfARZombieman : PB_XDeathHalfZombieman
{
    States
    {
		Spawn:
			TNT1 A 0 A_SpawnItem("NashgoreBloodSpot",0,0,0,1);
			ROSX F 12;
			Loop;
		Death:
			TNT1 A 0 A_SpawnItem("NashgoreBloodSpot",0,0,0,1);
			ROSX G 1 A_SpawnItem("PB_Gib_HalfARZombieMan",0,0,0,1);
			Stop;
    }
}

//
class PB_XDeathHalfZombieScientistChainsaw : PB_XDeathHalfZombieman
{
    States
    {
		Spawn:
			TNT1 A 0 A_SpawnItem("NashgoreBloodSpot",0,0,0,1);
			5OSX F 12;
			Loop;
		Death:
			TNT1 A 0 A_SpawnItem("NashgoreBloodSpot",0,0,0,1);
			5OSX G 1 A_SpawnItem("PB_Gib_HalfZombieScientistChainsaw",0,0,0,1);
			Stop;
    }
}

class PB_XDeathHalfZombieScientist : PB_XDeathHalfZombieman
{
    States
    {
		Spawn:
			TNT1 A 0 A_SpawnItem("NashgoreBloodSpot",0,0,0,1);
			LOSX F 12;
			Loop;
		Death:
			TNT1 A 0 A_SpawnItem("NashgoreBloodSpot",0,0,0,1);
			LOSX G 1 A_SpawnItem("PB_Gib_HalfZombieScientist",0,0,0,1);
			Stop;
    }
}

class PB_XDeathHalfZombieScientistChainsaw2 : PB_XDeathHalfZombieman
{
    States
    {
		Spawn:
			TNT1 A 0 A_SpawnItem("NashgoreBloodSpot",0,0,0,1);
			5OSX A 12;
			Loop;
		Death:
			TNT1 A 0 A_SpawnItem("NashgoreBloodSpot",0,0,0,1);
			5OSX B 1 A_SpawnItem("PB_Gib_HalfZombieScientistChainsaw2",0,0,0,1);
			Stop;
    }
}

class PB_XDeathHalfZombieScientist2 : PB_XDeathHalfZombieman
{
    States
    {
		Spawn:
			TNT1 A 0 A_SpawnItem("NashgoreBloodSpot",0,0,0,1);
			LP06 F 12;
			Loop;
		Death:
			TNT1 A 0 A_SpawnItem("NashgoreBloodSpot",0,0,0,1);
			LP06 G 1 A_SpawnItem("PB_Gib_HalfZombieScientist2",0,0,0,1);
			Stop;
    }
}


class PB_XDeathHalfSergeant1: PB_XDeathHalfZombieman
{
    States
    {
		Spawn:
			TNT1 A 0 A_SpawnItem("NashgoreBloodSpot",0,0,0,1);
			SZR1 A 12;
			Loop;
		Death:
			TNT1 A 0 A_SpawnItem("NashgoreBloodSpot",0,0,0,1);
			SZR1 B 1 A_SpawnItem("PB_Gib_HalfSergeant1",0,0,0,1);
			Stop;
    }
}

class PB_XDeathHalfHelmetSergeant1: PB_XDeathHalfZombieman
{
    States
    {
		Spawn:
			TNT1 A 0 A_SpawnItem("NashgoreBloodSpot",0,0,0,1);
			SZR2 A 12;
			Loop;
		Death:
			TNT1 A 0 A_SpawnItem("NashgoreBloodSpot",0,0,0,1);
			SZR2 B 1 A_SpawnItem("PB_Gib_HalfHelmetSergeant1",0,0,0,1);
			Stop;
    }
}

class PB_XDeathHalfNazi1: PB_XDeathHalfZombieman
{
    States
    {
		Spawn:
			TNT1 A 0 A_SpawnItem("NashgoreBloodSpot",0,0,0,1);
			NZH1 A 12;
			Loop;
		Death:
			TNT1 A 0 A_SpawnItem("NashgoreBloodSpot",0,0,0,1);
			NZH1 B 1 A_SpawnItem("PB_Gib_HalfNazi1",0,0,0,1);
			Stop;
    }
}

class PB_XDeathHalfZombieman2 : PB_XDeathHalfZombieman
{
    States
    {
		Spawn:
			TNT1 A 0 A_SpawnItem("NashgoreBloodSpot",0,0,0,1);
			PP2X F 12;
			Loop;
		Death:
			TNT1 A 0 A_SpawnItem("NashgoreBloodSpot",0,0,0,1);
			PP2X F 1 A_SpawnItem("PB_Gib_HalfZombieMan2",0,0,0,1);
			Stop;
    }
}

class PB_XDeathHalfARZombieman2 : PB_XDeathHalfZombieman
{
    States
    {
		Spawn:
			TNT1 A 0 A_SpawnItem("NashgoreBloodSpot",0,0,0,1);
			RP2X F 12;
			Loop;
		Death:
			TNT1 A 0 A_SpawnItem("NashgoreBloodSpot",0,0,0,1);
			RP2X F 1 A_SpawnItem("PB_Gib_HalfARZombieMan2",0,0,0,1);
			Stop;
    }
}

class PB_XDeathHalfHelmetZombieman : PB_XDeathHalfZombieman
{
    States
    {
		Spawn:
			TNT1 A 0 A_SpawnItem("NashgoreBloodSpot",0,0,0,1);
			4OSX F 12;
			Loop;
		Death:
			TNT1 A 0 A_SpawnItem("NashgoreBloodSpot",0,0,0,1);
			4OSX F 1 A_SpawnItem("PB_Gib_HalfHelmetZombieMan",0,0,0,1);
			Stop;
    }
}

class PB_XDeathHalfHelmetZombieman2 : PB_XDeathHalfZombieman
{
    States
    {
		Spawn:
			TNT1 A 0 A_SpawnItem("NashgoreBloodSpot",0,0,0,1);
			4P2X F 12;
			Loop;
		Death:
			TNT1 A 0 A_SpawnItem("NashgoreBloodSpot",0,0,0,1);
			4P2X F 1 A_SpawnItem("PB_Gib_HalfHelmetZombieMan2",0,0,0,1);
			Stop;
    }
}

//
Class PB_Gib_HalfSergeant1: PB_GibBase
{
    States
    {
		Spawn:
			SZR1 B 1 A_SpawnItem("NashgoreBloodSpot",0,0,0,1);
			SZR1 B -1;
			Stop;
	}
}


Class PB_Gib_HalfNazi1: PB_GibBase
{
    States
    {
		Spawn:
			NZH1 B 1 A_SpawnItem("NashgoreBloodSpot",0,0,0,1);
			NZH1 B -1;
			Stop;
		Death:
			TNT1 AAAAAAA 0 A_SpawnProjectile ("PB_XDeathSkinPiece2", 5, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH, random (0, 160));
			TNT1 AAAA 0 A_SpawnProjectile ("PB_XDeathSkinPiece1", 5, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH, random (0, 160));
			TNT1 AAAA 0 A_SpawnProjectile ("PB_SmallGib", 10, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH, random (10, 170));
			TNT1 AA 0 A_SpawnProjectile ("NashGoreBlood", 10, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH, random (30, 90));
			TNT1 AA 0 A_SpawnProjectile ("PB_XDeath1", 0, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH, random (0, 160));
			TNT1 A 0 A_SpawnProjectile ("PB_XDeathNaziHead", 0, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH, random (0, 160));
			TNT1 AA 0 A_SpawnProjectile ("PB_NaziArm", 0, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH, random (0, 160));
			Stop;
		Death.Trample:
		Death.Crush:
		Death.Stomp:
		Death.SuperPunch:
		Death.ExtremePunches:
			 TNT1 AAA 0 A_SpawnProjectile ("PB_XDeath1", 5, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH, random (0, 30));
			 TNT1 AAAA 0 A_SpawnProjectile ("NashGoreBlood", 5, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH, random (0, 30));
			 TNT1 AAAAAAA 0 A_SpawnProjectile ("PB_XDeathSkinPiece2", 5, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH, random (10, 30));
			 TNT1 AAAA 0 A_SpawnProjectile ("PB_XDeathSkinPiece1", 5, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH, random (10, 130));
			 TNT1 AAAA 0 A_SpawnProjectile ("PB_SmallGib", 10, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH, random (10, 30));
			 TNT1 A 0 A_SpawnProjectile ("PB_XDeathNaziHead", 0, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH, random (0, 30));
			 TNT1 AA 0 A_SpawnProjectile ("PB_NaziArm", 0, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH, random (0, 30));
			 XME2 L 1;
			 XME2 L -1;
			 Stop;
	}
}

Class PB_Gib_HalfHelmetSergeant1: PB_GibBase
{
    States
    {
		Spawn:
			SZR2 B 1 A_SpawnItem("NashgoreBloodSpot",0,0,0,1);
			SZR2 B -1;
			Stop;
	}
}


Class PB_Gib_HalfPlasmaZombie: PB_GibBase
{
    States
    {
		Spawn:
			PZ07 G 1 A_SpawnItem("NashgoreBloodSpot",0,0,0,1);
			PZ07 G -1;
			Stop;
	}
}


Class PB_Gib_HalfPlasmaZombie2: PB_GibBase
{
	
	override void BeginPlay(void)
	{
		ChangeStatNum(STAT_NashGore_Gore);
		NashGoreStatics.QueueGore();
		//NashGoreStatics.RandomXFlip(self);
		Super.BeginPlay();
	}

    States
    {
		Spawn:
			PZ06 B 1 A_SpawnItem("NashgoreBloodSpot",0,0,0,1);
			PZ06 B -1;
			Stop;
	}
}

Class PB_Gib_HalfZombieMan: PB_GibBase
{
    States
    {
		Spawn:
			POSX F 1 A_SpawnItem("NashgoreBloodSpot",0,0,0,1);
			POSX F -1;
			Stop;
	}
}

Class PB_Gib_HalfARZombieMan: PB_GibBase
{
    States
    {
		Spawn:
			ROSX G 1 A_SpawnItem("NashgoreBloodSpot",0,0,0,1);
			ROSX G -1;
			Stop;
	}
}

Class PB_Gib_HalfZombieScientistChainsaw : PB_Gibbase
{
    States
    {
		Spawn:
			5OSX G 1 A_SpawnItem("NashgoreBloodSpot",0,0,0,1);
			5OSX G -1;
			Stop;
	}
}

Class PB_Gib_HalfZombieScientist: PB_GibBase
{
    States
    {
		Spawn:
			LOSX G 1 A_SpawnItem("NashgoreBloodSpot",0,0,0,1);
			LOSX G -1;
			Stop;
	}
}

Class PB_Gib_HalfZombieScientistChainsaw2 : PB_GibBase
{
    States
    {
		Spawn:
			5OSX A 1 A_SpawnItem("NashgoreBloodSpot",0,0,0,1);
			5OSX B -1;
			Stop;
	}
}

Class PB_Gib_HalfZombieScientist2: PB_GibBase
{
    States
    {
		Spawn:
			LP06 G 1 A_SpawnItem("NashgoreBloodSpot",0,0,0,1);
			LP06 G -1;
			Stop;
	}
}

Class PB_Gib_HalfZombieMan2: PB_GibBase
{
    States
    {
		Spawn:
			PP2X G 1 A_SpawnItem("NashgoreBloodSpot",0,0,0,1);
			PP2X G -1;
			Stop;
	}
}

Class PB_Gib_HalfARZombieMan2: PB_GibBase
{
    States
    {
		Spawn:
			RP2X G 1 A_SpawnItem("NashgoreBloodSpot",0,0,0,1);
			RP2X G -1;
			Stop;
	}
}

Class PB_Gib_HalfHelmetZombieMan: PB_GibBase
{
    States
    {
		Spawn:
			4OSX F 1 A_SpawnItem("NashgoreBloodSpot",0,0,0,1);
			4OSX F -1;
			Stop;
	}
}

Class PB_Gib_HalfHelmetZombieMan2: PB_GibBase
{
    States
    {
		Spawn:
			4P2X G 1 A_SpawnItem("NashgoreBloodSpot",0,0,0,1);
			4P2X G -1;
			Stop;
	}
}

Class PB_RipZombieMan : PB_GibBase
{
	Default
	{
		Radius 1;
		Height 1;
		Scale 0.8;
		Speed 0;
		Mass 1;
		Decal "BloodSuper";
		BounceFactor 0.5;
		+DOOMBOUNCE;
		+MISSILE;
		+NOBLOCKMAP;
		+NOTELEPORT;
		+MOVEWITHSECTOR;
		+NOGRAVITY;
		+NOCLIP;
		+DONTSPLASH;
	}
    States
    {
    Spawn:
		TNT1 AAA 0 A_SpawnProjectile ("PB_BloodMist", 40, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH, random (0, 160));
		TNT1 A 0 A_SpawnProjectile ("PB_XDeathHalfZombieMan", 32, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH, random (0, 160));
		TNT1 AAAAAAAA 0 A_SpawnProjectile ("PB_Intestine", 32, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH, random (0, 160));
	Death:
	    TNT1 A 0;
        Stop;
    }
}

Class PB_RipSergeant1 : PB_GibBase
{
	Default
	{
		Radius 1;
		Height 1;
		Scale 0.8;
		Speed 0;
		Mass 1;
		Decal "BloodSuper";
		BounceFactor 0.5;
		+DOOMBOUNCE;
		+MISSILE;
		+NOBLOCKMAP;
		+NOTELEPORT;
		+MOVEWITHSECTOR;
		+NOGRAVITY;
		+NOCLIP;
		+DONTSPLASH;
	}
    States
    {
    Spawn:
		TNT1 AAA 0 A_SpawnProjectile ("PB_BloodMist", 40, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH, random (0, 160));
		TNT1 A 0 A_SpawnProjectile ("PB_XDeathHalfSergeant1", 32, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH, random (0, 160));
		TNT1 AAAAAAAA 0 A_SpawnProjectile ("PB_Intestine", 32, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH, random (0, 160));
	Death:
	    TNT1 A 0;
        Stop;
    }
}

Class PB_RipARZombieMan : PB_GibBase
{
	Default
	{
		Radius 1;
		Height 1;
		Scale 0.8;
		Speed 0;
		Mass 1;
		Decal "BloodSuper";
		BounceFactor 0.5;
		+DOOMBOUNCE;
		+MISSILE;
		+NOBLOCKMAP;
		+NOTELEPORT;
		+MOVEWITHSECTOR;
		+NOGRAVITY;
		+NOCLIP;
		+DONTSPLASH;
	}
    States
    {
    Spawn:
		TNT1 AAA 0 A_SpawnProjectile ("PB_BloodMist", 40, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH, random (0, 160));
		TNT1 A 0 A_SpawnProjectile ("PB_XDeathHalfARZombieMan", 32, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH, random (0, 160));
		TNT1 AAAAAAAA 0 A_SpawnProjectile ("PB_Intestine", 32, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH, random (0, 160));
	Death:
	    TNT1 A 0;
        Stop;
    }
}


Class PB_RipPlasmaZombie : PB_GibBase
{
	Default
	{
		Radius 1;
		Height 1;
		Scale 0.8;
		Speed 0;
		Mass 1;
		Decal "BloodSuper";
		BounceFactor 0.5;
		+DOOMBOUNCE;
		+MISSILE;
		+NOBLOCKMAP;
		+NOTELEPORT;
		+MOVEWITHSECTOR;
		+NOGRAVITY;
		+NOCLIP;
		+DONTSPLASH;
	}
    States
    {
    Spawn:
		TNT1 AAA 0 A_SpawnProjectile ("PB_BloodMist", 40, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH, random (0, 160));
		TNT1 A 0 A_SpawnProjectile ("PB_XDeathHalfPlasmaZombie", 32, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH, random (0, 160));
		TNT1 AAAAAAAA 0 A_SpawnProjectile ("PB_Intestine", 32, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH, random (0, 160));
	Death:
	    TNT1 A 0;
        Stop;
    }
}

Class PB_RipPlasmaZombie2 : PB_GibBase
{
	Default
	{
		Radius 1;
		Height 1;
		Scale 0.8;
		Speed 0;
		Mass 1;
		Decal "BloodSuper";
		BounceFactor 0.5;
		+DOOMBOUNCE;
		+MISSILE;
		+NOBLOCKMAP;
		+NOTELEPORT;
		+MOVEWITHSECTOR;
		+NOGRAVITY;
		+NOCLIP;
		+DONTSPLASH;
	}
    States
    {
    Spawn:
		TNT1 AAA 0 A_SpawnProjectile ("PB_BloodMist", 40, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH, random (0, 160));
		TNT1 A 0 A_SpawnProjectile ("PB_XDeathHalfPlasmaZombie2", 32, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH, random (0, 160));
		TNT1 AAAAAAAA 0 A_SpawnProjectile ("PB_Intestine", 32, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH, random (0, 160));
	Death:
	    TNT1 A 0;
        Stop;
    }
}

Class PB_RipZombieMan2 : PB_RipZombieMan
{
    States
    {
    Spawn:
		TNT1 AAA 0 A_SpawnProjectile ("PB_BloodMist", 40, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH, random (0, 160));
		TNT1 A 0 A_SpawnProjectile ("PB_XDeathHalfZombieMan2", 32, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH, random (0, 160));
		TNT1 AAAAAAAA 0 A_SpawnProjectile ("PB_Intestine", 32, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH, random (0, 160));
	Death:
	    TNT1 A 0;
        Stop;
    }
}

Class PB_RipZombieScientistChainsaw : PB_RipZombieMan
{
    States
    {
    Spawn:
		TNT1 AAA 0 A_SpawnProjectile ("PB_BloodMist", 40, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH, random (0, 160));
		TNT1 A 0 A_SpawnProjectile ("PB_XDeathHalfZombieScientistChainsaw", 32, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH, random (0, 160));
		TNT1 AAAAAAAA 0 A_SpawnProjectile ("PB_Intestine", 32, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH, random (0, 160));
	Death:
	    TNT1 A 0;
        Stop;
    }
}

Class PB_RipZombieScientist : PB_RipZombieMan
{
    States
    {
    Spawn:
		TNT1 AAA 0 A_SpawnProjectile ("PB_BloodMist", 40, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH, random (0, 160));
		TNT1 A 0 A_SpawnProjectile ("PB_XDeathHalfZombieScientist", 32, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH, random (0, 160));
		TNT1 AAAAAAAA 0 A_SpawnProjectile ("PB_Intestine", 32, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH, random (0, 160));
	Death:
	    TNT1 A 0;
        Stop;
    }
}
Class PB_RipZombieScientistChainsaw2 : PB_RipZombieMan
{
    States
    {
    Spawn:
		TNT1 AAA 0 A_SpawnProjectile ("PB_BloodMist", 40, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH, random (0, 160));
		TNT1 A 0 A_SpawnProjectile ("PB_XDeathHalfZombieScientistChainsaw2", 32, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH, random (0, 160));
		TNT1 AAAAAAAA 0 A_SpawnProjectile ("PB_Intestine", 32, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH, random (0, 160));
	Death:
	    TNT1 A 0;
        Stop;
    }
}

Class PB_RipZombieScientist2 : PB_RipZombieMan
{
    States
    {
    Spawn:
		TNT1 AAA 0 A_SpawnProjectile ("PB_BloodMist", 40, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH, random (0, 160));
		TNT1 A 0 A_SpawnProjectile ("PB_XDeathHalfZombieScientist2", 32, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH, random (0, 160));
		TNT1 AAAAAAAA 0 A_SpawnProjectile ("PB_Intestine", 32, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH, random (0, 160));
	Death:
	    TNT1 A 0;
        Stop;
    }
}

Class PB_RipARZombieMan2 : PB_RipZombieMan
{
    States
    {
    Spawn:
		TNT1 AAA 0 A_SpawnProjectile ("PB_BloodMist", 40, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH, random (0, 160));
		TNT1 A 0 A_SpawnProjectile ("PB_XDeathHalfARZombieMan2", 32, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH, random (0, 160));
		TNT1 AAAAAAAA 0 A_SpawnProjectile ("PB_Intestine", 32, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH, random (0, 160));
	Death:
	    TNT1 A 0;
        Stop;
    }
}

Class PB_RipHelmetZombieMan2 : PB_RipZombieMan
{
    States
    {
    Spawn:
		TNT1 AAA 0 A_SpawnProjectile ("PB_BloodMist", 40, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH, random (0, 160));
		TNT1 A 0 A_SpawnProjectile ("PB_XDeathHalfHelmetZombieMan2", 32, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH, random (0, 160));
		TNT1 AAAAAAAA 0 A_SpawnProjectile ("PB_Intestine", 32, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH, random (0, 160));
	Death:
	    TNT1 A 0;
        Stop;
    }
}


Class PB_RipHelmetZombieMan : PB_RipZombieMan
{
    States
    {
		Spawn:
			TNT1 AAA 0 A_SpawnProjectile ("PB_BloodMist", 40, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH, random (0, 160));
			TNT1 A 0 A_SpawnProjectile ("PB_XDeathHalfHelmetZombieMan", 32, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH, random (0, 160));
			TNT1 AAAAAAAA 0 A_SpawnProjectile ("PB_Intestine", 32, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH, random (0, 160));
		Death:
			TNT1 A 0;
			Stop;
    }
}

Class PB_DetectCeilXDeath2 : Actor
{
	Default
	{
		scale 0.4;
		speed 0;
		health 1;
		radius 1;
		height 1;
		Gravity 0.0;
		damage 0;
		Renderstyle "Translucent";
		Alpha 0.95;
		DamageType "Blood";
		+MISSILE;
		//+CLIENTSIDEONLY;
		+NOTELEPORT;
		+NOBLOCKMAP;
		+FORCEXYBILLBOARD;
		+NODAMAGETHRUST;
		-DONTSPLASH;
		+NOGRAVITY;
   }
	States
    {
		Spawn:
			TNT1 A 0 ThrustThingZ(0,25,0,1);
			TNT1 A 2;
			TNT1 A 0 A_SpawnItem("PB_SmearingXDeath2", 0, -25);
			Stop;
		Death:
			TNT1 A 0 A_SpawnProjectile ("PB_CeilXDeath2Checker", -15, 0, 90, 2, 90);
			Stop;
    }
}


class PB_SmearingXDeath2 : PB_GibBase
{
	Default
	{
		Radius 2;
		Height 2;
		Speed 10;
		Mass 1;
		Scale 1.0;
		+NOBLOCKMAP;
		+NOTELEPORT;
		+THRUGHOST;
		//+CLIENTSIDEONLY;
		+DONTSPLASH;
		+MOVEWITHSECTOR;
		-DONTSPLASH;
		+FORCEXYBILLBOARD;
		+QUARTERGRAVITY;
	}
    States
    {
		Spawn:
		TNT1 A 0 {
			bNOGRAVITY = true;
			A_Recoil(-25);
		}
		TNT1 A 0 A_Jump(255, "Spawn1", "Spawn2", "Spawn3", "Spawn4");
		Goto Spawn1;
		
		Spawn1:
			XME1 GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG 1 A_CheckFloor("Rest");
			Goto Death;
		
		Spawn2:
			XME1 GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG 1 A_CheckFloor("Rest");
			Goto Death;
		
		Spawn3:
			XME1 GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG 1 A_CheckFloor("Rest");
			Goto Death;
		
		Spawn4:
			XME1 GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGgg 1 A_CheckFloor("Rest");
			Goto Death;
		
		Death:
			TNT1 A 0 A_SpawnItem("PB_XDeath2NoStick");
			Stop;
		Rest:
			XME1 E 3 A_SpawnItem("NashgoreBloodSpot",0,0,0,1);
			XME1 E -1;
			Stop;
    }
}


Class PB_XDeathHalfZombiemanNoArmNoHead : PB_GibBase
{
	Default
	{
		Radius 8;
		Height 8;
		Speed 10;
		Gravity 0.7;
		Mass 4;
		Decal "BrutalBloodSplat";
		BounceFactor 0.01;
		+DOOMBOUNCE;
		+MISSILE;
		+MOVEWITHSECTOR;
		//+CLIENTSIDEONLY;
		+NOBLOCKMAP;
		+NOTELEPORT;
		Scale 1.3;
	}
    States
    {
		Spawn:
			TNT1 A 0 A_SpawnItem("NashGoreBloodSpot",0,0,0,1);
			POSX GHIJKLMN 4;
			Loop;
		Death:
			TNT1 A 0 A_SpawnItem("NashGoreBloodSpot",0,0,0,1);
			TNT1 AAA 0 A_SpawnItem("NashgoreBlood", 0, 5);
			TNT1 A 0 A_SpawnItem("PB_Gib_HalfZombiemanNoArmNoHead",0,0,0,1);
			Stop;
    }
}

Class PB_Gib_HalfZombieManNoArmNoHead: PB_GibBase
{
	Default
	{
		Scale 1.3;
	}
    States
    {
		Spawn:
			POSX O -1;
			Stop;
	}
}
	   



Class PB_CeilXDeath2Checker: PB_GibBase
{
	Default
	{
		damagetype "Blood";
		damage 0;
		Radius 0;
		Height 0;
		Speed 400;
		Gravity 0.0;
		Decal "BrutalBloodSuper";
	}
    States
    {
		Spawn:
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Splash");
			TNT1 A 4;
			Stop;
		Splash:
			BLOD A 0;
			stop;
		Death:
			TNT1 A 1 A_SpawnItem("PB_CeilXDeath2",0,0,0,1);
			TNT1 A 5;
			stop;
		Xdeath:
			TNT1 A 1;
			Stop;
    }
}

class PB_CeilXDeath2: PB_GibBase
{
	Default
	{
		+SPAWNCEILING;
		+MOVEWITHSECTOR;
		-DOOMBOUNCE;
		+NOGRAVITY;
		+DontSplash;
		+MISSILE;
		Scale 1.1;
		Renderstyle "Normal";
	}
	states
	{
		Spawn:
			Goto Crash;
		Death:
		Crash:
			TNT1 A 0 A_Jump (255, "Live1", "Live2", "Live3");
			Goto Live1;

		Live1:
			XME1 FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF 3 ThrustThingZ(0,35,0,1);
			Goto Fall;

		Live2:
			XME1 FFFFFFFFFFFFFFFFFFFFFFFFFFFF 3 ThrustThingZ(0,35,0,1);
			Goto Fall;

		Live3:
			XME1 FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF 3 ThrustThingZ(0,35,0,1);
			Goto Fall;

		Fall:
			TNT1 A 0 A_SpawnItem("PB_XDeath2NoStick");
			stop;
		Splash:
			BLOD A 0;
			stop;
	}
}


Class PB_XDeath2NoStick: PB_XDeath1
{
	Default
	{
		//+CLIENTSIDEONLY;
		+DONTSPLASH;
		Speed 0;
		Gravity 0.4;
		DeathSound "misc/xdeath2";
		Decal "BrutalBloodSplat";
		Scale 1.1;
		Radius 1;
		Height 0;
	}
    States
    {
		Spawn:
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Splash");
			TNT1 A 0 A_CheckFloor("Death");
			XME1 H 3;
			Loop;
		Death:
			TNT1 AAAAAAA 0 A_SpawnProjectile ("NashGoreClassicBloodTrail", 0, 0, random (0, 180), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH, random (0, 180));
			XME1 E 1 A_SpawnItem("NashgoreBloodSpot",0,0,0,1);
			XME1 E -1;
			Stop;
    }
}
