enum Bobbing
{
	Bob_Normal,
	Bob_Inverse,
	Bob_Alpha,
	Bob_InverseAlpha,
	Bob_Smooth,
	Bob_InverseSmooth,
}

class PlayerPawnBase : PlayerPawn
{
	const MOVEMENT_FRICTION		= 1.6;
	const MAX_GROUND_SPEED		= 15.1;
	const WALK_SPEED			= 0.5;
	const CROUCH_SPEED			= 0.5;
	const STRAFE_MODIFIER		= 1.33;

	const JUMP_HEIGHT			= 8.0;
	const SET_GRAVITY			= 1.0;

	const DOUBLE_JUMP_HEIGHT	= 1.0;

	const CSLIDE_STRENGTH		= 2.0;
	const CSLIDE_DURATION		= 10;
	
	const DASH_MAX_CHARGE		= 35;
	
	const CMD_MAXVALUE			= 12800; //maximum value of the sidemove/forwardmove vars
	
	double dashDir, dashSpeed;
	int dashTics, dashCharge, airTics;
	bool dJump, waiting;
	
	PB_GlobalStats Stats;
	TextureID dashTex;
	float alphaFade;
	
	bool InSlime;
	int	SlimeSoundCooler;
	
	bool IsTank;
	Property IsTank : IsTank;
	int tankdeathcounter;
	int tankspritecounter;
	bool baseweaponpda;
	
	Actor TankTurretSprite;
	string TankTurretSpriteActor;
	
	Array<String> CollectedWeapons, BaseWeapons;

	array<int> oldPTics;
  	array<int> oldPUTics;
	
	SpriteID skinSprite;
	int skinInd;
	bool hasSkin;
	void checkSkin(){
		let plr = self.player;
		if(plr){
			skinInd = plr.GetSkin();
			hasSkin = skinInd != 0;
			skinSprite = sprite;
		}
	}
	
	///////////////////////////////////
	//Common
	
	//Movement General
	bool	Pain;
	bool	StrafeRunning;
	double	ViewAngleDelta;
	double	ViewPitchDelta;
	float	ActualSpeed;
	float	MaxAirSpeed;
	float 	MaxGroundSpeed;
	float	ZMoveFactor;
	int		AnimateJump;
	int		OldRealFloorZ;
	int		RealFloorZ;
	sector	RealFloor;
	vector2	Acceleration;
	vector3	Acceleration3;
	playerinfo ZMPlayer;
	double 	ssup;
	
	//////////////////
	
	//Jumping
	bool 	BlockJump;
	bool	ZMJumpTics;
	float	FloorAngle;
	int		JumpSoundCooler;
	vector3	FloorNormal;
    uint8 coyoteTime;
	bool dashJumped;
	
	//Double Jump
	bool	BlockDoubleJump;
	bool	CanDoubleJump;
	
	//////////////////
	
	//Crouch Slide
	bool	CanCSlide;
	float	MaximumSlideSpeed;
	int		CSlideStartTime;
	
	//Ledge Grabbing
	bool	LedgeGrabbed;
	float	LedgeAngle;
	int		LedgeHeight;
	bool	LedgeCheck;
	int		LedgeTime;
	int		LedgeHeightMax;
	int		LedgeHeightMin;
	float	FrameTime;
	double	velx;
	double	vely;
	double	velz;
	weapon	ReselectWeapon;
	
	//////////////////
	
	//View Bobbing
	bool	PostLandingBob;
	float	ZMBob;
	
	//Weapon Bobbing
	bool	HoppingBob;
	double	BobRangeMulti;
	double	MaxBob;
	double	MoveRangeMulti;
	double	StillRangeMulti;
	double	XBob;
	double	XBobOffset;
	double	YBob;
	double	YBobOffset;
	float	BobTime;
	vector2 FinalBob;
	
    //Muzzle Flash
    int8 m_MuzzleFlashTimer;
	
	bool Reloading;
	
	Default
    {
		Player.DisplayName "ZMovement Player";
        PainChance 255;
    }

	override int DamageMobj(Actor inflictor, Actor source, int damage, Name mod, int flags, double angle) 
	{
		int result = super.DamageMobj(inflictor, source, damage, mod, flags, angle);
		// Reset damagecount after damage processing to avoid the red flash.
		if(player) player.damagecount = clamp(player.damagecount, 0, 10);
		return result;
	}

	////////////////////////////////////////////////////////////////////////////////////////////////
	////////////////////////////////////////////////////////////////////////////////////////////////
	////																						////
	//// Non-Movement Stuff																		////
	////																						////
	////////////////////////////////////////////////////////////////////////////////////////////////
	////////////////////////////////////////////////////////////////////////////////////////////////
	
	//Because GZDoom's Unit() returns NaN if a vector has no value
	vector3 SafeUnit3(Vector3 VecToUnit)
	{
		if(VecToUnit.Length()) { VecToUnit /= VecToUnit.Length(); }
		return VecToUnit;
	}
	
	vector2 SafeUnit2(Vector2 VecToUnit)
	{
		if(VecToUnit.Length()) { VecToUnit /= VecToUnit.Length(); }
		return VecToUnit;
	}
	
	override void CheckWeaponChange()
	{
		if(reloading && player.PendingWeapon != WP_NOCHANGE) {player.weaponstate |= WF_WEAPONSWITCHOK; reloading = false;}
		Super.CheckWeaponChange();
	}
	Override void PlayerThink()
	{
		let player = self.player;
		UserCmd cmd = player.cmd;
		
		//Set some basic parameters
		if(CheckNotPredicting())
		{
			ActualSpeed = Speed * GetPowerSpeed();
			bNOFRICTION = True;
			GetFloorInfo();
			MaxGroundSpeed = (deathmatch && !pb_forcespmovement) ? 10.1 * ActualSpeed : MAX_GROUND_SPEED * ActualSpeed;
			Pain = InStateSequence(CurState, FindState("Pain"));
			StrafeRunning = abs(cmd.forwardmove) == CMD_MAXVALUE && abs(cmd.sidemove) == CMD_MAXVALUE;
			ZMoveFactor = ZMScale();
		}
		
		//Execute Player tic cycle
		Super.PlayerThink();

		bool wasOnGround = player.onGround;
		Player.OnGround = (Pos.Z <= FloorZ) || bONMOBJ || bMBFBOUNCER || (Player.Cheats & CF_NOCLIP2); // Moved after super call, otherwise it doesn't register.

        if(Player.OnGround) coyoteTime = 3;
        else if(coyoteTime > 0) coyoteTime--;

        // Stick player to ground when going down stairs
        if (wasOnGround && dashtics < 1 && !player.onGround && pos.z - GetZAt() < maxDropOffHeight && vel.z <= 0)
        {
            //player.viewHeight += (pos.z - GetZAt());
            //player.deltaViewHeight -= (pos.z - GetZAt()) / 8;
            //SetZ(GetZAt());
			// may revisit this -BROS_ETT_311
			ssup = max(0,(pos.z-floorz));
			SetOrigin(Vec2OffsetZ(0,0,floorz),true);
            player.onGround = true;
        }

        // I'm not sure how this is done in PlayerPawn
        // Put player back in idle state after moving
        if (!player.cmd.forwardMove && !player.cmd.sideMove && (!player.onGround || !player.vel.Length())) PlayIdle();
		
		//Bob weapon stuff
		BobWeaponAuxiliary();
		
		ExecutionChecker();
		
		//Old values for comparisons
		OldRealFloorZ = RealFloorZ;
	}
	
	bool frozenByExecution;
	void ExecutionChecker()
	{
		if(CheckInventory("ExecutionToken", 1)) {
			SetPlayerProperty(0,1,PROP_TOTALLYFROZEN);
			frozenByExecution = true;
		}
		else if(frozenByExecution) {
			SetPlayerProperty(0,0,PROP_TOTALLYFROZEN);
			frozenByExecution = false;
		}
	}
	
	float GetAlphaFade()
	{
		return alphaFade;
	}
	
	void GetFloorInfo()
	{
		[RealFloorZ, RealFloor] = FloorSector.NextLowestFloorAt(Pos.X, Pos.Y, Pos.Z, FFCF_3DRESTRICT, MaxStepHeight);
		FloorNormal = RealFloor.FloorPlane.Normal;
	}
	
	float GetPowerSpeed()
	{
		float factor = 1.f;
		
		if(!player.morphTics)
		{
			for(let it = Inv; it != null; it = it.Inv)
			{
				factor *= it.GetSpeedFactor();
			}
		}
		
		return factor;
	}
	
	Override void DeathThink()
	{
		bNOFRICTION = False;
		Gravity = SET_GRAVITY;
		
		Super.DeathThink();
	}

    const am_maxBobFreq = 35.0;
	
	Override void CalcHeight()
	{
		let player = self.player;
		UserCmd cmd = player.cmd;
		
		double HeightAngle;
		double bob, bobfreq;
		bool still = false;

		if(!Player.OnGround || (Player.OnGround && ((cmd.buttons & BT_JUMP) && !BlockJump)) || player.cheats & CF_NOCLIP2) //nobody walks in the air
		{
			ZMBob--;
			ZMBob = max(bNOGRAVITY ? 0.5f : 0.f, ZMBob);
			PostLandingBob = True;
            //bobrange = 0;
			bobfreq = 0;
		}
		else
		{
			if(PostLandingBob)
			{
				ZMBob += Vel.XY.Length() / (MaxGroundSpeed ? MaxGroundSpeed : 1.f);
				if(ZMBob >= Vel.XY.Length() * player.GetMoveBob()) { PostLandingBob = False; }
			}
			else
			{
				ZMBob = Vel.XY.Length() * player.GetMoveBob(); //this way all GetMoveBob() values are meaningful
			}

            bobfreq = PB_Math.LinearMap(vel.xy.length(), 0, 15, 0, am_maxBobFreq, true);
			//bobrange = PB_Math.LinearMap(hvel, 0, maxvel, 0, am_viewBobRangeVert, true);
			
			if(!ZMBob)
				still = true;
			else
				ZMBob = min(MaxGroundSpeed, ZMBob);
		}

        am_prevbobphase = am_bobphase;
		am_bobphase += bobfreq;

		double defaultviewheight = ViewHeight + player.crouchviewdelta;

		if(player.cheats & CF_NOVELOCITY)
		{
			player.viewz = pos.Z + defaultviewheight;

			if(player.viewz > ceilingz-4)
				player.viewz = ceilingz-4;

			return;
		}

		if(still)
		{
			if(player.health > 0)
			{
				HeightAngle = Level.maptime / (120 * TICRATE / 35.) * 360.;
				bob = player.GetStillBob() * sin(HeightAngle);
			}
			else
			{
				bob = 0;
			}
		}
		else
		{
			HeightAngle = Level.maptime / 20. * 360.;
			bob = ZMBob * cos(am_bobphase * 0.5) * (waterlevel > 2 ? 0.0625f : 0.125f);
		}
		
		if(player.morphTics) { bob = 0; }
		
		//////////////////////////////////////////////////////
		// Customizable Landing
		
		if(player.playerstate == PST_LIVE)
		{
			player.viewheight += player.deltaviewheight;

			if(player.viewheight > defaultviewheight)
			{
				player.viewheight = defaultviewheight;
				player.deltaviewheight = 0;
			}
			else if(player.viewheight < (defaultviewheight/2))
			{
				player.viewheight = defaultviewheight/2;
				if(player.deltaviewheight <= 0)
					player.deltaviewheight = 1 / 65536.;
			}
			
			if(player.deltaviewheight)	
			{
				player.deltaviewheight += 0.25;
				if(!player.deltaviewheight) { player.deltaviewheight = 1/65536.; }
			}
		}
		
		//Let's highlight the important stuff shall we?
		player.viewz = pos.Z + player.viewheight + (bob * clamp(ViewBob, 0., 1.5)); // [SP] Allow DECORATE changes to view bobbing speed.
		// handle smooth step down (hacky but looks ok)
		player.viewz += ssup;
		ssup = max(0,(ssup*0.7)-0.25);
		
		if(Floorclip && player.playerstate != PST_DEAD && pos.Z <= floorz) { player.viewz -= Floorclip; }
		if(player.viewz > ceilingz - 4) { player.viewz = ceilingz - 4; }
		if(player.viewz < FloorZ + 4) { player.viewz = FloorZ + 4; }
	}
	
	Override void CheckPitch()
	{
		let player = self.player;
		
		int clook = player.cmd.pitch;
		if(clook != 0)
		{
			if(clook == -32768)
			{
				player.centering = true;
			}
			else if(!player.centering)
			{
				Pitch = clamp(Pitch - clook * (360. / 65536.), player.MinPitch, player.MaxPitch);
			}
		}
		
		if(player.centering)
		{
			if(abs(Pitch) > 2.)
			{
				Pitch *= (2. / 3.);
			}
			else
			{
				Pitch = 0.;
				player.centering = false;
				if(PlayerNumber() == consoleplayer)
				{
					LocalViewPitch = 0;
				}
			}
		}
	}

	bool CheckNotPredicting()
	{
		return self && player && !(player.cheats & CF_PREDICTING);
	}
	
	////////////////////////////////////////////////////////////////////////////////////////////////
	////////////////////////////////////////////////////////////////////////////////////////////////
	////																						////
	//// Movement Stuff																			////
	////																						////
	////////////////////////////////////////////////////////////////////////////////////////////////
	////////////////////////////////////////////////////////////////////////////////////////////////
	void ForceMoveUnlock()
    {
        LedgeCheck = false;
    }
	Override void HandleMovement()
	{
		let player = self.player;
		UserCmd cmd = Player.cmd;
		
		//Slime Dissolving sound effect
		if(CheckNotPredicting())
			CheckSlime();

		if (SlimeSoundCooler) 
		{
			SlimeSoundCooler--;
		}
		if(InSlime == true)
		{
			if(!SlimeSoundCooler && CheckNotPredicting())
			{
				A_Startsound("world/barrelloop", 12, CHANF_LOOPING  );
				SlimeSoundCooler = 8;
			}
		}
		
		// [RH] Check for fast turn around
		if(player.cmd.buttons & BT_TURN180 && !(player.oldbuttons & BT_TURN180)) { player.turnticks = TURN180_TICKS; }

		// Handle movement
		if(reactiontime)
		{ // Player is frozen
			reactiontime--;
		}
		else
		{	
			if(!FindInventory("PlayerWheelOpen") || CVar.GetCVar("gb_time_freeze",player).GetInt() != 1)
			{
				ViewAngleDelta = cmd.Yaw * (360.0 / 65536.0); //needed for two other things
				ViewPitchDelta = cmd.Pitch * (90.0 / 65536.0);
				if(FindInventory("PlayerWheelOpen")) {ViewAngleDelta = 0; ViewPitchDelta = 0;}
			}
			
			if(Player.TurnTicks) //moved here to save many doubled lines
			{
				Player.TurnTicks--;
				Angle += ViewAngleDelta;
			}
			else
			{
				angle += ViewAngleDelta;
				if(LedgeGrabbed) { Angle = clamp(Angle, LedgeAngle - 20, LedgeAngle + 20); }
			}
			
// 			/////////////////////////////////////////
// 			//Acrobatics triggers
			if(!CheckNotPredicting())
				return;
			//Crouchsliding
			CSlideInitiator();
			
			/////////////////////////////////////////
			//Gravity
			DGravity();
			
			/////////////////////////////////////////
			//Actual Movement selection
			if(LedgeCheck && CheckNotPredicting())
			{
				LedgeReach();
			}
			else if(LedgeGrabbed && CheckNotPredicting())
			{
				LedgeGrab();
			}
			else if(WaterLevel >= 2)
			{
				DoomWaterMove();
				
				if(CheckNotPredicting()) 
				{ 
					LedgeGrabInitiator(); 
				}
			}
			else if(bNOGRAVITY)
			{
				DoomFlyMove();
			}
			else if(CanCSlide && CheckNotPredicting())
			{
				CSlideMove();
			}
			else
			{
				DoomHandleMove();
			}
			
			/////////////////////////////////////////
			//Jumping
			CheckJump();
			
			/////////////////////////////////////////
			//Misc
			
			if(cmd.sidemove | cmd.forwardmove)
			{
				if(Player.Cheats & CF_REVERTPLEASE)
				{
					Player.Cheats &= ~CF_REVERTPLEASE;
					Player.Camera = Player.Mo;
				}
			}
			
			CheckMoveUpDown();
		}
	}
	
	void CheckSlime()
	{
		sector sss=floorsector;
		if(player.health > 0 && A_CheckFloor("null") && sss.damagetype == "Slime" && !pb_hazardmovement) {
			InSlime = true;
		}
		else {
			InSlime = false;
			A_StopSound(12);
			SlimeSoundCooler = 0;
		}
	}
	
	
	//////////////////////////////////////////
	// Jumping								//
	//////////////////////////////////////////
	
	void PreJumpCommon()
	{
		let player = self.player;
		
		//Jump Sound Cooler
		if(JumpSoundCooler) { JumpSoundCooler--; }
		
		//Double Jump
		if(Player.OnGround) { CanDoubleJump = True; }
		
		//Jumptics settings
		if(ZMJumpTics && (Player.OnGround || WaterLevel >= 2 || bNOGRAVITY)) { ZMJumpTics = False; }
	}
	
	float GetPowerJump()
	{
		Float JumpFac = 0.f;
		
		for(let p = Inv; p != null; p = p.Inv)
		{
			let pp = PowerHighJump(p);
			if(pp) { JumpFac = max(JumpFac, pp.Strength); }
		}
		
		return JumpFac;
	}
	
	bool, bool CheckIfJumpable()
	{
		if(CeilingZ - RealFloorZ <= Height) //sector is just high enough for player to pass through but not jump
		{
			return True, False;
		}
		else if(FloorSector)
		{
			FloorAngle = atan2(FloorNormal.XY.Length(), FloorNormal.Z);
			
			if(!FloorAngle) //flat surface
			{
				return BlockJump ? True : False, False;
			}
			else
			{
				if(FloorAngle >= 45)
					return Player.OnGround ? True : False, True; //floor is too steep
				else
					return BlockJump ? True : False, True; //you can jump, BUT YOU CANNOT ~~HIDE~~ ELEVATE!!
			}
		}
		else // whatever else
		{
			return BlockJump ? True : False, False;
		}
    }
	
	void DGravity()
	{
		if(WaterLevel >= 2)
		{
			if(Vel.Length() < MaxGroundSpeed / 3.f)
				Gravity = 0.5f;
			else
				Gravity = 0.f;
		}
		else if(bNOGRAVITY)
		{
			Gravity = 0.f;
		}
		else
		{
			Gravity = SET_GRAVITY;
		}
	}
	
	Override void CheckJump()
	{
		let player = self.player;
		
		//Common stuff
		PreJumpCommon();
		
		//underwater/flying specific jump behavior are in WaterMove and FlyMove
		if(WaterLevel >= 2 || bNOGRAVITY) { return; }
		
		//Check slope angle and sector height
		Bool SlopedFloor;
		[BlockJump, SlopedFloor] = CheckIfJumpable();
		
		////////////////////////////////
		//Actual Jump
		if(player.cmd.buttons & BT_JUMP)
		{
			//Special circumstances jump denial
			if(LedgeGrabbed) { return; }
			
			if(player.crouchoffset != 0)
			{
				player.crouching = 1;
			}
			
			//Check if player is above a damaging floor. We don't cheese map design here!
			sector sss=floorsector;
			if(A_CheckFloor("null") && sss.damagetype == "Slime" && !pb_hazardmovement && CheckNotPredicting()) {
				if(!JumpSoundCooler)
					A_StartSound("Daedabus/impact", 32);
					JumpSoundCooler = 4;
				return;
			}
		
			else if(coyoteTime > 0 && !BlockJump)
			{
                coyoteTime = 0;
				Float JumpVelZ = JUMP_HEIGHT;
				Float JumpFac = GetPowerJump();
				if(JumpFac) { JumpVelZ *= JumpFac; }
				
				if(dashCharge >= DASH_MAX_CHARGE / 2 && FindInventory("PlayerDashed") && !FindInventory("Kicking") && !dashJumped) {
					if(!FindInventory("PB_PowerSpeed")) {
						waiting = true;
						dashCharge = 0;
					}
					
					SetOrigin((pos.x, pos.y, pos.z + 1), true);
					dashTics = 0;
					SetInventory("PlayerDashed", 0);
					A_StartSound("JMPBOOT", 33);
					JumpVelZ *= 1.5;
					VelFromAngle(JumpVelZ * 6.5, DashDir);
					dashJumped = true;
				}
				
				Vel.Z = (- FloorNormal.XY dot SafeUnit2(Vel.XY) > 0 ? 1.f + sin(FloorAngle) : 1.f) * JumpVelZ; // - FloorNormal.XY dot SafeUnit2(Vel.XY) > 0 == going uphill on a slope
				
				bOnMobj = false;
				ZMJumpTics = True;
				
				if(CheckNotPredicting() && !JumpSoundCooler)
				{
					A_StartSound("pb/player/jump", 31);
					A_StartSound("*jump", 32);
					JumpSoundCooler = 4;
				}
				
				BlockJump = False;
				BlockDoubleJump = True;
				SetInventory("PlayerDashed", 0);
				dashtics = 0;
			}
			else if(!Player.OnGround && CanDoubleJump && !BlockDoubleJump)
			{
				Float DoubleJumpVelZ = JUMP_HEIGHT * DOUBLE_JUMP_HEIGHT;
				Float JumpFac = GetPowerJump();
				if(JumpFac) { DoubleJumpVelZ *= JumpFac; }
				Vel.Z = DoubleJumpVelZ;
				
				bOnMobj = false;
				ZMJumpTics = True;
				
				if(CheckNotPredicting()) { A_StartSound("JMPBOOT", 32); }
				
				CanDoubleJump = False;
				SetInventory("PlayerDashed", 0);
				dashtics = -5;
			}
		}
		else
		{
			BlockDoubleJump = False;
			BlockJump = False;
		}
	}
	
	override void PlayerLandedMakeGruntSound(actor onmobj)
	{
		bool grunted;

		// [RH] only make noise if alive
		if (self.health > 0 && !Alternative)
		{
			grunted = false;
			// Why should this number vary by gravity?
			if (self.Vel.Z < -self.player.mo.GruntSpeed)
			{
				A_StartSound("*grunt", CHAN_VOICE);
				A_StartSound("pb/player/hitfloor", CHAN_AUTO);
				grunted = true;
			}
			bool isliquid = (pos.Z <= floorz) && GetFloorTerrain().IsLiquid;
			if (onmobj != NULL || !isliquid)
			{
				if (!grunted)
				{
					A_StartSound("*land", CHAN_AUTO);
				}
				else
				{
					A_StartSoundIfNotSame("*land", "*grunt", CHAN_AUTO);
				}
				A_StartSound("pb/player/land", CHAN_AUTO);
			}
		}
	}
	
	//////////////////////////////////////////
	// Ground Movement						//
	//////////////////////////////////////////
	
	float ZMScale()
	{
        // Let Player = self.Player;
		UserCmd cmd = player.cmd;
		
		Bool 	IsWalking = !CheckRunning();
		Float 	MoveMulti;
		
		if(cmd.sidemove || cmd.forwardmove)
		{
			if(Player.CrouchFactor == 0.5)
				MoveMulti = min(CROUCH_SPEED, WALK_SPEED);
			else if(IsWalking)
				MoveMulti = WALK_SPEED;
			else
				MoveMulti = 1;
		}
		else
		{
			MoveMulti = 1; //to fix a bobbing issue
		}
		
		return MoveMulti;
	}
	
	float GroundSpeedMulti(bool SpeedOrAccel)
	{
		return (SpeedOrAccel ? ZMoveFactor : ActualSpeed) * (Straferunning ? STRAFE_MODIFIER : 1);
	}
	
    bool CheckRunning() {
        return (player.cmd.buttons & BT_RUN);
    }
	
	void GroundSpriteAnimation()
	{
		Let Player = Self.Player;
		UserCmd cmd = Player.cmd;
		
		if(Player.Cheats & CF_PREDICTING == 0 && Vel.XY.Length() > 1.f && (cmd.forwardmove || cmd.sidemove))
			PlayRunning();
		else
			PlayIdle();
			
		AnimateJump = 6;
	}
	
	void AirSpriteAnimation()
	{
		if(AnimateJump)
		{
			PlayRunning();
			AnimateJump--;
		}
		else
		{
			PlayIdle();
		}
	}
	
	//////////////////////////////////////////
	// Doom
	
	void DoomHandleMove()
	{
		MaxGroundSpeed *= GroundSpeedMulti(True);
		
		if(!Player.OnGround)
		{
			DoomAirMove();
			LedgeGrabInitiator();
		}
		else
		{
			DoomGroundMove();
		}
	}
	
	void DFriction()
	{
		Let Player = Self.Player;
		UserCmd cmd = Player.cmd;
		
		//Going too slow, stop
		if(WaterLevel >= 2 || bNOGRAVITY)
		{
			if(Vel.Length() < 1.f && !cmd.sidemove && !cmd.forwardmove)
			{
				Vel.XY = (0, 0);
				return;
			}
		}
		else if(Vel.XY.Length() < 1.f && !cmd.sidemove && !cmd.forwardmove)
		{
			Vel.XY = (0, 0);
			return;
		}
		
		//Balance friction with inputs strength
		if(WaterLevel >= 2)
		{
			Acceleration3 *= 4.f;
			Vel *= 0.6f;
		}
		else if(bNOGRAVITY)
		{
			Vel *= 0.9f;
		}
		else
		{
			Acceleration *= MOVEMENT_FRICTION;
			Vel.XY *= 1 - MOVEMENT_FRICTION / 10.f;
		}
	}
	
	void DoomGroundMove()
	{
		let player = self.player;
		UserCmd cmd = player.cmd;
		
		dashJumped = false;
		
		///////////////////////////////////////////
		//Actual Movement
		
		//Directional inputs
		Acceleration = RotateVector((cmd.forwardmove, -cmd.sidemove), Angle);
		Acceleration = (MaxGroundSpeed / 10.f) * SafeUnit2(Acceleration) * min(1.0, (cmd.forwardmove, cmd.sidemove).length() / CMD_MAXVALUE);
		
		//Friction
		DFriction();
		
		//Acceleration
		Vel.XY += Acceleration;
		
		// Sprite Animation
		GroundSpriteAnimation();
	}
	
	void DoomAirMove()
	{
		let player = self.player;
		UserCmd cmd = player.cmd;
		
		///////////////////////////////////////////
		//Actual Movement
		
		//Directional inputs
		Acceleration = RotateVector((cmd.forwardmove, -cmd.sidemove), Angle);
		Acceleration = (MaxGroundSpeed / 20.f) * SafeUnit2(Acceleration) * min(1.0, (cmd.forwardmove, cmd.sidemove).length() / CMD_MAXVALUE);
		
		//Acceleration
		Vel.XY += Acceleration;
		
		//Limiter
		if(dashJumped) {
			Vel.XY *= 0.95;
		}
		else {
			Vel.XY = min(Vel.XY.Length(), MaxGroundSpeed) * SafeUnit2(Vel.XY);
		}
		
		//Sprite Animation
		AirSpriteAnimation();
	}
	
	void WaterVelZLimiter()
	{
		//Avoids dolphin jumping out of water
		Vel.Z = min(6.f, Vel.Z);
		if(Pitch < 0) { Acceleration3.Z = 0; }
	}
	
	void DoomWaterMove()
	{
		Let Player = Self.Player;
		UserCmd cmd = Player.cmd;
		
		//Value Resets
		MaxAirSpeed = Vel.XY.Length();
		
		///////////////////////////////////////////
		//Actual Movement
		
		//Directional inputs
		Acceleration3 = (cmd.forwardmove, -cmd.sidemove, 0);
		//XY
		Acceleration3.XY = (MaxGroundSpeed / 20.f) * SafeUnit2(Acceleration3.XY);
		//Z
		if(cmd.buttons & BT_JUMP || cmd.buttons & BT_CROUCH)
		{
			Acceleration3.Z = (cmd.buttons & BT_JUMP ? 1 : -1) * (MaxGroundSpeed / 20.f) * ActualSpeed;
		}
		else
		{
			Acceleration3.Z = Acceleration3.X * sin(-Pitch);
			Acceleration3.X *= cos(Pitch);
		}
		
		//Friction
		DFriction();
		if(WaterLevel == 2) { WaterVelZLimiter(); }
		
		//Acceleration
		Vel += (RotateVector(Acceleration3.XY, Angle), Acceleration3.Z);
		
		//Sprite Animation
		GroundSpriteAnimation();
	}
	
	void DoomFlyMove()
	{
		Let Player = Self.Player;
		UserCmd cmd = Player.cmd;
		
		//Value Resets
		MaxAirSpeed = Vel.XY.Length();
		
		///////////////////////////////////////////
		//Actual Movement
		
		//Directional inputs
		Acceleration3 = (cmd.forwardmove, -cmd.sidemove, 0);
		//XY
		if(Acceleration3.Length()) { Acceleration3.XY = (MaxGroundSpeed * 3.f / 20.f) * SafeUnit2(Acceleration3.XY); }
		//Z
		if(cmd.buttons & BT_JUMP || cmd.buttons & BT_CROUCH)
		{
			Acceleration3.Z = (cmd.buttons & BT_JUMP ? 1 : -1) * (MaxGroundSpeed * 3.f / 20.f) * ActualSpeed;
		}
		else
		{
			Acceleration3.Z = Acceleration3.X * sin(-Pitch);
			Acceleration3.X *= cos(Pitch);
		}
		
		//Friction
		DFriction();
		
		//Acceleration
		Vel += (RotateVector(Acceleration3.XY, Angle), Acceleration3.Z);
		
		//Limiter
		Vel = min(Vel.Length(), (MaxGroundSpeed * 3.f) / 2.f) * SafeUnit3(Vel);
		
		//Sprite Animatiom
		PlayIdle();
	}
	
	//////////////////////////////////////////
	// Crouching							//
	//////////////////////////////////////////
	
	//////////////////////////////////////////
	// Regular crouching
	
	Override void CheckCrouch(bool totallyfrozen)
	{
		let player = self.player;
		UserCmd cmd = player.cmd;

		if(cmd.buttons & BT_JUMP)
		{
			cmd.buttons &= ~BT_CROUCH;
		}
		
		if(player.health > 0)
		{
			if(!totallyfrozen)
			{
				int crouchdir = player.crouching; // player.crouching from ZMovement 3.2.1
				
				if(bNOGRAVITY || WaterLevel >= 2) //forcefully uncrouch when flying/swimming
					crouchdir = 1; 
				else if(crouchdir == 0) // These will fix crouch toggling. From ZMovement 3.2.1
					crouchdir = (cmd.buttons & BT_CROUCH) ? -1 : 1;
				else if(cmd.buttons & BT_CROUCH) // From ZMovement 3.2.1
					player.crouching = 0;
				
				if(crouchdir == 1 && player.crouchfactor < 1 && pos.Z + height < ceilingz)
					CrouchMove(1);
				else if(crouchdir == -1 && player.crouchfactor > 0.5)
					CrouchMove(-1);
			}
		}
		else
		{
			player.Uncrouch();
		}

		player.crouchoffset = -(ViewHeight) * (1 - player.crouchfactor);
	}
	
	Override void CrouchMove(int direction)
	{
		let player = self.player;
		
		double defaultheight = FullHeight;
		double savedheight = Height;
		double crouchspeed = (CanCSlide ? - 1.5 : direction) * CROUCHSPEED;
		double oldheight = player.viewheight;

		player.crouchdir = direction;
		player.crouchfactor += crouchspeed;

		// check whether the move is ok
		Height  = defaultheight * player.crouchfactor;
		if(!TryMove(Pos.XY, false, NULL))
		{
			Height = savedheight;
			if(direction > 0)
			{
				// doesn't fit
				player.crouchfactor -= crouchspeed;
				return;
			}
		}
		Height = savedheight;

		player.crouchfactor = clamp(player.crouchfactor, 0.5, 1.);
		player.viewheight = ViewHeight * player.crouchfactor;
		player.crouchviewdelta = player.viewheight - ViewHeight;

		// Check for eyes going above/below fake floor due to crouching motion.
		CheckFakeFloorTriggers(pos.Z + oldheight, true);
	}
	
	//////////////////////////////////////////
	// Crouch Sliding
	
	void CSlideInitiator()
	{
		Let Player = Self.Player;
		UserCmd cmd = Player.cmd;
		
		
		//Check if player is above a damaging floor. We don't cheese map design here!
		
		if(WaterLevel >= 2 || bNOGRAVITY) // in the water or flying forbid attempting to start a slide
		{
			CSlideStartTime = 1;
			A_StopSound(32);
			return;
		}
		else if(Player.CrouchFactor == 1 && CSlideStartTime) // reallow attempting to slide after player stands back up
		{
			CSlideStartTime = 0;
			return;
		}
		
		if(Player.OnGround)
		{
			Int BT=cmd.buttons;
			
			bool ct = CVar.GetCVar("pb_bd_slide", Player).GetBool();
			if(Player.CrouchFactor != 1 && !CSlideStartTime && (!ct && BT & BT_RUN || ct && BT & BT_USER4) && CheckNotPredicting())
			{
				sector sss=floorsector;
				if(A_CheckFloor("null") && sss.damagetype == "Slime" && !pb_hazardmovement) {
					return;
				}
				if(cmd.forwardmove || cmd.sidemove)
				{
					//Not enough space for a slide
					FLineTraceData DirTrace;
					Double SlideAngle = Angle - VectorAngle(cmd.forwardmove, cmd.sidemove);
					LineTrace(SlideAngle, Radius * 2, 0, TRF_SOLIDACTORS|TRF_BLOCKSELF, Height * 0.5, data: DirTrace);
					if(DirTrace.Distance < Radius * 2) { return; }
					
					CanCSlide = True;
					A_StartSound("SlideKick/Start",32);
					A_GiveInventory("CanSlideKick");
					MaximumSlideSpeed = CSLIDE_STRENGTH * MaxGroundSpeed;
					Vel.XY = MaximumSlideSpeed * AngleToVector(SlideAngle);
				}
				
				CSlideStartTime = Level.MapTime;
			}
		}
	}
	
	void CSlideMove()
	{
		Let Player = Self.Player;
		UserCmd cmd = player.cmd;
		
		//Value reset
		MaxAirSpeed = MaxGroundSpeed;
		
		///////////////////////////////////////////
		//Actual Movement
		
		//Directional inputs
		Acceleration = RotateVector((cmd.forwardmove, - cmd.sidemove), Angle);
		Acceleration = 2.f * SafeUnit2(Acceleration);
		
		//Friction (if in the air or slide time has run out)
		if(Level.MapTime > CSlideStartTime + CSLIDE_DURATION)
		{
			Int FrictionDiv = abs(GetZAt(0,0) - Pos.Z) > 16 ? 500 : 100;
			MaximumSlideSpeed *= 1 - Vel.XY.Length() / FrictionDiv;
		}
			
		//Acceleration
		Vel.XY += Acceleration;
		
		//Limiter
		Vel.XY = MaximumSlideSpeed * SafeUnit2(Vel.XY);
		
		//Sprite animation
		PlayIdle();
		
		///////////////////////////////////////////
		//Fun is over
		if(WaterLevel >= 2 || bNOGRAVITY || MaximumSlideSpeed <= MaxGroundSpeed)
		{
			CSlideStartTime = 1;
			CanCSlide = False;
			A_StartSound("SlideKick/Stop", 32);
			A_TakeInventory("CanSlideKick");
			return;
		}
		
		//Check imminent collision, only needed if previous check did not pass (save calculations)
		FLineTraceData DirTraceGeometry;
		LineTrace(VectorAngle(Vel.X, Vel.Y), 100, 0, TRF_SOLIDACTORS|TRF_BLOCKSELF, Height, data: DirTraceGeometry);
		
		FLineTraceData DirTraceActor;
		LineTrace(VectorAngle(Vel.X, Vel.Y), 100, 0, TRF_SOLIDACTORS|TRF_BLOCKSELF, 0.f, data: DirTraceActor);
		
		//Only stop if the first hit anything or second hit an actor
		if(DirTraceGeometry.Distance < 100.f || (DirTraceActor.Distance < 100.f && DirTraceActor.HitType == TRACE_HitActor) || player.crouchdir == 1)
		{
			CSlideStartTime = 1;
			CanCSlide = False;
			A_StartSound("SlideKick/Stop", 32);
			A_TakeInventory("CanSlideKick");
		}
	}
	
	//////////////////////////////////////
	// Ledge Grab						//
	//////////////////////////////////////
	
	void LedgeGrabInitiator()
	{
		ZMPlayer = self.player;
		
		if(
			WaterLevel > 2 || CountInv("GrabbedIceBarrel") > 0 || CountInv("GrabbedFlameBarrel") > 0 || CountInv("GrabbedBarrel") > 0 ||
			CountInv("HasIceBarrel") > 0 || CountInv("HasFlameBarrel") > 0 || CountInv("HasBarrel") > 0
		) { return; }
		
		//Already ledge grabbing, no clipping, moving away from where you are looking, ceiling already too low for sure
		if((pos.z <= floorz) || LedgeCheck || LedgeGrabbed || (ZMPlayer.Cheats & CF_NOCLIP2) || Vel.XY dot AngleToVector(Angle) <= 0 || CeilingZ <= Pos.Z + Height * 1.6f) { return; }
		
		//============================================
		//Find ledge (if any)						//
		//============================================
		
		FLineTraceData LedgeTrace;
		Float TraceDistance = sqrt(2) * Radius + 1; //account for the fact that Doom's hitboxes are square
		LineTrace(Angle, TraceDistance, 0, TRF_BLOCKSELF|TRF_THRUACTORS, Height * 1.2f, data: LedgeTrace);
		Vector3 HitPos = LedgeTrace.HitLocation;
		
		Int LedgeCandidate;
		if(LedgeTrace.HitType == TRACE_HitWall) //hit wall scenario
		{
			if(LedgeTrace.Hit3DFloor != NULL) //3D floor
			{
				LedgeCandidate = LedgeTrace.Hit3DFloor.Top.ZAtPoint(HitPos.XY);
			}
			else //regular wall
			{
				Line HitLine = LedgeTrace.HitLine;
				if(HitLine.FrontSector != NULL && HitLine.FrontSector != CurSector)
					LedgeCandidate = HitLine.FrontSector.FloorPlane.ZatPoint(HitPos.XY);
				else if(HitLine.BackSector != NULL && HitLine.BackSector != CurSector)
					LedgeCandidate = HitLine.BackSector.FloorPlane.ZatPoint(HitPos.XY);
			}
		}
		else if(LedgeTrace.HitSector != CurSector)//tracer stopper mid air in a sector that is not the one where player currently is
		{
			LedgeCandidate = LedgeTrace.HitSector.NextLowestFloorAt(HitPos.X, HitPos.Y, HitPos.Z, FFCF_3DRESTRICT, 0);
		}
		else
		{
			return;
		}
		
		//Check if the candidate ledge can suffice
		if(LedgeCandidate > Pos.Z + Height * 0.6f && LedgeCandidate <= Pos.Z + Height * 1.2f)
		{
			Vector3 OrigPos = Pos;
			SetXYZ((Pos.XY, LedgeCandidate));
			if(!CheckMove(Pos.XY + 5.f * AngleToVector(Angle))) //not enough space, cancel everything :(
			{
				SetXYZ(OrigPos);
				return;
			}
			SetXYZ(OrigPos);
			LedgeHeight = LedgeCandidate;
			LedgeHeightMin = (LedgeHeight - Height * 0.97f);
			LedgeHeightMax = (LedgeHeight - Height * 0.751f);
		}
		else
		{
			return; //too high/low
		}
		
		//============================================
		//Abemus ledge, execute						//
		//============================================
		
		//Switch to a weapon that forbids firing during the ledge grab
		
		//Credit Cherno
		//Console.Printf("Num: %f", LedgeHeight);
		
		velz = 8;
		LedgeCheck = True;
		
		if(!player.ReadyWeapon)
		{
			GiveInventory("LedgeGrabWeapon", 1);
			let w = Weapon(FindInventory("LedgeGrabWeapon"));
			if(w) player.ReadyWeapon = w;
		}
		if(vel.length() < 5)
		{
			GiveInventory("Grabbing_A_Ledge", 1);
		}
		if(pos.z >= (LedgeHeightMin+20))
		{
			player.SetPSprite(PSP_WEAPON,player.ReadyWeapon.FindState("FinishClimb"));
			
			A_StopSound(CHAN_WEAPON);
			A_StartSound("ledgeclimb");
			LedgeAngle = Angle;
			LedgeCheck = False;
			LedgeGrabbed = True;
			return;
		}
		if((player.readyweapon is "PB_Fists") || (player.readyweapon is "PB_Chainsaw") || (player.readyweapon is "PB_Axe"))
		{
			player.SetPSprite(PSP_WEAPON,player.ReadyWeapon.FindState("StainedLedgeClimb"));
		}
		else
		{
			player.SetPSprite(PSP_WEAPON,player.ReadyWeapon.FindState("LedgeClimb"));
		}
	}
	void LedgeReach()
	{
		LedgeTime++;
		if(LedgeTime >= 30)
		{
			SetPlayerProperty(0,0,PROP_TOTALLYFROZEN);
			LedgeGrabbed = LedgeTime = LedgeHeight = LedgeHeightMin = LedgeHeightMax = FrameTime = 0;
		}
	}
	
	void LedgeGrab()
	{
		if(Pos.Z >= LedgeHeight || !Vel.Length() || LedgeTime >= 35)
		{
			//End Ledge Grab
			LedgeCheck = False;
			SetOrigin((Pos.X, Pos.Y, LedgeHeight), True);
			SetPlayerProperty(0,0,PROP_TOTALLYFROZEN);
			
			//Only if ledge grab was successful
			if(LedgeTime >= 35) { return; }
			LedgeGrabbed = LedgeTime = LedgeHeight = LedgeHeightMin = LedgeHeightMax = FrameTime = 0;
			Vel = Vel.Length() ? (5.f * AngleToVector(LedgeAngle), -3) : (0, 0, 0); //push player forward and downward
			A_StartSound("pb/player/land", 32);
		}
		else
		{
			Vel = Vel.Length() ? (0, 0, 8) : (0, 0, 0);
		}
		
		//Fail safe to unlock player movement if something goes wrong
		LedgeTime++;
		if(LedgeTime >= 35)
		{
			SetPlayerProperty(0,0,PROP_TOTALLYFROZEN);
			LedgeGrabbed = LedgeTime = LedgeHeight = LedgeHeightMin = LedgeHeightMax = FrameTime = 0;
		}
		
		//Sprite animation
		PlayIdle();
	}
	
	
	//////////////////////////////////////
	// Bobbing							//
	//////////////////////////////////////
	
	void BobWeaponAuxiliary()
	{
		///////////////////////////
		//Bobbing Speed
		if(MoveRangeMulti) { BobTime += Vel.XY.Length() / MAX_GROUND_SPEED; }
		
		///////////////////////////
		//Bobbing Range
		Double MaxBobCandidate = MAX_GROUND_SPEED * ZMoveFactor;
		
		if(MaxBobCandidate == MaxBob || !MaxBob)
		{
			MaxBob = MaxBobCandidate;
		}
		else
		{
			if(MaxBobCandidate > MaxBob)
			{
				MaxBob += 0.5f;
				MaxBob = min(MaxBob, MaxBobCandidate);
			}
			else
			{
				MaxBob -= 0.5f;
				MaxBob = max(MaxBob, MaxBobCandidate);
			}
		}
	}

    // [gng] thanks to Agent_Ash for creating AshMove, where this bob formula
    // is from.
    const am_weapBobRangeHorz = 9.0;
    const am_weapBobRangeVert = 4.3;

    double am_prevbobphase;
	double am_bobphase;
	
	Override Vector2 BobWeapon(double ticfrac)
	{
		if(FindInventory("PlayerWheelOpen") && CVar.GetCVar("gb_time_freeze",player).GetInt() == 1) return FinalBob;

		let player = self.player;
		UserCmd cmd = player.cmd;
		
		Vector2 p1, p2, r;
		Vector2 result;
		
		if(!player) return (0, 0);
		let weapon = player.ReadyWeapon;

		if(weapon == null || weapon.bDontBob)
		{
			MoveRangeMulti = StillRangeMulti = XBob = XBobOffset = YBob = YBobOffset = 0;
			return (0, 0);
		}
		
		// Int BobStyle = weapon.BobStyle;
		Double RangeX = weapon.BobRangeX;
		Double RangeY = weapon.BobRangeY;

		// [AA] Movement-based bobbing:
		
		// Bobdamp lets the weapon smoothly transition between bobbing
		// and non-bobbing frames by modifying reducing the range.
		// am_prevWeapBobDamp and am_weapBobDamp are calculated in
		// PlayerThink(), then lerp'd here:
		RangeX = PB_Math.LinearMap(FindInventory("PlayerDashed") ? self.vel.xy.Length() * 0.3 : self.vel.xy.Length(), 0, 15, 0, am_weapBobRangeHorz);
		RangeY = PB_Math.LinearMap(FindInventory("PlayerDashed") ? self.vel.xy.Length() * 0.3 : self.vel.xy.Length(), 0, 15, 0, am_weapBobRangeVert);
		// deeper downward movement when underwater:
		if (waterlevel) RangeY *= 1.8;
		// multiply by weapon-specific bobranges:
		if (player.readyweapon)
		{
			RangeX *= player.readyweapon.BobRangeX;
			RangeY *= player.readyweapon.BobRangeY;
		}

		double bobphase;

		for(int i = 0; i < 2; i++)
		{
			if(WaterLevel >= 2 || bNOGRAVITY) //water, flying
			{
				XBob *= abs(XBob) > 0.1 ? 0.988 : 0;
				YBob *= abs(YBob) > 0.1 ? 0.988 : 0;
			}
			else if(ZMJumpTics || abs(RealFloorZ - Pos.Z) > 16 && !player.onground || CanCSlide) //mid air or csliding or wallsliding
			{
				if(CanCSlide) //don't you move boi
				{
					XBob *= abs(XBob) > 0.1 ? 0.988 : 0;
					YBob *= abs(YBob) > 0.1 ? 0.988 : 0;
				}
				else //vertical offset
				{
					Int OffsetSpeed = CVar.GetCVar("pb_offsetspeed", Player).GetInt();
					Int	OffsetRange = CVar.GetCVar("pb_offsetmaxrange", Player).GetInt();
					
					if(Xbob) { XBob *= abs(XBob) > 0.1 ? 0.988 : 0; }
					
					if(!CVar.GetCVar("pb_offsetdirection", Player).GetBool())
					{
                        if(OffsetSpeed > 0)
                        {
    						if(Vel.Z >= 0)
    							YBob += Vel.Z / OffsetSpeed * (1. - abs(YBob) / OffsetRange);
    						else
    							YBob += 2. * Vel.Z / OffsetSpeed * max(abs(YBob) / OffsetRange, 1);
    					}
					}
					else
					{
                        if(OffsetSpeed > 0)
                        {
    						if(Vel.Z >= 0)
    							YBob -= 2. * Vel.Z / OffsetSpeed * max(abs(YBob) / OffsetRange, 1);
    						else
    							YBob -= Vel.Z / OffsetSpeed * (1. - abs(YBob) / OffsetRange);
    					}
					}
					YBob = clamp(YBob, 0, OffsetRange);
				}
				
				HoppingBob = True;
				MoveRangeMulti = StillRangeMulti = BobTime = 0;
			}
			else //ground movement
			{
				if(HoppingBob)
				{
					XBob *= abs(XBob) > 0.1f ? 0.5 : 0;
					YBob *= abs(YBob) > 0.1f ? 0.5 : 0;
					if(!XBob && !YBob) { HoppingBob = False; }
				}
				else
				{
					Float SpeedToFullBob = max(1, CVar.GetCVar("pb_fullbobspeed", Player).GetInt());
					
					if((cmd.forwardmove || cmd.sidemove) && Vel.XY.Length() > 1.f)
					{	
						BobRangeMulti = min(Vel.XY.Length(), MAX_GROUND_SPEED) / MAX_GROUND_SPEED;
						MoveRangeMulti = min(MoveRangeMulti + BobRangeMulti / SpeedToFullBob, MaxBob);
						StillRangeMulti = 0;
					}
					else
					{
						if(MoveRangeMulti)
						{
							MoveRangeMulti = max(MoveRangeMulti - max(BobRangeMulti / SpeedToFullBob, 0.1f), 0);
						}
						else
						{
							XBob = BobTime = 0;
							if(CVar.GetCVar("pb_stillbob", Player).GetBool()) //still weapon bobbing
							{
								StillRangeMulti = min(StillRangeMulti + 0.001, 1); //probably nobody would notice the occasional tiny warps BUT I WOULD KNOW
								YBob = StillRangeMulti * sin(Level.Maptime / 120. * 360.) + StillRangeMulti;
							}
							else
							{
								YBob = 0;
							}
						}
					}
						
					if(MoveRangeMulti)
					{
                        bobphase = (i == 0? am_prevbobphase : am_bobphase) * player.GetWBobSpeed();
                        XBob = (cos(bobphase*0.5)) * (-RangeX * (MoveRangeMulti /  15.f));
                        double t = (sin(bobphase) + 1.0) * 0.5;
                        YBob = (t ** 2.0) * (RangeY * (MoveRangeMulti /  15.f));

						/*Double BobAngle = (BobSpeed * player.GetWBobSpeed() * (BobTime - 1 + i)) * (360. / 8192.);
						Double BobXMulti = (MoveRangeMulti * RangeX);
						Double BobYMulti = (MoveRangeMulti * RangeY);
						
						switch(BobStyle)
						{
							case Bob_Normal:
								XBob = BobXMulti * cos(BobAngle);
								YBob = BobYMulti * abs(sin(BobAngle));
								break;
							
							case Bob_Inverse:
								XBob = BobXMulti * cos(BobAngle);
								YBob = BobYMulti * (1. - abs(sin(BobAngle)));
								break;
							
							case Bob_Alpha:
								XBob = BobXMulti * sin(BobAngle);
								YBob = BobYMulti * abs(sin(BobAngle));
								break;
							
							case Bob_InverseAlpha:
								XBob = BobXMulti * sin(BobAngle);
								YBob = BobYMulti * (1. - abs(sin(BobAngle)));
								break;
							
							case Bob_Smooth:
								XBob = BobXMulti * cos(BobAngle);
								YBob = 0.5f * (BobYMulti * (1. - (cos(BobAngle * 2))));
								break;
							
							case Bob_InverseSmooth:
								XBob = BobXMulti * cos(BobAngle);
								YBob = 0.5f * (BobYMulti * (1. + (cos(BobAngle * 2))));
								break;
						}*/
					}
				}
			}
			
			r = (XBob, YBob);
			
			//////////////////////////////
			//Yaw Weapon Sway
			if(CVar.GetCVar("pb_yawsway", Player).GetBool())
			{
				Double SwayRange = CVar.GetCVar("pb_yawswayrange", Player).GetFloat() * 10;
				Double SwayFrictionMulti = CVar.GetCVar("pb_yawswayfriction", Player).GetFloat() / 10;
				
				XBobOffset += (CVar.GetCVar("pb_yawswaydirection", Player).GetBool() ? -1 : 1) * ViewAngleDelta * CVar.GetCVar("pb_yawswayspeed", Player).GetFloat() / 50;
				YBobOffset += (CVar.GetCVar("pb_yawswaydirection", Player).GetBool() ? -1 : 1) * ViewPitchDelta * CVar.GetCVar("pb_yawswayspeed", Player).GetFloat() / 25;
				
				if(abs(XBobOffset) > 0.2)
				{
					XBobOffset -= XBobOffset / ((1.5 - SwayFrictionMulti) * 100);
				}
				else if(!ViewAngleDelta)
				{
					XBobOffset = 0;
				}
				
				if(abs(YBobOffset) > 0.2)
				{
					YBobOffset -= YBobOffset / ((1.5 - SwayFrictionMulti) * 100);
				}
				else if(!ViewPitchDelta)
				{
					YBobOffset = 0;
				}
				
				r.X += clamp(XBobOffset, -SwayRange, SwayRange);
				if(CVar.GetCVar("pb_pitchswaytype", Player).GetBool() == 0)
				{
					r.Y += clamp((abs(YBobOffset)), 0, SwayRange);
				}
				else
				{
					r.Y += clamp(YBobOffset, 0, SwayRange);
				}

			}
			else
			{
				XBobOffset = 0;
				YBobOffset = 0;
			}
				
			//////////////////////////////
			
			if(i == 0) p1 = r; else p2 = r;
		}
		FinalBob = (p1 * (1. - ticfrac) + p2 * ticfrac) * (CountInv("Zoomed") >= 1 ? 0.2 : 1.0);
		return FinalBob;
	}
	
	// The rest of Project Brutality player class
	void SpawnTankSprite()
	{
		TankTurretSprite = Spawn(TankTurretSpriteActor,self.pos + self.vel,ALLOW_REPLACE);
	}
	void DestroyTankSprites()
	{	
		TankTurretSprite.Destroy();
		
		TankTurretSprite = NULL;
	}
	
	// huh????
	/*void SetTankSpritePosition(int spritestate,double angle = 0)
	{
		
		{
			
		}
	}*/
	
	void CheckTargetHitRegistration()
	{
		// Check the parent class the monster is derived from
		//let target_ptr = AAPTR_PLAYER_GETTARGET;
		if (GetPointer(AAPTR_PLAYER_GETTARGET) is "PB_Monster"){
			//A_Print("This is a PB Monster!!!"); // Debug code
			A_GiveInventory("HeadshotToken", 1, AAPTR_PLAYER_GETTARGET);
		}
	}
	
	void CatchUpOnTiers()
	 {
	  if(player!=null)
	  {
       if(CVar.GetCVar("PlayerCatchup",Player).GetBool()==true)
	   {
		//if(CountInv("PlayerHasCaughtup")==0)
		//{
		 if(CountInv("PlayerHasChainsawPermanent")==1){A_GiveInventory("PB_Chainsaw",1);}
		 if(CountInv("PlayerHasFLMTPermanent")==1){A_GiveInventory("PB_Flamethrower",1);}
		 if(CountInv("PlayerHasFLMTUPermanent")==1){A_GiveInventory("PB_FlamethrowerUpgrade",1);}
		  
		 if(CountInv("PlayerHasShotgunPermanent")==1){A_GiveInventory("PB_Shotgun",1);}
		 if(CountInv("PlayerHasRevolverPermanent")==1){A_GiveInventory("PB_Revolver",1);}
	 	 if(CountInv("PlayerHasRevolverPermanent")>1){A_GiveInventory("PB_Revolver",2);}
		 if(CountInv("PlayerHasASGPermanent")==1){A_GiveInventory("PB_Autoshotgun",1);}
	 	 if(CountInv("PlayerHasASGPermanent")>1){A_GiveInventory("PB_Autoshotgun",2);}
		 if(CountInv("PlayerHasSGMagPermanent")==1){A_GiveInventory("PB_SGMagazine",1);}
		 if(CountInv("PlayerHasDeaglePermanent")==1){A_GiveInventory("PB_Deagle",1);}
		 if(CountInv("PlayerHasDeaglePermanent")>1){A_GiveInventory("PB_Deagle",2);}
		  
		 if(CountInv("PlayerHasSSGPermanent")==1){A_GiveInventory("PB_SSG",1);}
		 if(CountInv("PlayerHasSSGPermanent")>1){A_GiveInventory("PB_SSG",2);}
		 if(CountInv("PlayerHasQuadSGPermanent")==1){A_GiveInventory("PB_QuadSG",1);}
		 if(CountInv("PlayerHasQuadSGPermanent")>1){A_GiveInventory("PB_QuadSG",2);}
		 if(CountInv("PlayerHasASGDrumPermanent")==1){A_GiveInventory("PB_AutoshotgunUpgrade",1);}
		  
		 if(CountInv("PlayerHasMGPermanent")==1){A_GiveInventory("PB_Minigun",1);}
		 if(CountInv("PlayerHasCarbinePermanent")==1){A_GiveInventory("PB_Carbine",1);}
		 if(CountInv("PlayerHasCarbinePermanent")>1){A_GiveInventory("PB_Carbine",2);}
		 if(CountInv("PlayerHasNailGunPermanent")==1){A_GiveInventory("PB_Nailgun",1);}
		 if(CountInv("PlayerHasHDMRPermanent")==1){A_GiveInventory("PB_HDMRUpgrade",1);}
		 if(CountInv("PlayerHasSMGPermanent")==1){A_GiveInventory("PB_SMG",1);}
		 if(CountInv("PlayerHasSMGPermanent")>1){A_GiveInventory("PB_SMG",2);}
		 if(CountInv("PlayerHasMGUPermanent")==1){A_GiveInventory("PB_MinigunUpgrade",1);}
		 if(CountInv("PlayerHasLMGPermanent")==1){A_GiveInventory("PB_LMG",1);}
		 
		 if(CountInv("PlayerHasRLPermanent")==1){A_GiveInventory("PB_RocketLauncher",1);}
		 if(CountInv("PlayerHasSGLPermanent")==1){A_GiveInventory("PB_SuperGL",1);}
		
		 if(CountInv("PlayerHasM1PlasmaPermanent")==1){A_GiveInventory("PB_M1Plasma",1);}
		 if(CountInv("PlayerHasM1PlasmaPermanent")>1){A_GiveInventory("PB_M1Plasma",2);}
		 if(CountInv("PlayerHasM2PlasmaPermanent")==1){A_GiveInventory("M2Plasma",1);}
		 if(CountInv("PlayerHasM2PlasmaPermanent")>1){A_GiveInventory("M2Plasma",2);}
		 if(CountInv("PlayerHasRGPermanent")==1){A_GiveInventory("PB_Railgun",1);}
		 if(CountInv("PlayerHasCryoPermanent")==1){A_GiveInventory("PB_CryoRifle",1);}
		 if(CountInv("PlayerHasM2UPermanent")==1){A_GiveInventory("PB_M2Upgrade",1);}
		  
		 if(CountInv("PlayerHasBFGPermanent")==1){A_GiveInventory("PB_BFG9000",1);}
		 if(CountInv("PlayerHasMG42Permanent")==1){A_GiveInventory("PB_MG42",1);}
		 if(CountInv("PlayerHasUnmakerPermanent")==1){A_GiveInventory("PB_Unmaker",1);}
		 //A_GiveInventory("PlayerHasCaughtup",1);
		//}
	   }
	  }
	 }
/*
	void InitPDAWeaponList()
	{
		if (FindInventory("PB_PDAWeaponContainer")) return;
		A_GiveInventory("PB_PDAWeaponContainer",1);
		PB_PDAWeaponContainer pdaweapContainer = PB_PDAWeaponContainer(FindInventory("PB_PDAWeaponContainer"));
		if (pdaweapContainer) pdaweapContainer.InitializePDATexts();
	}
*/
	
	override void Die(Actor source, Actor inflictor, int dmgflags)
	{
		A_TakeInventory("CameraRunner",1);
		Super.Die(source, inflictor, dmgflags);
	}
	override void PostBeginPlay()
	{
		Super.PostBeginPlay();
		CatchUpOnTiers();
		if (!level.IsJumpingAllowed() || (player && player.mo && player.mo.JumpZ == 0)) A_GiveInventory("DoNotDoubleJump",1);
		Shader.SetEnabled(player,"Invulnerability",false);
		Shader.SetEnabled(player,"NightVision",false);
	}
	override void Tick()
	{
		checkSkin();
		Super.Tick();
		if(health <= 0){ A_OverlayOffset(1, 0, 1000); }
		
		//Just to make sure NO TRACES of this softlocking motherfucker is left -generic name guy
		if(player && self && CheckNotPredicting())
		{
			A_SetInventory("GoFatality", 0);
			// CheckTargetHitRegistration();
		}
		//CatchUpOnTiers();
		if(!player || player.mo != self) return;
		// Dash and double jump code by malingo ( https://www.youtube.com/watch?v=mTfGxY_Afhs )
		PlayerInfo plr = player;
		
		if(plr && !waiting && (!dashJumped || !JumpSoundCooler) && (plr.cmd.buttons & BT_USER3) && dashCharge >= DASH_MAX_CHARGE / 2 && dashtics == 0 && !FindInventory("IsSlideKicking")) {
			sector sss = floorsector;
			if(A_CheckFloor("null") && sss.damagetype == "Slime" && !pb_hazardmovement) {
				A_StartSound("Daedabus/impact", 32);
				return;
			}
			// [gng] thanks to kodi and lewisk3, analog compatible dash direction
			dashDir = DeltaAngle(atan2(plr.cmd.sidemove, plr.cmd.forwardmove), angle);
			
			if(DashCharge < DASH_MAX_CHARGE) { 
				waiting = true; 
				dashCharge = 0; 
			}
			
			if(!FindInventory("PB_PowerSpeed")) {
				dashCharge = max(0, dashCharge - DASH_MAX_CHARGE / 2);
			}
			
			dashSpeed = 50;
			dashTics = 10;
			
			EventHandler.SendInterfaceEvent(PlayerNumber(), "PB_DashWhatchamacallit");
			A_StartSound("player/dash", 69, CHANF_OVERLAP);
			
			if(!PB_HelpNotificationsHandler.CheckTipEvent(1 << 1, CVar.GetCvar("pb_helpflags", Player))) {
				Array<String> pbDashTips;
				pbDashTips.Push("$PB_DASH_TIP_1");
				pbDashTips.Push("$PB_DASH_TIP_2");
				pbDashTips.Push("$PB_DASH_TIP_3");
				pbDashTips.Push("$PB_DASH_TIP_4");
				PB_HelpNotificationsHandler.PB_SendTipArray(pbDashTips, "pb_helpflags", 1 << 1);
			}
			SetInventory("PlayerDashed", 1);
			A_QuakeEx(2, 2, 2, dashTics, 0, 1, "", QF_SCALEDOWN, rollintensity:0.2);
		}
		
		if(FindInventory("ExecutionToken")) {
			vel.xy *= 0;
			dashTics = 0;
			SetInventory("PlayerDashed", 0);
		}
		
		double airControlBuffer = level.aircontrol;
		if(dashTics > 0) {
			dashTics--;
			
			if(dashTics == 3) {
				dashSpeed *= 0.4;
				SetInventory("PlayerDashed", 0);
			}
			VelFromAngle(DashSpeed, DashDir );
			
			vel.z = 0;
			
			level.airControl = 0.25;
		}
		
		if(plr && plr.onGround) {
			dJump = true;
			airTics = 0;
			level.airControl = airControlBuffer;
		}
		else {
			airTics++;
		}	
			
		// [gng] recharge the dash
		if(dashCharge < DASH_MAX_CHARGE) {
			if(FindInventory("PB_PowerSpeed")) {
				dashCharge = DASH_MAX_CHARGE;
			}
			dashCharge++;
			
			if(dashCharge == DASH_MAX_CHARGE && !plr.onGround) 
				dashCharge = DASH_MAX_CHARGE - 1;
				
			if(dashCharge == DASH_MAX_CHARGE) {
				waiting = false;
				if (gamestate != GS_TITLELEVEL) // Just don't play this on TitleMaps it's unnecessary.
					A_StartSound("player/dashready", 69, CHANF_OVERLAP);
			}
		}
		
		if(dashtics < 0) {
			dashtics++;
		}
		
        if(CheckNotPredicting())
        {
            if(m_MuzzleFlashTimer > 0)
            {        
                m_MuzzleFlashTimer--;
            }
            else if (m_MuzzleFlashTimer == 0)
            {
                A_RemoveLight('MuzzleFlashLight');
                m_MuzzleFlashTimer = -1;
            }
        }

		//Screen Overlay Handlers
		//Disabled until we can convert the screen splatters to ZScript
/*		if (GetCvar("BloodSplash") == 1) {
			if (CheckInventory("RedBloodSplatterz",1)) {
				A_TakeInventory("RedBloodSplatterz", 1);
				A_Giveinventory("BloodOnVisor",1);
				int selector = (random(0,1));
				if (selector == 0){ACS_NamedExecute("RedBloodSplatter580", 0);}
				if (selector == 1){ACS_NamedExecute("RedBloodSplatter580", 1);}
			}
			
			if (CheckInventory("BlueBloodSplatterz",1)) {
				A_TakeInventory("BlueBloodSplatterz", 1);
				A_Giveinventory("BlueBloodOnVisor",1);
				int selector = (random(0,1));
				if (selector == 0){ACS_NamedExecute("BlueBloodSplatter583", 0);}
			}
			if (CheckInventory("GreenBloodSplatterz",1)) {
				A_TakeInventory("GreenBloodSplatterz", 1);
				A_Giveinventory("GreenBloodOnVisor",1);
				int selector = (random(0,1));
				if (selector == 0){ACS_NamedExecute("GreenBloodSplatter582", 0);}
			}
			if (CheckInventory("BloodSplasherz",1)) {
				A_TakeInventory("BloodSplasherz", 1);
				A_Giveinventory("BloodOnVisor",1);
				int selector = (random(0,5));
				if (selector == 0){ACS_Execute(580, 0, 0, 0, 0);}
				if (selector == 1){ACS_Execute(581, 0, 0, 0, 0);}
				if (selector == 2){ACS_Execute(582, 0, 0, 0, 0);}
				if (selector == 3){ACS_Execute(583, 0, 0, 0, 0);}
				if (selector == 4){ACS_Execute(584, 0, 0, 0, 0);}
				if (selector == 5){ACS_Execute(585, 0, 0, 0, 0);}
			}
		}
		if (CheckInventory("WaterSplasherz",1)) {
			A_TakeInventory("WaterSplasherz", 1);
			A_Giveinventory("WaterOnVisor",1);
			int selector = (random(0,4));
			if (selector == 0){ACS_Execute(550, 0, 0, 0, 0);}
			if (selector == 1){ACS_Execute(551, 0, 0, 0, 0);}
			if (selector == 2){ACS_Execute(552, 0, 0, 0, 0);}
			if (selector == 3){ACS_Execute(554, 0, 0, 0, 0);}
			if (selector == 4){ACS_Execute(555, 0, 0, 0, 0);}
		}
		if (CheckInventory("SlimeSplasherz",1)) {
			A_TakeInventory("SlimeSplasherz", 1);
			A_Giveinventory("SlimeOnVisor",1);
			int selector = (random(0,5));			
		}
		if (CheckInventory("SludgeSplasherz",1)) {
			A_TakeInventory("SludgeSplasherz", 1);
			A_Giveinventory("SludgeOnVisor",1);
			int selector = (random(0,5));
			if (selector == 0){ACS_Execute(5530, 0, 0, 0, 0);}
			if (selector == 1){ACS_Execute(5531, 0, 0, 0, 0);}
			if (selector == 2){ACS_Execute(5532, 0, 0, 0, 0);}
			if (selector == 3){ACS_Execute(5533, 0, 0, 0, 0);}
			if (selector == 4){ACS_Execute(5534, 0, 0, 0, 0);}
			if (selector == 5){ACS_Execute(5535, 0, 0, 0, 0);}
		}
		
		if (CheckInventory("LavaSplasherz",1)) {
			A_TakeInventory("LavaSplasherz", 1);
			A_Giveinventory("LavaOnVisor",1);
			int selector = (random(0,5));
			if (selector == 0){ACS_NamedExecute("LavaScreenSplash550", 0);}
			if (selector == 1){ACS_NamedExecute("LavaScreenSplash551", 0);}
			if (selector == 2){ACS_NamedExecute("LavaScreenSplash552", 0);}
			if (selector == 3){ACS_NamedExecute("LavaScreenSplash553", 0);}
			if (selector == 4){ACS_NamedExecute("LavaScreenSplash554", 0);}
			if (selector == 5){ACS_NamedExecute("LavaScreenSplash555", 0);}
		}
		*/
		if (player && self && CheckNotPredicting() && IsTank && !(health <= 0))
		{
			if (TankTurretSprite != NULL)
			{
				//TankTurretSprite.Tics = -1;
				TankTurretSprite.A_Setangle(self.angle,SPF_INTERPOLATE);
				TankTurretSprite.SetOrigin(self.pos + self.vel,true);
				TankTurretSprite.bINVISIBLE = false;
			}
			if (health < 500)
			{
				A_SpawnProjectile ("BigNeoSmoke", 0, 0, random (0, 360), 2, -random (0, 360));
				A_SpawnProjectile ("ExplosionSmoke", 0, 0, random (0, 360), 2, -random (0, 360));
			}
			if (health < 350)
			{
				A_SpawnProjectile ("BigNeoSmoke", 0, 0, random (0, 360), 2, -random (0, 360));
				A_SpawnProjectile ("ExplosionSmoke", 0, 0, random (0, 360), 2, -random (0, 360));
			}
			if (Health < 200)
			{
				A_SpawnProjectile ("BigBlackSmoke", 40, 0, random (0, 360), 2, -random (40, 160));
			}
			if (health < 30)
			{
				A_SpawnProjectile ("FlameThrowerFireParticles", 0, 0, random (0, 360), 2, -random (0, 360));
				A_StartSound("BDFireplace2", 1, CHANF_LOOPING, 1);
				tankdeathcounter += 1;
				if (tankdeathcounter >= (35 * 5))
				{
					tankdeathcounter = 0;
					A_Die();
				}
			}
		}
	}
}


//////////////////////////////////////
// EventHandlers					//
//////////////////////////////////////

//Edit of a SpeedOMeter from Gutawer
Class SpeedoMeterHandler : EventHandler
{
	override void renderOverlay(RenderEvent e)
	{
		if(CVar.GetCvar("zm_speedometer", players[consoleplayer]).GetInt())
		{
			Actor mo = players[consoleplayer].mo;
			if(mo != NULL && PlayerInGame[consoleplayer])
			{
				let scalevec = statusbar.GetHUDScale();
				Vector2 scaler = (1 / scalevec.x, 1 / scalevec.y);
				Vector2 screenSize = (Screen.GetWidth() * scaler.x, Screen.GetHeight() * scaler.y);
			
				double unitscale;
				switch(CVar.GetCvar("zm_speedometer", players[consoleplayer]).GetInt()) {
				default:
				case 1:
					unitscale = 10; //doom
					break;
				case 2:
					unitscale = 32; //quake
					break;
				case 3:
					unitscale = 655360; //srb2
					break;
				}
				Vector2 drawPos = (-4 * (screenSize.x / 320), 106 * (screenSize.y / 200));
				Screen.drawText(CONFONT, Font.CR_WHITE, drawPos.x, drawPos.y, String.format("%i", mo.Vel.XY.Length() * unitscale), DTA_HUDRules, true);
				Screen.drawText(CONFONT, Font.CR_WHITE, drawPos.x, drawPos.y + (screenSize.y / 50), String.format("%i", mo.Vel.z * unitscale), DTA_HUDRules, true);
			}
		}
	}
}

Class LedgeGrabWeapon : PB_WeaponBase
{
	Default
	{
		Tag " ";
	}
	States
	{
		SelectAnimation:
		Select:
		Deselect:
		Ready:
		Fire:
			TNT1 A 0 SetInventory("LedgeGrabWeapon", 0);
			Stop;
	}
}