class PB_PlayerPrawn : PlayerPawnBase
{
	bool lfoot;
	
	Default
	{
		Mass 500;
		GibHealth 20;
		Species "Marines";
		BloodType "NashGoreBlood";
		
		DamageFactor "Head",1.0;
		DamageFactor "Leg",1.0;
		DamageFactor "FriendBullet",0.0;
		DamageFactor "Taunt",0.0;
		DamageFactor "KillMe",0.0;
		DamageFactor "SSG",5.0;
		DamageFactor "Shrapnel",0.0;
		DamageFactor "Blood",0.0;
		DamageFactor "BlueBlood",0.0;
		DamageFactor "GreenBlood",0.0;
		DamageFactor "MinorHead",0.0;
		DamageFactor "Decaptate",0.0;
		DamageFactor "IceExplosion",0.0;
		DamageFactor "MonsterKnocked",0.0;
		DamageFactor "Trample",0.0;
		DamageFactor "Kick",0.75;
		DamageFactor "Fatality",5.0;
		DamageFactor "BHFTOnBarrel",0.0;
		DamageFactor "GibRemoving",0.0;
		DamageFactor "SuperPunch",5.0;
		DamageFactor "HelperMarineFatallity",0.0;
		DamageFactor "SpawnMarine",0.0;
		DamageFactor "TeleportRemover",0.0;
		DamageFactor "CancelTeleportFog",0.0;
		DamageFactor "CauseObjectsToSplash",0.0;
		DamageFactor "CauseObjectsToSplashSlime",0.0;
		DamageFactor "CauseObjectsToSplashNukage",0.0;
		DamageFactor "CauseObjectsToSplashBlood",0.0;
		DamageFactor "CauseObjectsToSplashLava",0.0;
		DamageFactor "SuperKick",0.0 ;
		DamageFactor "BFGShield",0.0;
		DamageFactor "KillMeBot",0.0;
		DamageFactor "Flames",0.875;
		DamageFactor "Fire",0.875;
		DamageFactor "Burn",0.875;
		DamageFactor "Disintegrate",1.0;
		DamageFactor "Avoid",0;
		
		Player.ViewHeight 46;
		Player.AttackZOffset 19;
		Player.ColorRange 112,127;
		Player.JumpZ 7.4;
		Player.GruntSpeed 24;
		Player.DisplayName "Project Brutality";
		Player.CrouchSprite "PLYC";
		//Player.ViewBob 0.0;

		Player.WeaponSlot 1,"PB_Axe","PB_Chainsaw","PB_Fists";
		Player.WeaponSlot 2,"PB_Pistol","PB_MP40","PB_SMG","PB_Revolver","PB_Deagle";
		Player.WeaponSlot 3,"PB_Shotgun","PB_AutoShotgun","PB_SSG","PB_QuadSG";
		Player.WeaponSlot 4,"PB_ChexRifle","PB_DMR","PB_Carbine","PB_LMG";
		Player.WeaponSlot 5,"PB_MG42","PB_Minigun","PB_Nailgun";
		Player.WeaponSlot 6,"PB_RocketLauncher","PB_SuperGL";
		Player.WeaponSlot 7,"PB_M1Plasma","PB_M2Plasma","PB_DTechRifle";
		Player.WeaponSlot 8,"PB_CryoRifle","PB_Flamethrower";
		Player.WeaponSlot 9,"PB_Unmaker","PB_BFG9000","PB_Railgun";

		// Player.StartItem "PB_PDAWeaponContainer",1;
		Player.StartItem "PB_DMR";
		Player.StartItem "PB_Pistol";
		Player.StartItem "PB_Fists";
		
		Player.StartItem "CarbineFullAuto";
		Player.StartItem "HasNotPickedUpSSG",1;
		Player.StartItem "IsPlayer",1;
		Player.StartItem "FragGrenadeSelected",1;
		
		Player.StartItem "PB_HighCalMag", 90;
		Player.StartItem "PB_LowCalMag", 60;
		Player.StartItem "PB_GrenadeAmmo",3;
		Player.StartItem "PB_QuickLauncherAmmo",4;
		
		Player.StartItem "PB_PistolMag", 16;
		Player.StartItem "PB_PistolLeftMag", 16;
		Player.StartItem "PB_SMGMag", PB_SMG.MAGAZINE_SIZE;
		Player.StartItem "PB_SMGLeftMag", PB_SMG.MAGAZINE_SIZE;
		Player.StartItem "PB_RevolverMag", 6;
		Player.StartItem "PB_RevolverLeftMag", 6;
		Player.StartItem "PB_DeagleMag", 12;
		Player.StartItem "PB_DeagleLeftMag", 12;
		Player.StartItem "PB_MP40Mag", PB_MP40.MAGAZINE_SIZE;
		Player.StartItem "PB_MP40LeftMag", PB_MP40.MAGAZINE_SIZE;
		Player.StartItem "PB_ShotgunMag", 9;
		Player.StartItem "AutoShotgunAmmo", 12;
		Player.StartItem "LeftASGAmmo", 12;
		Player.StartItem "PB_SSGMag", PB_SSG.MAGAZINE_SIZE;
		Player.StartItem "PB_SSGLeftMag", PB_SSG.MAGAZINE_SIZE;
		Player.StartItem "QSSGAmmoCounter", 4;
		Player.StartItem "LeftQSSGAmmoCounter", 4;
		Player.StartItem "DMRAmmo", 31;
		Player.StartItem "LeftDMRAmmo", 31;
		Player.StartItem "XRifleAmmo", 41;
		Player.StartItem "LeftXRifleAmmo", 41;
		Player.StartItem "LMGAmmo", 100;
		Player.StartItem "CheXRifleAmmo", 42;
		Player.StartItem "PB_NailgunAmmo", 120;
		Player.StartItem "RocketRounds", 10;
		Player.StartItem "PB_SuperGLMag", 7;
		Player.StartItem "PB_M1PlasmaMag", 60;
		Player.StartItem "PB_M1PlasmaLeftMag", 60;
		//Player.StartItem "PulseCannonAmmo",60;
		Player.StartItem "M2PlasmaAmmo", 50;
		Player.StartItem "LeftM2PlasmaAmmo", 50;
		Player.StartItem "PB_DTechRifleMag", PB_DTechRifle.MAGAZINE_SIZE;
		Player.StartItem "FlamerAmmo", 90;
        Player.StartItem "PB_CryoRifleMag", 60;
		Player.StartItem "RailgunAmmo", 60;

		+ROLLSPRITE
		+THRUSPECIES
		+MTHRUSPECIES
		+THRUGHOST
		-NOSKIN
	}

	override void PostBeginPlay()
	{
		Super.PostBeginPlay();
		if(!player||(player.mo!=self))
		{
			let v = Spawn("PB_VoodooDoll",pos);
			v.angle = angle; v.player = player;
			Destroy(); return;
		}
		if(level.info.mapname == "TITLEMAP")
		{
			player.SetFOV(90);
		}
	}

	override int DamageMobj(actor inflictor,actor source,int damage,name mod,int flags,double angle)
	{
		if(!inflictor&&!source&&(FloorSector.flags&Sector.SECF_ENDLEVEL))
		{ level.ExitLevel(0,false); return 0; }
		if(source&&source.FindInventory("EnemyIsArchvile"))
		{
			A_SpawnProjectile("NewRocketExploFX",30,0,random(0,360),2,random(0,360));
			for(int i=12;i>0;i--) A_SpawnProjectile("ExplosionParticleHeavy",30,0,random(0,360),2,random(0,180));
		}
		return Super.DamageMobj(inflictor,source,damage,mod,flags,angle);
	}
	
	override void CheatGive (String name, int amount)
	{
		if(name ~== "Everything" || name ~== "All")
		{
			giveinventory("PB_BlueArmor",1);
		}
		if(name ~== "Everything" || name ~== "PB_Upgrades")
		{
            if(name ~== "PB_Upgrades") console.printf("Gave all upgrades");
			for(int i = 0; i <= self.PB_ActUpgrades.size() -1; i++)
				giveinventory(self.PB_ActUpgrades[i],1);
			if(name ~== "PB_Upgrades") return;
		}
        else if(name ~== "currentammo")
		{
            Weapon gun = player.readyweapon;
            if(gun)
            {
                console.printf("Gave ammo for current weapon");
			    if(gun.ammo1) 
                {
                    gun.ammo1.Amount = player.readyweapon.ammo1.maxamount;
                    // S_StartSound(gun.ammo1.PickupSound, 0);
                }
                if(gun.ammo2) 
                {
                    gun.ammo2.Amount = player.readyweapon.ammo2.maxamount;
                    // S_StartSound(gun.ammo1.PickupSound, 0);
                }

                S_StartSound("misc/givecurrentammo", 0);
            }

			return;
		}
		super.cheatgive(name,amount);
	}
	
	//array to save all the upgrades
	static const string PB_ActUpgrades[] = {
		"PB_Deagle", "PB_SMG", //slot 2
		"PB_AutoshotgunUpgrade","PB_QuadSG","PB_SGMagazine", //slot3
		"PB_HDMRUpgrade", //slot 4
		"PB_MinigunUpgrade", //slot 5 
		"PB_M2Upgrade", //slot 7
		"PB_FlamethrowerUpgrade" //slot 9?
	};

	States
	{
	Spawn:
		PL4Y A 1
		{
			ForceMoveUnlock();
			A_TakeInventory("PlayerIsDead",1);
				A_TakeInventory("DeathFader",1);
			A_TakeInventory("IsInvisible",1);
			A_TakeInventory("ChainguyguyContinue",1);
			A_TakeInventory("DoNotJump",1);
			A_TakeInventory("CantDoAction",1);
			A_Takeinventory("PB_LockScreenTilt",1);
			A_ClearOverlays(66);
			ACS_ExecuteAlways(171,0,0,0,0);
		}
	StandStillLoop:
		PL4Y A 4
		{
			bTHRUSPECIES = 0;
			A_TakeInventory("PlayerIsDead",1);
				A_TakeInventory("DeathFader",1);
			ForceMoveUnlock();
		}
		loop;
	See:
		TNT1 A 0 {
			A_TakeInventory("PlayerIsDead",1);	
			A_TakeInventory("DeathFader",1);
		}
		PL4Y A 4 A_TakeInventory("ChainguyguyContinue",1);
		PL4Y B 4;
		PL4Y C 4
		{
			if(lfoot) lfoot = false;
			else lfoot = true;
			if(CountInv("BootsSmearedWithRedBlood"))
			{
				A_SpawnItemEx(lfoot?"RedBloodFootPrintLeft":"RedBloodFootPrintRight",0,7);
				A_TakeInventory("BootsSmearedWithRedBlood",1);
			}
			if(CountInv("BootsSmearedWithBlueBlood"))
			{
				A_SpawnItemEx(lfoot?"BlueBloodFootPrintLeft":"BlueBloodFootPrintRight",0,7);
				A_TakeInventory("BootsSmearedWithBlueBlood",1);
			}
			if(CountInv("BootsSmearedWithGreenBlood"))
			{
				A_SpawnItemEx(lfoot?"GreenBloodFootPrintLeft":"GreenBloodFootPrintRight",0,7);
				A_TakeInventory("BootsSmearedWithGreenBlood",1);
			}
		}
		PL4Y D 4;
		goto StandStillLoop;
	Missile:
		PL4Y E 12;
		goto Spawn;
	Melee:
		PL4Y F 2 BRIGHT;
		PL4Y E 4;
		goto Missile;
	Pain:
		PL4Y G 4 A_Pain;
		goto See;
	Death:
		TNT1 A 0 A_JumpIf(hasSkin, "AltDeath");
		TNT1 A 0
		{
			A_ClearOverlays(-999,-999);
			A_StopSound(7);
			A_StopSound(1);
			if(target&&target.FindInventory("TypeSergeant")) SetStateLabel("ArmDeath");
		}
		MARN A 0
		{
			A_Giveinventory("PB_LockScreenTilt",1);
			A_GiveInventory("PlayerIsDead",1);
			A_ClearOverlays(2,11);
			A_Overlay(66,"FirstPersonDeath1");
			A_ClearOverlays(-779,-777);
		}
		PL4Y HHHHHH 1; //A_SetRoll(roll+5.0,SPF_INTERPOLATE);
		PL4Y IIIIII 1 A_SpawnProjectile("Brutal_LiquidBlood3",40,0,random(0,360),2,random(60,120));
		TNT1 A 0 A_PlayerScream;
		PL4Y JJJJJJ 1 A_SpawnProjectile("Brutal_LiquidBlood2",30,0,random(0,360),2,random(60,120));
		PL4Y KKKKKK 1 A_SpawnProjectile("Brutal_LiquidBlood2",10,0,random (0,360),2,random(60,120));
		PL4Y LM 10;
		TNT1 A 0 A_SpawnItemEx("GrowingBloodPool");
		PL4Y NNNNNN 1 A_SpawnProjectile("Brutal_LiquidBlood2",10,0,random(0,360),2,random(60,120));
		PL4Y N -1;
		stop;
	Death.Ice: Death.Frost: Death.Freeze:
		TNT1 A 0 A_JumpIf(hasSkin, "AltFreezeDeath");
		FZD1 C 0
		{
			A_ClearOverlays(-999,-999);
			A_StopSound(7);
			A_StopSound(1);
			A_GiveInventory("PlayerIsDead",1);
			A_GiveInventory("CantDoAction",1);
			A_NoBlocking();
			A_StartSound("DSBOTTLE");
			for(int i=4;i>0;i--)
			{
				A_SpawnProjectile("IceDust",48,0,random(0,360),2,random(0,160));
				A_SpawnProjectile("IceBlood",48,0,random(0,360),2,random(0,160));
			}
		}
		FZD1 C -1;
		stop;
	ArmDeath:
		XPL5 A 10
		{
			A_StopSound(7);
			A_StopSound(1);
			A_Giveinventory("PB_LockScreenTilt",1);
			A_GiveInventory("PlayerIsDead",1);
			A_ClearOverlays(2,10);
			A_Overlay(66,"FirstPersonDeath2");
			A_ClearOverlays(-779,-777);
			A_Scream();
			A_StartSound("DSFDTHE");
			A_SpawnProjectile("XDeathArm1",50,0,random(0,360),2,random(0,160));
			for(int i=3;i>0;i--) A_SpawnProjectile("MuchBlood",50,0,random(0,360),2,random(0,160));
			for(int i=2;i>0;i--) A_SpawnProjectile("XDeath1",50,0,random(0,360),2,random(0,160));
		}
		XPL5 BCBCBCBC 10 A_SpawnProjectile ("MuchBlood",25,0,random (0,360),2,random (0,160));
		TNT1 A 0 A_NoBlocking;
		XPL5 DE 7 A_SpawnProjectile ("MuchBlood",15,0,random (0,360),2,random (0,160));
		TNT1 A 0 A_SpawnItemEx("GrowingBloodPool");
		XPL5 E -1;
		stop;
	Death.ExtremePunches: Death.ExplosiveImpact:
		TNT1 A 0 A_JumpIf(hasSkin, "AltXDeath");
		XPL6 A 5
		{
			A_ClearOverlays(-999,-999);
			A_StopSound(7);
			A_StopSound(1);
			A_Giveinventory("PB_LockScreenTilt",1);
			A_GiveInventory("PlayerIsDead",1);
			A_ClearOverlays(2,10);
			A_Overlay(66,"FirstPersonDeath3");
			A_ClearOverlays(-779,-777);
			A_Takeinventory("Kicking",1);
			ThrustThingZ(0,50,0,1);
			A_Recoil(25);
			A_SpawnProjectile("Brains2",50,0,random (0,360),2,random (0,160));
			A_SpawnProjectile("Brains3",50,0,random (0,360),2,random (0,160));
			A_SpawnProjectile("Brains4",50,0,random (0,360),2,random (0,160));
			A_SpawnProjectile("Brains5",50,0,random (0,360),2,random (0,160));
			A_SpawnProjectile("XDeathArm1",35,0,random (0,360),2,random (0,160));
			A_SpawnProjectile("XDeath3",40,0,random (0,360),2,random (0,160));
			A_SpawnItemEx("BasicMarineGib1",flags:SXF_TRANSFERTRANSLATION);
			A_XScream();
			A_NoBlocking();
			for(int i=2;i>0;i--) A_SpawnProjectile("SuperWallRedBlood",46,0,random (170,190),2,random (0,40));
			for(int i=4;i>0;i--)
			{
				A_SpawnProjectile("Brains1",50,0,random (0,360),2,random (0,160));
				A_SpawnProjectile("SmallBrainPiece",random (45,55),random (5,-5),random (170,190),2,random (0,40));
				A_SpawnProjectile("SmallBrainPiece",50,0,random (0,360),2,random (0,160));
				A_SpawnProjectile("BrainBlood",50,0,random (0,360),2,random (0,160));
				A_SpawnProjectile("XDeath1",40,0,random (0,360),2,random (0,160));
			}
		}
		XPL6 BCDE 5;
		XPL6 F -1;
		stop;
	Death.Disintegrate: Death.Slime:
		TNT1 A 0 A_JumpIf(hasSkin, "AltSlimeDeath");
		PMET A 0
		{
			A_ClearOverlays(-999,-999);
			A_StopSound(7);
			A_StopSound(1);
			A_Giveinventory("PB_LockScreenTilt",1);
			A_GiveInventory("PlayerIsDead",1);
			A_ClearOverlays(2,10);
			A_Overlay(66,"FirstPersonDeath4");
			A_ClearOverlays(-779,-777);
			A_StartSound("BIGSCREA");
			A_Takeinventory("Kicking",1);
			for(int i=2;i>0;i--) A_SpawnProjectile("MuchBlood",30,0,random (0,360),2,random (0,160));
			for(int i=3;i>0;i--) A_SpawnProjectile("Brutal_FlyingBloodLevel3",30,0,random (0,360),2,random (10,50));
			for(int i=4;i>0;i--)
			{
				A_SpawnProjectile("Brutal_FlyingBloodLevel3",25,0,random (0,360),2,random (40,60));
				A_SpawnProjectile("BrainBlood",40,0,random (0,360),2,random (0,160));
			}
		}
		PMET AAABBBCC 1;
		TNT1 A 0
		{
			for(int i=3;i>0;i--) A_SpawnProjectile("Brutal_FlyingBloodLevel3",30,0,random (0,360),2,random (10,50));
			for(int i=2;i>0;i--) A_SpawnProjectile("Brutal_FlyingBloodLevel3",25,0,random (0,360),2,random (40,60));
			A_SpawnItemEx("DisintegratedHuman3",flags:SXF_TRANSFERTRANSLATION);
			A_NoBlocking();
		}
		TNT1 A -1;
		stop;
	Crush: GenericCrush:
		CRS1 A 5
		{
			A_StopSound(7);
			A_StopSound(6);
			A_StopSound(5);
			A_StopSound(4);
			A_StopSound(1);
			A_ClearOverlays(-779,-777);
			A_StartSound("misc/xdeath4");
		}
		CRS1 A -1;
		stop;
	//Classic Death
	FirstPersonDeath1:
		TNT1 A 0 A_OverlayFlags(66, PSPF_PLAYERTRANSLATED, false);
		TNT1 A 0 A_StartSound("MinorHeadshot",0);
		PD01 AABBCCDDEEFF 1 A_SetRoll(roll+4.0);
		PD01 GGHHIIJJKKLLMMNNOOPP 1 A_SetRoll(roll-5.0);
		TNT1 A 0 A_StartSound("BODYF",0);
		PD01 OONNMMLLKKJJ 1 A_SetRoll(roll-5.0);
		TNT1 A 0 A_GiveInventory("DeathFader");
		PD01 J -1;
		stop;
	//Arm Blown Off
	FirstPersonDeath2:
		TNT1 A 0 A_OverlayFlags(66, PSPF_PLAYERTRANSLATED, false);
		TNT1 A 0 A_StartSound("MinorHeadshot",0);
		PD02 AABBC 1 A_SetRoll(roll-5.0);
		PD02 CDDEE 1 A_SetRoll(roll+5.0);
		PD02 GGHHIIGGHH 1
		{
			A_SpawnProjectile("Brutal_LiquidBlood2",30,0,random (0,360),2,random (60,120));
			A_SetRoll(roll+1.0);
		}
		PD02 IIGGHHIIGG 1
		{
			A_SpawnProjectile("Brutal_LiquidBlood2",30,0,random (0,360),2,random (60,120));
			A_SetRoll(roll-1.0);
		}
		PD02 GGHHIIGGHH 1
		{
			A_SpawnProjectile("Brutal_LiquidBlood2",30,0,random (0,360),2,random (60,120));
			A_SetRoll(roll+1.0);
		}
		PD02 IIGGHHIIGG 1
		{
			A_SpawnProjectile("Brutal_LiquidBlood2",30,0,random (0,360),2,random (60,120));
			A_SetRoll(roll-1.0);
		}
		PD02 GGHHIIGGHH 1
		{
			A_SpawnProjectile("Brutal_LiquidBlood2",30,0,random (0,360),2,random (60,120));
			A_SetRoll(roll+1.0);
		}
		PD02 IIGGHHIIGG 1
		{
			A_SpawnProjectile("Brutal_LiquidBlood2",30,0,random (0,360),2,random (60,120));
			A_SetRoll(roll-1.0);
		}
		PD02 GGHHIIGGHH 1
		{
			A_SpawnProjectile("Brutal_LiquidBlood2",30,0,random (0,360),2,random (60,120));
			A_SetRoll(roll+1.0);
		}
		PD02 IIGGHHIIGG 1
		{
			A_SpawnProjectile("Brutal_LiquidBlood2",30,0,random (0,360),2,random (60,120));
			A_SetRoll(roll-1.0);
		}
		PD02 JJKKLLMMNNOOPP 1 A_SetRoll(roll+2.0);
		TNT1 A 0 A_StartSound("BODYF",0);
		PD02 QQQQQQ 1 A_SpawnProjectile("Brutal_LiquidBlood2",10,0,random (0,360),2,random (60,120));
		TNT1 A 0 A_GiveInventory("DeathFader");
		PD02 Q -1;
		stop;
	//Explosive DeathPump
	FirstPersonDeath3:
		TNT1 A 0 A_OverlayFlags(66, PSPF_PLAYERTRANSLATED, true);
		PD03 AABBCC 1 A_SetRoll(roll+3.0);
	FPD3Loop:
		PD03 BBAABBCC 1
		{
			A_SetRoll(roll-1.0);
			if(!vel.z) { A_ClearOverlays(66,66); A_Overlay(66,"FPD3Splat"); }
		}
		PD03 AABBCC 1
		{
			A_SetRoll(roll+1.0);
			if(!vel.z) { A_ClearOverlays(66,66); A_Overlay(66,"FPD3Splat"); }
		}
	loop;
	FPD3Splat:
		TNT1 A 0
		{
			A_StartSound("BODYF",0);
			for(int i=5;i>0;i--) A_SpawnProjectile("XDeath1",20,0,random (0,360),2,random (0,160));
		}
		PD03 DDEEG 1 A_SetRoll(roll+5.0);
		PD03 GGGGG 1 A_SpawnProjectile("Brutal_LiquidBlood2",10,0,random (0,360),2,random (60,120));
		TNT1 A 0 A_GiveInventory("DeathFader");
		PD03 G -1;
		stop;
	//Slime Death
	FirstPersonDeath4:
		TNT1 A 0 A_OverlayFlags(66, PSPF_PLAYERTRANSLATED, false);
		TNT1 A 0 A_GiveInventory("DeathFader");
		PD04 AABBCCDD 1
		{
			A_SetRoll(roll+0.5);
			A_SetPitch(pitch+1.0);
			A_SpawnProjectile("Brutal_LiquidBlood3",40,0,random (0,360),2,random (60,120));
		}
		PD04 EEEFFFGGGHHH 1
		{
			A_SetRoll(roll-0.5);
			A_SetPitch(pitch+1.0);
			A_SpawnProjectile("Brutal_LiquidBlood3",30,0,random (0,360),2,random (60,120));
		}
		PD04 IIIJJJKKKLLL 1
		{
			A_SetRoll(roll+0.5);
			A_SetPitch(pitch+1.0);
			A_SpawnProjectile("Brutal_LiquidBlood3",30,0,random (0,360),2,random (60,120));
		}
		PD04 MMNNOO 1
		{
			A_SetRoll(roll-0.5);
			A_SetPitch(pitch+1.0);
			A_SpawnProjectile("Brutal_LiquidBlood3",20,0,random (0,360),2,random (60,120));
		}
		TNT1 A -1;
		stop;
		
	//Skin deaths:
	AltDeath:
		"####" O 0 {sprite = skinSprite;}
		"####" A 0
		{
			sprite = skinSprite;
			A_ClearOverlays(-999,-999);
			A_StopSound(7);
			A_StopSound(1);
			A_Giveinventory("PB_LockScreenTilt",1);
			A_GiveInventory("PlayerIsDead",1);
			if(target&&target.FindInventory("TypeSergeant")){
				A_ClearOverlays(2,10);
				A_Overlay(66,"FirstPersonDeath2");
			} else {
				A_ClearOverlays(2,11);
				A_Overlay(66,"FirstPersonDeath1");
			}
			A_ClearOverlays(-779,-777);
		}
		"####" HHHHHH 1; //A_SetRoll(roll+5.0,SPF_INTERPOLATE);
		"####" IIIIII 1 A_SpawnProjectile("Brutal_LiquidBlood3",40,0,random(0,360),2,random(60,120));
		"####" A 0 A_PlayerScream;
		"####" JJJJJJ 1 A_SpawnProjectile("Brutal_LiquidBlood2",30,0,random(0,360),2,random(60,120));
		"####" KKKKKK 1 A_SpawnProjectile("Brutal_LiquidBlood2",10,0,random (0,360),2,random(60,120));
		"####" LM 10;
		"####" A 0 A_SpawnItemEx("GrowingBloodPool");
		"####" NNNNNN 1 A_SpawnProjectile("Brutal_LiquidBlood2",10,0,random(0,360),2,random(60,120));
		"####" N -1;
		stop;
	AltSlimeDeath:
		"####" A 0 {sprite = skinSprite;}
		"####" A 0
		{
			A_ClearOverlays(-999,-999);
			A_StopSound(7);
			A_StopSound(1);
			A_Giveinventory("PB_LockScreenTilt",1);
			A_GiveInventory("PlayerIsDead",1);
			A_ClearOverlays(2,10);
			A_Overlay(66,"FirstPersonDeath4");
			A_ClearOverlays(-779,-777);
			A_PlayerScream();
			A_Takeinventory("Kicking",1);
			for(int i=2;i>0;i--) A_SpawnProjectile("MuchBlood",30,0,random (0,360),2,random (0,160));
			for(int i=3;i>0;i--) A_SpawnProjectile("Brutal_FlyingBloodLevel3",30,0,random (0,360),2,random (10,50));
			for(int i=4;i>0;i--)
			{
				A_SpawnProjectile("Brutal_FlyingBloodLevel3",25,0,random (0,360),2,random (40,60));
				A_SpawnProjectile("BrainBlood",40,0,random (0,360),2,random (0,160));
			}
		}
		"####" H 5 A_SpriteOffset(0, 2);
		"####" I 5 A_SpriteOffset(0, 3);
		"####" J 5 A_SpriteOffset(0, 4);
		"####" K 5 A_SpriteOffset(0, 4);
		"####" L 5 A_SpriteOffset(0, 5);
		"####" M 5 A_SpriteOffset(0, 6);
		"####" N 2
		{
			A_SpriteOffset(0.0, 8);
			for(int i=3;i>0;i--) A_SpawnProjectile("Brutal_FlyingBloodLevel3",30,0,random (0,360),2,random (10,50));
			for(int i=2;i>0;i--) A_SpawnProjectile("Brutal_FlyingBloodLevel3",25,0,random (0,360),2,random (40,60));
			A_NoBlocking();
		}
		TNT1 A -1;
		stop;
	AltXDeath:
		"####" O 0 {sprite = skinSprite;}
		"####" O 5
		{
			A_ClearOverlays(-999,-999);
			A_StopSound(7);
			A_StopSound(1);
			A_Giveinventory("PB_LockScreenTilt",1);
			A_GiveInventory("PlayerIsDead",1);
			A_ClearOverlays(2,10);
			A_Overlay(66,"FirstPersonDeath3");
			A_ClearOverlays(-779,-777);
			A_Takeinventory("Kicking",1);
			ThrustThingZ(0,50,0,1);
			A_Recoil(25);
			A_XScream();
			A_NoBlocking();
			for(int i=2;i>0;i--) A_SpawnProjectile("SuperWallRedBlood",46,0,random (170,190),2,random (0,40));
		}
		"####" QRSTUV 5;
		"####" W -1;
		stop;
	AltFreezeDeath:
		"####" G 0 {sprite = skinSprite;}
		"####" G 0
		{
			A_ClearOverlays(-999,-999);
			A_StopSound(7);
			A_StopSound(1);
			A_GiveInventory("PlayerIsDead",1);
			A_GiveInventory("CantDoAction",1);
			A_NoBlocking();
			A_StartSound("DSBOTTLE");
			for(int i=4;i>0;i--)
			{
				A_SpawnProjectile("IceDust",48,0,random(0,360),2,random(0,160));
				A_SpawnProjectile("IceBlood",48,0,random(0,360),2,random(0,160));
			}
		}
		"####" G 0 A_SetTranslation("FreezeDeath");
		"####" G -1;
		stop;
	}
}

class PB_VoodooDoll : PB_PlayerPrawn
{
	override void PostBeginPlay() {}
	
	Default
	{
		+NOPAIN;
		/*+ROLLSPRITE
		+ROLLCENTER
		+FLOATBOB*/
	}
	
	States
	{
	Spawn:
		TNT1 A 0;
		TNT1 A 0 A_TakeInventory("PlayerIsDead",1);
		TNT1 A 2;
	Death:
	XDeath:
	VooDoo:
		PL4Y A 1;
		loop;
	}
}