class PB_PlayerPawn : PlayerPawnBase
{
	bool lfoot;
	
	Default
	{
		Mass 500;
		GibHealth 20;
		Species "Marines";
		BloodType "NashGoreBlood";
		
		DamageFactor "Head",1.0;
		DamageFactor "Leg",1.0;
		DamageFactor "FriendBullet",0.0;
		DamageFactor "Taunt",0.0;
		DamageFactor "KillMe",0.0;
		DamageFactor "SSG",5.0;
		DamageFactor "Shrapnel",0.0;
		DamageFactor "Blood",0.0;
		DamageFactor "BlueBlood",0.0;
		DamageFactor "GreenBlood",0.0;
		DamageFactor "MinorHead",0.0;
		DamageFactor "Decaptate",0.0;
		DamageFactor "IceExplosion",0.0;
		DamageFactor "MonsterKnocked",0.0;
		DamageFactor "Trample",0.0;
		DamageFactor "Kick",0.75;
		DamageFactor "Fatality",5.0;
		DamageFactor "BHFTOnBarrel",0.0;
		DamageFactor "GibRemoving",0.0;
		DamageFactor "SuperPunch",5.0;
		DamageFactor "HelperMarineFatallity",0.0;
		DamageFactor "SpawnMarine",0.0;
		DamageFactor "TeleportRemover",0.0;
		DamageFactor "CancelTeleportFog",0.0;
		DamageFactor "CauseObjectsToSplash",0.0;
		DamageFactor "CauseObjectsToSplashSlime",0.0;
		DamageFactor "CauseObjectsToSplashNukage",0.0;
		DamageFactor "CauseObjectsToSplashBlood",0.0;
		DamageFactor "CauseObjectsToSplashLava",0.0;
		DamageFactor "SuperKick",0.0 ;
		DamageFactor "BFGShield",0.0;
		DamageFactor "KillMeBot",0.0;
		DamageFactor "Flames",0.875;
		DamageFactor "Fire",0.875;
		DamageFactor "Burn",0.875;
		DamageFactor "Disintegrate",1.0;
		DamageFactor "Avoid",0;
		
		Player.ViewHeight 44;
		Player.AttackZOffset 17;
		Player.ColorRange 112,127;
		Player.JumpZ 7.4;
		Player.GruntSpeed 24;
		Player.DisplayName "Project Brutality";
		Player.CrouchSprite "PLYC";
		Player.ViewBob 0.0;

		Player.WeaponSlot 1,"PB_Axe","PB_Chainsaw","PB_Fists";
		Player.WeaponSlot 2,"PB_Pistol","PB_Revolver","PB_Deagle","PB_SMG","PB_MP40";
		Player.WeaponSlot 3,"PB_Shotgun","PB_AutoShotgun","PB_SSG","PB_QuadSG";
		Player.WeaponSlot 4,"PB_DMR","PB_Carbine","PB_ChexRifle","PB_LMG";
		Player.WeaponSlot 5,"PB_Minigun","PB_Nailgun","PB_MG42";
		Player.WeaponSlot 6,"PB_SuperGL","PB_RocketLauncher";
		Player.WeaponSlot 7,"PB_M1Plasma","PB_M2Plasma";
		Player.WeaponSlot 8,"PB_CryoRifle","PB_Flamethrower";
		Player.WeaponSlot 9,"PB_Railgun","PB_BFG9000";
		Player.WeaponSlot 0,"PB_DemonTech","PB_Unmaker";

		// Player.StartItem "PB_PDAWeaponContainer",1;
		Player.StartItem "PB_DMR";
		Player.StartItem "PB_Pistol";
		Player.StartItem "PB_Fists";
		Player.StartItem "CarbineFullAuto";
		Player.StartItem "PB_HighCalMag",90;
		Player.StartItem "DMRAmmo",31;
		Player.StartItem "LeftDMRAmmo",31;
		Player.StartItem "PrimaryPistolAmmo",16;
		Player.StartItem "SecondaryPistolAmmo",16;
		Player.StartItem "PB_LowCalMag",60;
		Player.StartItem "ShotgunAmmo",9;
		Player.StartItem "AutoShotgunAmmo",12;
		Player.StartItem "LeftASGAmmo",12;
		Player.StartItem "RevolverAmmo",6;
		Player.StartItem "LeftRevolverAmmo",6;
		Player.StartItem "SSGAmmoCounter",2;
		Player.StartItem "LeftSSGAmmo",2;
		Player.StartItem "HasNotPickedUpSSG",1;
		Player.StartItem "QSSGAmmoCounter",4;
		Player.StartItem "PB_NailgunAmmo",120;
		Player.StartItem "PlasmaAmmo",60;
		Player.StartItem "LeftPlasmaAmmo",60;
		Player.StartItem "RocketRounds",6;
		Player.StartItem "RailgunAmmo",60;
		Player.StartItem "IsPlayer",1;
		Player.StartItem "SMGAmmo",51;
		Player.StartItem "LeftSMGAmmo",51;
		Player.StartItem "XRifleAmmo",41;
		Player.StartItem "LeftXRifleAmmo",41;
		Player.StartItem "LMGAmmo",75;
		Player.StartItem "M2PlasmaAmmo",50;
		Player.StartItem "LeftM2PlasmaAmmo",50;
		Player.StartItem "MP40Ammo",32;
		Player.StartItem "LeftMP40Ammo",32;
		Player.StartItem "HellAmmo",60;
		Player.StartItem "GrenadeRounds",7;
		//Player.StartItem "PulseCannonAmmo",60;
		Player.StartItem "DeagleAmmo",12;
		Player.StartItem "LeftDeagleAmmo",12;
		Player.StartItem "CheXRifleAmmo",42;
		Player.StartItem "CryoDMRAmmo",60;
		Player.StartItem "HasBuckShot",1; //Added for proper SG ammo type sorting
		Player.StartItem "FragGrenadeSelected",1;
		Player.StartItem "PB_GrenadeAmmo",3;
		Player.StartItem "PB_QuickLauncherAmmo",4;
		Player.StartItem "FlamerAmmo",90;

		+ROLLSPRITE
		+THRUSPECIES
		+MTHRUSPECIES
		+THRUGHOST
		-NOSKIN
	}

	override void PostBeginPlay()
	{
		Super.PostBeginPlay();
		if(!player||(player.mo!=self))
		{
			let v = Spawn("PB_VoodooDoll",pos);
			v.angle = angle; v.player = player;
			Destroy(); return;
		}
	}

	override int DamageMobj(actor inflictor,actor source,int damage,name mod,int flags,double angle)
	{
		switch(mod)
		{ case 'Blast': case 'ExplosiveImpact': case 'Explosive': ThrustThingZ(0,20,1,0); break; }
		if(source&&source.FindInventory("EnemyIsArchvile"))
		{
			A_SpawnProjectile("NewRocketExploFX",30,0,random(0,360),2,random(0,360));
			for(int i=12;i>0;i--) A_SpawnProjectile("ExplosionParticleHeavy",30,0,random(0,360),2,random(0,180));
		}
		return Super.DamageMobj(inflictor,source,damage,mod,flags,angle);
	}
	
	override void CheatGive (String name, int amount)
	{
		if(name ~== "PB_ALL" || name ~== "PB_Upgrades")
		{
			for(int i = 0; i <= self.PB_ActUpgrades.size() -1; i++)
				giveinventory(self.PB_ActUpgrades[i],2);
			return;
		}
		super.cheatgive(name,amount);
	}
	
	//array to save all the upgrades
	static const string PB_ActUpgrades[] = {
		"PB_Deagle", "PB_SMG", //slot 2
		"PB_AutoshotgunUpgrade","PB_QuadSGUpgrade","PB_SGMagazine", //slot3
		"PB_LMG","PB_HDMRUpgrade", //slot 4
		"PB_Minigun","MinigunUpgraded"," PB_MinigunUpgrade", //slot 5 
		"PB_M2Upgrade", //slot 7
		"PB_Flamethrower", "PB_FlamethrowerUpgrade","FlamerUpgraded" //slot 9?
	};

	States
	{
	Spawn:
		PLAY A 1
		{
			let psp = player.FindPSprite(PSP_WEAPON);
			let pspOverlay = player.FindPSprite(OverlayID());
			if (!psp||!pspOverlay)
				return;
			ForceMoveUnlock();
			A_TakeInventory("PlayerIsDead",1);
				A_TakeInventory("DeathFader",1);
			A_TakeInventory("IsInvisible",1);
			A_TakeInventory("ChainguyguyContinue",1);
			A_TakeInventory("DoNotJump",1);
			A_TakeInventory("CantDoAction",1);
			A_Takeinventory("PB_LockScreenTilt",1);
			A_ClearOverlays(66);
			ACS_ExecuteAlways(171,0,0,0,0);
		}
	StandStillLoop:
		PLAY A 4
		{
			bTHRUSPECIES = 0;
			A_TakeInventory("PlayerIsDead",1);
				A_TakeInventory("DeathFader",1);
			ForceMoveUnlock();
		}
		loop;
	See:
		TNT1 A 0 {
			A_TakeInventory("PlayerIsDead",1);	
			A_TakeInventory("DeathFader",1);
		}
		PLAY A 4 A_TakeInventory("ChainguyguyContinue",1);
		PLAY B 4;
		PLAY C 4
		{
			if(lfoot) lfoot = false;
			else lfoot = true;
			if(CountInv("BootsSmearedWithRedBlood"))
			{
				A_SpawnItemEx(lfoot?"RedBloodFootPrintLeft":"RedBloodFootPrintRight",0,7);
				A_TakeInventory("BootsSmearedWithRedBlood",1);
			}
			if(CountInv("BootsSmearedWithBlueBlood"))
			{
				A_SpawnItemEx(lfoot?"BlueBloodFootPrintLeft":"BlueBloodFootPrintRight",0,7);
				A_TakeInventory("BootsSmearedWithBlueBlood",1);
			}
			if(CountInv("BootsSmearedWithGreenBlood"))
			{
				A_SpawnItemEx(lfoot?"GreenBloodFootPrintLeft":"GreenBloodFootPrintRight",0,7);
				A_TakeInventory("BootsSmearedWithGreenBlood",1);
			}
		}
		PLAY D 4;
		goto StandStillLoop;
	Missile:
		PLAY E 6 BRIGHT;
		goto Spawn;
	Melee:
		PLAY F 6;
		goto Missile;
	Pain:
		PLAY G 4 A_Pain;
		goto See;
	Death:
		TNT1 A 0
		{
			A_ClearOverlays(-999,-999);
			A_StopSound(7);
			A_StopSound(1);
			if(target&&target.FindInventory("TypeSergeant")) SetStateLabel("ArmDeath");
		}
		MARN A 0
		{
			A_Giveinventory("PB_LockScreenTilt",1);
			A_GiveInventory("PlayerIsDead",1);
			A_ClearOverlays(2,11);
			A_Overlay(66,"FirstPersonDeath1");
			A_ClearOverlays(-779,-777);
		}
		PLAY HHHHHH 1; //A_SetRoll(roll+5.0,SPF_INTERPOLATE);
		PLAY IIIIII 1 A_SpawnProjectile("Brutal_LiquidBlood3",40,0,random(0,360),2,random(60,120));
		TNT1 A 0 A_PlayerScream;
		PLAY JJJJJJ 1 A_SpawnProjectile("Brutal_LiquidBlood2",30,0,random(0,360),2,random(60,120));
		PLAY KKKKKK 1 A_SpawnProjectile("Brutal_LiquidBlood2",10,0,random (0,360),2,random(60,120));
		PLAY LM 10;
		TNT1 A 0 A_SpawnItemEx("GrowingBloodPool");
		PLAY NNNNNN 1 A_SpawnProjectile("Brutal_LiquidBlood2",10,0,random(0,360),2,random(60,120));
		PLAY N -1;
		stop;
	Death.Ice: Death.Frost: Death.Freeze:
		FZD1 C 0
		{
			A_ClearOverlays(-999,-999);
			A_StopSound(7);
			A_StopSound(1);
			A_GiveInventory("PlayerIsDead",1);
			A_GiveInventory("CantDoAction",1);
			A_NoBlocking();
			A_StartSound("DSBOTTLE");
			for(int i=4;i>0;i--)
			{
				A_SpawnProjectile("IceDust",48,0,random(0,360),2,random(0,160));
				A_SpawnProjectile("IceBlood",48,0,random(0,360),2,random(0,160));
			}
		}
		FZD1 C -1;
		stop;
	ArmDeath:
		XPL5 A 10
		{
			A_StopSound(7);
			A_StopSound(1);
			A_Giveinventory("PB_LockScreenTilt",1);
			A_GiveInventory("PlayerIsDead",1);
			A_ClearOverlays(2,10);
			A_Overlay(66,"FirstPersonDeath2");
			A_ClearOverlays(-779,-777);
			A_Scream();
			A_StartSound("DSFDTHE");
			A_SpawnProjectile("XDeathArm1",50,0,random(0,360),2,random(0,160));
			for(int i=3;i>0;i--) A_SpawnProjectile("MuchBlood",50,0,random(0,360),2,random(0,160));
			for(int i=2;i>0;i--) A_SpawnProjectile("XDeath1",50,0,random(0,360),2,random(0,160));
		}
		XPL5 BCBCBCBC 10 A_SpawnProjectile ("MuchBlood",25,0,random (0,360),2,random (0,160));
		TNT1 A 0 A_NoBlocking;
		XPL5 DE 7 A_SpawnProjectile ("MuchBlood",15,0,random (0,360),2,random (0,160));
		TNT1 A 0 A_SpawnItemEx("GrowingBloodPool");
		XPL5 E -1;
		stop;
	Death.ExtremePunches: Death.ExplosiveImpact:
		XPL6 A 5
		{
			A_ClearOverlays(-999,-999);
			A_StopSound(7);
			A_StopSound(1);
			A_Giveinventory("PB_LockScreenTilt",1);
			A_GiveInventory("PlayerIsDead",1);
			A_ClearOverlays(2,10);
			A_Overlay(66,"FirstPersonDeath3");
			A_ClearOverlays(-779,-777);
			A_Takeinventory("Kicking",1);
			ThrustThingZ(0,50,0,1);
			A_Recoil(25);
			A_SpawnProjectile("Brains2",50,0,random (0,360),2,random (0,160));
			A_SpawnProjectile("Brains3",50,0,random (0,360),2,random (0,160));
			A_SpawnProjectile("Brains4",50,0,random (0,360),2,random (0,160));
			A_SpawnProjectile("Brains5",50,0,random (0,360),2,random (0,160));
			A_SpawnProjectile("XDeathArm1",35,0,random (0,360),2,random (0,160));
			A_SpawnProjectile("XDeath3",40,0,random (0,360),2,random (0,160));
			A_SpawnItemEx("BasicMarineGib1",flags:SXF_TRANSFERTRANSLATION);
			A_XScream();
			A_NoBlocking();
			for(int i=2;i>0;i--) A_SpawnProjectile("SuperWallRedBlood",46,0,random (170,190),2,random (0,40));
			for(int i=4;i>0;i--)
			{
				A_SpawnProjectile("Brains1",50,0,random (0,360),2,random (0,160));
				A_SpawnProjectile("SmallBrainPiece",random (45,55),random (5,-5),random (170,190),2,random (0,40));
				A_SpawnProjectile("SmallBrainPiece",50,0,random (0,360),2,random (0,160));
				A_SpawnProjectile("BrainBlood",50,0,random (0,360),2,random (0,160));
				A_SpawnProjectile("XDeath1",40,0,random (0,360),2,random (0,160));
			}
		}
		XPL6 BCDE 5;
		XPL6 F -1;
		stop;
	Death.Disintegrate: Death.Slime:
		PMET A 0
		{
			A_ClearOverlays(-999,-999);
			A_StopSound(7);
			A_StopSound(1);
			A_Giveinventory("PB_LockScreenTilt",1);
			A_GiveInventory("PlayerIsDead",1);
			A_ClearOverlays(2,10);
			A_Overlay(66,"FirstPersonDeath4");
			A_ClearOverlays(-779,-777);
			A_StartSound("BIGSCREA");
			A_Takeinventory("Kicking",1);
			for(int i=2;i>0;i--) A_SpawnProjectile("MuchBlood",30,0,random (0,360),2,random (0,160));
			for(int i=3;i>0;i--) A_SpawnProjectile("Brutal_FlyingBloodLevel3",30,0,random (0,360),2,random (10,50));
			for(int i=4;i>0;i--)
			{
				A_SpawnProjectile("Brutal_FlyingBloodLevel3",25,0,random (0,360),2,random (40,60));
				A_SpawnProjectile("BrainBlood",40,0,random (0,360),2,random (0,160));
			}
		}
		PMET AAABBBCC 1;
		TNT1 A 0
		{
			for(int i=3;i>0;i--) A_SpawnProjectile("Brutal_FlyingBloodLevel3",30,0,random (0,360),2,random (10,50));
			for(int i=2;i>0;i--) A_SpawnProjectile("Brutal_FlyingBloodLevel3",25,0,random (0,360),2,random (40,60));
			A_SpawnItemEx("DisintegratedHuman3",flags:SXF_TRANSFERTRANSLATION);
			A_NoBlocking();
		}
		TNT1 A -1;
		stop;
	Crush: GenericCrush:
		CRS1 A 5
		{
			A_StopSound(7);
			A_StopSound(6);
			A_StopSound(5);
			A_StopSound(4);
			A_StopSound(1);
			A_ClearOverlays(-779,-777);
			A_StartSound("misc/xdeath4");
		}
		CRS1 A -1;
		stop;
	//Classic Death
	FirstPersonDeath1:
		TNT1 A 0 A_OverlayFlags(66, PSPF_PLAYERTRANSLATED, false);
		TNT1 A 0 A_StartSound("MinorHeadshot",0);
		PD01 AABBCCDDEEFF 1 A_SetRoll(roll+4.0);
		PD01 GGHHIIJJKKLLMMNNOOPP 1 A_SetRoll(roll-5.0);
		TNT1 A 0 A_StartSound("BODYF",0);
		PD01 OONNMMLLKKJJ 1 A_SetRoll(roll-5.0);
		TNT1 A 0 A_GiveInventory("DeathFader");
		PD01 J -1;
		stop;
	//Arm Blown Off
	FirstPersonDeath2:
		TNT1 A 0 A_OverlayFlags(66, PSPF_PLAYERTRANSLATED, false);
		TNT1 A 0 A_StartSound("MinorHeadshot",0);
		PD02 AABBC 1 A_SetRoll(roll-5.0);
		PD02 CDDEE 1 A_SetRoll(roll+5.0);
		PD02 GGHHIIGGHH 1
		{
			A_SpawnProjectile("Brutal_LiquidBlood2",30,0,random (0,360),2,random (60,120));
			A_SetRoll(roll+1.0);
		}
		PD02 IIGGHHIIGG 1
		{
			A_SpawnProjectile("Brutal_LiquidBlood2",30,0,random (0,360),2,random (60,120));
			A_SetRoll(roll-1.0);
		}
		PD02 GGHHIIGGHH 1
		{
			A_SpawnProjectile("Brutal_LiquidBlood2",30,0,random (0,360),2,random (60,120));
			A_SetRoll(roll+1.0);
		}
		PD02 IIGGHHIIGG 1
		{
			A_SpawnProjectile("Brutal_LiquidBlood2",30,0,random (0,360),2,random (60,120));
			A_SetRoll(roll-1.0);
		}
		PD02 GGHHIIGGHH 1
		{
			A_SpawnProjectile("Brutal_LiquidBlood2",30,0,random (0,360),2,random (60,120));
			A_SetRoll(roll+1.0);
		}
		PD02 IIGGHHIIGG 1
		{
			A_SpawnProjectile("Brutal_LiquidBlood2",30,0,random (0,360),2,random (60,120));
			A_SetRoll(roll-1.0);
		}
		PD02 GGHHIIGGHH 1
		{
			A_SpawnProjectile("Brutal_LiquidBlood2",30,0,random (0,360),2,random (60,120));
			A_SetRoll(roll+1.0);
		}
		PD02 IIGGHHIIGG 1
		{
			A_SpawnProjectile("Brutal_LiquidBlood2",30,0,random (0,360),2,random (60,120));
			A_SetRoll(roll-1.0);
		}
		PD02 JJKKLLMMNNOOPP 1 A_SetRoll(roll+2.0);
		TNT1 A 0 A_StartSound("BODYF",0);
		PD02 QQQQQQ 1 A_SpawnProjectile("Brutal_LiquidBlood2",10,0,random (0,360),2,random (60,120));
		TNT1 A 0 A_GiveInventory("DeathFader");
		PD02 Q -1;
		stop;
	//Explosive DeathPump
	FirstPersonDeath3:
		TNT1 A 0 A_OverlayFlags(66, PSPF_PLAYERTRANSLATED, true);
		PD03 AABBCC 1 A_SetRoll(roll+3.0);
	FPD3Loop:
		PD03 BBAABBCC 1
		{
			A_SetRoll(roll-1.0);
			if(!vel.z) { A_ClearOverlays(66,66); A_Overlay(66,"FPD3Splat"); }
		}
		PD03 AABBCC 1
		{
			A_SetRoll(roll+1.0);
			if(!vel.z) { A_ClearOverlays(66,66); A_Overlay(66,"FPD3Splat"); }
		}
	loop;
	FPD3Splat:
		TNT1 A 0
		{
			A_StartSound("BODYF",0);
			for(int i=5;i>0;i--) A_SpawnProjectile("XDeath1",20,0,random (0,360),2,random (0,160));
		}
		PD03 DDEEG 1 A_SetRoll(roll+5.0);
		PD03 GGGGG 1 A_SpawnProjectile("Brutal_LiquidBlood2",10,0,random (0,360),2,random (60,120));
		TNT1 A 0 A_GiveInventory("DeathFader");
		PD03 G -1;
		stop;
	//Slime Death
	FirstPersonDeath4:
		TNT1 A 0 A_OverlayFlags(66, PSPF_PLAYERTRANSLATED, false);
		TNT1 A 0 A_GiveInventory("DeathFader");
		PD04 AABBCCDD 1
		{
			A_SetRoll(roll+0.5);
			A_SetPitch(pitch+1.0);
			A_SpawnProjectile("Brutal_LiquidBlood3",40,0,random (0,360),2,random (60,120));
		}
		PD04 EEEFFFGGGHHH 1
		{
			A_SetRoll(roll-0.5);
			A_SetPitch(pitch+1.0);
			A_SpawnProjectile("Brutal_LiquidBlood3",30,0,random (0,360),2,random (60,120));
		}
		PD04 IIIJJJKKKLLL 1
		{
			A_SetRoll(roll+0.5);
			A_SetPitch(pitch+1.0);
			A_SpawnProjectile("Brutal_LiquidBlood3",30,0,random (0,360),2,random (60,120));
		}
		PD04 MMNNOO 1
		{
			A_SetRoll(roll-0.5);
			A_SetPitch(pitch+1.0);
			A_SpawnProjectile("Brutal_LiquidBlood3",20,0,random (0,360),2,random (60,120));
		}
		TNT1 A -1;
		stop;
	}
}

class PB_VoodooDoll : PB_PlayerPawn
{
	override void PostBeginPlay() {}
	
	Default
	{
		+NOPAIN;
		/*+ROLLSPRITE
		+ROLLCENTER
		+FLOATBOB*/
	}
	
	States
	{
	Spawn:
		TNT1 A 0;
		TNT1 A 0 A_TakeInventory("PlayerIsDead",1);
		TNT1 A 2;
	Death:
	XDeath:
	VooDoo:
		PLAY A 1;
		loop;
	}
}