Class PB_PistolZombieman: PB_Zombieman //Replaces ZombieMan
{
	Default
	{
		DropItem "PistolDrop";
	}
	States
	{
	
		Death.Ice:
		Death.Freeze:
		Death.Frost:
		TNT1 A 0 A_ChangeFlag("SHOOTABLE", 0);
		TNT1 A 0 A_ChangeFlag("SOLID", 0);
		TNT1 A 0 A_SpawnItem("FrozenPistolZombieman");
		Stop;
		
	Pain.Stun:
		TNT1 A 0
		TNT1 A 0 A_SpawnItemEx ("StunElectrocute", random (-4, 4), random (-4, 4),  random (16, 32), 0, 0)
        TNT1 A 0 A_SpawnItem ("HeadshotTarget30", 0, 45,0)
		PSPO G 1 A_Pain
		PSPO GGGGGGGGGG 3 A_SpawnItemEx ("StunElectrocute", random (-12, 12), random (-12, 12),  random (16, 52), 0, 0)
        TNT1 A 0 A_SpawnItem ("HeadshotTarget30", 0, 45,0)
		PSPO G 1 A_Pain
		PSPO GGGGGGGGGG 3 A_SpawnItemEx ("StunElectrocute", random (-12, 12), random (-12, 12),  random (16, 52), 0, 0)
        TNT1 A 0 A_SpawnItem ("HeadshotTarget30", 0, 45,0)
		PSPO G 1 A_Pain
		PSPO GGGGGGGGGG 3 A_SpawnItemEx ("StunElectrocute", random (-12, 12), random (-12, 12),  random (16, 52), 0, 0)
        TNT1 A 0 A_SpawnItem ("HeadshotTarget30", 0, 45,0)
		PSPO G 1 A_Pain
		PSPO GGGGGGGGGG 3 A_SpawnItemEx ("StunElectrocute", random (-12, 12), random (-12, 12),  random (16, 52), 0, 0)
        TNT1 A 0 A_SpawnItem ("HeadshotTarget30", 0, 45,0)
		PSPO G 1 A_Pain
		PSPO GGGGGGGGGG 3 A_SpawnItemEx ("StunElectrocute", random (-12, 12), random (-12, 12),  random (16, 52), 0, 0)
        TNT1 A 0 A_SpawnItem ("HeadshotTarget30", 0, 45,0)
		PSPO G 1 A_Pain
		Goto See
		
	Pain.Siphon:
        TNT1 A 0 A_SpawnItem ("HeadshotTarget30", 0, 45,0)
		
		TNT1 AAA 0 A_SpawnItemEx ("RedLightning_Small", random (-12, 12), random (-12, 12), random (16, 52), 0, 0)
		PSPO G 1 
		{
			A_FaceTarget;
			A_GiveToTarget("HealthBonus",4);
		}
		PSPO G 5 A_FaceTarget 
		TNT1 A 0 A_Pain
		Goto See
	
	
		Possession:
		TNT1 A 0 A_SetInvulnerable
		PSPO G 3
		PSPO G 3 A_Pain
		"####" "#" 35 ACS_NamedExecuteAlways("Pos - Flicker effect")
		TNT1 A 0 A_UnSetInvulnerable
		Goto See
	
	
	Death.Fatality:
	    TNT1 A 0
		TNT1 A 0 A_Pain
        TNT1 A 0 A_NoBlocking
		TNT1 A 0 A_JumpIfIntargetInventory("FistsSelected", 1, 1)
		Goto Death.ExplosiveImpact
		TNT1 A 0 A_GiveToTarget("GoFatality", 1)
        TNT1 A 0 A_Jump(256,"Death.Fatality1", "Death.Fatality1", "Death.Fatality2", "Death.Fatality2", "Death.Fatality3", "Death.Fatality4")
		Goto Death.Fatality1

	Death.Fatality1:
		TNT1 A 0 A_Scream
        TNT1 A 0 A_GiveToTarget("ZombieManFatality", 1)
        Stop
	Death.Fatality2:
		TNT1 A 0 A_Scream
        TNT1 A 0 A_GiveToTarget("ZombieManFatality2", 1)
        Stop
	Death.Fatality3:
		TNT1 A 0 A_Scream
        TNT1 A 0 A_GiveToTarget("PistolZombiemanFatality1", 1)
        Stop
	Death.Fatality4:
		TNT1 A 0 A_Scream
        TNT1 A 0 A_GiveToTarget("ZombieManFatality4", 1)
        Stop
	Death.Fatality5://Didn't like this one, but it gives me an idea...
		TNT1 A 0 A_Scream
		TNT1 A 0 A_GiveToTarget("ZombieManFatality5", 1)
		Stop
	Death.Fatality6:
		TNT1 A 0 A_Scream
		TNT1 A 0 A_GiveToTarget("ZombieManFatality6", 1)
		Stop
	
	Death.Shrink:
		TNT1 A 1 A_PlaySound("Shrink", 3)
		TNT1 A 0 A_SpawnItemEx ("PistolZombiemanShrinkFX1", 0, 0,  5, 0, 0)
		TNT1 A 1 A_SpawnItemEx ("PistolZombiemanShrinkFX2", 0, 0, 5, 0, 0)
		TNT1 A 1 A_SpawnItemEx ("PistolZombiemanShrinkFX3", 0, 0, 5, 0, 0)
		TNT1 A 1 A_SpawnItemEx ("PistolZombiemanShrinkFX4", 0, 0, 5, 0, 0)
		TNT1 A 1 A_SpawnItemEx ("PistolZombiemanShrinkFX5", 0, 0, 5, 0, 0)
		TNT1 A 1 A_SpawnItemEx ("PistolZombiemanShrinkFX6", 0, 0, 5, 0, 0)
		TNT1 A 1 A_SpawnItemEx ("PistolZombiemanShrinkFX7", 0, 0, 5, 0, 0)
		TNT1 A 1 A_SpawnItemEx ("LilPistolZombieMan", 1)
		stop
		
			ReplaceVanilla:
		TNT1 A 0 A_ChangeFlag("THRUACTORS", 1)
		TNT1 A 0 A_ChangeFlag("COUNTKILL", 0)
		TNT1 A 0 A_SpawnItemEx ("Vanilla_PistolZombieman",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION |SXF_TRANSFERSPECIAL| SXF_TRANSFERAMBUSHFLAG ,0)
		Stop
	
	Spawn:
		TNT1 A 0
		TNT1 A 0 ACS_ExecuteAlways(796, 0, 0, 0, 0)//Check if Vanilla Mode is activated
		TNT1 A 0 A_GiveInventory("SKZombieman", 1)
		TNT1 A 0 A_GiveInventory("TypeZombieMan", 1)
		TNT1 A 0 A_TakeInventory("ZombiemanAmmo", 20)
		TNT1 A 0 A_GiveInventory("ZombieManAmmo", random(1,10))
		
		PSPO B 1
	Goto Stand
	
	Stand:
		//TNT1 A 0 A_SpawnItem ("LegTarget100", 10)
		TNT1 A 0 A_CheckSight("Stand2")
		TNT1 A 0 A_SpawnItem ("HeadshotTarget20", 5, 44,0)
		PSPO AB 10 A_Look
		Loop
		
	Stand2:
		PSPO AB 14 A_Look
		Goto Stand
		
	WalkAround:
		TNT1 A 0 A_TakeInventory("SKZombieman", 1)

        TNT1 A 0 A_SpawnItemEx("FootStep", 0, 0, 10, 0, 0)

		TNT1 A 0 A_SpawnItem ("HeadshotTarget4", 5, 40,0)
		TNT1 A 0 A_SpawnItem ("LegTargetBase", 10)

		PSPO A 2 A_Look
		TNT1 A 0 A_SpawnItem ("HeadshotTarget4", 5, 40,0)
		TNT1 A 0 A_SpawnItem ("LegTargetBase", 10)
		PSPO A 2 A_Wander
        TNT1 A 0 A_SpawnItem ("HeadshotTarget10", 5, 40,0)
		TNT1 A 0 A_SpawnItem ("LegTargetBase", 10)
		TNT1 A 0 A_Recoil(-1)

		TNT1 A 0 A_SpawnItem ("HeadshotTarget4", 5, 40,0)
		TNT1 A 0 A_SpawnItem ("LegTargetBase", 10)
		PSPO B 2 A_Look
		TNT1 A 0 A_SpawnItem ("HeadshotTarget4", 5, 40,0)
		TNT1 A 0 A_SpawnItem ("LegTargetBase", 10)
		PSPO B 2 A_Wander
	    TNT1 A 0 A_PlaySound("humans/step",3)

		TNT1 A 0 A_SpawnItem ("HeadshotTarget4", 5, 40,0)
		TNT1 A 0 A_SpawnItem ("LegTargetBase", 10)
		PSPO D 2 A_Look
		TNT1 A 0 A_SpawnItem ("HeadshotTarget4", 5, 40,0)
		TNT1 A 0 A_SpawnItem ("LegTargetBase", 10)
		PSPO D 2 A_Wander
	    TNT1 A 0 A_PlaySound("humans/step",4)

		TNT1 A 0 A_SpawnItem ("HeadshotTarget4", 5, 40,0)
		TNT1 A 0 A_SpawnItem ("LegTargetBase", 10)
		PSPO C 2 A_Look
		TNT1 A 0 A_SpawnItem ("HeadshotTarget4", 5, 40,0)
		TNT1 A 0 A_SpawnItem ("LegTargetBase", 10)
		PSPO C 2 A_Wander

		TNT1 A 0 A_SpawnItem ("HeadshotTarget4", 5, 40,0)
		TNT1 A 0 A_SpawnItem ("LegTargetBase", 10)
		PSPO D 2 A_Look
		TNT1 A 0 A_SpawnItem ("HeadshotTarget4", 5, 40,0)
		TNT1 A 0 A_SpawnItem ("LegTargetBase", 10)
		PSPO D 2 A_Wander
	    TNT1 A 0 A_PlaySound("humans/step",4)

		TNT1 A 0 A_SpawnItem ("HeadshotTarget4", 5, 40,0)
		TNT1 A 0 A_SpawnItem ("LegTargetBase", 10)
		PSPO B 2 A_Look
		TNT1 A 0 A_SpawnItem ("HeadshotTarget4", 5, 40,0)
		TNT1 A 0 A_SpawnItem ("LegTargetBase", 10)
		PSPO B 2 A_Wander
	    TNT1 A 0 A_PlaySound("humans/step",4)
        TNT1 A 0 A_SpawnItem ("HeadshotTarget10", 5, 40,0)
		TNT1 A 0 A_SpawnItem ("LegTargetBase", 10)
		TNT1 A 0 A_Jump(32, "Stand")
		Loop
		
	
	SearchForPlayer:
	Idle:
		TNT1 A 0 A_JumpIfHealthLower(1, "Death")
	    TNT1 A 0 A_ClearTarget
	    TNT1 A 0 A_TakeInventory("EnemyMemory", 30)
		TNT1 A 0 A_GiveInventory("SKZombieMan", 1)
        TNT1 A 0 A_SpawnItem ("HeadshotTarget10", 5, 40,0)
		TNT1 A 0 A_SpawnItem ("LegTargetBase", 10)
		PSPO A 10 A_Look
        TNT1 A 0 A_SpawnItem ("HeadshotTarget10", 5, 40,0)
		TNT1 A 0 A_SpawnItem ("LegTargetBase", 10)
		PSPO B 10 A_Look
		TNT1 A 0 A_SetAngle(angle - 40)
		TNT1 A 0 A_SpawnItem ("HeadshotTarget10", 5, 40,0)
		TNT1 A 0 A_SpawnItem ("LegTargetBase", 10)
		PSPO A 10 A_Look
        TNT1 A 0 A_SpawnItem ("HeadshotTarget10", 5, 40,0)
		TNT1 A 0 A_SpawnItem ("LegTargetBase", 10)
		PSPO C 10 A_Look
		TNT1 A 0 A_SetAngle(angle + 40)
		TNT1 A 0 A_SpawnItem ("HeadshotTarget10", 5, 40,0)
		TNT1 A 0 A_SpawnItem ("LegTargetBase", 10)
		PSPO A 10 A_Look
		TNT1 A 0 A_SpawnItem ("HeadshotTarget10", 5, 40,0)
		TNT1 A 0 A_SpawnItem ("LegTargetBase", 10)
		PSPO D 10 A_Look
		TNT1 A 0 A_SpawnItem ("HeadshotTarget10", 5, 40,0)
		TNT1 A 0 A_SpawnItem ("LegTargetBase", 10)
		TNT1 A 0 A_SetAngle(angle + 40)
		PSPO A 10 A_Look
		
		PSPO A 4 A_Look
		TNT1 A 0 A_SpawnItem ("HeadshotTarget4", 5, 40,0)
		TNT1 A 0 A_Wander
		TNT1 A 0 A_Recoil(-1)
		PSPO B 4 A_Look
		TNT1 A 0 A_SpawnItem ("HeadshotTarget4", 5, 40,0)
		TNT1 A 0 A_Wander
		TNT1 A 0 A_Recoil(-1)
		PSPO C 4 A_Look
		TNT1 A 0 A_SpawnItem ("HeadshotTarget4", 5, 40,0)
		TNT1 A 0 A_Wander
		TNT1 A 0 A_Recoil(-1)
		PSPO D 4 A_Look
		TNT1 A 0 A_SpawnItem ("HeadshotTarget4", 5, 40,0)
		TNT1 A 0 A_Wander
		TNT1 A 0 A_Recoil(-1)
		
		TNT1 A 0 A_Jump(128, "Idle")
		PSPO A 4 A_Look
		TNT1 A 0 A_SpawnItem ("HeadshotTarget4", 5, 40,0)
		TNT1 A 0 A_Wander
		TNT1 A 0 A_Recoil(-1)
		PSPO B 4 A_Look
		TNT1 A 0 A_SpawnItem ("HeadshotTarget4", 5, 40,0)
		TNT1 A 0 A_Wander
		TNT1 A 0 A_Recoil(-1)
		PSPO C 4 A_Look
		TNT1 A 0 A_SpawnItem ("HeadshotTarget4", 5, 40,0)
		TNT1 A 0 A_Wander
		TNT1 A 0 A_Recoil(-1)
		PSPO D 4 A_Look
		TNT1 A 0 A_SpawnItem ("HeadshotTarget4", 5, 40,0)
		TNT1 A 0 A_Wander
		TNT1 A 0 A_Recoil(-1)
		Loop
		
	FallBack:
	TNT1 A 0 A_CheckSight("Advance")
	TNT1 A 0 A_ChangeFLag("NODROPOFF", 1)
	TNT1 A 0 A_SpawnItem ("HeadshotTarget4", 5, 40,0)
	PSPO D 2 A_FaceTarget
	PSPO D 2 A_Recoil(2)
	TNT1 A 0 A_jump(64, "Missile")
	TNT1 A 0 A_SpawnItem ("HeadshotTarget4", 5, 40,0)
	PSPO C 2 A_FaceTarget
	PSPO C 2 A_Recoil(2)
	TNT1 A 0 A_SpawnItem ("HeadshotTarget4", 5, 40,0)
	PSPO B 2 A_FaceTarget
	PSPO B 2 A_Recoil(2)
	TNT1 A 0 A_SpawnItem ("HeadshotTarget4", 5, 40,0)
	PSPO A 2 A_FaceTarget
	PSPO A 2 A_Recoil(2)
	TNT1 A 0 A_SpawnItem ("HeadshotTarget4", 5, 40,0)
	PSPO D 2 A_FaceTarget
	PSPO D 2 A_Recoil(2)
	TNT1 A 0 A_jump(64, "Missile")
	TNT1 A 0 A_SpawnItem ("HeadshotTarget4", 5, 40,0)
	PSPO C 2 A_FaceTarget
	PSPO C 2 A_Recoil(2)
	TNT1 A 0 A_SpawnItem ("HeadshotTarget4", 5, 40,0)
	PSPO B 2 A_FaceTarget
	PSPO B 2 A_Recoil(2)
	TNT1 A 0 A_SpawnItem ("HeadshotTarget4", 5, 40,0)
	PSPO A 2 A_FaceTarget
	PSPO A 2 A_Recoil(2)
	GOto Missile
	
	See:
	TNT1 A 0 A_JumpIfHealthLower(1, "Death")
	TNT1 A 0 A_ChangeFLag("NODROPOFF", 0)
	TNT1 A 0 A_TakeInventory("SKZombieman", 1)
	TNT1 A 0 A_TakeInventory("EnemyMemory", 15)
	TNT1 A 0 A_CheckSight("SeeNeverSeen")
	Goto SeeContinue
	
	SeeContinue:
	TNT1 A 0 A_JumpIfHealthLower(1, "Death")
		TNT1 A 0 A_ChangeFlag("SOLID", 1)
		TNT1 A 0 A_ChangeFlag("SHOOTABLE", 1)
		TNT1 A 0 A_ChangeFlag("GHOST", 0)
		TNT1 A 0 A_ChangeFlag("INVULNERABLE", 0)
		TNT1 A 0 A_ChangeFlag("SOLID", 1)
		TNT1 A 0 A_ChangeFlag("SHOOTABLE", 1)
		TNT1 A 0 A_ChangeFlag("GHOST", 0)
		TNT1 A 0 A_ChangeFlag("INVULNERABLE", 0)
		TNT1 A 0 A_JumpIfCloser(200, "FallBack")
		Advance:
		TNT1 A 0 A_ChangeFLag("NODROPOFF", 0)
        TNT1 A 0 A_SpawnItemEx("FootStep", 0, 0, 10, 0, 0)
		TNT1 A 0 A_JumpIfInventory("EnemyMemory", 15, "SearchForPlayer")
		TNT1 A 0 A_GiveInventory("EnemyMemory", 1)
		TNT1 A 0 A_SpawnItem ("HeadshotTarget4", 5, 40,0)
		TNT1 A 0 A_SpawnItem ("LegTargetBase", 10)
		
		PSPO AA 2 A_Chase
		TNT1 A 0 A_Recoil(-1)
		TNT1 A 0 A_TakeInventory("SKZombieman", 1)
		
		TNT1 A 0 A_SpawnItem ("HeadshotTarget4", 5, 40,0)
		TNT1 A 0 A_SpawnItem ("LegTargetBase", 10)
		PSPO BB 2 A_Chase
		TNT1 A 0 A_PlaySound("humans/step",3)
		
		TNT1 A 0 A_SpawnItem ("HeadshotTarget4", 5, 40,0)
		TNT1 A 0 A_SpawnItem ("LegTargetBase", 10)
		PSPO CC 2 A_Chase
		
		TNT1 A 0 A_SpawnItem ("HeadshotTarget4", 5, 40,0)
		TNT1 A 0 A_SpawnItem ("LegTargetBase", 10)
		PSPO DD 2 A_Chase
		TNT1 A 0 A_PlaySound("humans/step",3)
		Loop
		
	SeeNeverSeen:
		TNT1 A 0 A_JumpIfCloser(200, "FallBack")
		Advance:
		TNT1 A 0 A_ChangeFLag("NODROPOFF", 0)
        TNT1 A 0 A_SpawnItemEx("FootStep", 0, 0, 10, 0, 0)
		TNT1 A 0 A_SpawnItem ("HeadshotTarget4", 5, 40,0)
		TNT1 A 0 A_SpawnItem ("LegTargetBase", 10)
		PSPO AA 2 A_Chase
		TNT1 A 0 A_Recoil(-1)
		TNT1 A 0 A_TakeInventory("SKZombieman", 1)
		TNT1 A 0 A_SpawnItem ("HeadshotTarget4", 5, 40,0)
		TNT1 A 0 A_SpawnItem ("LegTargetBase", 10)
		PSPO BB 2 A_Chase
		TNT1 A 0 A_PlaySound("humans/step",3)
		TNT1 A 0 A_SpawnItem ("HeadshotTarget4", 5, 40,0)
		TNT1 A 0 A_SpawnItem ("LegTargetBase", 10)
		PSPO CC 2 A_Chase
		TNT1 A 0 A_SpawnItem ("HeadshotTarget4", 5, 40,0)
		TNT1 A 0 A_SpawnItem ("LegTargetBase", 10)
		PSPO DD 2 A_Chase
		TNT1 A 0 A_PlaySound("humans/step",3)
		Loop
	//////////////////////////////////////////
		
	Missile:
		TNT1 A 0 A_TakeInventory("SKZombieman", 1)
        TNT1 A 0 A_Jump(122, "Attack2", "AimedAttack", "CrouchAttack")

        TNT1 A 0 A_GiveInventory("ZombieManAmmo", 1)
		
		TNT1 A 0 A_SpawnItem ("HeadshotTarget10", 4, 44,0)
		TNT1 A 0 A_SpawnItem ("LegTarget12", 10)
		PSPO E 8 A_FaceTarget
		TNT1 A 0 A_SpawnItem ("LegTarget12", 10)
		TNT1 A 0 A_SpawnItem ("HeadshotTarget10", 4, 44,0)
		TNT1 A 0 A_PlaySound("weapons/pistol")
		PSPO F 3 BRIGHT A_CustomMissile("MonsterHandgunTracer", 42, 0, random(-8, 8), 0)
        TNT1 A 0 A_CustomMissile("OrangeLensFlareAlt", 44, 10, 15, 0)
        TNT1 A 0 A_CustomMissile("SmokeSpawner", 34, 10, 15, 0)
		TNT1 A 0 A_SpawnItem ("Mp40CaseSpawn", 0, 30,0)
		PSPO E 4 A_FaceTarget
		TNT1 A 0 A_SpawnItem ("LegTarget12", 10)
		TNT1 A 0 A_SpawnItem ("HeadshotTarget10", 4, 40,0)
        TNT1 A 0 A_JumpIfInventory("ZombieManAmmo", 20, "Reload")
        Goto See

	Attack2:
        TNT1 A 0 A_GiveInventory("ZombieManAmmo", 1)
		TNT1 A 0 A_SpawnItem ("HeadshotTarget10", 4, 44,0)
		TNT1 A 0 A_SpawnItem ("LegTarget12", 10)
		PSPO E 8 A_FaceTarget
		TNT1 A 0 A_SpawnItem ("LegTarget12", 10)
		TNT1 A 0 A_SpawnItem ("HeadshotTarget10", 4, 44,0)
		TNT1 A 0 A_PlaySound("weapons/pistol")
		PSPO F 3 BRIGHT A_CustomMissile("MonsterHandgunTracer", 42, 0, random(-8, 8), 0)
        TNT1 A 0 A_CustomMissile("OrangeLensFlareAlt", 44, 10, 15, 0)
        TNT1 A 0 A_CustomMissile("SmokeSpawner", 34, 10, 15, 0)
		TNT1 A 0 A_SpawnItem ("Mp40CaseSpawn", 0, 30,0)
		PSPO E 5 A_FaceTarget
		TNT1 A 0 A_SpawnItem ("LegTarget12", 10)
		TNT1 A 0 A_SpawnItem ("HeadshotTarget10", 4, 40,0)
		TNT1 A 0 A_PlaySound("weapons/pistol")
		PSPO F 3 BRIGHT A_CustomMissile("MonsterHandgunTracer", 42, 0, random(-8, 8), 0)
        TNT1 A 0 A_CustomMissile("OrangeLensFlareAlt", 44, 10, 15, 0)
        TNT1 A 0 A_CustomMissile("SmokeSpawner", 34, 10, 15, 0)
		TNT1 A 0 A_SpawnItem ("Mp40CaseSpawn", 0, 30,0)
		PSPO E 5 A_FaceTarget
		TNT1 A 0 A_SpawnItem ("LegTarget12", 10)
		TNT1 A 0 A_SpawnItem ("HeadshotTarget10", 4, 44,0)
		TNT1 A 0 A_PlaySound("weapons/pistol")
		PSPO F 3 BRIGHT A_CustomMissile("MonsterHandgunTracer", 42, 0, random(-8, 8), 0)
        TNT1 A 0 A_CustomMissile("OrangeLensFlareAlt", 44, 10, 15, 0)
        TNT1 A 0 A_CustomMissile("SmokeSpawner", 34, 10, 15, 0)
		TNT1 A 0 A_SpawnItem ("Mp40CaseSpawn", 0, 30,0)
		PSPO E 4 A_FaceTarget
		TNT1 A 0 A_SpawnItem ("LegTarget12", 10)
		TNT1 A 0 A_SpawnItem ("HeadshotTarget10", 4, 40,0)
        TNT1 A 0 A_JumpIfInventory("ZombieManAmmo", 20, "Reload")
        Goto See

    AimedAttack:
		TNT1 A 0 A_GiveInventory("ZombieManAmmo", 5)
		TNT1 A 0 A_SpawnItem ("HeadshotTarget10", 6, 40,0)
		TNT1 A 0 A_SpawnItem ("LegTarget12", 10)
		PSPO E 3 A_FaceTarget
		TNT1 A 0 A_SpawnItem ("HeadshotTarget10", 6, 40,0)
		TNT1 A 0 A_SpawnItem ("LegTarget12", 10)
		PSPO J 3 A_FaceTarget
		TNT1 A 0 A_SpawnItem ("HeadshotTarget10", 6, 40,0)
		TNT1 A 0 A_SpawnItem ("LegTarget12", 10)
        TNT1 AA 0 A_CustomMissile("OrangeLensFlareAlt", 52, 10, 15, 0)
        TNT1 A 0 A_PlaySound("weapons/pistol")
		PSPO K 3 BRIGHT A_CustomMissile("MonsterHandgunTracer", 48, 0, random(-8, 8), 0)
		TNT1 A 0 A_SpawnItem ("Mp40CaseSpawn", 0, 30,0)
		TNT1 A 0 A_SpawnItem ("HeadshotTarget10", 6, 40,0)
		TNT1 A 0 A_SpawnItem ("LegTarget12", 10)
		PSPO J 3 A_FaceTarget
		TNT1 A 0 A_SpawnItem ("HeadshotTarget10", 6, 40,0)
		TNT1 A 0 A_SpawnItem ("LegTarget12", 10)
        TNT1 AA 0 A_CustomMissile("OrangeLensFlareAlt", 52, 10, 15, 0)
        TNT1 A 0 A_PlaySound("weapons/pistol")
		PSPO K 3 BRIGHT A_CustomMissile("MonsterHandgunTracer", 48, 0, random(-9, 9), 0)
		TNT1 A 0 A_SpawnItem ("Mp40CaseSpawn", 0, 30,0)
		TNT1 A 0 A_SpawnItem ("HeadshotTarget10", 6, 40,0)
		TNT1 A 0 A_SpawnItem ("LegTarget12", 10)
		PSPO J 3 A_FaceTarget
        TNT1 AA 0 A_CustomMissile("OrangeLensFlareAlt", 52, 10, 15, 0)
        TNT1 A 0 A_PlaySound("weapons/pistol")
		PSPO K 3 BRIGHT A_CustomMissile("MonsterHandgunTracer", 48, 0, random(-10, 10), 0)
		TNT1 A 0 A_SpawnItem ("Mp40CaseSpawn", 0, 30,0)
		TNT1 A 0 A_SpawnItem ("HeadshotTarget10", 6, 40,0)
		TNT1 A 0 A_SpawnItem ("LegTarget12", 10)
		PSPO J 4 A_FaceTarget
        TNT1 AA 0 A_CustomMissile("OrangeLensFlareAlt", 52, 10, 15, 0)
        TNT1 A 0 A_PlaySound("weapons/pistol")
		PSPO K 3 BRIGHT A_CustomMissile("MonsterHandgunTracer", 48, 0, random(-9, 9), 0)
		TNT1 A 0 A_SpawnItem ("Mp40CaseSpawn", 0, 30,0)
		TNT1 A 0 A_SpawnItem ("HeadshotTarget10", 6, 40,0)
		TNT1 A 0 A_SpawnItem ("LegTarget12", 10)
		PSPO J 4 A_FaceTarget
        TNT1 AA 0 A_CustomMissile("OrangeLensFlareAlt", 52, 10, 15, 0)
        TNT1 A 0 A_PlaySound("weapons/pistol")
		PSPO K 4 BRIGHT A_CustomMissile("MonsterHandgunTracer", 38, 0, random(-9, 9), 0)
		TNT1 A 0 A_SpawnItem ("Mp40CaseSpawn", 0, 30,0)
		TNT1 A 0 A_SpawnItem ("HeadshotTarget10", 6, 40,0)
		TNT1 A 0 A_SpawnItem ("LegTarget12", 10)
		PSPO E 3
        TNT1 A 0 A_JumpIfInventory("ZombieManAmmo", 20, "Reload")
        Goto See
		
		
	CrouchAttack:
		TNT1 A 0 A_GiveInventory("ZombieManAmmo", 5)
		TNT1 A 0 A_SpawnItem ("HeadshotTarget10", 6, 40,0)
		TNT1 A 0 A_SpawnItem ("LegTarget12", 10)
		PSPO EJ 3 A_FaceTarget
		TNT1 A 0 A_SpawnItem ("HeadshotTarget10", 6, 40,0)
		TNT1 A 0 A_SpawnItem ("LegTarget12", 10)
		PSPO H 3 A_FaceTarget
		TNT1 A 0 A_SpawnItem ("HeadshotTarget10", 6, 40,0)
		TNT1 A 0 A_SpawnItem ("LegTarget12", 10)
        TNT1 AA 0 A_CustomMissile("OrangeLensFlareAlt", 40, 10, 15, 0)
        TNT1 A 0 A_PlaySound("weapons/pistol")
		PSPO I 3 BRIGHT A_CustomMissile("MonsterHandgunTracer", 48, 0, random(-8, 8), 0)
		TNT1 A 0 A_SpawnItem ("Mp40CaseSpawn", 0, 30,0)
		TNT1 A 0 A_SpawnItem ("HeadshotTarget10", 6, 40,0)
		TNT1 A 0 A_SpawnItem ("LegTarget12", 10)
		PSPO H 3 A_FaceTarget
		TNT1 A 0 A_SpawnItem ("HeadshotTarget10", 6, 40,0)
		TNT1 A 0 A_SpawnItem ("LegTarget12", 10)
        TNT1 AA 0 A_CustomMissile("OrangeLensFlareAlt", 40, 10, 15, 0)
        TNT1 A 0 A_PlaySound("weapons/pistol")
		PSPO I 3 BRIGHT A_CustomMissile("MonsterHandgunTracer", 48, 0, random(-9, 9), 0)
		TNT1 A 0 A_SpawnItem ("Mp40CaseSpawn", 0, 30,0)
		TNT1 A 0 A_SpawnItem ("HeadshotTarget10", 6, 40,0)
		TNT1 A 0 A_SpawnItem ("LegTarget12", 10)
		PSPO H 3 A_FaceTarget
        TNT1 AA 0 A_CustomMissile("OrangeLensFlareAlt", 40, 10, 15, 0)
        TNT1 A 0 A_PlaySound("weapons/pistol")
		PSPO I 3 BRIGHT A_CustomMissile("MonsterHandgunTracer", 48, 0, random(-10, 10), 0)
		TNT1 A 0 A_SpawnItem ("Mp40CaseSpawn", 0, 30,0)
		TNT1 A 0 A_SpawnItem ("HeadshotTarget10", 6, 40,0)
		TNT1 A 0 A_SpawnItem ("LegTarget12", 10)
		PSPO H 3 A_FaceTarget
        TNT1 AA 0 A_CustomMissile("OrangeLensFlareAlt", 40, 10, 15, 0)
        TNT1 A 0 A_PlaySound("weapons/pistol")
		PSPO I 3 BRIGHT A_CustomMissile("MonsterHandgunTracer", 48, 0, random(-9, 9), 0)
		TNT1 A 0 A_SpawnItem ("Mp40CaseSpawn", 0, 30,0)
		TNT1 A 0 A_SpawnItem ("HeadshotTarget10", 6, 40,0)
		TNT1 A 0 A_SpawnItem ("LegTarget12", 10)
		PSPO H 3 A_FaceTarget
        TNT1 AA 0 A_CustomMissile("OrangeLensFlareAlt", 40, 10, 15, 0)
        TNT1 A 0 A_PlaySound("weapons/pistol")
		PSPO I 3 BRIGHT A_CustomMissile("MonsterHandgunTracer", 38, 0, random(-9, 9), 0)
		TNT1 A 0 A_SpawnItem ("Mp40CaseSpawn", 0, 30,0)
		TNT1 A 0 A_SpawnItem ("HeadshotTarget10", 6, 40,0)
		TNT1 A 0 A_SpawnItem ("LegTarget12", 10)
		PSPO HJE 3
        TNT1 A 0 A_JumpIfInventory("ZombieManAmmo", 20, "Reload")
        Goto See
		
	Reload:
		TNT1 A 0 A_TakeInventory("ZombieManAmmo", 20)
		TNT1 A 0 A_SpawnItem ("HeadshotTarget4", 5, 44,0)
		TNT1 A 0 A_SpawnItem ("LegTarget12", 10)
        PSPO E 3
		PSPO E 1 A_CustomMissile("EmptyClipMP40", 38, 0, random(-11, 11), 0)
        TNT1 A 0 A_PlaySound("PSRLOUT", 1)
		TNT1 A 0 A_SpawnItem ("HeadshotTarget10", 5, 44,0)
		TNT1 A 0 A_SpawnItem ("LegTarget12", 10)
        IDP2 A 6
		TNT1 A 0 A_SpawnItem ("HeadshotTarget10", 5, 44,0)
		TNT1 A 0 A_SpawnItem ("LegTarget12", 10)
        IDP2 A 6
		TNT1 A 0 A_SpawnItem ("HeadshotTarget10", 5, 44,0)
		TNT1 A 0 A_SpawnItem ("LegTarget12", 10)
        IDP2 B 6
		TNT1 A 0 A_SpawnItem ("HeadshotTarget10", 5, 44,0)
		TNT1 A 0 A_SpawnItem ("LegTarget12", 10)
        IDP2 C 6
        TNT1 A 0 A_PlaySound("PSRLFIN", 3)
		TNT1 A 0 A_SpawnItem ("HeadshotTarget10", 5, 44,0)
		TNT1 A 0 A_SpawnItem ("LegTarget12", 10)
        IDP2 A 6
		TNT1 A 0 A_SpawnItem ("HeadshotTarget10", 5, 44,0)
		TNT1 A 0 A_SpawnItem ("LegTarget12", 10)
        PSPO A 6
        Goto SeeContinue

   Pain.Avoid:
        PSPO AABBCC 3 A_FastChase
        Goto Missile

   Pain.ExtremePunches:
	Pain.ExplosiveImpact:
	Pain.Explosive:
	     TNT1 A 0
	     TNT1 A 0 A_Pain
		 TNT1 A 0 A_JumpIfInventory ("IsDown", 1, "Pain")
		 TNT1 A 0 A_TakeInventory("SKZombieman", 1)
         TNT1 A 0 A_GiveInventory("IsDown", 1)
         TNT1 A 0 ThrustThingZ(0,40,0,1)
         ID31 AB 12
		 Goto FallingAfterImpact

	Pain.BlackHole:
		TNT1 A 0
         ID31 A 1 A_Pain
		 TNT1 A 0 A_JumpIfInventory ("IsDown", 1, "Pain")
		 TNT1 A 0 A_TakeInventory("SKZombieman", 1)
         TNT1 A 0 A_GiveInventory("IsDown", 1)
         TNT1 A 0 ThrustThingZ(0,9,0,1)
		 ID31 A 1 A_facetarget
         ID31 A 6 ThrustThing(angle*256/360+128, 10, 0, 0)
         ID31 A 8
		 Goto FallingAfterImpact
		
	Pain.Kick:
	Pain.extremepunches:
         TNT1 A 0
         ID31 A 1 A_Pain
		 TNT1 A 0 A_JumpIfInventory ("IsDown", 1, "Pain")
		 TNT1 A 0 A_TakeInventory("SKZombieman", 1)
         TNT1 A 0 A_GiveInventory("IsDown", 1)
         TNT1 A 0 ThrustThingZ(0,30,0,1)
		 ID31 A 1 A_facetarget
         ID31 A 6 ThrustThing(angle*256/360+128, 15, 0, 0)
		 Goto FallingAfterImpact

	FallingAfterImpact:
		ID31 B 1 A_GiveInventory ("FallingHeight", 1)
		ID31 B 1 A_CheckFloor ("GetUp")
		TNT1 A 0 A_PlaySound("BODYF",6)
		TNT1 A 0 A_JumpIf (momz == 0, "GetUp")
		Loop

	GetUp:
		TNT1 A 0
		TNT1 A 0 A_SpawnItem("LargeMassWaterImpact")
		TNT1 A 0 A_JumpIfInventory ("FallingHeight", 5, "FallingDie")
		TNT1 A 0 A_TakeInventory("FallingHeight", 100)
		2D11 RRRRRRR 5 A_JumpIf(momz < 0, "FallingAfterImpact")
        TNT1 A 0 A_TakeInventory("IsDown", 1)
		2D11 Q 10
        Goto See
	
	FallingDie:
		TNT1 A 0
		TNT1 A 0 A_ChangeFlag("COUNTKILL", 0)
		TNT1 A 0 A_ChangeFlag("SHOOTABLE", 0)
		TNT1 A 0 A_SpawnItem("SplatteredSmall")
		TNT1 A 0 A_JumpIfInventory ("FallingHeight", 15, "Death.Stomp")
		TNT1 A 0 A_JumpIfInventory ("FallingHeight", 10, "FallingSuperDeath")
		TNT1 A 0 A_JumpIfInventory ("FallingHeight", 5, "FallingDeath")
	FallingDeath:
		TNT1 A 0
		TNT1 A 0 A_Scream
		TNT1 A 0 //A_NoBLocking
		TNT1 A 0 A_SpawnItem ("Ploft")
		TNT1 AAAA 0 A_CustomMissile ("XDeath1", 32, 0, random (0, 360), 2, random (50, 130))
		ID31 EF 2
		TNT1 A 0 A_PlaySound("BODYF",6)
		TNT1 A 0 A_SpawnItem ("GrowingBloodPool")
		TNT1 A 0 A_SpawnItem ("DeadZombieman1")
		Stop

	FallingSuperDeath:
		TNT1 A 0
		TNT1 A 0 A_XScream
		TNT1 A 0 //A_NoBLocking
		TNT1 A 0 A_SpawnItem ("GrowingBloodPool")
		TNT1 AAA 0 A_SpawnItem ("Ploft")
		Goto Death.ExplosiveImpact+1

	Pain:
	    TNT1 A 0 A_TakeInventory("SKZombieman", 1)
        TNT1 A 0 A_JumpIfInventory ("IsDown", 1, 6)
		TNT1 A 0 A_SpawnItem ("HeadshotTarget4", 0, 40,0)
		TNT1 A 0 A_CustomMissile ("brutal_FlyingBlood", 35, 0, random (0, 360), 2, random (0, 160))
	    PSPO G 3
		TNT1 A 0 A_SpawnItem ("HeadshotTarget4", 0, 40,0)
		PSPO G 3 A_Pain
	    Goto See
        TNT1 AAAA 0
        TNT1 A 0 A_Pain
        2D11 RRRRQ 10
        TNT1 A 0 A_TakeInventory("IsDown", 1)
        Goto See

       Pain.Melee:
		TNT1 A 0
		TNT1 A 0 A_JumpIfInventory ("SKZombieMan", 1, "StealthKill")
        TNT1 A 0 A_JumpIfInventory ("IsDown", 1, 6)
		TNT1 A 0 A_SpawnItem ("HeadshotTarget4", 0, 40,0)
		TNT1 A 0 A_SpawnItem ("LegTargetBase", 10)
	    PSPO G 3
		TNT1 A 0 A_SpawnItem ("HeadshotTarget4", 0, 40,0)
		TNT1 A 0 A_SpawnItem ("LegTargetBase", 10)
		PSPO G 3 A_Pain
		Goto See
        TNT1 AAAA 0
        TNT1 A 0 A_Pain
        2D11 RRRRQ 10
		TNT1 A 0 A_TakeInventory("SKZombieman", 1)
        TNT1 A 0 A_TakeInventory("IsDown", 1)
        Goto See
		
	Death:
        TNT1 A 0 A_JumpIfInventory ("IsDown", 1, "Death.Down")
        TNT1 A 0
		TNT1 AA 0 A_CustomMissile ("Brutal_FlyingBlood", 7, 0, random (0, 360), 2, random (0, 160))
        TNT1 A 0 A_Jump(32, "Death.Arm")
	Death.MinorLeg:
		TNT1 A 0 A_Jump(129, "DeathOther", "DeathOther2")
		TNT1 A 0 A_Jump(128, "DeathMirror")
		TNT1 A 0 A_NoBlocking
		TNT1 A 0 A_Scream
		POSS J 5 A_SpawnItem("Zombieman_DeathMinorLeg")
		Stop
}
}