Class PB_PistolZombieman2: PB_Zombieman //Replaces ZombieMan
{
	Default
	{
		//$Title Helmet Pistol Zombieman
		//$Category Project Brutality - Monsters/Former Humans/Zombiemen
		//$Sprite 9OS2B1
		damagefactor "Head", 0.60;
		DropItem "PB_Pistol";
		PB_Monster.MonDMGMult 1.25, 1.25, 0.8, 1.0, 0.95, 0.7;

		PB_Monster.TailPitch 0.8;
	}
	States
	{
		Death.KillMe:
		Death.Taunt:
		Death.Avoid:
			TNT1 A 0;
			TNT1 A 0 {
				bTHRUACTORS = true;
				bCOUNTKILL = false;
			}
			TNT1 A 0 A_SpawnItemEx ("PB_PistolZombieman2",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION |SXF_TRANSFERSPECIAL| SXF_TRANSFERAMBUSHFLAG ,0);
			Stop;
		
		Spawn:
			9OS2 A 1;
			TNT1 A 0 {
				A_TakeInventory("EnemyPistolAmmo", 15);
				A_GiveInventory("EnemyPistolAmmo", random(1,10));
				A_GiveInventory("SKHelmetZombie1", 1);
				A_GiveInventory("TypeZombieMan", 1);
			}
		Stand:
			TNT1 A 0;
			TNT1 A 0 {
				bNoPain = false;
				A_SetRoll(0);
			}
			9OS2 AA 10 A_Look();
			Loop;
		See:
			TNT1 A 0;
			TNT1 A 0 {
				bNoPain = false;
				A_SetRoll(0);
			}
			TNT1 A 0 {
				A_TakeInventory("SKHelmetZombie1", 1);
				EnemyLastSighted = Level.MapTime;
			}
		SeeContinue:
			9OS2 AA 1 A_SmartChase("Missile", "Melee", 0);
			9OS2 AA 1 A_SmartChase(null, null, CHF_DONTTURN);
			9OS2 BB 1 A_SmartChase("Missile", "Melee", 0);
			9OS2 BB 1 A_SmartChase(null, null, CHF_DONTTURN);
			TNT1 A 0 A_StartSound("humans/step");
			9OS2 CC 1 A_SmartChase("Missile", "Melee", 0);
			9OS2 CC 1 A_SmartChase(null, null, CHF_DONTTURN);
			9OS2 DD 1 A_SmartChase("Missile", "Melee", 0);
			9OS2 DD 1 A_SmartChase(null, null, CHF_DONTTURN);
			TNT1 A 0 A_StartSound("humans/step");
			TNT1 A 0 A_JumpIf(CountInv("Wandering") == 71 && !OnPatrol,"LookAround");
			Loop;
		LookAround:
			TNT1 A 0 A_ClearTarget();
			TNT1 A 0 A_TakeInventory("Wandering", 71);
			TNT1 A 0 A_Jump(200, 2);
			TNT1 A 0 A_StartSound("monsters/zombie/searching", CHAN_AUTO);
			9OS2 AAAA 10 A_Look();
			Goto See;
		FallBack:
			9OS2 D 4 {
				A_FaceTarget();
				A_Recoil(2);
				A_StartSound("humans/step",3);
				return A_Jump(64,"Missile");
			}
			9OS2 C 4 {
				A_FaceTarget();
				A_Recoil(2);
				return A_Jump(64,"Missile");
			}
			9OS2 B 4 {
				A_FaceTarget();
				A_Recoil(2);
				A_StartSound("humans/step",3);
				return A_Jump(64,"Missile");
			}
			9OS2 A 2 {
				A_FaceTarget();
				A_Recoil(2);
				return A_Jump(64,"Missile");
			}
			9OS2 D 4 {
				A_FaceTarget();
				A_Recoil(2);
				A_StartSound("humans/step",3);
				return A_Jump(64,"Missile");
			}
			9OS2 C 4 {
				A_FaceTarget();
				A_Recoil(2);
				return A_Jump(64,"Missile");
			}
			9OS2 B 4 {
				A_FaceTarget();
				A_Recoil(2);
				A_StartSound("humans/step",3);
				return A_Jump(64,"Missile");
			}
			9OS2 A 4 {
				A_FaceTarget();
				A_Recoil(2);
			}
			Goto Missile;
	
		////////////////
		//Attack Logic// 
		////////////////
		Grenade:
			TNT1 A 0 A_JumpIfCloser(500, 1);
			Goto Attack1;
			TNT1 A 0 A_JumpIfCloser(90, "Attack1");
		ThrowGrenade:
			TNT1 A 0 A_StartSound("monsters/zombie/special",CHAN_AUTO);
			P25G A 6 {
				A_FaceTarget(90,45);
				A_StartSound("OPNGRN", 1);
			}
			P25G BC 6;
			P25G D 6 {
				A_FaceTarget(90,45);
				A_DropAdjust("EnemyThrownGrenade","EnemyThrownGrenade",0,18,28);
				A_GiveInventory("ZombieManGrenadeCount", 1);
				A_StartSound("THRGRN", 1);
			}
			P25G E 6;
			Goto See;
		Melee:
			TNT1 A 0 A_Jump(224, 2);
			TNT1 A 0 A_CombatDialogueHandler();
			ZBS4 A 6 A_FaceTarget();
			TNT1 A 0 {
				A_StartSound("skeleton/swing");
				A_CustomMeleeAttack(10, "monsters/nazi/bash", "", "Normal");
			}
			//TNT1 A 0 A_SpawnProjectile("ZombieBashAttack",10,0,0,0);
			ZBS4 B 6 A_FaceTarget();
			ZBS4 A 6;
			Goto See;
		DialogueCheck:
			TNT1 A 0 A_Jump(240, "MissileContinue");
			TNT1 A 0 A_CombatDialogueHandler();
			Goto MissileContinue;
		Missile:
			TNT1 A 0 A_JumpIfInTargetInventory("IsPlayer",1, "DialogueCheck");
			
			Goto AttackHandler;
		MissileContinue:
			9OS2 E 6 {
				A_Stop();
				A_FaceTarget();
				return A_CheckLOFRanged("AttackHandler", "SideHop");
				}
			Goto See;
		AttackHandler:
			TNT1 A 0 {
				int chance = (random(1,256));
				
				if((chance > 232) && (CountInv("ZombieManGrenadeCount") < 2)) {return A_Jump(256, "Grenade");}
				return A_Jump(256, "Attack", "Attack1", "Attack1", "Attack2", "Attack2", "Attack3");
			}
		//Standard, 1 round attack
		Attack:
			9OS2 E 9 A_FaceTarget();
			9OS2 F 3 BRIGHT {
				A_SpawnProjectile("PB_PistolBullet", 42, 1, random(-10, 10), 1, random(-3, 3));
				A_SpawnProjectile("MarineMuzzle1", 47, 1) ;
				A_SpawnProjectile("OrangeLensFlareAlt", 47, 5, 0, 0);
				A_StartSound("weapons/pistol");
				PB_DynamicTailMonster("pistol", "pistol");
				A_SpawnProjectile("EmptyBrassMP40", 25, 0, random(-80,-100), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH, random(45,80));
			}
			9OS2 E 6 {
				A_FaceTarget();
				A_GiveInventory("EnemyPistolAmmo", 1);
				return A_JumpIfInventory("EnemyPistolAmmo", 15, "Reload");
			}
			Goto See;
		//Standard, 2 round attack
		Attack1:
			9OS2 E 8 A_FaceTarget();
			9OS2 F 3 BRIGHT {
				A_SpawnProjectile("PB_PistolBullet", 42, 1, random(-10, 10), 1, random(-3, 3));
				A_SpawnProjectile("MarineMuzzle1", 47, 1) ;
				A_SpawnProjectile("OrangeLensFlareAlt", 47, 5, 0, 0);
				A_StartSound("weapons/pistol");
				PB_DynamicTailMonster("pistol", "pistol");
				A_SpawnProjectile("EmptyBrassMP40", 25, 0, random(-80,-100), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH, random(45,80));
			}
			9OS2 E 8 A_FaceTarget();
			9OS2 F 3 BRIGHT {
				A_SpawnProjectile("PB_PistolBullet", 42, 1, random(-10, 10), 1, random(-3, 3));
				A_SpawnProjectile("MarineMuzzle1", 47, 1) ;
				A_SpawnProjectile("OrangeLensFlareAlt", 47, 5, 0, 0);
				A_StartSound("weapons/pistol");
				PB_DynamicTailMonster("pistol", "pistol");
				A_SpawnProjectile("EmptyBrassMP40", 25, 0, random(-80,-100), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH, random(45,80));
			}
			9OS2 E 6 {
				A_FaceTarget();
				A_GiveInventory("EnemyPistolAmmo", 2);
				return A_JumpIfInventory("EnemyPistolAmmo", 15, "Reload");
			}
			Goto See;
		//Aimed, 3 round attack
		Attack2:
			9OS2 L 6 A_FaceTarget();
			9OS2 M 3 BRIGHT {
				A_SpawnProjectile("PB_PistolBullet", 42, 0, random(-8, 8), 1, random(-3, 3));
				A_SpawnProjectile("OrangeLensFlareAlt", 47, 5, 15, 0);
				A_SpawnProjectile("MarineMuzzle1", 48, 1) ;
				A_StartSound("weapons/pistol");
				PB_DynamicTailMonster("pistol", "pistol");
				A_SpawnProjectile("EmptyBrassMP40", 25, 0, random(-80,-100), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH, random(45,80));
			}
			9OS2 L 6 A_FaceTarget();
			9OS2 M 3 BRIGHT {
				A_SpawnProjectile("PB_PistolBullet", 42, 0, random(-8, 8), 1, random(-3, 3));
				A_SpawnProjectile("OrangeLensFlareAlt", 47, 5, 15, 0);
				A_SpawnProjectile("MarineMuzzle1", 48, 1) ;
				A_StartSound("weapons/pistol");
				PB_DynamicTailMonster("pistol", "pistol");
				A_SpawnProjectile("EmptyBrassMP40", 25, 0, random(-80,-100), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH, random(45,80));
			}
			9OS2 L 6 A_FaceTarget();
			9OS2 M 3 BRIGHT {
				A_SpawnProjectile("PB_PistolBullet", 42, 0, random(-8, 8), 1, random(-3, 3));
				A_SpawnProjectile("OrangeLensFlareAlt", 47, 5, 15, 0);
				A_SpawnProjectile("MarineMuzzle1", 48, 1) ;
				A_StartSound("weapons/pistol");
				PB_DynamicTailMonster("pistol", "pistol");
				A_SpawnProjectile("EmptyBrassMP40", 25, 0, random(-80,-100), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH, random(45,80));
			}
			9OS2 L 6 {
				A_FaceTarget();
				A_GiveInventory("EnemyPistolAmmo", 3);
				return A_JumpIfInventory("EnemyPistolAmmo", 20, "Reload");
			}
			Goto See;
		Attack3:
			9OS2 EL 4 A_FaceTarget();
			Crouching:
			9OS2 K 6 A_FaceTarget();
			9OS2 J 2 BRIGHT {
				A_SpawnProjectile("PB_PistolBullet", 32, 0, random(-4, 4), 1, random(-3, 3));
				A_SpawnProjectile("OrangeLensFlareAlt", 34, 16, 15, 0);
				A_SpawnProjectile("MarineMuzzle1", 34, 4) ;
				A_SpawnProjectile("EmptyBrassMP40", 31, 0, random(-80,-100), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH, random(45,80));
				A_StartSound("weapons/pistol");
				PB_DynamicTailMonster("pistol", "pistol");
			}
			9OS2 K 6 A_FaceTarget();
			9OS2 J 3 BRIGHT {
				A_SpawnProjectile("PB_PistolBullet", 32, 0, random(-4, 4), 1, random(-3, 3));
				A_SpawnProjectile("OrangeLensFlareAlt", 34, 16, 15, 0);
				A_SpawnProjectile("MarineMuzzle1", 34, 3) ;
				A_SpawnProjectile("EmptyBrassMP40", 31, 0, random(-80,-100), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH, random(45,80));
				A_StartSound("weapons/pistol");
				PB_DynamicTailMonster("pistol", "pistol");
			}
			9OS2 K 6 A_FaceTarget();
			9OS2 J 3 BRIGHT {
				A_SpawnProjectile("PB_PistolBullet", 32, 0, random(-4, 4), 1, random(-3, 3));
				A_SpawnProjectile("OrangeLensFlareAlt", 34, 16, 15, 0);
				A_SpawnProjectile("MarineMuzzle1", 34, 3) ;
				A_SpawnProjectile("EmptyBrassMP40", 31, 0, random(-80,-100), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH, random(45,80));
				A_StartSound("weapons/pistol");
				PB_DynamicTailMonster("pistol", "pistol");
			}
			9OS2 K 4  {
				A_FaceTarget();
				A_GiveInventory("EnemyPistolAmmo", 3);
				return A_JumpIfInventory("EnemyPistolAmmo", 15, "Reload");
				return A_jump(24, "Attack3");
			}
			DoneCrouching:
			9OS2 LE 4 A_FaceTarget();
			Goto See;
		Reload:
			TNT1 A 0 A_StartSound("monsters/zombie/reload",CHAN_AUTO);
			9OS2 E 4 {
				A_TakeInventory("EnemyPistolAmmo", 15);
				//A_StartSound("PSRLOUT");
				}
			IDP3 AC 5;
			IDP3 B 5 A_StartSound("PSRLOUT");
			IDP3 A 5 A_SpawnProjectile("EmptyClipMP40", 38, 0, random(-11, 11), 0);
			IDP3 B 5;
			IDP3 C 10 A_StartSound("PSRLIN");
			IDP3 A 10;
			9OS2 A 5;
			IDP3 C 5 A_StartSound("PSRLFIN");
			9OS2 EA 5;
			9OS2 A 5;
			Goto See;
		
		////////////////
		//Pain Logic// 
		////////////////
		Pain.Melee:
		Pain:
			TNT1 A 0 A_JumpIfInventory ("IsDown", 1, "Downed");
			9OS2 G 6 A_Pain();
			TNT1 A 0 A_JumpIfInTargetInventory("IsPlayer",1, "See");
			
			TNT1 A 0 A_Jump(180, "See");
			TNT1 A 0 A_StartSound("monsters/zombie/infight",CHAN_AUTO);
			Goto See;
			
		Pain.Head:
			TNT1 A 0 A_JumpIfInventory ("IsDown", 1, "Downed");
			TNT1 A 0 A_SpawnProjectile ("NashGoreBloodSpurt", 52, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH, random (0, 160));
			P5SH G 6 {
				A_Pain();
				A_Stop();
			}
			TNT1 AA 0 A_SpawnProjectile ("PB_Teeth", 50, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH, random (0, 160));
			P5SH HIJJJIH 4;
			TNT1 A 0 A_JumpIfInTargetInventory("IsPlayer",1, "See");
			TNT1 A 0 A_Jump(180, "See");
			TNT1 A 0 A_StartSound("monsters/zombie/infight",CHAN_AUTO);
			Goto See;
		
	
		
		Downed:
			ID31 F 6 A_Pain();
			Goto GetUp;
		Pain.Kick:
		Pain.ExtremePunches:
			TNT1 A 0 A_JumpIfInventory ("IsDown", 1, "Pain");
			9OS4 U 1 {
					bNODROPOFF = false;
					bFORCEXYBILLBOARD = true;
					A_TakeInventory("SKHelmetZombie1", 1);
					A_GiveInventory("IsDown", 1);
					A_Pain();
					A_facetarget();
					ThrustThingZ(0,30,0,1);
			}
			9OS4 U 2 A_facetarget();
			9OS4 U 1 A_Recoil(15);
			9OS4 UVWXY 3;
			Goto FallingAfterImpact;
		Pain.ExplosiveImpact:
		Pain.Explosive:
			TNT1 A 0 A_JumpIfInventory ("IsDown", 1, "Pain");
			9OS4 U 1 {
					bNODROPOFF = false;
					bFORCEXYBILLBOARD = true;
					A_TakeInventory("SKHelmetZombie1", 1);
					A_GiveInventory("IsDown", 1);
					A_Pain();
					ThrustThingZ(0,30,0,1);
			}
			9OS4 U 2 A_facetarget();
			9OS4 U 1 A_Recoil(5);
			9OS4 UVWXY 3;
			Goto FallingAfterImpact;
		FallingAfterImpact:
			9OS4 Y 1 {
				A_GiveInventory ("FallingHeight", 1);
				A_CheckFloor ("GetUp");
			}
			NULL A 0 A_JumpIf (Vel.Z == 0, "GetUp");
			Loop;
		
		GetUp:
			TNT1 A 0 A_JumpIfInventory ("FallingHeight", 16, "FallingDie");
			TNT1 A 0 {
				A_TakeInventory("FallingHeight", 100);
				A_Stop();
				bSOLID = false;
				A_StartSound("BODYF",6);
			}
			1D11 RRRRRRRRRR 5 A_JumpIf(Vel.Z < 0, "FallingAfterImpact");
			1D11 Q 10 {
				A_TakeInventory("IsDown", 1);
				bFORCEXYBILLBOARD = false;
				bSOLID = true;
			}
			TNT1 A 0 A_JumpIfInTargetInventory("IsPlayer",1, "See");
			
			TNT1 A 0 A_Jump(180, "See");
			TNT1 A 0 A_StartSound("monsters/zombie/infight",CHAN_AUTO);
			Goto See;
		 
		FallingDie:
			TNT1 A 0 {
				bCOUNTKILL = false;
				bNoPain = true;
				A_SpawnItem("SplatteredSmall");
			}
			TNT1 A 0 A_JumpIfInventory ("FallingHeight", 32, "Death.Stomp");
			TNT1 A 0 A_JumpIfInventory ("FallingHeight", 25, "FallingSuperDeath");
			TNT1 A 0 A_JumpIfInventory ("FallingHeight", 16, "FallingDeath");
		FallingDeath:
			TNT1 A 0 {
				A_Scream();
				A_SpawnProjectile ("PB_XDeath1", 32, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH, random (50, 130));
				A_SpawnProjectile ("PB_XDeath1", 32, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH, random (50, 130));
				A_SpawnProjectile ("PB_XDeath1", 32, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH, random (50, 130));
				A_SpawnProjectile ("PB_XDeath1", 32, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH, random (50, 130));
				}
			9OS4 Y 2;
			9OS4 Y 2 {
				A_StartSound("BODYF",6);
				A_SpawnItem ("GrowingBloodPool");
				A_SpawnItem ("DeadZombieman1");
			}
			Stop;
		FallingSuperDeath:
			TNT1 A 0 A_XScream();
			Goto Death.ExplosiveImpact+1;
				
		Pain.Taunt:
			TNT1 A 0 A_JumpIfInventory("Enraged", 1, "Missile");
			9OS2 B 1 {
				A_Pain();
				bMISSILEMORE = true;
				bMISSILEEVENMORE = true;
				A_StartSound("grunt/sight");
				A_FaceTarget();
				A_GiveInventory("Enraged", 1);
				}
			9OS2 B 9;
			Goto Missile;
		Pain.Siphon:
			9OS2 G 1 {
				A_SpawnItemEx("RedLightning_Small", random (-12, 12), random (-12, 12), random (16, 52), 0, 0);
				A_SpawnItemEx("RedLightning_Small", random (-12, 12), random (-12, 12), random (16, 52), 0, 0);
				A_SpawnItemEx("RedLightning_Small", random (-12, 12), random (-12, 12), random (16, 52), 0, 0);
				A_FaceTarget();
				A_GiveToTarget("HealthBonus",4);
			}
			9OS2 G 5 {
				A_FaceTarget();
				A_Pain();
				}
			Goto See;
		Possession:
			9OS2 G 3 {
				A_SetRoll(0);
				A_SetInvulnerable();
				A_Pain();
				}
			"####" "#" 35 ACS_NamedExecuteAlways("Pos - Flicker effect");
			TNT1 A 0 A_UnSetInvulnerable();
			Goto See;
	
		Pain.Stun:
			9OS2 G 1 A_Pain();
			9OS2 GGGGGGGGGG 3 A_SpawnItemEx ("StunElectrocute", random (-12, 12), random (-12, 12),  random (16, 52), 0, 0);
			9OS2 G 1 A_Pain();
			9OS2 GGGGGGGGGG 3 A_SpawnItemEx ("StunElectrocute", random (-12, 12), random (-12, 12),  random (16, 52), 0, 0);
			9OS2 G 1 A_Pain();
			9OS2 GGGGGGGGGG 3 A_SpawnItemEx ("StunElectrocute", random (-12, 12), random (-12, 12),  random (16, 52), 0, 0);
			9OS2 G 1 A_Pain();
			9OS2 GGGGGGGGGG 3 A_SpawnItemEx ("StunElectrocute", random (-12, 12), random (-12, 12),  random (16, 52), 0, 0);
			9OS2 G 1 A_Pain();
			9OS2 GGGGGGGGGG 3 A_SpawnItemEx ("StunElectrocute", random (-12, 12), random (-12, 12),  random (16, 52), 0, 0);
			9OS2 G 1 A_Pain();
			Goto See;
		Death:
			TNT1 A 0;
			TNT1 A 0 A_SetRoll(0);
			TNT1 A 0 A_JumpIfInventory ("IsDown", 1, "Death.Down");
			TNT1 A 0 A_DeathWepCheck("ShotgunSelected", 400, "Death.Shotgun");
			TNT1 A 0 A_DeathWepCheck("ASGSelected", 400, "Death.Shotgun");
			TNT1 A 0 A_DeathWepCheck("SSGSelected", 200, "Death.SSG");
			TNT1 A 0 A_DeathWepCheck("MinigunSelected", 1000, "Death.Minigun");
			TNT1 A 0 A_DeathWepCheck("NewChaingunSelected", 750, "Death.Nailgun");
			//TNT1 A 0 A_Jump(32, "Death.Arm");
		Death.MinorLeg:
			TNT1 A 0;
			TNT1 A 0 A_SetRoll(0);
			9OS2 H 6 A_NoBlocking();
			9OS2 I 5 A_Scream();
			9OS2 Z 5;
			POSS K 5;
			POSS L 1;
			TNT1 A 0 A_SpawnItem ("GrowingBloodPool");
			TNT1 A 0 A_StartSound("BODYF",6);
			TNT1 A 0 A_SpawnItem ("DeadZombieman1");
			Stop;
		
		Death.ArmHitbox:
		Death.Arm:
			TNT1 A 0;
			TNT1 A 0 A_SetRoll(0);
			TNT1 A 0 {
				A_SpawnProjectile ("PB_XDeathArm1", 35, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH, random (0, 160));
				A_SpawnProjectile ("PB_SmallGib", 35, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH, random (0, 160));
				A_SpawnProjectile ("PB_SmallGib", 35, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH, random (0, 160));
				A_SpawnProjectile ("PB_MuchBlood2", 35, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH, random (0, 160));
				A_NoBlocking();
				A_Scream();
				}
			HZD1 A 10;
			TNT1 A 0 A_SpawnItemEx ("DyingHelmetZombiemanNoArm",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
			Stop;
		
		Death.Saw:
			TNT1 A 0;
			TNT1 A 0 A_SetRoll(0);
			TNT1 A 0 A_Jump(96, "Saw2");
			TNT1 A 0 A_Jump(32, "Death.arm");
			Goto Death.Tear;
		Saw2:
			TNT1 A 0 A_NoBlocking();
			TNT1 AAAA 0 A_SpawnProjectile("PB_Intestine", 24, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH, random (0, 160));
			TNT1 AAA 0 A_SpawnProjectile ("PB_XDeath1", 42, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH, random (0, 160));
			TNT1 AAA 0 A_SpawnProjectile ("PB_SmallGib", 42, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH, random (0, 160));
			ZBLD ABCDE 5;
			TNT1 A 0 A_StartSound("BODYF",6);
			ZBLD F 1 A_SpawnItem("DeadZombiemanZBLDF");
			Stop;
		Death.cut:
		Death.HKFT:
			TNT1 A 0;
			TNT1 A 0 A_SetRoll(0);
			TNT1 A 0;
			TNT1 A 0 A_XScream();
			TNT1 O 0 A_NoBlocking();
			TNT1 A 0 A_SpawnProjectile ("PB_MuchBlood2", 35, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH, random (0, 160));
			TNT1 A 0 A_SpawnProjectile ("PB_RipHelmetZombieMan", 0, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH, random (0, 160));
			TNT1 AAAA 0 A_SpawnProjectile ("PB_SquirtingBloodTrail", 30, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH, random (0, 40));
			POSX AABCDE 9 A_SpawnProjectile ("PB_SquirtingBloodTrail", 30, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH, random (0, 40));
			TNT1 A 0 A_SpawnItem ("GrowingBloodPool");
			POSX EEEEEEEEEEEEEEEEEEEEEE 1 A_SpawnProjectile ("PB_SquirtingBloodTrail", 12, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH, random (0, 90));
			TNT1 A 0 A_StartSound("BODYF",6);
			TNT1 A 0 A_SpawnItem("DeadZombiemanJustLegsAreLeft");
			Stop;
		
		Death.Tear:
			TNT1 A 0;
			TNT1 A 0 A_SetRoll(0);
			TNT1 A 0 A_XScream();
			TNT1 O 0 A_NoBlocking();
			TNT1 A 0 A_SpawnProjectile ("PB_MuchBlood", 1, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH, random (0, 160));
			4P2X AA 8 A_SpawnProjectile ("PB_SquirtingBloodTrail", 30, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH, random (0, 40));
			TNT1 A 0 A_SpawnProjectile ("PB_XDeath4", 40, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH, random (0, 160));
			TNT1 AAA 0 A_SpawnProjectile ("PB_SmallGib", 42, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH, random (0, 160));
			TNT1 A 0 A_SpawnProjectile ("PB_RipHelmetZombieMan2", 0, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH, random (0, 160));
			PP2X BBCD 8 A_SpawnProjectile ("PB_SquirtingBloodTrail", 30, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH, random (0, 40));
			TNT1 A 0 A_SpawnItem ("GrowingBloodPool");
			TNT1 A 0 A_StartSound("BODYF",6);
			PP2X EEEEEEEEEEEEEEEEEEEE 2 A_SpawnProjectile("PB_SquirtingBloodTrail", 15, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH, random (0, 90));
			TNT1 A 0 A_SpawnItem("DeadZombieman_TearedInHalf");
			Stop;
			
		Death.cutless:
			TNT1 A 0 A_JumpIfInventory ("IsDown", 1, "Death.Down");
			TNT1 A 0 A_Jump(16, "Death.Saw");
			Goto Death.Minigun;
			
		Death.Minigun:
			TNT1 A 0;
			TNT1 A 0 A_SetRoll(0);
			TNT1 A 0 A_FaceTarget();
			TNT1 A 0 A_Scream();
			TNT1 O 0 A_NoBlocking();
			TNT1 A 0 A_SpawnItem ("BrutalizedHelmetZombieMan1");
			Stop;
			
		Death.LegMassacre:
			TNT1 A 0;
			TNT1 A 0 A_SetRoll(0);
			TNT1 A 0 A_SpawnProjectile ("PB_MuchBlood2", 15, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH, random (0, 160));
			TNT1 A 0 A_SpawnItem ("ZombieLegOnFoot");
			POS7 B 1 A_Scream();
			TNT1 A 0 A_NoBlocking();
			TNT1 A 0 A_SpawnItem ("BrutalizedHelmetZombieManLeg");
			Stop;
			
		Death.Decapitate:
			TNT1 A 0;
			TNT1 A 0 A_SetRoll(0);
			TNT1 A 0 {
				A_Stop();
				A_FaceTarget();
				A_NoBlocking();
				A_SpawnItemEx ("PB_XDeathHelmetZombieHead",0,0,50,random(-2,2),random(-2,2),12,0,SXF_NOCHECKPOSITION,0);
				A_SpawnProjectile ("PB_MuchBlood", 40, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH, random (0, 160));
			}
			//TNT1 A 0 A_Jump(64, "Deathchickenhead"); // This is causing crashes for some reason....
			ZMAD GGGGGGFFFFFF 1 {
					A_SpawnItemEx("NashGoreBloodSpurt",
					frandom(-5, 5), frandom(-5, 5), frandom(48, 52),
					frandom(-2, 2), frandom(-2, 2), frandom(4, 8),
					frandom(0, 360));
				}
			ZMAD AAAAABBBBBBBBBBCCCCC 2 A_SpawnProjectile ("PB_SquirtingBloodTrail", 30, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH, random (60, 120));
			TNT1 A 0 A_SpawnItem ("GrowingBloodPool");
			TNT1 A 0 A_StartSound("BODYF",6);
			ZMAD DDDDEEEEEEEEEEEEEEEE 2 A_SpawnProjectile ("PB_SquirtingBloodTrail", 10, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH, random (10, 40));
			ZMAD E 1 A_SpawnItem ("DeadZombieman_NoHeadFront");
			Stop;
		
		Death.LegHitbox:
		Death.Leg:
			TNT1 A 0;
			TNT1 A 0 A_SetRoll(0);
			TNT1 A 0 A_JumpIfHealthLower(-20, "LegRemove");
			Goto Death.MinorLeg;
		LegRemove:
			TNT1 A 0 A_Jump(64, "LegRemoveRare");
			TNT1 A 0 {
				A_SpawnProjectile ("PB_MuchBlood2", 15, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH, random (0, 160));
				A_SpawnProjectile ("PB_XDeath1", 15, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH, random (0, 160));
				A_SpawnProjectile ("PB_XDeathZombieLeg", 35, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH, random (0, 160));
				A_SpawnProjectile ("PB_SmallGib", 15, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH, random (0, 160));
				A_SpawnProjectile ("PB_SmallGib", 15, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH, random (0, 160));
				A_SpawnItem ("GrowingBloodPool");
				A_NoBlocking();
				A_Scream();
				A_SpawnItemEx ("HelmetZombiemanGotHisLegBlowed",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
				}
			Stop;
		LegRemoveRare:
			TNT1 A 0 {
				A_SpawnProjectile ("PB_MuchBlood2", 15, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH, random (0, 160));
				A_SpawnProjectile ("PB_XDeath1", 15, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH, random (0, 160));
				A_SpawnProjectile ("PB_XDeathZombieLeg", 35, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH, random (0, 160));
				A_SpawnItem ("GrowingBloodPool");
				A_NoBlocking();
				A_Scream();
				A_SpawnItemEx ("HelmetZombiemanSaciLol",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
			}
			Stop;
			
		Death.Melee:
			TNT1 A 0 A_JumpIfInventory ("IsDown", 1, "Death.Down");
		Death.Kick:
			TNT1 A 0;
			TNT1 A 0 A_SetRoll(0);
			TNT1 A 0 {
				bNODROPOFF = false;
				bSLIDESONWALLS = true;
				ThrustThingZ(0,30,0,1);
				A_Scream();
				A_NoBlocking();
				A_FaceTarget();
				A_Recoil (10);
			}
			9OS4 UUVWXY 5;
			TNT1 A 0 A_StartSound("BODYF");
			TNT1 A 0 A_SpawnItem("DeadZombieman1");
			Stop;

			
		Death.Incinerate:
			TNT1 A 0;
			TNT1 A 0 A_SetRoll(0);
			TNT1 A 0 {
				A_Stop();
				A_NoBlocking();
				A_StartSound("MELT");
			}
			TNT1 AAAA 0 A_SpawnProjectile ("ExplosionParticleHeavy", 32, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH, random (0, 360));
			TNT1 AAAA 0 A_SpawnProjectile ("ExplosionParticleVeryFast", 32, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH, random (0, 360));
			TNT1 A 0 A_SpawnItemEx ("ExplosionFlareSpawner",0,0,32,0,0,0,0,SXF_NOCHECKPOSITION,0);
			TNT1 A 0 A_SpawnItemEx("TinyBurningPiece", random (-15, 15), random (-15, 15));
			TNT1 A 0 A_SpawnItemEx("TinyBurningPiece2", random (-35, 35), random (-35, 35));
			TNT1 A 0 A_SpawnItemEx("TinyBurningPiece3", random (-45, 45), random (-45, 35));
			TNT1 A 0 A_SpawnItemEx ("RealisticFireSparks1",random(-2,2),random(-2,2),32,0,0,0,0,SXF_NOCHECKPOSITION  ,0);
			Z8RN KKKKK 1 BRIGHT Light("IncinerationGlow") A_SpawnProjectile ("BurningEmberParticlesFloating_Bigger", 36, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH, random (0, 160));
			TNT1 A 0 A_SpawnItemEx ("RealisticFireSparks1",random(-2,2),random(-2,2),28,0,0,0,0,SXF_NOCHECKPOSITION  ,0);
			Z8RN LLLLL 1 BRIGHT Light("IncinerationGlow") A_SpawnProjectile ("BurningEmberParticlesFloating_Bigger", 28, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH, random (0, 160));
			TNT1 A 0 A_SpawnItemEx ("RealisticFireSparks1",random(-2,2),random(-2,2),24,0,0,0,0,SXF_NOCHECKPOSITION  ,0);
			Z8RN CCCCC 1 BRIGHT Light("IncinerationGlow") A_SpawnProjectile ("BurningEmberParticlesFloating_Bigger", 36, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH, random (0, 160));
			TNT1 A 0 A_StartSound("SZZLL", 3);
			TNT1 A 0 A_SpawnItemEx ("RealisticFireSparks1",random(-2,2),random(-2,2),20,0,0,0,0,SXF_NOCHECKPOSITION  ,0);
			Z8RN DDDDD 1 BRIGHT Light("IncinerationGlow") A_SpawnProjectile ("BurningEmberParticlesFloating_Bigger", 20, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH, random (0, 160));
			TNT1 A 0 A_SpawnItemEx ("RealisticFireSparks1",random(-2,2),random(-2,2),16,0,0,0,0,SXF_NOCHECKPOSITION  ,0);
			Z8RN EEEEE 1 BRIGHT Light("IncinerationGlow") A_SpawnProjectile ("BurningEmberParticlesFloating_Bigger", 12, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH, random (0, 160));
			TNT1 A 0 A_SpawnItemEx ("RealisticFireSparks1",random(-2,2),random(-2,2),12,0,0,0,0,SXF_NOCHECKPOSITION  ,0);
			Z8RN FFFFF 1 BRIGHT Light("IncinerationGlow") A_SpawnProjectile ("BurningEmberParticlesFloating_Bigger", 10, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH, random (0, 160));
			TNT1 A 0 A_SpawnItemEx ("RealisticFireSparks1",random(-2,2),random(-2,2),8,0,0,0,0,SXF_NOCHECKPOSITION  ,0);
			TNT1 A 0 A_SpawnItem("BarrelExplosionSmokeColumn");
			Z8RN GGGG 2 Light("IncinerationGlow");
			TNT1 A 0 A_SpawnItemEx ("RealisticFireSparks1",random(-2,2),random(-2,2),8,0,0,0,0,SXF_NOCHECKPOSITION  ,0);
			Z8RN HHHH 2 Light("IncinerationGlow") A_SpawnProjectile ("PlasmaSmoke", 14, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH, random (0, 160));
			TNT1 A 0 A_SpawnItemEx ("RealisticFireSparks1",random(-2,2),random(-2,2),8,0,0,0,0,SXF_NOCHECKPOSITION  ,0);
			Z8RN HHHHHH 12 A_SpawnProjectile ("PlasmaSmoke", 14, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH, random (0, 160));
			Z8RN H -1;
			Stop;
		Death.Shrink:
			TNT1 A 1 {
				A_StartSound("Shrink", 3);
				A_SpawnItemEx ("PistolZombieman2ShrinkFX1", 0, 0,  5, 0, 0);
				}
			TNT1 A 1 A_SpawnItemEx ("PistolZombieman2ShrinkFX1", 0, 0, 5, 0, 0);
			TNT1 A 1 A_SpawnItemEx ("PistolZombieman2ShrinkFX1", 0, 0, 5, 0, 0);
			TNT1 A 1 A_SpawnItemEx ("PistolZombieman2ShrinkFX1", 0, 0, 5, 0, 0);
			TNT1 A 1 A_SpawnItemEx ("PistolZombieman2ShrinkFX1", 0, 0, 5, 0, 0);
			TNT1 A 1 A_SpawnItemEx ("PistolZombieman2ShrinkFX1", 0, 0, 5, 0, 0);
			TNT1 A 1 A_SpawnItemEx ("PistolZombieman2ShrinkFX1", 0, 0, 5, 0, 0);
			TNT1 A 1 A_SpawnItemEx ("LilPistolZombieMan2", 1);
			stop;

		Death.Shotgun:
			TNT1 A 0;
			TNT1 A 0 A_SetRoll(0);
			TNT1 A 0 A_Jump(42, "Death.Shotgunontheface");
			TNT1 A 0 A_JumpIfCloser(80, "Death.Blast");
			TNT1 A 0 A_JumpIfCloser(320, "Death.Shotgunontheface");
			Goto Death;
			
		Death.Shotgunontheface:	
			TNT1 A 0 {
				bSLIDESONWALLS = false;
				bNOBLOCKMONST = true;
			}
			TNT1 A 0 A_Jump(160, "DeathShotgunFly");
			
			9OS4 G 1 {
				A_FaceTarget();
				A_Stop();
				A_Pain();
				A_Recoil(13);
				ThrustThingZ(0,20,0,1);
				}
			TNT1 A 0 A_JumpIf(Vel.Y == 0, "DeathShotgunFly");
			TNT1 A 0 A_Jump(128, "DeathShotgunontheface2");
			TNT1 A 0 {
				A_Scream();
				A_SpawnProjectile ("PB_XDeath1", 35, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH, random (0, 160));
				A_SpawnProjectile ("PB_XDeath1", 35, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH, random (0, 160));
				A_NoBlocking();
				}
			Z6Z7 AAAABBBBCCCCDDDD 1 A_SpawnProjectile ("Brutal_LiquidBlood3", 15, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH, random (0, 40));
			Z6Z7 EFGHIJ 4 A_JumpIf((Vel.Y == 0), "DSFStop");
			Goto DSFStop;
		DSFStop:
			TNT1 A 0{
				A_Stop();
				A_SpawnItem ("GrowingBloodPool");
				A_SpawnProjectile ("PB_SuperWallRedBlood", 2, 0, random (170, 190), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH, random (0, 0));
				A_StartSound("BODYF",6);
				A_SpawnItem("DeadHelmetZombiemanShotguntotheFace1");
				}
			Stop;
		DeathShotgunontheface2:	
			TNT1 A 0 {
				A_Scream();
				A_SpawnProjectile ("PB_XDeath1", 35, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH, random (0, 160));
				A_SpawnProjectile ("PB_XDeath1", 35, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH, random (0, 160));
				A_NoBlocking();
				}
			Z6Z7 KKKKLLLLMMMMNNNN 1 A_SpawnProjectile ("PB_SquirtingBloodTrail", 15, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH, random (0, 40));
			Z6Z7 OPQRST 4 A_JumpIf((Vel.Y == 0), "DSFStop2");
			Goto DSFStop2;
			
		DSFStop2:
			TNT1 A 0 {
				A_Stop();
				A_SpawnItem ("GrowingBloodPool");
				A_SpawnProjectile ("PB_SuperWallRedBlood", 2, 0, random (170, 190), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH, random (0, 0));
				A_StartSound("BODYF",6);
				A_SpawnItem("DeadHelmetZombiemanShotguntotheFace2");
			}
			Stop;
		
		
		DeathShotgunFly:
			TNT1 A 0 {
				bNODROPOFF = false;
				bSLIDESONWALLS = false;
				ThrustThingZ(0,30,0,1);
				A_Scream();
				A_NoBlocking();
				A_FaceTarget();
				A_Recoil (6);
			}
			9OS4 U 5 A_SpawnProjectile ("PB_SquirtingBloodTrail", 15, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH, random (0, 40));
			TNT1 A 0 A_JumpIf((Vel.Y == 0), "TakeASit");
			9OS4 U 5 A_SpawnProjectile ("PB_SquirtingBloodTrail", 15, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH, random (0, 40));
			TNT1 A 0 A_JumpIf((Vel.Y == 0), "TakeASit");
			9OS4 V 5 A_SpawnProjectile ("PB_SquirtingBloodTrail", 15, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH, random (0, 40));
			TNT1 A 0 A_JumpIf((Vel.Y == 0), "TakeASit");
			9OS4 W 5 A_SpawnProjectile ("PB_SquirtingBloodTrail", 15, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH, random (0, 40));
			9OS4 X 5 A_SpawnProjectile ("PB_SquirtingBloodTrail", 15, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH, random (0, 40));
			9OS4 Y 5 A_SpawnProjectile ("PB_SquirtingBloodTrail", 15, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH, random (0, 40));
			TNT1 A 0 A_StartSound("BODYF",6);
			TNT1 A 0 A_SpawnItem("GrowingBloodPool");
			TNT1 A 0 A_SpawnItem("DeadZombieman1");
			Stop;
		TakeASit:
			TNT1 AAAA 0 A_SpawnProjectile ("PB_SuperWallRedBlood", 6, 0, random (170, 190), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH, random (0, 40));
			TNT1 A 0 A_StartSound("BODYF",6);
			9OS4 U 5;
			TNT1 A 0 A_SpawnItem("GrowingBloodPool");
			TNT1 A 0 A_SpawnItemEx("DeadHelmetZombieman_Slumped", 10);
			Stop;
			
		Death.HeadHitbox:
		Death.Head:
			TNT1 A 0;
			TNT1 A 0 A_SetRoll(0);
			TNT1 A 0 A_FaceTarget();
			TNT1 A 0 A_JumpIfInTargetInventory("HasIncendiaryWeapon",1,"Death.Incinerate");
			TNT1 A 0 A_JumpIfInTargetInventory("HasPlasmaWeapon", 1, "Death.Plasma");
			TNT1 A 0 A_JumpIfInTargetInventory("HasCutingWeapon", 1, "Death.Decapitate");
			TNT1 A 0 A_JumpIfInTargetInventory("RandomHeadExploder", 1, "HeadExplode");
			TNT1 A 0 A_JumpIfHealthLower(-100, "HeavyHead");
			TNT1 A 0 A_JumpIfHealthLower(-60, "HeadExplode");
		HeadMinor:
			TNT1 A 0 A_StartSound("MinorHeadshot");
			TNT1 A 0 A_Jump (256, "DeathMinorhead1", "DeathMinorhead2", "DeathMinorhead3", "DeathMinorhead4", "DeathMinorhead5");
		DeathMinorHead1:
			TNT1 A 0 A_Pain();
			TNT1 A 0 A_FaceTarget();
			TNT1 A 0 A_SpawnProjectile ("PB_Brains4Green", random (45, 55), random (5, -5), random (170, 190), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH, random (-10, 10));
			TNT1 AA 0 A_SpawnProjectile ("PB_SmallBrainPieceFast", random (45, 55), random (5, -5), random (170, 190), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH, random (-10, 10));
			TNT1 A 0 A_SpawnProjectile ("PB_SmallBrainPiece", 50, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH, random (0, 160));
			TNT1 A 0 A_SpawnProjectile ("PB_SuperWallRedBlood", 46, 0, random (170, 190), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH, random (0, 40));
			
			U4M7 A 6 A_SpawnProjectile ("PB_MuchBlood2", 40, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH, random (0, 160));
			U4M7 BC 8;
						
			U4M7 D 6 A_NoBlocking();
			TNT1 A 0 A_SpawnItem ("GrowingBloodPool");
			TNT1 A 0 A_StartSound("BODYF",6);
			U4M7 E 1;
			TNT1 A 0 A_SpawnItem ("DeadZombieman_U4M7");
			Stop;
		
		DeathMinorHead2:
			TNT1 A 0 A_Pain();
			TNT1 A 0 A_FaceTarget();
			TNT1 A 0 A_SpawnProjectile ("PB_Brains4Green", random (45, 55), random (5, -5), random (170, 190), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH, random (-10, 10));
			TNT1 AA 0 A_SpawnProjectile ("PB_SmallBrainPieceFast", random (45, 55), random (5, -5), random (170, 190), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH, random (-10, 10));
			TNT1 A 0 A_SpawnProjectile ("PB_SmallBrainPiece", 50, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH, random (0, 160));
			TNT1 A 0 A_SpawnProjectile ("PB_SuperWallRedBlood", 46, 0, random (170, 190), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH, random (0, 40));
			
			U4M7 F 6 A_SpawnProjectile ("PB_MuchBlood2", 40, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH, random (0, 160));
			U4M7 GH 8;
						
			U4M7 I 6 A_NoBlocking();
			TNT1 A 0 A_SpawnItem ("GrowingBloodPool");
			TNT1 A 0 A_StartSound("BODYF",6);
			U4M7 J 1;
			TNT1 A 0 A_SpawnItem ("DeadZombieman_U4M7J");
			Stop;
		DeathMinorhead3:
			U4M9 A 5 A_SpawnProjectile ("PB_MuchBlood2", 40, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH, random (0, 160));
			U4M9 B 5;
			TNT1 A 0 A_SpawnProjectile ("PB_Brains2", random (45, 55), random (5, -5), random (170, 190), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH, random (-10, 10));
			TNT1 A 0 A_SpawnProjectile ("PB_Brains4", random (45, 55), random (5, -5), random (170, 190), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH, random (-10, 10));
			TNT1 A 0 A_SpawnProjectile ("PB_SmallBrainPiece", 50, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH, random (0, 160));
			TNT1 AAA 0 A_SpawnProjectile ("PB_Teeth", 50, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH, random (0, 160));
			TNT1 A 0 A_SpawnProjectile ("PB_SuperWallRedBlood", 46, 0, random (170, 190), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH, random (0, 40));
			U4M9 C 5 A_NoBlocking();
			U4M9 DE 5;
			TNT1 A 0 A_StartSound("BODYF",6);
			U4M9 F 1;
			TNT1 A 0 A_SpawnItem ("GrowingBloodPool");
			TNT1 A 0 A_SpawnItem ("DeadZombieman_U4M9");
			Stop;
		DeathMinorhead4:
			TNT1 A 0 A_Pain();
			TNT1 A 0 A_FaceTarget();
			TNT1 A 0 A_SpawnProjectile ("PB_Brains4Green", random (45, 55), random (5, -5), random (170, 190), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH, random (-10, 10));
			TNT1 AA 0 A_SpawnProjectile ("PB_SmallBrainPieceFast", random (45, 55), random (5, -5), random (170, 190), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH, random (-10, 10));
			TNT1 A 0 A_SpawnProjectile ("PB_SmallBrainPiece", 50, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH, random (0, 160));
			TNT1 A 0 A_SpawnProjectile ("PB_SuperWallRedBlood", 46, 0, random (170, 190), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH, random (0, 40));
			
			PXS4 A 6 A_SpawnProjectile ("PB_MuchBlood2", 40, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH, random (0, 160));
			PXS4 BC 7;
			PXS4 D 6 A_NoBlocking();
			PXS4 EF 6;
			TNT1 A 0 A_SpawnItem ("GrowingBloodPool");
			TNT1 A 0 A_StartSound("BODYF",6);
			TNT1 A 0 A_SpawnItem ("DeadZombieman_PXS4");
			Stop;
		
		DeathMinorHead5:
			TNT1 A 0 A_NoBlocking();
			TNT1 A 0 A_SpawnItemEx ("DyingHelmetZombiemanLostTeeth", 0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
			Stop;
		
		XDeath:
			TNT1 A 0 A_JumpIfInTargetInventory("HasIncendiaryWeapon",1,"Death.Incinerate");
			TNT1 A 0 A_JumpIfInTargetInventory("SSGSelected", 1, "Death.SSG");
			TNT1 A 0 { 
				NashGoreGibs.SpawnGibs(self);
				A_SpawnProjectile ("PB_XDeath1", 42, 0, random (0, 290), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH, random (10, 60));
				A_SpawnProjectile ("PB_XDeath3", 42, 0, random (0, 290), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH, random (10, 60));
				A_SpawnProjectile ("PB_XDeath3", 42, 0, random (0, 290), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH, random (10, 60));
				A_SpawnProjectile ("PB_XDeath3", 42, 0, random (0, 290), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH, random (10, 60));
				A_SpawnProjectile ("PB_XDeath2", 42, 0, random (0, 190), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH, random (10, 60));
				A_SpawnProjectile ("PB_XDeath4", 42, 0, random (0, 190), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH, random (10, 60));
				}
			TNT1 AAAAAA 0 A_SpawnProjectile ("PB_BloodmistLarge", 40, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH, random (30, 90));
			TNT1 A 1 {
				A_SpawnItemEx("PB_HelmetZombieXDeath",0,0,2,Vel.X,Vel.Y,Vel.Z,angle,SXF_ABSOLUTEVELOCITY|SXF_ABSOLUTEANGLE|SXF_NOCHECKPOSITION,0);
				A_Recoil(2);
				A_XScream();
				A_NoBlocking();
			}
			Stop;
			
		Death.SSG:
			TNT1 A 0;
			TNT1 A 0 A_SetRoll(0);
			ZZD1 E 1 {
					ThrustThing(angle * 256 / 360 + 128, 22, 0, 0);
					A_FaceTarget();
					NashGoreGibs.SpawnGibs(self);
					for (int i = 0; i < 5; i++) {	
						A_SpawnProjectile ("PB_BloodmistLarge", 32, 0, random (170, 190), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH, random (0, 40));
						A_SpawnProjectile ("PB_SuperWallRedBlood", 32, 0, random (170, 190), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH, random (0, 40));
					}
					
					A_SpawnProjectile ("PB_Intestine", 32, 0, random (150, 210), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH,  random (0, 40));
					A_SpawnProjectile ("PB_Intestine", 32, 0, random (150, 210), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH, random (0, 40));
					A_SpawnProjectile ("PB_Intestine", 32, 0, random (150, 210), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH, random (0, 40));
					A_SpawnProjectile ("PB_SuperWallRedBlood", 32, 0, random (170, 190), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH, random (0, 40));
					A_SpawnProjectile ("PB_XDeathArm1", 32, 0, random (180, 190), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH, random (0, 80));
					A_SpawnProjectile ("PB_XDeathArm1", 32, 0, random (160, 170), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH, random (0, 80));
					A_SpawnProjectile ("PB_XDeathHelmetZombieHead", 32, 0, random (170, 190), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH, random (0, 80));
					A_XScream();
					A_NoBlocking();
				}
			ZZD1 EEFFGH 6;
			ZZD1 H 1 A_StartSound("BODYF");
			ZZD1 HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH 2 {
				A_SpawnItemEx("PB_SquirtingBloodTrail", 
				0, 0, frandom(3, 4),
				frandom(-3, 3), frandom(-3, 3), frandom(3, 6),
				frandom(0.0, 360));
			}
			TNT1 A 0 {
				A_SpawnItem ("GrowingBloodPool");
				A_SpawnItem("DeadZombiemanJustLegsAreLeft2");
			}
			Stop;
			
		Death.Railgun:
			TNT1 A 0 A_Jump(96, "Death.SSG");
		Death.Blast:
			TNT1 A 0;
			TNT1 A 0 A_SetRoll(0);
			TNT1 A 0 A_FaceTarget();
			TNT1 A 0 A_Jump(12, "Death.Arm");
			TNT1 A 0 A_Jump(128, "Death.Blast2");
			TNT1 A 0 A_NoBlocking();
			TNT1 A 0 {
				A_SpawnProjectile ("PB_Intestine", 32, 0, random (150, 210), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH, random (0, 40));
				A_SpawnProjectile ("PB_Intestine", 32, 0, random (150, 210), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH, random (0, 40));
				A_SpawnProjectile ("PB_Intestine", 32, 0, random (150, 210), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH, random (0, 40));
				A_SpawnProjectile ("PB_XDeath1", 32, 0, random (150, 210), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH, random (0, 40));
				A_SpawnProjectile ("PB_SmallGib", 32, 0, random (150, 210), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH, random (0, 40));
				A_SpawnProjectile ("PB_XDeath1", 32, 0, random (150, 210), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH, random (0, 40));
				A_SpawnProjectile ("PB_XDeath3", 16, 0, random (170, 190), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH, random (0, 40));
				A_SpawnProjectile ("PB_SmallGib", 16, 0, random (170, 190), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH, random (0, 40));
				A_SpawnProjectile ("PB_XDeath3", 16, 0, random (170, 190), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH, random (0, 40));
				A_SpawnProjectile ("NashGoreBloodSpurt", 32, 0, random (170, 190), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH, random (0, 40));
				A_SpawnProjectile ("NashGoreBloodSpurt", 32, 0, random (170, 190), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH, random (0, 40));
				A_SpawnProjectile ("NashGoreBloodSpurt", 32, 0, random (170, 190), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH, random (0, 40));
				A_SpawnProjectile ("NashGoreBloodSpurt", 32, 0, random (170, 190), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH, random (0, 40));
				A_SpawnProjectile ("PB_SuperWallRedBlood", 32, 0, random (170, 190), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH, random (0, 40));
				A_SpawnProjectile ("PB_SuperWallRedBlood", 32, 0, random (170, 190), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH, random (0, 40));
				A_SpawnProjectile ("PB_SuperWallRedBlood", 32, 0, random (170, 190), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH, random (0, 40));
				A_SpawnProjectile ("PB_SuperWallRedBlood", 32, 0, random (170, 190), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH, random (0, 40));
				A_SpawnProjectile ("PB_BloodmistLarge", 40, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH, random (30, 90));
				A_SpawnProjectile ("PB_BloodmistLarge", 40, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH, random (30, 90));
				A_SpawnProjectile ("PB_BloodmistLarge", 40, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH, random (30, 90));
				}
			Z4Z7 A 6 {
				A_Stop();
				A_SpawnItem ("GrowingBloodPool");
			}
			Z4Z7 BBBBBBBBBB 3 A_SpawnProjectile ("PB_SquirtingBloodTrail", 26, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH, random (30, 60));
			Z4Z7 CCC 3 A_SpawnProjectile ("PB_SquirtingBloodTrail", 26, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH, random (10, 40));
			Z4Z7 DD 3 A_SpawnProjectile ("PB_SquirtingBloodTrail", 6, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH, random (30, 60));
			TNT1 A 0 A_StartSound("BODYF");
			TNT1 A 0 A_SpawnItem("DeadZombieMan_Z4Z7");
			Stop;
			
			
		Death.Nailgun:
			TNT1 A 0;
			TNT1 A 0 A_SetRoll(0);
			TNT1 A 0 A_Jump(256,
				"Naildeath1", "Naildeath1",
				"Naildeath2", "Naildeath2",
				"NailDeath3", "NailDeath3",
				"Death.Blast", "Death.Blast2");
		Naildeath1:
			TNT1 A 0 {
				bNODROPOFF = false;
				bSLIDESONWALLS = false;
				ThrustThingZ(0,random(20,30),0,1);
				A_Scream();
				A_NoBlocking();
				A_FaceTarget();
				A_Recoil(30);
			}
			9OS4 U 5 A_SpawnProjectile ("PB_SquirtingBloodTrail", 15, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH, random (0, 40));
			TNT1 A 0 A_JumpIf((Vel.Y == 0), "PinToWall");
			9OS4 U 5 A_SpawnProjectile ("PB_SquirtingBloodTrail", 15, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH, random (0, 40));
			TNT1 A 0 A_JumpIf((Vel.Y == 0), "PinToWall");
			9OS4 V 5 A_SpawnProjectile ("PB_SquirtingBloodTrail", 15, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH, random (0, 40));
			TNT1 A 0 A_JumpIf((Vel.Y == 0), "PinToWall");
			9OS4 W 5 A_SpawnProjectile ("PB_SquirtingBloodTrail", 15, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH, random (0, 40));
			9OS4 X 5 A_SpawnProjectile ("PB_SquirtingBloodTrail", 15, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH, random (0, 40));
			9OS4 Y 5 A_SpawnProjectile ("PB_SquirtingBloodTrail", 15, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH, random (0, 40));
			TNT1 A 0 A_StartSound("BODYF",6);
			TNT1 A 0 A_SpawnItem("GrowingBloodPool");
			TNT1 A 0 A_SpawnItem("DeadZombieman1");
			Stop;
		PinToWall:
			TNT1 A 0 A_SpawnProjectile ("PB_MuchBlood2", 35, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH, random (0, 160));
			TNT1 AA 0 A_SpawnProjectile ("PB_XDeath1", 35, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH, random (0, 160));
			TNT1 AAAA 0 A_SpawnProjectile ("PB_SuperWallRedBlood", 6, 0, random (170, 190), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH, random (0, 40));
			TNT1 A 0 A_StartSound("Weapons/NailHitBleed");
			PIN3 A 5;
			TNT1 A 0 A_SpawnItem("GrowingBloodPool");
			TNT1 A 0 A_SpawnItemEx("Dead_Helmet_Zombieman_Pinned", 10);
			Stop;
			
		Naildeath2:
			TNT1 A 0 A_XScream();
			TNT1 A 0 A_NoBlocking();
			TNT1 A 0 A_FaceTarget();
			TNT1 AAA 0 A_SpawnProjectile ("PB_Intestine", 32, 0, random (150, 210), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH, random (0, 40));
			TNT1 AAA 0 A_SpawnProjectile ("PB_XDeath1", 32, 0, random (150, 210), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH, random (0, 40));
			TNT1 AAA 0 A_SpawnProjectile ("PB_Xdeath3", 16, 0, random (170, 190), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH, random (0, 40));
			TNT1 AA 0 A_SpawnProjectile ("PB_Xdeath2", 16, 0, random (130, 210), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH, random (0, 40));
			TNT1 AAAA 0 A_SpawnProjectile ("NashGoreBloodSpurt", 32, 0, random (170, 190), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH, random (0, 40));
			TNT1 AAAA 0 A_SpawnProjectile ("PB_SuperWallRedBlood", 32, 0, random (170, 190), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH, random (0, 40));
			TNT1 AAAA 0 A_SpawnProjectile ("PB_BloodMistBig", 40, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH, random (30, 90));
			TNT1 A 0 A_SpawnProjectile ("PinnedHelmetZombiemanTorso", 32, 0, 180, 2, random (-2, 2));
			
			TNT1 AAAA 0 A_SpawnProjectile ("PB_SquirtingBloodTrail", 30, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH, random (0, 40));
			POSX AAAAAA 2 A_SpawnProjectile ("PB_SquirtingBloodTrail", 36, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH, random (0, 40));
			POSX BCDE 9 A_SpawnProjectile ("PB_SquirtingBloodTrail", 28, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH, random (0, 40));
			TNT1 A 0 A_SpawnItem ("GrowingBloodPool");
			POSX EEEEEEEEEEEEEEEEEEEEEE 1 A_SpawnProjectile ("PB_SquirtingBloodTrail", 12, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH, random (0, 90));
			TNT1 A 0 A_StartSound("BODYF",6);
			TNT1 A 0 A_SpawnItem("DeadZombiemanJustLegsAreLeft");
			Stop;
			
		NailDeath3:
			TNT1 A 0 A_XScream();
			TNT1 A 0 A_NoBlocking();
			TNT1 A 0 A_FaceTarget();
			TNT1 AAA 0 A_SpawnProjectile ("PB_XDeath1", 32, 0, random (150, 210), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH, random (0, 40));
			TNT1 AA 0 A_SpawnProjectile ("PB_Xdeath2", 16, 0, random (130, 210), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH, random (0, 40));
			TNT1 AAAA 0 A_SpawnProjectile ("NashGoreBloodSpurt", 32, 0, random (170, 190), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH, random (0, 40));
			TNT1 AAAA 0 A_SpawnProjectile ("PB_SuperWallRedBlood", 32, 0, random (170, 190), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH, random (0, 40));
			TNT1 AAAA 0 A_SpawnProjectile ("PB_BloodMistBig", 40, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH, random (30, 90));
			TNT1 A 0 A_SpawnProjectile ("PinnedHelmetZombiemanTorso2", 32, 0, 180, 2, random (-2, 2));
			PP2X BBCD 6 A_SpawnProjectile ("PB_SquirtingBloodTrail", 30, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH, random (0, 40));
			TNT1 A 0 A_SpawnItem ("GrowingBloodPool");
			TNT1 A 0 A_StartSound("BODYF",6);
			PP2X EEEEEEEEEEEEEEEEEEEE 2 A_SpawnProjectile("PB_SquirtingBloodTrail", 15, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH, random (0, 90));
			TNT1 A 0 A_SpawnItem("DeadZombieman_TearedInHalf");
			Stop;
			
		Death.Fatality:
				TNT1 A 0 A_Pain();
				TNT1 A 0 A_NoBlocking();
				TNT1 A 0 A_JumpIfIntargetInventory("FistsSelected", 1, 1);
			Goto Death.ExplosiveImpact;
				TNT1 A 0 A_GiveToTarget("GoFatality", 1);
				TNT1 A 0 A_Jump(256,"Death.Fatality1", "Death.Fatality2", "Death.Fatality3", "Death.Fatality4");
				Stop;
			Death.Fatality1:
				TNT1 A 0 A_GiveToTarget("HelmetZombieManFatality", 1);
				Stop;
			Death.Fatality2:
				TNT1 A 0 A_GiveToTarget("HelmetZombieManFatality2", 1);
				Stop;
			Death.Fatality3:
				TNT1 A 0 A_GiveToTarget("HelmetZombieManFatality3", 1);
				Stop;
			Death.Fatality4:
				TNT1 A 0 A_GiveToTarget("HelmetZombieManFatality4", 1);
				Stop;
		
		//New Evade Animation
		DiveLeft:
			9OS2 A 1 A_FaceTarget();
			9OS2 A 1 A_SetAngle(angle+90, SPF_INTERPOLATE);
			//POSS A 1 A_SetAngle(angle*256/360+192, SPF_INTERPOLATE);
			Goto DivingBegin;
		DiveRight:
			9OS2 A 1 A_FaceTarget();
			9OS2 A 1 A_SetAngle(angle-90, SPF_INTERPOLATE);
		//	POSS A 1 A_SetAngle(angle*256/360+64, SPF_INTERPOLATE);
			Goto DivingBegin;
		DiveBack:
			9OS2 A 1 A_FaceTarget();
			9OS2 A 1 A_SetAngle(angle-180, SPF_INTERPOLATE);
			//POSS A 1 A_SetAngle(angle*256/360+128, SPF_INTERPOLATE);
			Goto DivingBegin;
		DiveFront:
			9OS2 A 1 A_FaceTarget();
			Goto DivingBegin;
		DivingBegin:
			ZDE5 A 5 A_SetAngle(angle, SPF_INTERPOLATE);
			TNT1 A 0 {
				ThrustThingZ(0,30,0,0);
				ThrustThing(angle, 15, 0, 0);
			}
			ZDE5 B 8 A_SetAngle(angle, SPF_INTERPOLATE);
		DivingLoop:
			ZDE5 B 1 A_CheckFloor ("DiveStop");
			ZDE5 B 1 A_JumpIf (Vel.Z == 0, "DiveStop");
			Loop;
		DiveStop:
			TNT1 A 0 A_StartSound("BODYF", CHAN_AUTO);
			ZDE5 C 25 A_Stop();
			ZDE5 D 6;
			9OS2 F 6;
			9OS2 E 6;
			Goto Missile;
		
		//Avoid damage
		Pain.Avoid:
			TNT1 A 0 A_JumpIfInTargetInventory("IsPlayer",1, "PlayerActionDialogue");
		Avoid:
			TNT1 A 0
			{
				avoidCooldown = 175;
			}
			TNT1 A 0 A_Jump(256, "DiveLeft", "DiveRight", "DiveLeft", "DiveRight", "DiveFront");
			Goto DiveFront;
		Roll:
			TNT1 A 0;
			TNT1 A 0 A_DeathWepCheck("MinigunSelected", 2000, "Avoid");
			TNT1 A 0 A_DeathWepCheck("RocketLauncherSelected", 2000, "Avoid");
			TNT1 A 0 A_DeathWepCheck("SGLSelected", 2000, "Avoid");
			TNT1 A 0 A_DeathWepCheck("PlayerIsThrowingAGrenade", 2000, "Avoid");
			TNT1 A 0 A_Jump(256, "RollR", "RollL");
		RollL:
			TNT1 A 0 A_WallCheck(2, "RollLNow", "See");
		RollLNow:
			TNT1 AAA 0 A_FaceTarget(0);
			5RO1 A 1 A_FaceTarget(0);
			TNT1 A 0
			{
				ThrustThing(angle * 256 / 360 + 192, 13, 0, 0);
				//Play the Roll sound
				bNoPain = true;
				bNODROPOFF = true;
			}
			5RO1 AAAAAAAAAAAAAAAA 1 A_SetRoll(roll+22, SPF_INTERPOLATE);
			5RO1 A 1
			{
				//A_Stop();
				A_SetRoll(0);
				bNoPain = false;
				bNODROPOFF = false;
			}
			5RO1 A 1;
			goto See;
		RollR:
			TNT1 A 0 A_WallCheck(2, "RollLNow", "See");
		RollRNow:
			TNT1 AAA 0 A_FaceTarget(0);
			5RO2 A 1 A_FaceTarget(0);
			TNT1 A 0
			{
				ThrustThing(angle * 256 / 360 + 64, 13, 0, 0);
				//Play the Roll sound
				bNoPain = true;
				bNODROPOFF = true;
			}
			5RO2 AAAAAAAAAAAAAAAA 1 A_SetRoll(roll-22, SPF_INTERPOLATE);
			5RO2 A 1
			{
				//A_Stop();
				A_SetRoll(0);
				bNoPain = false;
				bNODROPOFF = false;
			}
			5RO2 A 1;
			goto See;
		SideStep:
			//Undone
		SideHop:
			TNT1 A 0 A_Jump(256, "SHR", "SHL");
		SHR:
			9OS2 A 3 A_FaceTarget;
			9OS2 E 3 A_FaceTarget;
			TNT1 A 0 ThrustThingZ(0, 20, 0, 0);
			TNT1 A 0 ThrustThing(angle*256/360+192, 8, 0, 0);
			5RO1 A 12;
		SHRL:
			5RO1 A 1 A_CheckFloor("SHRE");
			5RO1 A 1;
			Loop;
		SHRE:
			5RO1 A 1 A_FaceTarget;
			TNT1 A 0 A_Jump(256, "RollR", "See", "Missile");
			Goto See;
		SHL:
			9OS2 A 3 A_FaceTarget;
			9OS2 E 3 A_FaceTarget;
			TNT1 A 0 ThrustThingZ(0, 20, 0, 0);
			TNT1 A 0 ThrustThing(angle*256/360+64, 8, 0, 0);
			5RO2 A 12;
		SHLL:
			5RO2 A 1 A_CheckFloor("SHLE");
			5RO2 A 1 A_CheckCeiling("SHLE");
			Loop;
		SHLE:
			5RO2 A 1 A_FaceTarget;
			TNT1 A 0 A_Jump(256, "RollL", "See", "Missile");
			Goto See;
		
		Death.Ice:
		Death.IceExplosion:
		Death.Freeze:
		Death.Frost:
			TNT1 A 0 {
				bShootable = false;
				bSOLID = false;
				A_SpawnItem("FrozenPistolZombieman2");
			}
			Stop;
			
/*		Death.Fatality:
				TNT1 A 0 A_Pain();
				TNT1 A 0 A_NoBlocking();
				TNT1 A 0 A_JumpIfIntargetInventory("FistsSelected", 1, 1);
				Goto Death.ExplosiveImpact;
				TNT1 A 0 A_GiveToTarget("GoFatality", 1);
				TNT1 A 0 A_Jump(256,"Death.Fatality1", "Death.Fatality1", "Death.Fatality2", "Death.Fatality2", "Death.Fatality3", "Death.Fatality4");
				Goto Death.Fatality1;

		Death.Fatality1:
			TNT1 A 0 A_GiveToTarget("HelmetZombieManFatality", 1);
			Stop;
		Death.Fatality2:
			TNT1 A 0 A_GiveToTarget("HelmetZombieManFatality2", 1);
			Stop;
		Death.Fatality3:
			TNT1 A 0 A_GiveToTarget("HelmetZombieManFatality3", 1);
			Stop;
		Death.Fatality4:
			TNT1 A 0 A_GiveToTarget("HelmetZombieManFatality4", 1);
			Stop;*/
	}
}
