Class PB_CarbineZombieman: PB_Zombieman //Replaces ZombieMan
{
	Default
	{
		DropItem "DropedCarbine";
		DropItem "DropedGrenade", 15;
	}
	States
	{
		
		Spawn:
			TNT1 A 0 {
				A_TakeInventory("ZombiemanAmmo", 20);
				A_GiveInventory("ZombieManAmmo", random(1,10));
				A_GiveInventory("SKZombieman", 1);
				A_GiveInventory("TypeZombieMan", 1);
			}
		Stand:
			RFTR AA 10 A_Look();
			Loop;
		See:
			RFTR AABB 2 A_SmartChase();
			TNT1 A 0 A_PlaySound("humans/step");
			RFTR CCDD 2 A_SmartChase();
			TNT1 A 0 A_PlaySound("humans/step");
			TNT1 A 0 A_JumpIfInventory("Wandering",1,"LookAround");
			Loop;
		LookAround:
			TNT1 A 0 A_ClearTarget();
			RFTR ABACAD 10 A_Look();
			RFTR ABCD 4 A_SmartChase();
			Goto See+2;
		FallBack:
			RFTR D 4 {
				A_FaceTarget();
				A_Recoil(2);
				A_PlaySound("humans/step",3);
				return A_Jump(64,"Missile");
			}
			RFTR C 4 {
				A_FaceTarget();
				A_Recoil(2);
				return A_Jump(64,"Missile");
			}
			RFTR B 4 {
				A_FaceTarget();
				A_Recoil(2);
				A_PlaySound("humans/step",3);
				return A_Jump(64,"Missile");
			}
			RFTR A 2 {
				A_FaceTarget();
				A_Recoil(2);
				return A_Jump(64,"Missile");
			}
			RFTR D 4 {
				A_FaceTarget();
				A_Recoil(2);
				A_PlaySound("humans/step",3);
				return A_Jump(64,"Missile");
			}
			RFTR C 4 {
				A_FaceTarget();
				A_Recoil(2);
				return A_Jump(64,"Missile");
			}
			RFTR B 4 {
				A_FaceTarget();
				A_Recoil(2);
				A_PlaySound("humans/step",3);
				return A_Jump(64,"Missile");
			}
			RFTR A 4 {
				A_FaceTarget();
				A_Recoil(2);
			}
			Goto Missile;
	
		////////////////
		//Attack Logic// 
		////////////////
		Missile:
			RFTR E 6 {
				A_Stop();
				A_FaceTarget();
				return A_CheckLOF("AttackHandler");
				}
			Goto See;
		AttackHandler:
			TNT1 A 0 {
				int chance = (random(1,256));
				
				if((chance > 232) && (CountInv("ZombieManGrenadeCount") < 3)) {return A_Jump(256, "Grenade");}
				return A_Jump(256, "Attack1", "Attack1", "Attack2", "Attack2", "Attack3");
			}
			
		//Standard, 3 round burst attack
		Attack1:
			RFTR E 6 A_FaceTarget();
			RFTR F 2 BRIGHT {
				A_CustomMissile("ZombieManTracer", 32, 0, random(-8, 8), 1, random(-3, 3));
				A_PlaySound("Weapons/Rifle/SFire");
				A_SpawnItem ("RifleCaseSpawn", 0, 30,0);
				}
			RFTR E 1 A_FaceTarget();
			RFTR F 2 BRIGHT {
				A_CustomMissile("ZombieManTracer", 32, 0, random(-8, 8), 1, random(-3, 3));
				A_PlaySound("Weapons/Rifle/SFire");
				A_SpawnItem ("RifleCaseSpawn", 0, 30,0);
				}
			RFTR E 1 A_FaceTarget();
			RFTR F 2 BRIGHT {
				A_CustomMissile("ZombieManTracer", 32, 0, random(-8, 8), 1, random(-3, 3));
				A_PlaySound("Weapons/Rifle/SFire");
				A_SpawnItem ("RifleCaseSpawn", 0, 30,0);
				}
			RFTR E 2 {
				A_FaceTarget();
				A_GiveInventory("ZombieManAmmo", 2);
				return A_JumpIfInventory("ZombieManAmmo", 20, "Reload");
				}
			Goto See;
		//Aimed, 5 round burst attack
		Attack2:
			P066 E 6 A_FaceTarget();
			P066 E 2 BRIGHT {
				A_FaceTarget();
				A_CustomMissile("ZombieManTracer", 32, 0, random(-4, 4), 1, random(-3, 3));
				A_CustomMissile("OrangeLensFlareAlt", 42, 16, 15, 0);
				A_CustomMissile("MarineMuzzle1", 39, 4);
				A_SpawnItem ("RifleCaseSpawn", 0, 36,0);
				A_PlaySound("Weapons/Rifle/SFire");
			}
			P066 E 1 A_FaceTarget();
			P066 E 2 BRIGHT {
				A_FaceTarget();
				A_CustomMissile("ZombieManTracer", 32, 0, random(-4, 4), 1, random(-3, 3));
				A_CustomMissile("OrangeLensFlareAlt", 42, 16, 15, 0);
				A_CustomMissile("MarineMuzzle1", 39, 4);
				A_SpawnItem ("RifleCaseSpawn", 0, 36,0);
				A_PlaySound("Weapons/Rifle/SFire");
			}
			P066 E 1 A_FaceTarget();
			P066 E 2 BRIGHT {
				A_FaceTarget();
				A_CustomMissile("ZombieManTracer", 32, 0, random(-4, 4), 1, random(-3, 3));
				A_CustomMissile("OrangeLensFlareAlt", 42, 16, 15, 0);
				A_CustomMissile("MarineMuzzle1", 39, 4);
				A_SpawnItem ("RifleCaseSpawn", 0, 36,0);
				A_PlaySound("Weapons/Rifle/SFire");
			}
			P066 E 1 A_FaceTarget();
			P066 E 2 BRIGHT {
				A_FaceTarget();
				A_CustomMissile("ZombieManTracer", 32, 0, random(-4, 4), 1, random(-3, 3));
				A_CustomMissile("OrangeLensFlareAlt", 42, 16, 15, 0);
				A_CustomMissile("MarineMuzzle1", 39, 4);
				A_SpawnItem ("RifleCaseSpawn", 0, 36,0);
				A_PlaySound("Weapons/Rifle/SFire");
			}
			P066 E 1 A_FaceTarget();
			P066 E 2 BRIGHT {
				A_FaceTarget();
				A_CustomMissile("ZombieManTracer", 32, 0, random(-4, 4), 1, random(-3, 3));
				A_CustomMissile("OrangeLensFlareAlt", 42, 16, 15, 0);
				A_CustomMissile("MarineMuzzle1", 39, 4);
				A_SpawnItem ("RifleCaseSpawn", 0, 36,0);
				A_PlaySound("Weapons/Rifle/SFire");
			}
			P066 E 2 {
				A_GiveInventory("ZombieManAmmo", 3);
				return A_JumpIfInventory("ZombieManAmmo", 20, "Reload");
				return A_jump(16, "Missile");
			}
			Goto See;
		// Crouched 4-round burst
		Attack3:
			P066 E 4 A_FaceTarget();
			Crouching:
			P066 F 6 A_FaceTarget();
			P066 F 2 BRIGHT {
				A_CustomMissile("ZombieManTracer", 32, 0, random(-4, 4), 1, random(-3, 3));
				A_CustomMissile("OrangeLensFlareAlt", 32, 16, 15, 0);
				A_CustomMissile("MarineMuzzle1", 32, 4) ;
				A_SpawnItem ("RifleCaseSpawn", 0, 36,0);
				A_PlaySound("Weapons/Rifle/SFire");
			}
			P066 F 1 A_FaceTarget();
			P066 F 2 BRIGHT {
				A_CustomMissile("ZombieManTracer", 32, 0, random(-4, 4), 1, random(-3, 3));
				A_CustomMissile("OrangeLensFlareAlt", 32, 16, 15, 0);
				A_CustomMissile("MarineMuzzle1", 32, 4) ;
				A_SpawnItem ("RifleCaseSpawn", 0, 36,0);
				A_PlaySound("Weapons/Rifle/SFire");
			}
			P066 F 1 A_FaceTarget();
			P066 F 2 BRIGHT {
				A_CustomMissile("ZombieManTracer", 32, 0, random(-4, 4), 1, random(-3, 3));
				A_CustomMissile("OrangeLensFlareAlt", 32, 16, 15, 0);
				A_CustomMissile("MarineMuzzle1", 32, 4) ;
				A_SpawnItem ("RifleCaseSpawn", 0, 36,0);
				A_PlaySound("Weapons/Rifle/SFire");
			}
			P066 F 1 A_FaceTarget();
			P066 F 2 BRIGHT {
				A_CustomMissile("ZombieManTracer", 32, 0, random(-4, 4), 1, random(-3, 3));
				A_CustomMissile("OrangeLensFlareAlt", 32, 16, 15, 0);
				A_CustomMissile("MarineMuzzle1", 32, 4) ;
				A_SpawnItem ("RifleCaseSpawn", 0, 36,0);
				A_PlaySound("Weapons/Rifle/SFire");
			}
			P066 F 4 {
				A_FaceTarget();
				A_GiveInventory("ZombieManAmmo", 5);
				return A_JumpIfInventory("ZombieManAmmo", 20, "Reload");
				return A_jump(24, "Attack3");
			}
			DoneCrouching:
			P066 E 6 A_FaceTarget();
			Goto See;
			
		Grenade:
			TNT1 A 0 A_JumpIfCloser(500, 1);
			Goto Attack1;
			TNT1 A 0 A_JumpIfCloser(90, "Attack1");
		ThrowGrenade:
			RFG1 A 6 {
				A_FaceTarget(90,45);
				A_PlaySound("OPNGRN", 1);
			}
			RFG1 A 6 A_FaceTarget(90,45);
			RFG1 B 6 {
				A_FaceTarget(90,45);
				A_DropAdjust("EnemyThrownGrenade","EnemyThrownGrenade",0,18,28);
				A_GiveInventory("ZombieManGrenadeCount", 1);
				A_PlaySound("THRGRN", 1);
			}
			RFG1 B 6;
        Goto See;
		
		Reload:
			RFTR E 4 {
				A_TakeInventory("ZombieManAmmo", 20);
				A_CustomMissile("EmptyClipSpawn", 38, 0, random(-11, 11), 0);
				A_PlaySound("Reload");
				}
			RFR2 ABCD 10;
			RFTR A 10;
			Goto See;
		
		////////////////
		//Pain Logic// 
		////////////////
		Pain:
			TNT1 A 0 A_JumpIfInventory ("IsDown", 1, "Downed");
			RFTR G 6 A_Pain();
			Goto See;
        Downed:
			ID31 F 6 A_Pain();
			Goto GetUp;
		Pain.Kick:
		Pain.ExtremePunches:
			TNT1 A 0 A_JumpIfInventory ("IsDown", 1, "Pain");
			RFT9 A 1 {
					A_ChangeFLag("NODROPOFF", 0);
					A_ChangeFlag("FORCEXYBILLBOARD", 1);
					A_TakeInventory("SKZombieman", 1);
					A_GiveInventory("IsDown", 1);
					A_Pain();
					A_facetarget();
					ThrustThingZ(0,30,0,1);
			}
			RFT9 A 2 A_facetarget();
			RFT9 A 1 A_Recoil(15);
			RFT9 ABCDE 3;
			Goto FallingAfterImpact;
		FallingAfterImpact:
			RFT9 F 1 {
				A_GiveInventory ("FallingHeight", 1);
				A_CheckFloor ("GetUp");
			}
			NULL A 0 A_JumpIf (momz == 0, "GetUp");
			Loop;
		
		GetUp:
			TNT1 A 0 A_SpawnItem("LargeMassWaterImpact");
			TNT1 A 0 A_JumpIfInventory ("FallingHeight", 5, "FallingDie");
			TNT1 A 0 {
				A_TakeInventory("FallingHeight", 100);
				A_Stop();
				A_ChangeFlag("SOLID", 0);
				A_ChangeFlag("GHOST", 1);
				A_PlaySound("BODYF",6);
			}
			RFT9 GGGGGGGGGG 5 A_JumpIf(momz < 0, "FallingAfterImpact");
			RFT9 H 10 {
				A_TakeInventory("IsDown", 1);
				A_ChangeFlag("FORCEXYBILLBOARD", 0);
				A_ChangeFlag("SOLID", 1);
			}
			Goto See;
		 
		FallingDie:
			TNT1 A 0 {
				A_ChangeFlag("COUNTKILL", 0);
				A_ChangeFlag("SHOOTABLE", 0);
				A_SpawnItem("SplatteredSmall");
			}
			TNT1 A 0 A_JumpIfInventory ("FallingHeight", 15, "Death.Stomp");
			TNT1 A 0 A_JumpIfInventory ("FallingHeight", 10, "FallingSuperDeath");
			TNT1 A 0 A_JumpIfInventory ("FallingHeight", 5, "FallingDeath");
		FallingDeath:
			TNT1 A 0 {
				A_Scream();
				A_CustomMissile ("PB_XDeath1", 32, 0, random (0, 360), 2, random (50, 130));
				A_CustomMissile ("PB_XDeath1", 32, 0, random (0, 360), 2, random (50, 130));
				A_CustomMissile ("PB_XDeath1", 32, 0, random (0, 360), 2, random (50, 130));
				A_CustomMissile ("PB_XDeath1", 32, 0, random (0, 360), 2, random (50, 130));
				}
			RFT9 E 2;
			RFT9 F 2 {
				A_PlaySound("BODYF",6);
				A_SpawnItem ("GrowingBloodPool");
				A_SpawnItem ("Dead_AR_ZombieMan1");
			}
			Stop;
		FallingSuperDeath:
			TNT1 A 0 A_XScream();
			Goto Death.ExplosiveImpact+1;
				
		Pain.Taunt:
			TNT1 A 0 A_JumpIfInventory("Enraged", 1, "Missile");
			RFTR B 1 {
				A_Pain();
				A_ChangeFlag("FASTER", 1);
				A_ChangeFlag("MISSILEMORE", 1);
				A_ChangeFlag("MISSILEEVENMORE", 1);
				A_PlaySound("grunt/sight");
				A_FaceTarget();
				A_GiveInventory("Enraged", 1);
				}
			RFTR B 9;
			Goto Missile;
		Pain.Siphon:
			RFTR G 1 {
				A_SpawnItemEx("RedLightning_Small", random (-12, 12), random (-12, 12), random (16, 52), 0, 0);
				A_SpawnItemEx("RedLightning_Small", random (-12, 12), random (-12, 12), random (16, 52), 0, 0);
				A_SpawnItemEx("RedLightning_Small", random (-12, 12), random (-12, 12), random (16, 52), 0, 0);
				A_FaceTarget();
				A_GiveToTarget("HealthBonus",4);
			}
			RFTR G 5 {
				A_FaceTarget();
				A_Pain();
				}
			Goto See;
		Possession:
			RFTR G 3 {
				A_SetInvulnerable();
				A_Pain();
				}
			"####" "#" 35 ACS_NamedExecuteAlways("Pos - Flicker effect");
			TNT1 A 0 A_UnSetInvulnerable();
			Goto See;
	
		Pain.Stun:
			RFTR G 1 A_Pain();
			RFTR GGGGGGGGGG 3 A_SpawnItemEx ("StunElectrocute", random (-12, 12), random (-12, 12),  random (16, 52), 0, 0);
			RFTR G 1 A_Pain();
			RFTR GGGGGGGGGG 3 A_SpawnItemEx ("StunElectrocute", random (-12, 12), random (-12, 12),  random (16, 52), 0, 0);
			RFTR G 1 A_Pain();
			RFTR GGGGGGGGGG 3 A_SpawnItemEx ("StunElectrocute", random (-12, 12), random (-12, 12),  random (16, 52), 0, 0);
			RFTR G 1 A_Pain();
			RFTR GGGGGGGGGG 3 A_SpawnItemEx ("StunElectrocute", random (-12, 12), random (-12, 12),  random (16, 52), 0, 0);
			RFTR G 1 A_Pain();
			RFTR GGGGGGGGGG 3 A_SpawnItemEx ("StunElectrocute", random (-12, 12), random (-12, 12),  random (16, 52), 0, 0);
			RFTR G 1 A_Pain();
			Goto See;
			
		Death:
			TNT1 A 0 A_JumpIfInventory ("IsDown", 1, "Death.Down");
			TNT1 A 0 A_Jump(48, "Death.ARm");
			TNT1 A 0 A_Jump(132, "Death2");
			RFTR H 5 A_Stop();
			RFTR I 5 A_Scream();
			RFTR J 5 A_NoBlocking();
			RFTR K 5;
			TNT1 A 0 A_PlaySound("BODYF",6);
			TNT1 A 0 A_SpawnItem("Dead_AR_ZombieMan_RFTRL");
			Stop;
			
		Death2:
			RFT2 A 5;
			RFT2 B 5 A_Scream();
			RFT2 C 5 A_NoBlocking();
			RFT2 DE 5;
			TNT1 A 0 A_PlaySound("BODYF",6);
			TNT1 A 0 A_SpawnItem ("Dead_AR_ZombieMan1");
			Stop;
			
		Death.Arm:
			TNT1 A 0 A_CustomMissile ("XDeathArm1", 35, 0, random (0, 360), 2, random (0, 160));
			TNT1 AA 0 A_CustomMissile ("XDeath2", 35, 0, random (0, 360), 2, random (0, 160));
			TNT1 AAA 0 A_CustomMissile ("MuchBlood2", 35, 0, random (0, 360), 2, random (0, 160));
			RFT6 A 10 A_Scream();
			TNT1 A 0 A_NoBlocking();
			TNT1 A 0 A_PlaySound("BODYF",6);
			TNT1 A 0 A_SpawnItem ("DyingARZombiemanZombiemanNoArm");
			Stop;
	}
}