class Zombie_Man_Friendly : PB_ZombieMan
{
	Default
	{
		+FRIENDLY;
	}
}


class DeadZombieman1: PB_CurbstompedMarine Replaces DeadZombieman
{
	States
    {
    Spawn:
        POSS L -1;
        Stop;
	Raise:
		TNT1 A 2 A_CustomMissile ("RealFlameTrailsSmall", 6, 0, random (0, 360), 2, random (70, 110));
		TNT1 A 0 A_SpawnItem("PentagramSpawner", 0, 60);
		TNT1 A 2 A_CustomMissile ("RealFlameTrailsSmall", 6, 0, random (0, 360), 2, random (70, 110));
		TNT1 A 0 A_SpawnItem("PentagramSpawner", 0, 60);
		TNT1 A 2 A_CustomMissile ("RealFlameTrailsSmall", 6, 0, random (0, 360), 2, random (70, 110));
		TNT1 A 0 A_SpawnItem("PentagramSpawner", 0, 60);
		TNT1 A 0 A_SpawnItem("TeleportFog");
		TNT1 A 0 A_NoBlocking();
        TNT1 A 0 A_SpawnItem ("PB_ZombieMan");
		Stop;
		
	Pain.Kick:
	Pain.Fatality:
	Pain.ExtremePunches:
	Pain.ExplosiveImpact:
	Pain.Shotgun:
		 TNT1 A 0 A_ChangeFlag("NOPAIN", 1);
         TNT1 A 0 ThrustThingZ(0,30,0,1);
		 ID11 E 6;
         ID11 F 4;
		 TNT1 A 0 A_ChangeFlag("NOPAIN", 0);
         Goto Spawn;
		 
	Death:
		TNT1 A 0 A_Jump(256, "Death1", "Death2");
	Death1:
	    TNT1 A 0 A_NoBlocking();
		TNT1 AA 0 A_CustomMissile ("PB_XDeath1", 15, 0, random (0, 360), 2, random (0, 180));
		TNT1 A 0 A_CustomMissile ("PB_XDeathArm1", 15, 0, random (0, 360), 2, random (0, 180));
		TNT1 AAAA 0 A_CustomMissile ("PB_BloodMist", 15, 0, random (0, 360), 2, random (0, 180));
        TNT1 A 0 A_SpawnItem ("DeadZombieMan_NoArm");
		Stop;
	Death2:
	    TNT1 A 0 A_NoBlocking();
		TNT1 AA 0 A_CustomMissile ("PB_XDeath1", 15, 0, random (0, 360), 2, random (0, 180));
		TNT1 A 0 A_CustomMissile ("PB_XDeathZombieLeg", 15, 0, random (0, 360), 2, random (0, 180));
		TNT1 AAAA 0 A_CustomMissile ("PB_BloodMist", 15, 0, random (0, 360), 2, random (0, 180));
        TNT1 A 0 A_SpawnItem ("DeadZombieMan_NoLeg");
		Stop;
		
	Crush:
		TNT1 AAAA 0 bright A_CustomMissile ("PB_XDeath1", 5, 0, random (0, 360), 2, random (30, 180));
		TNT1 AA 0 bright A_CustomMissile ("PB_XDeath2", 55, 0, random (0, 360), 2, random (30, 180));
		TNT1 AA 0 bright A_CustomMissile ("PB_XDeath4", 55, 0, random (0, 360), 2, random (30, 180));
		TNT1 A 0 A_SpawnItem ("GrowingBloodPool");
		TNT1 A 0 A_SpawnItem ("CrushedRemains");
		TNT1 A 0 A_XScream();
        POSC A -1;
		Stop;
    }
}

class ZombiemanTorso: PB_CurbstompedMarine
{
	Default
	{
		Radius 12;
		Height 12;
		Scale 1.0;
		Mass 800;
		damagefactor "Crush", 50.0;
		damagefactor "Blood", 0.0;
		damagefactor "Trample", 0.0;
		+NOPAIN;
		+CORPSE;
	}
    States
    {
		 Spawn:
			BLUD C 0 {
				A_Recoil(3);
				ThrustThing(random(0,255),random(1,5));
				ThrustThingZ(0,random(0,50),random(0,1),0);
				A_SetInvulnerable();
			}
			GORX A 10;
			TNT1 A 0 A_UnSetInvulnerable();
			GORX A -1;
			Stop;
		Crush:
			TNT1 AAAAAAAAAAAAAAAAAAAAAAAAA 0 A_CustomMissile ("PB_SquirtingBloodTrail", 0, 0, random (0, 360), 2, random (0, 360));
			TNT1 A 0 A_PlaySound("misc/xdeath4");
			POSC A 5;
			POSC A -1;
			Stop;
		Raise:
			TNT1 A 2 {
				A_CustomMissile ("RealFlameTrailsSmall", 6, 0, random (0, 360), 2, random (70, 110));
				A_SpawnItem("PentagramSpawner", 0, 60);
				A_SpawnItem("PentagramSpawner", 0, 60);
				A_SpawnItem("TeleportFog");
				A_NoBlocking();
				A_SpawnItem ("PB_ZombieMan");
			}
			Stop;
    }
}

class DeadZombieMan_BottomLessActionMovie: ZombiemanTorso
{ 
	Default
	{
		Health 90;
	}
	States
	{
		Spawn:
			BLUD C 0 {
				A_Recoil(3);
				ThrustThing(random(0,255),random(1,5));
				ThrustThingZ(0,random(0,50),random(0,1),0);
			}
			12DG TUVWX 5;
			12DG X -1;
			Stop;
		Crush:
			TNT1 AAAAAAAAAAAAAAAAAAAAAAAAA 0 A_CustomMissile ("PB_SquirtingBloodTrail", 0, 0, random (0, 360), 2, random (0, 360));
			TNT1 A 0 A_PlaySound("misc/xdeath4");
			POSC A -1;
			Stop;
	}
}


Class DeadZombieman1F: DeadZombieman1
{
	States
	{
		Spawn:
			POSS P -1;
			Stop;
	}
}

Class DeadZombieman1FG: DeadZombieman1
{
	States
    {
		Spawn:
			P05D L -1;
			Stop;
	}
}

Class Zombieman_DeathPNDT: DeadZombieman1
{
	States
    {
		Spawn:
			PNDT Z -1;
			Stop;

		Death:
			TNT1 A 0 A_NoBlocking();
			TNT1 AA 0 A_CustomMissile ("PB_XDeath1", 15, 0, random (0, 360), 2, random (0, 180));
			TNT1 A 0 A_CustomMissile ("PB_XDeathArm1", 15, 0, random (0, 360), 2, random (0, 180));
			TNT1 AAAA 0 A_CustomMissile ("PB_BloodMist", 15, 0, random (0, 360), 2, random (0, 180));
			TNT1 A 0 A_SpawnItem ("DeadZombieMan_NoArm3");
			Stop;
	}
}

Class DeadZombieMan_NoArm: ZombiemanTorso
{
	Default
	{
		Health 300;
	}
	States
	{
		Spawn:
			POS3 E -1;
			Stop;
		
		Death:
			TNT1 A 0 A_NoBlocking();
			TNT1 AAAAAA 0 A_CustomMissile ("PB_Intestine", 12, 0, random (0, 360), 2, random (0, 160));
			TNT1 A 0 A_CustomMissile ("PB_XDeathZombiemanHead", 15, 0, random (0, 360), 2, random (0, 180));
			TNT1 AAAAAA 0 A_CustomMissile ("PB_SmallGib", 15, 0, random (0, 360), 2, random (0, 180));
			TNT1 AA 0 A_CustomMissile ("PB_XDeathZombieLeg", 6, 0, random (0, 360), 2, random (0, 90));
			TNT1 A 0 A_SpawnItem("DeadZombiemanPXSXO");
			Stop;
	}
}
		
Class DeadZombieMan_NoArm3: ZombiemanTorso
{

	Default
	{
		Health 300;
	}

	States
	{
		Spawn:
			PND1 Z -1;
			Stop;
		
		Death:
			TNT1 A 0 A_NoBlocking();
			TNT1 AAAAAA 0 A_CustomMissile ("PB_Intestine", 12, 0, random (0, 360), 2, random (0, 160));
			TNT1 A 0 A_CustomMissile ("PB_XDeathZombiemanHead", 15, 0, random (0, 360), 2, random (0, 180));
			TNT1 AAAAAA 0 A_CustomMissile ("PB_SmallGib", 15, 0, random (0, 360), 2, random (0, 180));
			TNT1 A 0 A_SpawnItem("DeadZombieMan_Topless");
			Stop;
	}
}

class DeadZombieMan_NoLeg: DeadZombieMan_NoArm
{
	Default
	{
		Health 300;
	}
	States{
		Spawn:
			POS7 D -1;
			Stop;
		Death:
			TNT1 A 0 A_NoBlocking();
			TNT1 A 0 A_SpawnItem("DeadZombieMan_NoLegBoth", 0, 10);
			TNT1 A 0 A_SpawnItem("PB_MuchBlood", 0, 10);
			TNT1 A 0 A_CustomMissile ("PB_XDeathZombieLeg", 15, 0, random (0, 360), 2, random (0, 180));
			Stop;
    }
}
		 
		 
class DeadZombieMan_NoLegBoth: DeadZombieMan_NoArm
{

	Default
	{
		Health 300;
	}
	States
	{
		Spawn:
			POS8 D -1;
			Stop; 
		
		Death:
			TNT1 A 0 A_NoBlocking();
			TNT1 A 0 A_SpawnItem("RipZombieman", 0, 10);
			TNT1 A 0 A_SpawnItem("MeatDeathSmall", 0, 10);
			Stop;
    }
}


Class DeadZombieMan_NoHead: DeadZombieMan1f
{
	
	Default
	{
		Health 300;
	}
	States
	{
		Spawn:
			POSH F -1;
			Stop;
		Pain.Kick:
		Pain.Fatality:
		Pain.ExtremePunches:
		Pain.ExplosiveImpact:
		Pain.Shotgun:
			 TNT1 A 0 A_ChangeFlag("NOPAIN", 1);
			 TNT1 A 0 ThrustThingZ(0,30,0,1);
			 ID11 E 6;
			 ID11 F 4;
			 TNT1 A 0 A_ChangeFlag("NOPAIN", 0);
			 Goto Spawn;
	}
}

Class DeadZombieMan_NoHeadFront: DeadZombieMan_NoArm
{
	
	Default
	{
		Health 300;
	}
	States
	{

		Spawn:
			ZMAD E -1;
			Stop;
			
		Death:
			TNT1 A 0 A_NoBlocking();
			TNT1 AA 0 A_CustomMissile ("PB_XDeath1", 15, 0, random (0, 360), 2, random (0, 180));
			TNT1 A 0 A_CustomMissile ("PB_XDeathArm1", 15, 0, random (0, 360), 2, random (0, 180));
			TNT1 AAAA 0 A_CustomMissile ("PB_BloodMist", 15, 0, random (0, 360), 2, random (0, 180));
			TNT1 A 0 A_SpawnItem ("DeadZombieman_NoHeadNoArm");
			Stop;
			
		Death.Fatality:
		Death.Melee:
		Death.Kick:
		Death.ExplosiveImpact:
			 TNT1 A 0 {
				A_NoBlocking();
				ThrustThingZ(0,15,0,1);
				A_FaceTarget();
				A_Recoil(1);
			}
			ID11 EF 8;
			TNT1 A 1 A_SpawnItem ("DeadZombieMan1", 5);
			Stop;
	}
}

Class DeadZombieMan_Half: ZombieManTorso
{
	Default
	{
		Mass 300;
		Health 300;
	}
	States
	{
		Spawn:
			POSX E -1;
			Stop;
	}
}
