Class PB_ZombieMan : PB_Monster
{
		Default
		{
		Monster;
		Radius 16;
		Height 56;
		Speed 6;
		FastSpeed 10;
		MaxStepHeight 24;
		MaxDropOffHeight 32;
		Mass 100;
		SeeSound "grunt/sight";
		AttackSound "grunt/attack";
		PainSound "grunt/pain";
		DeathSound "grunt/death";
		ActiveSound "grunt/active";
		BloodType "NashGoreBlood", "NashGoreBlood", "NashGoreBlood";
		Health 60;
		PainChance 200;
		PainChance "Avoid", 50;
		PainChance "Head", 255;
		PainChance "Kick", 255;
		PainChance "Melee", 255;
		PainChance "Taunt", 255;
		PainChance "MonsterKnocked", 255;
		PainChance "ExplosiveImpact", 255;
		PainChance "Trample", 255;
		PainChance "Stun", 255;
		PainChance "Siphon", 255;
		damagefactor "Crush", 5.0;
		damagefactor "GibRemoving", 0.0;
		damagefactor "DontCallTheBaron", 0.0;
		damagefactor "Blood", 0.0; damagefactor "BlueBlood", 0.0; damagefactor "GreenBlood", 0.0;
		damagefactor "Kick", 0.4;
		damagefactor "Shrapnel", 0.4;
		damagefactor "ExplosiveImpact", 0.6;
		damagefactor "killme", 0.0;
		damagefactor "Taunt", 1.0;
		DamageFactor "CauseObjectsToSplash", 0.0;
		damagefactor "SSG", 50.0;
		DropItem "Rifle";
		DropItem "DropedGrenade", 7;
		DropItem "BDPistol";
		Obituary "%o has been gunned down by a Zombie Soldier.";
		+FLOORCLIP;
		+SLIDESONWALLS;
		}
		
		int movement_direction;
		
		void FireProjBulletsMoving()
		{
				A_FaceTarget();
				A_SpawnProjectile("ZombieManTracer", 42, 0, 0, 0);
				A_SpawnProjectile("OrangeLensFlareAlt", 42, 16, 15, 0);
				A_SpawnProjectile("MarineMuzzle1", 34, 6);
				A_SpawnItem ("RifleCaseSpawn", 0, 30,0);
				A_PlaySound("weapons/rifle");
				ThrustThing(angle*256/360+movement_direction, 1, 0, 0);
		}
		void FireProjBullets(){
				A_SpawnProjectile("ZombieManTracer", 32, 0, random(-8, 8), 1, random(-3, 3));
				A_PlaySound("weapons/rifle");
				A_SpawnItem ("RifleCaseSpawn", 0, 30,0);
				}
		
		void A_SmartChase() {
			EnemySightedNew = Level.MapTime;
			if (CheckIfCloser(target, 200)) {
				SetStateLabel("Fallback");
			}
			if (CheckSight(target) == true) {
				EnemySightedOld = Level.MapTime;
				A_TakeInventory("Wandering",1);
				A_Chase();
			}
			else if (abs(EnemySightedNew - EnemySightedOld) < 180) {
				A_Chase();
			}
			else {
				A_GiveInventory("Wandering",1);
				A_Wander();
			}
		}
		
		override void PostBeginPlay() {
			Super.PostBeginPlay(); // call the super function for virtual functions so we don't break shit if GZdoom update.
			HitBoxSpawned = False;
		
		}
		
		override void Tick()
		{
			Super.Tick();
			
			// Update recognition if crouching
			if(self.InStateSequence(self.Curstate, self.ResolveState("Crouching"))) {
				self.Height = 44;
			}
			else {
				self.Height = 56;
			}
			
			//Handle Hitbox system
			HitboxerHandler();
			
		}
		
		States
		{
		
		Spawn:
			TNT1 A 0 {
				A_TakeInventory("ZombiemanAmmo", 20);
				A_GiveInventory("ZombieManAmmo", random(1,10));
				A_GiveInventory("SKZombieman", 1);
				A_GiveInventory("TypeZombieMan", 1);
			}
		Stand:
			PSSS AB 10 A_Look();
			Loop;
		See:
			POSS AABB 2 A_SmartChase();
			TNT1 A 0 A_PlaySound("humans/step");
			POSS CCDD 2 A_SmartChase();
			TNT1 A 0 A_PlaySound("humans/step");
			TNT1 A 0 A_JumpIfInventory("Wandering",1,"LookAround");
			Loop;
		LookAround:
			TNT1 A 0 A_ClearTarget();
			PSSS ABACAD 10 A_Look();
			POSS ABCD 4 A_SmartChase();
			Goto See+2;
		FallBack:
			POSS D 4 {
				A_FaceTarget();
				A_Recoil(2);
				A_PlaySound("humans/step",3);
				return A_Jump(64,"Missile");
			}
			POSS C 4 {
				A_FaceTarget();
				A_Recoil(2);
				return A_Jump(64,"Missile");
			}
			POSS B 4 {
				A_FaceTarget();
				A_Recoil(2);
				A_PlaySound("humans/step",3);
				return A_Jump(64,"Missile");
			}
			POSS A 2 {
				A_FaceTarget();
				A_Recoil(2);
				return A_Jump(64,"Missile");
			}
			POSS D 4 {
				A_FaceTarget();
				A_Recoil(2);
				A_PlaySound("humans/step",3);
				return A_Jump(64,"Missile");
			}
			POSS C 4 {
				A_FaceTarget();
				A_Recoil(2);
				return A_Jump(64,"Missile");
			}
			POSS B 4 {
				A_FaceTarget();
				A_Recoil(2);
				A_PlaySound("humans/step",3);
				return A_Jump(64,"Missile");
			}
			POSS A 4 {
				A_FaceTarget();
				A_Recoil(2);
			}
			Goto Missile;
		
		////////////////
		//Attack Logic// 
		////////////////
		Missile:
			POSS E 6 {
				A_Stop();
				A_FaceTarget();
				return A_CheckLOF("AttackHandler");
				}
			Goto See;
		AttackHandler:
			TNT1 A 0 {
				int chance = (random(1,256));
				
				if((chance > 232) && (CountInv("ZombieManGrenadeCount") < 3)) {return A_Jump(256, "Grenade");}
				if(chance > 200) {return A_Jump(256, "AttackMoving");}
				return A_Jump(256, "Attack1", "Attack2", "Attack3");
			}
		//Standard, 3 round burst attack
		Attack1:
			POSS E 6 A_FaceTarget();
			POSS F 2 BRIGHT FireProjBullets;
			POSS E 2 A_FaceTarget();
			POSS F 2 BRIGHT FireProjBullets;
			POSS E 2 A_FaceTarget();
			POSS F 2 BRIGHT FireProjBullets;
			POSS E 2 {
				A_FaceTarget();
				A_GiveInventory("ZombieManAmmo", 2);
				return A_JumpIfInventory("ZombieManAmmo", 20, "Reload");
				}
			Goto See;
		//Aimed, 4 round burst attack
		Attack2:
			P055 E 6 A_FaceTarget();
			P055 E 2 BRIGHT {
				A_FaceTarget();
				A_SpawnProjectile("ZombieManTracer", 32, 0, random(-4, 4), 1, random(-3, 3));
				A_SpawnProjectile("OrangeLensFlareAlt", 42, 16, 15, 0);
				A_SpawnProjectile("MarineMuzzle1", 39, 4);
				A_SpawnItem ("RifleCaseSpawn", 0, 36,0);
				A_PlaySound("weapons/rifle");
			}
			P055 E 4 A_FaceTarget();
			P055 E 2 BRIGHT {
				A_FaceTarget();
				A_SpawnProjectile("ZombieManTracer", 32, 0, random(-4, 4), 1, random(-3, 3));
				A_SpawnProjectile("OrangeLensFlareAlt", 42, 16, 15, 0);
				A_SpawnProjectile("MarineMuzzle1", 39, 4);
				A_SpawnItem ("RifleCaseSpawn", 0, 36,0);
				A_PlaySound("weapons/rifle");
			}
			P055 E 4 A_FaceTarget();
			P055 E 2 BRIGHT {
				A_FaceTarget();
				A_SpawnProjectile("ZombieManTracer", 32, 0, random(-4, 4), 1, random(-3, 3));
				A_SpawnProjectile("OrangeLensFlareAlt", 42, 16, 15, 0);
				A_SpawnProjectile("MarineMuzzle1", 39, 4);
				A_SpawnItem ("RifleCaseSpawn", 0, 36,0);
				A_PlaySound("weapons/rifle");
			}
			P055 E 4 A_FaceTarget();
			P055 E 2 BRIGHT {
				A_FaceTarget();
				A_SpawnProjectile("ZombieManTracer", 32, 0, random(-4, 4), 1, random(-3, 3));
				A_SpawnProjectile("OrangeLensFlareAlt", 42, 16, 15, 0);
				A_SpawnProjectile("MarineMuzzle1", 39, 4);
				A_SpawnItem ("RifleCaseSpawn", 0, 36,0);
				A_PlaySound("weapons/rifle");
			}
			P055 E 2 {
				A_GiveInventory("ZombieManAmmo", 3);
				return A_JumpIfInventory("ZombieManAmmo", 20, "Reload");
				return A_jump(16, "Missile");
			}
			Goto See;
		// Crouched 4-round burst
		Attack3:
			P055 E 4 A_FaceTarget();
			Crouching:
			P055 F 6 A_FaceTarget();
			P055 F 2 BRIGHT {
				A_SpawnProjectile("ZombieManTracer", 32, 0, random(-4, 4), 1, random(-3, 3));
				A_SpawnProjectile("OrangeLensFlareAlt", 32, 16, 15, 0);
				A_SpawnProjectile("MarineMuzzle1", 32, 4) ;
				A_SpawnItem ("RifleCaseSpawn", 0, 36,0);
				A_PlaySound("weapons/rifle");
			}
			P055 F 3 A_FaceTarget();
			P055 F 2 BRIGHT {
				A_SpawnProjectile("ZombieManTracer", 32, 0, random(-4, 4), 1, random(-3, 3));
				A_SpawnProjectile("OrangeLensFlareAlt", 32, 16, 15, 0);
				A_SpawnProjectile("MarineMuzzle1", 32, 4) ;
				A_SpawnItem ("RifleCaseSpawn", 0, 36,0);
				A_PlaySound("weapons/rifle");
			}
			P055 F 3 A_FaceTarget();
			P055 F 2 BRIGHT {
				A_SpawnProjectile("ZombieManTracer", 32, 0, random(-4, 4), 1, random(-3, 3));
				A_SpawnProjectile("OrangeLensFlareAlt", 32, 16, 15, 0);
				A_SpawnProjectile("MarineMuzzle1", 32, 4) ;
				A_SpawnItem ("RifleCaseSpawn", 0, 36,0);
				A_PlaySound("weapons/rifle");
			}
			P055 F 3 A_FaceTarget();
			P055 F 2 BRIGHT {
				A_SpawnProjectile("ZombieManTracer", 32, 0, random(-4, 4), 1, random(-3, 3));
				A_SpawnProjectile("OrangeLensFlareAlt", 32, 16, 15, 0);
				A_SpawnProjectile("MarineMuzzle1", 32, 4) ;
				A_SpawnItem ("RifleCaseSpawn", 0, 36,0);
				A_PlaySound("weapons/rifle");
			}
			P055 F 4 {
				A_FaceTarget();
				A_GiveInventory("ZombieManAmmo", 5);
				return A_JumpIfInventory("ZombieManAmmo", 20, "Reload");
				return A_jump(24, "Attack3");
			}
			DoneCrouching:
			P055 E 6 A_FaceTarget();
			Goto See;
		AttackMoving:
			POSS E 2 {
				int chance = (random(1,4));
				if(chance == 1) { movement_direction = 192;} //Move Left
				if(chance == 2) { movement_direction = 64;} //Move Right
				if(chance == 3) { movement_direction = 128;} //Move Back
				if(chance == 4) { movement_direction = 0;} //Move Back
			}
			P055 AA 2 {
				A_FaceTarget();
				ThrustThing(angle*256/360+movement_direction, 1, 0, 0);
			}
			P055 B 3 BRIGHT FireProjBulletsMoving;
			P055 CC 2 {
				A_FaceTarget();
				ThrustThing(angle*256/360+movement_direction, 1, 0, 0);
			}
			P055 D 3 BRIGHT FireProjBulletsMoving;
			P055 AA 2 {
				A_FaceTarget();
				ThrustThing(angle*256/360+movement_direction, 1, 0, 0);
			}
			P055 B 3 BRIGHT FireProjBulletsMoving;
			P055 CC 2 {
				A_FaceTarget();
				ThrustThing(angle*256/360+movement_direction, 1, 0, 0);
			}
			P055 D 3 BRIGHT FireProjBulletsMoving;
			POSS E 4 {
				A_Stop();
				A_GiveInventory("ZombieManAmmo", 4);
				return A_JumpIfInventory("ZombieManAmmo", 20, "Reload");
				return A_jump(12, "Missile");
			}
			Goto See;
			
		Grenade:
			TNT1 A 0 A_JumpIfCloser(500, 1);
			Goto Attack1;
			TNT1 A 0 A_JumpIfCloser(90, "Attack1");
		ThrowGrenade:
			POSG A 6 {
				A_FaceTarget(90,45);
				A_PlaySound("OPNGRN", 1);
			}
			POSG A 6 A_FaceTarget(90,45);
			POSG B 6 {
				A_FaceTarget(90,45);
				A_DropAdjust("EnemyThrownGrenade","EnemyThrownGrenade",0,18,28);
				A_GiveInventory("ZombieManGrenadeCount", 1);
				A_PlaySound("THRGRN", 1);
			}
			POSG B 6;
        Goto See;
		
		Reload:
			POSS E 4 {
				A_TakeInventory("ZombieManAmmo", 20);
				A_SpawnProjectile("EmptyClipSpawn", 38, 0, random(-11, 11), 0);
				A_PlaySound("Reload");
				}
			ID12 ABCD 10;
			POSS A 10;
			Goto See;
			
		
		////////////////
		//Pain Logic// 
		////////////////
		Pain:
			TNT1 A 0 A_JumpIfInventory ("IsDown", 1, "Downed");
			POSS G 6 A_Pain();
			Goto See;
        Downed:
			ID11 F 6 A_Pain();
			Goto GetUp;
		Pain.Kick:
			TNT1 A 0 A_JumpIfInventory ("IsDown", 1, "Pain");
			POS4 U 1 {
					A_ChangeFLag("NODROPOFF", 0);
					A_ChangeFlag("FORCEXYBILLBOARD", 1);
					A_TakeInventory("SKZombieman", 1);
					A_GiveInventory("IsDown", 1);
					A_Pain();
					A_facetarget();
					ThrustThingZ(0,30,0,1);
			}
			POS4 U 2 A_facetarget();
			POS4 U 1 A_Recoil(15);
			POS4 UVWXY 3;
			Goto FallingAfterImpact;
		FallingAfterImpact:
			ID11 F 1 {
				A_GiveInventory ("FallingHeight", 1);
				A_CheckFloor ("GetUp");
			}
			NULL A 0 A_JumpIf (momz == 0, "GetUp");
			Loop;
		
		
		GetUp:
			TNT1 A 0 A_SpawnItem("LargeMassWaterImpact");
			TNT1 A 0 A_JumpIfInventory ("FallingHeight", 5, "FallingDie");
			TNT1 A 0 {
				A_TakeInventory("FallingHeight", 100);
				A_Stop();
				A_ChangeFlag("SOLID", 0);
				A_ChangeFlag("GHOST", 1);
				A_PlaySound("BODYF",6);
			}
			ID11 RRRRRRRRRR 5 A_JumpIf(momz < 0, "FallingAfterImpact");
			ID11 Q 10 {
				A_TakeInventory("IsDown", 1);
				A_ChangeFlag("FORCEXYBILLBOARD", 0);
				A_ChangeFlag("SOLID", 1);
			}
			Goto See;
		 
		FallingDie:
			TNT1 A 0 {
				A_ChangeFlag("COUNTKILL", 0);
				A_ChangeFlag("SHOOTABLE", 0);
				A_SpawnItem("SplatteredSmall");
			}
			TNT1 A 0 A_JumpIfInventory ("FallingHeight", 15, "Death.Stomp");
			TNT1 A 0 A_JumpIfInventory ("FallingHeight", 10, "FallingSuperDeath");
			TNT1 A 0 A_JumpIfInventory ("FallingHeight", 5, "FallingDeath");
		FallingDeath:
			TNT1 A 0 {
				A_Scream();
				A_SpawnProjectile ("XDeath1", 32, 0, random (0, 360), 2, random (50, 130));
				A_SpawnProjectile ("XDeath1", 32, 0, random (0, 360), 2, random (50, 130));
				A_SpawnProjectile ("XDeath1", 32, 0, random (0, 360), 2, random (50, 130));
				A_SpawnProjectile ("XDeath1", 32, 0, random (0, 360), 2, random (50, 130));
				}
			ID11 E 2;
			ID11 F 2 {
				A_PlaySound("BODYF",6);
				A_SpawnItem ("GrowingBloodPool");
				A_SpawnItem ("DeadZombieman1");
			}
			Stop;
		FallingSuperDeath:
			TNT1 A 0 A_XScream();
			Goto Death.ExplosiveImpact+1;
				
		Pain.Taunt:
			TNT1 A 0 A_JumpIfInventory("Enraged", 1, "Missile");
			POSS B 1 {
				A_Pain();
				A_ChangeFlag("FASTER", 1);
				A_ChangeFlag("MISSILEMORE", 1);
				A_ChangeFlag("MISSILEEVENMORE", 1);
				A_PlaySound("grunt/sight");
				A_FaceTarget();
				A_GiveInventory("Enraged", 1);
				}
			POSS B 9;
			Goto Missile;
		Pain.Siphon:
			POSS G 1 {
				A_SpawnItemEx("RedLightning_Small", random (-12, 12), random (-12, 12), random (16, 52), 0, 0);
				A_SpawnItemEx("RedLightning_Small", random (-12, 12), random (-12, 12), random (16, 52), 0, 0);
				A_SpawnItemEx("RedLightning_Small", random (-12, 12), random (-12, 12), random (16, 52), 0, 0);
				A_FaceTarget();
				A_GiveToTarget("HealthBonus",4);
			}
			POSS G 5 {
				A_FaceTarget();
				A_Pain();
				}
			Goto See;
		Possession:
			POSS G 3 {
				A_SetInvulnerable();
				A_Pain();
				}
			"####" "#" 35 ACS_NamedExecuteAlways("Pos - Flicker effect");
			TNT1 A 0 A_UnSetInvulnerable();
			Goto See;
	
		Pain.Stun:
			POSS G 1 A_Pain();
			POSS GGGGGGGGGG 3 A_SpawnItemEx ("StunElectrocute", random (-12, 12), random (-12, 12),  random (16, 52), 0, 0);
			POSS G 1 A_Pain();
			POSS GGGGGGGGGG 3 A_SpawnItemEx ("StunElectrocute", random (-12, 12), random (-12, 12),  random (16, 52), 0, 0);
			POSS G 1 A_Pain();
			POSS GGGGGGGGGG 3 A_SpawnItemEx ("StunElectrocute", random (-12, 12), random (-12, 12),  random (16, 52), 0, 0);
			POSS G 1 A_Pain();
			POSS GGGGGGGGGG 3 A_SpawnItemEx ("StunElectrocute", random (-12, 12), random (-12, 12),  random (16, 52), 0, 0);
			POSS G 1 A_Pain();
			POSS GGGGGGGGGG 3 A_SpawnItemEx ("StunElectrocute", random (-12, 12), random (-12, 12),  random (16, 52), 0, 0);
			POSS G 1 A_Pain();
			Goto See;
		Death:
			TNT1 A 0 A_Jump(32, "Death.Arm");
			TNT1 A 0 A_Jump(18, "Death.Rare");
			TNT1 A 0 A_Jump(129, "DeathOther", "DeathOther2");
			TNT1 A 0 A_Jump(128, "DeathMirror");
			TNT1 A 0 {
				A_SpawnItem("Zombieman_DeathMinorLeg");
				A_Scream();
				A_NoBlocking();
				}
			Stop;
		
		DeathOther:
			TNT1 A 0 {
				A_Scream();
				A_NoBlocking();
			}
			PNDT Z 1 A_SpawnItem("ZombieMan_DeathOther");
			Stop;
		DeathOther2:
			TNT1 A 0 {
				A_Scream();
				A_NoBlocking();
			}
			PSSR A 1 A_SpawnItem("ZombieMan_DeathOther2");
			Stop;
		Death.Rare:
			TNT1 A 0 {
				A_FaceTarget();
				A_Scream();
				A_NoBlocking();
			}
			12DG A 1 A_SpawnItem("ZombieMan_DeathActionMovie");
			Stop;
		
		DeathMirror:
			TNT1 A 0 {
				A_NoBlocking();
				A_Scream();
			}
			POSS R 6 A_SpawnItem("Zombieman_DeathMinorLeg");
			Stop;

		 Death.Arm:
			TNT1 A 0 {
				A_CustomMissile ("XDeathArm1", 35, 0, random (0, 360), 2, random (0, 160));
				A_CustomMissile ("MuchBlood2", 35, 0, random (0, 360), 2, random (0, 160));
				A_NoBlocking();
				A_Scream();
				}
			ZZD1 I 10;
			TNT1 A 0 A_SpawnItemEx ("DyingZombiemanNoArm",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
			Stop;
		
		Death.Head:
			TNT1 A 0 A_JumpIfInTargetInventory("HasIncendiaryWeapon",1,"Death.Incinerate");
			TNT1 A 0 A_JumpIfInTargetInventory("HasPlasmaWeapon", 1, "Death.Plasma");
			TNT1 A 0 A_JumpIfInTargetInventory("HasCutingWeapon", 1, "Death.Decaptate");
			TNT1 A 0 A_JumpIfInTargetInventory("RandomHeadExploder", 1, "HeadExplode");
			TNT1 A 0 A_JumpIfHealthLower(-200, "HeavyHead");
			TNT1 A 0 A_JumpIfHealthLower(-80, "HeadExplode");
		HeadMinor:
			TNT1 A 0 A_Playsound("MinorHeadshot");
			TNT1 A 0 A_Jump (256, "DeathMinorhead1", "DeathMinorhead2", "DeathMinorhead3", "DeathMinorhead4");
		DeathMinorHead1:
			TNT1 A 0 A_Scream();
			TNT1 A 0 A_NoBlocking();
			TNT1 A 0 A_SpawnItem("ZombieMan_DeathHeadMinor");
			Stop;
		DeathMinorHead2:
			TNT1 A 0 A_NoBlocking();
			TNT1 A 0 A_SpawnItem("DyingZombiemanLostTeeth");
			Stop;
		DeathMinorhead3:
			TNT1 A 0 {
				A_Pain();
				A_FaceTarget();
				A_SpawnProjectile ("Brains4Green", random (45, 55), random (5, -5), random (170, 190), 2, random (-10, 10));
				A_SpawnProjectile ("SmallBrainPieceFast", random (45, 55), random (5, -5), random (170, 190), 2, random (-10, 10));
				A_SpawnProjectile ("SmallBrainPiece", 50, 0, random (0, 360), 2, random (0, 160));
				A_SpawnProjectile ("SuperWallRedBlood", 46, 0, random (170, 190), 2, random (0, 40));
			}
			12DG J 2 {
				A_NoBlocking();
				A_SpawnProjectile ("MuchBlood2", 40, 0, random (0, 360), 2, random (0, 160));
				A_SpawnItem("ZombieMan_DeathMinorHead4");
			}
			Stop;
		DeathMinorhead4:
			PXS3 A 1 {
				A_Pain();
				A_FaceTarget();
				A_SpawnProjectile ("Brains4Green", random (45, 55), random (5, -5), random (170, 190), 2, random (-10, 10));
				A_SpawnProjectile ("SmallBrainPieceFast", random (45, 55), random (5, -5), random (170, 190), 2, random (-10, 10));
				A_SpawnProjectile ("SmallBrainPiece", 50, 0, random (0, 360), 2, random (0, 160));
				A_SpawnProjectile ("SuperWallRedBlood", 46, 0, random (170, 190), 2, random (0, 40));
				A_SpawnProjectile ("MuchBlood2", 40, 0, random (0, 360), 2, random (0, 160));
			}
			TNT1 A 0 A_SpawnItem("ZombieMan_DeathMinorHead5");
			Stop;
					
		HeadExplode:
			TNT1 A 0 {
				A_PlaySound("gore/headshot", CHAN_BODY);
				A_SpawnItem("ZombiemanHeadExplode", 0, 40);
				A_XScream();
				A_SpawnItem("BloodSplasher2");
				A_NoBlocking();
			}
			ZMAD AAAAABBBBBBBBBBCCCCC 2 A_SpawnProjectile ("Brutal_LiquidBlood2", 30, 0, random (0, 360), 2, random (60, 120));
			TNT1 A 0 {
				A_SpawnItem("GrowingBloodPool");
				A_PlaySoundEx("BODYF","Auto");
				}
			ZMAD DDDDEEEEEEEEEEEEEEEE 2 A_SpawnProjectile ("Brutal_LiquidBlood2", 10, 0, random (0, 360), 2, random (10, 40));
			TNT1 A 0 A_SpawnItem ("DeadZombieman_NoHeadFront");
			Stop;
		HeavyHead:	
			TNT1 A 0 A_ClearTarget();
			POSL G 2 {
				A_SpawnItem("ZombiemanHeadExplode", 0, 40);
				A_SpawnItem("BloodSplasher2");
				A_ChangeFlag("NOBLOCKMONST", 1);
				A_PlaySound("misc/xdeath4");
				A_FaceTarget();
				A_XScream();
				A_NoBlocking();
				ThrustThingZ(0,35,0,1);
				}
			POSL G 2 A_FaceTarget();
			POSL G 2 A_Recoil(10);
			POSL HIJK 6;
			TNT1 A 0 A_PlaySound("BODYF",6);
			POSL LLLLLLLLLLLLLLLLLLL 4 A_SpawnProjectile ("Brutal_LiquidBlood2", 10, 0, random (0, 360), 2, random (10, 40));
			POSL L 1 A_SpawnItem ("DeadZombieman_HeavyHead");
			Stop;
			
     Death.Leg:
		TNT1 A 0 A_JumpIfHealthLower(-100,"DoubleLegRemove");
		TNT1 A 0 A_JumpIfHealthLower(-20, "LegRemove");
		TNT1 A 0 {
			A_Scream();
			A_NoBlocking();
			}
		POSL MO 6;
		POSS K 6 ;
		TNT1 A 0 {
			A_PlaySound("BODYF",6);
			A_SpawnItem("DeadZombieman1");
			A_SpawnItem ("GrowingBloodPool");
			}
		Stop;
	DoubleLegRemove:
		TNT1 A 0 {
			A_Scream();
			A_NoBlocking();
			A_SpawnProjectile ("XDeathZombieLeg", 15, 0, random (0, 360), 2, random (0, 160));
			A_SpawnProjectile ("XDeathZombieLeg", 15, 0, random (0, 360), 2, random (0, 160));
			A_SpawnProjectile ("XDeath1", 15, 0, random (0, 360), 2, random (0, 160));
			A_SpawnProjectile ("XDeath1", 15, 0, random (0, 360), 2, random (0, 160));
			A_SpawnProjectile ("XDeath1", 15, 0, random (0, 360), 2, random (0, 160));
			A_SpawnProjectile ("XDeath2b", 15, 0, random (0, 360), 2, random (0, 160));
			A_SpawnProjectile ("XDeath2b", 15, 0, random (0, 360), 2, random (0, 160));
			ThrustThingZ(0,50,0,1);
			}
		POS8 ABC 3;
		POS8 D 4;
		TNT1 A 0 {
			A_SpawnItem ("GrowingBloodPool");
			A_PlaySound("BODYF",6);
			A_SpawnItem ("DeadZombieMan_NoLegBoth");
		}
		Stop;
	LegRemove:
		TNT1 A 0 A_Jump(64, "LegRemoveRare");
        TNT1 A 0 {
			A_SpawnProjectile ("MuchBlood2", 15, 0, random (0, 360), 2, random (0, 160));
			A_SpawnProjectile ("XDeath1", 15, 0, random (0, 360), 2, random (0, 160));
			A_SpawnProjectile ("XDeathZombieLeg", 35, 0, random (0, 360), 2, random (0, 160));
			A_SpawnItem ("GrowingBloodPool");
			A_NoBlocking();
			A_Scream();
			A_SpawnItemEx ("ZombiemanGotHisLegBlowed",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
			}
        Stop;
	LegRemoveRare:
        TNT1 A 0 {
			A_SpawnProjectile ("MuchBlood2", 15, 0, random (0, 360), 2, random (0, 160));
			A_SpawnProjectile ("XDeath1", 15, 0, random (0, 360), 2, random (0, 160));
			A_SpawnProjectile ("XDeathZombieLeg", 35, 0, random (0, 360), 2, random (0, 160));
			A_SpawnItem ("GrowingBloodPool");
			A_NoBlocking();
			A_Scream();
			A_SpawnItemEx ("ZombiemanSacilol",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
		}
        Stop;

		Death.ExplosiveImpact:
			TNT1 A 1 {
					A_ChangeFLag("NODROPOFF", 0);
					ThrustThingZ(0,30,0,1);
					A_FaceTarget();
			}
			TNT1 A 0 A_JumpIf(angle < 180, "IsFacingNorth");
			TNT1 A 0 A_JumpIf(velx < 0, "BlownAwayRight");
			TNT1 A 0 A_JumpIf(velx > 0, "BlownAwayLeft");
			Goto XDeath;
		IsFacingNorth:
			TNT1 A 0 A_JumpIf(velx > 0, "BlownAwayRight");
			TNT1 A 0 A_JumpIf(velx < 0, "BlownAwayLeft");
			Goto XDeath;
		
		BlownAwayLeft:	
			//TNT1 A 0 //A_Jump(96, "Death.Landmine")
			TNT1 A 0 {
				A_Xscream();
				A_NoBlocking();
				ThrustThingZ(0,30,0,1);
				A_SpawnProjectile ("XDeath1", 32, 0, random (0, 360), 2, random (0, 160));
				A_SpawnProjectile ("XDeath2", 32, 0, random (0, 360), 2, random (0, 160));
				A_SpawnProjectile ("Brains2", 50, 0, random (0, 360), 2, random (0, 160));
				A_SpawnProjectile ("Brains3", 50, 0, random (0, 360), 2, random (0, 160));
				A_SpawnProjectile ("Brains4Green", 50, 0, random (0, 360), 2, random (0, 160));
				A_SpawnProjectile ("Brains5", 50, 0, random (0, 360), 2, random (0, 160));
				A_SpawnProjectile ("SmallBrainPieceFast", random (45, 55), random (5, -5), random (170, 190), 2, random (-10, 10));
				A_SpawnProjectile ("SmallBrainPieceFast", random (45, 55), random (5, -5), random (170, 190), 2, random (-10, 10));
				A_SpawnProjectile ("SmallBrainPieceFast", random (45, 55), random (5, -5), random (170, 190), 2, random (-10, 10));
				A_SpawnProjectile ("SmallBrainPieceFast", random (45, 55), random (5, -5), random (170, 190), 2, random (-10, 10));
				A_SpawnProjectile ("SmallBrainPiece", random (45, 55), random (5, -5), random (170, 190), 2, random (-10, 10));
				A_SpawnProjectile ("SmallBrainPiece", random (45, 55), random (5, -5), random (170, 190), 2, random (-10, 10));
				A_SpawnProjectile ("SmallBrainPiece", random (45, 55), random (5, -5), random (170, 190), 2, random (-10, 10));
				A_SpawnProjectile ("SmallBrainPiece", random (45, 55), random (5, -5), random (170, 190), 2, random (-10, 10));
				A_SpawnProjectile ("SuperWallRedBlood", 46, 0, random (170, 190), 2, random (0, 40));
				A_SpawnProjectile ("SuperWallRedBlood", 46, 0, random (170, 190), 2, random (0, 40));
				A_SpawnProjectile ("XDeathArm1", 35, 0, random (0, 360), 2, random (0, 160));
				A_SpawnProjectile ("XDeath3", 40, 0, random (0, 360), 2, random (0, 160));
				A_SpawnProjectile ("XDeathZombieLeg", 32, 0, random (0, 360), 2, random (0, 160));
				A_SpawnProjectile ("XDeath1", 40, 0, random (0, 360), 2, random (0, 160));
				A_SpawnProjectile ("XDeath1", 40, 0, random (0, 360), 2, random (0, 160));
				A_SpawnProjectile ("BloodMistLarge", 40, 0, random (0, 360), 2, random (20, 90));
				A_SpawnProjectile ("BloodMistLarge", 40, 0, random (0, 360), 2, random (20, 90));
				A_SpawnProjectile ("BloodMistLarge", 40, 0, random (0, 360), 2, random (20, 90));
			}
			PXSX GHIJKLM 3 A_SpawnProjectile ("Brutal_FlyingBlood", 0, 0, 0, 2, 90);
			TNT1 A 0 A_CheckFloor("Land8473");
			PXSX GHIJKLMGHIJKLM 5 A_CheckFloor("Land8473");
		Land8473:
			TNT1 A 0 {
				A_Stop();
				A_SpawnItem("GrowingBloodPool");
				A_SpawnItem("DeadZombiemanPXSXO");
				}
			Stop;
		
	BlownAwayRight:
			//TNT1 A 0 //A_Jump(96, "Death.ExtremePunches")
			TNT1 A 0 {
				A_Xscream();
				A_NoBlocking();
				ThrustThingZ(0,30,0,1);
				A_SpawnProjectile ("XDeath1", 32, 0, random (0, 360), 2, random (0, 160));
				A_SpawnProjectile ("XDeath2", 32, 0, random (0, 360), 2, random (0, 160));
				A_SpawnProjectile ("Brains2", 50, 0, random (0, 360), 2, random (0, 160));
				A_SpawnProjectile ("Brains3", 50, 0, random (0, 360), 2, random (0, 160));
				A_SpawnProjectile ("Brains4Green", 50, 0, random (0, 360), 2, random (0, 160));
				A_SpawnProjectile ("Brains5", 50, 0, random (0, 360), 2, random (0, 160));
				A_SpawnProjectile ("SmallBrainPieceFast", random (45, 55), random (5, -5), random (170, 190), 2, random (-10, 10));
				A_SpawnProjectile ("SmallBrainPieceFast", random (45, 55), random (5, -5), random (170, 190), 2, random (-10, 10));
				A_SpawnProjectile ("SmallBrainPieceFast", random (45, 55), random (5, -5), random (170, 190), 2, random (-10, 10));
				A_SpawnProjectile ("SmallBrainPieceFast", random (45, 55), random (5, -5), random (170, 190), 2, random (-10, 10));
				A_SpawnProjectile ("SmallBrainPiece", random (45, 55), random (5, -5), random (170, 190), 2, random (-10, 10));
				A_SpawnProjectile ("SmallBrainPiece", random (45, 55), random (5, -5), random (170, 190), 2, random (-10, 10));
				A_SpawnProjectile ("SmallBrainPiece", random (45, 55), random (5, -5), random (170, 190), 2, random (-10, 10));
				A_SpawnProjectile ("SmallBrainPiece", random (45, 55), random (5, -5), random (170, 190), 2, random (-10, 10));
				A_SpawnProjectile ("SuperWallRedBlood", 46, 0, random (170, 190), 2, random (0, 40));
				A_SpawnProjectile ("SuperWallRedBlood", 46, 0, random (170, 190), 2, random (0, 40));
				A_SpawnProjectile ("XDeathArm1", 35, 0, random (0, 360), 2, random (0, 160));
				A_SpawnProjectile ("XDeath3", 40, 0, random (0, 360), 2, random (0, 160));
				A_SpawnProjectile ("XDeathZombieLeg", 32, 0, random (0, 360), 2, random (0, 160));
				A_SpawnProjectile ("XDeath1", 40, 0, random (0, 360), 2, random (0, 160));
				A_SpawnProjectile ("XDeath1", 40, 0, random (0, 360), 2, random (0, 160));
				A_SpawnProjectile ("BloodMistLarge", 40, 0, random (0, 360), 2, random (20, 90));
				A_SpawnProjectile ("BloodMistLarge", 40, 0, random (0, 360), 2, random (20, 90));
				A_SpawnProjectile ("BloodMistLarge", 40, 0, random (0, 360), 2, random (20, 90));
			}
			PXS2 GHIJKLM 3 A_SpawnProjectile ("Brutal_FlyingBlood", 0, 0, 0, 2, 90);
			TNT1 A 0 A_CheckFloor("Land8472");
			PXS2 GHIJKLMGHIJKLM 5 A_CheckFloor("Land8472");
		Land8472:
			TNT1 A 0 {
				A_Stop();
				A_SpawnItem("GrowingBloodPool");
				A_SpawnItem("DeadZombiemanPXS2O");
				}
			Stop;
		Death.Shrink:
			TNT1 A 1 {
				A_PlaySound("Shrink", 3);
				A_SpawnItemEx ("ZombieManShrinkFX1", 0, 0,  5, 0, 0);
				}
			TNT1 A 1 A_SpawnItemEx ("ZombieManShrinkFX2", 0, 0, 5, 0, 0);
			TNT1 A 1 A_SpawnItemEx ("ZombieManShrinkFX3", 0, 0, 5, 0, 0);
			TNT1 A 1 A_SpawnItemEx ("ZombieManShrinkFX4", 0, 0, 5, 0, 0);
			TNT1 A 1 A_SpawnItemEx ("ZombieManShrinkFX5", 0, 0, 5, 0, 0);
			TNT1 A 1 A_SpawnItemEx ("ZombieManShrinkFX6", 0, 0, 5, 0, 0);
			TNT1 A 1 A_SpawnItemEx ("ZombieManShrinkFX7", 0, 0, 5, 0, 0);
			TNT1 A 1 A_SpawnItemEx ("LilZombieMan", 1);
			stop;
			
		 Death.Melee:
			TNT1 A 0 A_JumpIfInventory ("IsDown", 1, "Death.Down");
			TNT1 A 0 A_JumpIfInventory ("SKZombieMan", 1, "StealthKill");
        Death.Kick:
			TNT1 A 0 {
				A_ChangeFLag("NODROPOFF", 0);
				A_ChangeFLag("SLIDESONWALLS", 1);
				ThrustThingZ(0,30,0,1);
				A_Scream();
				A_NoBlocking();
				A_FaceTarget();
				A_Recoil (10);
			}
			POS4 UUVWXY 5;
			TNT1 A 0 A_PlaySound("BODYF");
			TNT1 A 0 A_SpawnItem("DeadZombieman1");
			Stop;
		StealthKill:
			TNT1 A 0 A_JumpIfInTargetInventory("FistsSelected", 1, 1);
			Goto Death;
			TNT1 A 0 {
				A_GiveToTarget("GoFatality", 1);
				A_GiveToTarget("SKZombieMan", 1);
				A_NoBlocking();
				A_Die("Stealthy");
			}
			Stop;
		Death.Stealthy:
			TNT1 A 0;
			Stop;
	
	   Death.Trample:	
	   Death.Down:
			TNT1 A 0 {
				A_Scream();
				A_Stop();
				A_NoBlocking();
				}
			TNT1 A 0 {
				A_SpawnProjectile ("XDeath1", 2, 0, random (0, 360), 2, random (0, 40));
				A_SpawnProjectile ("XDeath1", 2, 0, random (0, 360), 2, random (0, 40));
				A_SpawnProjectile ("XDeath1", 2, 0, random (0, 360), 2, random (0, 40));
				}
			ID11 F 12;
			POSS K 3;
			TNT1 A 0 A_SpawnItem("DeadZombieman1");
			Stop;
		Death.Shotgun:
			TNT1 A 0 A_Jump(42, "Death.Shotgunontheface");
			TNT1 A 0 A_JumpIfCloser(80, "Death.Blast");
			TNT1 A 0 A_JumpIfCloser(320, "Death.Shotgunontheface");
			Goto Death;
			
		Death.Shotgunontheface:	
			TNT1 A 0 {
				A_ChangeFlag("SLIDESONWALLS", 0);
				A_ChangeFlag("NOBLOCKMONST", 1);
			}
			TNT1 A 0 A_Jump(160, "DeathShotgunFly");
			
			POSS H 1 {
				A_FaceTarget();
				A_Stop();
				A_Pain();
				A_Recoil(13);
				ThrustThingZ(0,20,0,1);
				}
			TNT1 A 0 A_JumpIf(momy == 0, "DeathShotgunFly");
			TNT1 A 0 A_Jump(128, "DeathShotgunontheface2");
			TNT1 A 0 {
				A_Scream();
				A_SpawnProjectile ("MuchBlood2", 35, 0, random (0, 360), 2, random (0, 160));
				A_SpawnProjectile ("XDeath1", 35, 0, random (0, 360), 2, random (0, 160));
				A_SpawnProjectile ("XDeath1", 35, 0, random (0, 360), 2, random (0, 160));
				A_NoBlocking();
				}
			POS4 AAAABBBBCCCCDDDD 1 A_SpawnProjectile ("Brutal_LiquidBlood3", 15, 0, random (0, 360), 2, random (0, 40));
			POS4 EFGHIJ 4 A_JumpIf((MomY == 0), "DSFStop");
			Goto DSFStop;
		DSFStop:
			TNT1 A 0{
				A_Stop();
				A_SpawnItem ("GrowingBloodPool");
				A_SpawnProjectile ("SuperWallRedBlood", 2, 0, random (170, 190), 2, random (0, 0));
				A_PlaySound("BODYF",6);
				A_SpawnItem("DeadZombiemanShotguntotheFace1");
				}
			Stop;
		DeathShotgunontheface2:	
			TNT1 A 0 {
				A_Scream();
				A_SpawnProjectile ("MuchBlood2", 35, 0, random (0, 360), 2, random (0, 160));
				A_SpawnProjectile ("XDeath1", 35, 0, random (0, 360), 2, random (0, 160));
				A_SpawnProjectile ("XDeath1", 35, 0, random (0, 360), 2, random (0, 160));
				A_NoBlocking();
				}
			POS4 KKKKLLLLMMMMNNNN 1 A_SpawnProjectile ("Brutal_LiquidBlood3", 15, 0, random (0, 360), 2, random (0, 40));
			POS4 OPQRST 4 A_JumpIf((MomY == 0), "DSFStop2");
			Goto DSFStop2;
			
		DSFStop2:
			TNT1 A 0 {
				A_Stop();
				A_SpawnItem ("GrowingBloodPool");
				A_SpawnProjectile ("SuperWallRedBlood", 2, 0, random (170, 190), 2, random (0, 0));
				A_PlaySound("BODYF",6);
				A_SpawnItem("DeadZombiemanShotguntotheFace2");
			}
			Stop;
		
	Death.Blast:
	Death.Railgun:
		TNT1 A 0 A_FaceTarget();
		TNT1 A 0 A_Jump(12, "Death.Arm");
		TNT1 A 0 A_NoBlocking();
		TNT1 A 0 A_Jump(128, "Death.Blast2");
		TNT1 A 0 {
			A_Scream();
			A_SpawnProjectile ("Instestin", 32, 0, random (150, 210), 2, random (0, 40));
			A_SpawnProjectile ("Instestin", 32, 0, random (150, 210), 2, random (0, 40));
			A_SpawnProjectile ("Instestin", 32, 0, random (150, 210), 2, random (0, 40));
			A_SpawnProjectile ("XDeath1", 32, 0, random (150, 210), 2, random (0, 40));
			A_SpawnProjectile ("XDeath1", 32, 0, random (150, 210), 2, random (0, 40));
			A_SpawnProjectile ("XDeath1", 32, 0, random (150, 210), 2, random (0, 40));
			A_SpawnProjectile ("Xdeath3", 16, 0, random (170, 190), 2, random (0, 40));
			A_SpawnProjectile ("Xdeath3", 16, 0, random (170, 190), 2, random (0, 40));
			A_SpawnProjectile ("Xdeath3", 16, 0, random (170, 190), 2, random (0, 40));
			A_SpawnProjectile ("Brutal_FlyingBlood", 32, 0, random (170, 190), 2, random (0, 40));
			A_SpawnProjectile ("Brutal_FlyingBlood", 32, 0, random (170, 190), 2, random (0, 40));
			A_SpawnProjectile ("Brutal_FlyingBlood", 32, 0, random (170, 190), 2, random (0, 40));
			A_SpawnProjectile ("Brutal_FlyingBlood", 32, 0, random (170, 190), 2, random (0, 40));
			A_SpawnProjectile ("SuperWallRedBlood", 32, 0, random (170, 190), 2, random (0, 40));
			A_SpawnProjectile ("SuperWallRedBlood", 32, 0, random (170, 190), 2, random (0, 40));
			A_SpawnProjectile ("SuperWallRedBlood", 32, 0, random (170, 190), 2, random (0, 40));
			A_SpawnProjectile ("SuperWallRedBlood", 32, 0, random (170, 190), 2, random (0, 40));
			A_SpawnProjectile ("BloodMistBig", 40, 0, random (0, 360), 2, random (30, 90));
			A_SpawnProjectile ("BloodMistBig", 40, 0, random (0, 360), 2, random (30, 90));
			A_SpawnProjectile ("BloodMistBig", 40, 0, random (0, 360), 2, random (30, 90));
			}
		ZXZ1 A 6 {
			A_Stop();
			A_SpawnItem ("GrowingBloodPool");
			}
		ZXZ1 BBBBBBBBBB 3 A_SpawnProjectile ("Brutal_LiquidBlood2", 26, 0, random (0, 360), 2, random (30, 60));
		ZXZ1 CCC 3 A_SpawnProjectile ("Brutal_LiquidBlood2", 26, 0, random (0, 360), 2, random (10, 40));
		ZXZ1 DD 3 A_SpawnProjectile ("Brutal_LiquidBlood2", 6, 0, random (0, 360), 2, random (30, 60));
		TNT1 A 0 A_PlaySound("BODYF");
		TNT1 A 0 A_SpawnItem("DeadZombieMan_StomachExploded");
	    Stop;
		
	Death.Blast2:
	    TNT1 A 0 {
			A_XScream();
			A_SpawnProjectile ("XDeathArm1", 42, 0, random (0, 360), 2, random (0, 40));
			A_SpawnProjectile ("Instestin", 32, 0, random (150, 210), 2, random (0, 40));
			A_SpawnProjectile ("Instestin", 32, 0, random (150, 210), 2, random (0, 40));
			A_SpawnProjectile ("Instestin", 32, 0, random (150, 210), 2, random (0, 40));
			A_SpawnProjectile ("XDeath1", 32, 0, random (150, 210), 2, random (0, 40));
			A_SpawnProjectile ("XDeath1", 32, 0, random (150, 210), 2, random (0, 40));
			A_SpawnProjectile ("XDeath1", 32, 0, random (150, 210), 2, random (0, 40));
			A_SpawnProjectile ("Xdeath3", 16, 0, random (170, 190), 2, random (0, 40));
			A_SpawnProjectile ("Xdeath3", 16, 0, random (170, 190), 2, random (0, 40));
			A_SpawnProjectile ("Xdeath2", 16, 0, random (130, 210), 2, random (0, 40));
			A_SpawnProjectile ("Xdeath2", 16, 0, random (130, 210), 2, random (0, 40));
			A_SpawnProjectile ("Brutal_FlyingBlood", 32, 0, random (170, 190), 2, random (0, 40));
			A_SpawnProjectile ("Brutal_FlyingBlood", 32, 0, random (170, 190), 2, random (0, 40));
			A_SpawnProjectile ("Brutal_FlyingBlood", 32, 0, random (170, 190), 2, random (0, 40));
			A_SpawnProjectile ("Brutal_FlyingBlood", 32, 0, random (170, 190), 2, random (0, 40));
			A_SpawnProjectile ("Brutal_FlyingBloodFaster", 32, 0, random (170, 190), 2, random (0, 40));
			A_SpawnProjectile ("Brutal_FlyingBloodFaster", 32, 0, random (170, 190), 2, random (0, 40));
			A_SpawnProjectile ("Brutal_FlyingBloodMuchFaster", 32, 0, random (170, 190), 2, random (0, 40));
			A_SpawnProjectile ("SuperWallRedBlood", 32, 0, random (170, 190), 2, random (0, 40));
			A_SpawnProjectile ("SuperWallRedBlood", 32, 0, random (170, 190), 2, random (0, 40));
			A_SpawnProjectile ("SuperWallRedBlood", 32, 0, random (170, 190), 2, random (0, 40));
			A_SpawnProjectile ("SuperWallRedBlood", 32, 0, random (170, 190), 2, random (0, 40));
			A_SpawnProjectile ("BloodMistBig", 40, 0, random (0, 360), 2, random (30, 90));
			A_SpawnProjectile ("BloodMistBig", 40, 0, random (0, 360), 2, random (30, 90));
			A_SpawnProjectile ("BloodMistBig", 40, 0, random (0, 360), 2, random (30, 90));
			A_SpawnProjectile ("BloodMistBig", 40, 0, random (0, 360), 2, random (30, 90));
		}
		ZXZ2 A 6 {
			A_Stop();
			A_SpawnItem ("GrowingBloodPool");
			}
		ZXZ2 BBBBBBBBBBBBBBBBBBB 3 A_SpawnProjectile ("Brutal_LiquidBlood2", 26, 0, random (0, 360), 2, random (30, 60));
		ZXZ2 CCC 3 A_SpawnProjectile ("Brutal_LiquidBlood2", 26, 0, random (0, 360), 2, random (10, 40));
		ZXZ2 DD 3 A_SpawnProjectile ("Brutal_LiquidBlood2", 6, 0, random (0, 360), 2, random (30, 60));
		TNT1 A 0 {
			A_PlaySound("BODYF");
			A_SpawnItem("DeadZombieMan_Blasted");
			}
	    Stop;
	
	Death.SSG:
	    ZZD1 E 1 {
				A_Recoil(-20);
				A_FaceTarget();
				NashGoreGibs.SpawnGibs(self);
				for (int i = 0; i < 5; i++) {	
					A_SpawnProjectile ("NashGoreBloodParticle_Large", 32, 0, random (170, 190), 2, random (0, 40));
					A_SpawnProjectile ("PB_SuperWallRedBlood", 32, 0, random (170, 190), 2, random (0, 40));
				}
				
				/*
				A_SpawnProjectile ("XDeath1", 32, 0, random (170, 190), 2, random (0, 40));
				A_SpawnProjectile ("XDeath1", 32, 0, random (170, 190), 2, random (0, 40));
				A_SpawnProjectile ("XDeath1", 32, 0, random (170, 190), 2, random (0, 40));
				A_SpawnProjectile ("XDeath1", 32, 0, random (170, 190), 2, random (0, 40));
				A_SpawnProjectile ("XDeath3", 32, 0, random (170, 190), 2, random (0, 40));
				A_SpawnProjectile ("SuperGoreSpawner", 35, 0, random (170, 190), 2, random (0, 40));
				A_SpawnProjectile ("Instestin", 32, 0, random (150, 210), 2, random (0, 40));
				A_SpawnProjectile ("Instestin", 32, 0, random (150, 210), 2, random (0, 40));
				A_SpawnProjectile ("Instestin", 32, 0, random (150, 210), 2, random (0, 40));
				A_SpawnProjectile ("SuperWallRedBlood", 32, 0, random (170, 190), 2, random (0, 40));
				A_SpawnProjectile ("XDeathArm1", 32, 0, random (180, 190), 2, random (0, 40));
				A_SpawnProjectile ("XDeathArm1", 32, 0, random (160, 170), 2, random (0, 40));
				A_SpawnProjectile ("XDeathZombieManHead", 32, 0, random (170, 190), 2, random (0, 40));
				*/
				A_XScream();
				A_NoBlocking();
			}
        ZZD1 EEFFGH 6;
		ZZD1 H 1 A_PlaySound("BODYF");
		ZZD1 HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH 2 {
			A_SpawnItemEx("PB_SquirtingBloodTrail", 
			0, 0, frandom(3, 4),
			frandom(-3, 3), frandom(-3, 3), frandom(3, 6),
			frandom(0.0, 360));
		}
		TNT1 A 0 {
			A_SpawnItem ("GrowingBloodPool");
			A_SpawnItem("DeadZombiemanJustLegsAreLeft2");
		}
        Stop;
		
	XDeath:
		TNT1 A 0 A_JumpIfInTargetInventory("SSGSelected", 1, "Death.SSG");
		TNT1 A 0 { 
			NashGoreGibs.SpawnGibs(self);
			A_SpawnProjectile ("XDeath1", 42, 0, random (0, 290), 2, random (10, 60));
			A_SpawnProjectile ("XDeath3", 42, 0, random (0, 290), 2, random (10, 60));
			A_SpawnProjectile ("XDeath3", 42, 0, random (0, 290), 2, random (10, 60));
			A_SpawnProjectile ("XDeath3", 42, 0, random (0, 290), 2, random (10, 60));
			A_SpawnProjectile ("XDeath2", 42, 0, random (0, 190), 2, random (10, 60));
			A_SpawnProjectile ("XDeath4", 42, 0, random (0, 190), 2, random (10, 60));
			}
		TNT1 AAAAAA 0 A_SpawnProjectile ("BloodMistBig", 40, 0, random (0, 360), 2, random (30, 90));
        TNT1 A 1 {
			A_SpawnItemEx("ZombieXDeath",0,0,2,velx,vely,velz,angle,SXF_ABSOLUTEVELOCITY|SXF_ABSOLUTEANGLE|SXF_NOCHECKPOSITION,0);
			A_Recoil(2);
			A_XScream();
			A_NoBlocking();
		}
		Stop;
		
		Raise:
			POSS KJIH 5;
			Goto See;
		}
}