Class PBChaingunSpawner : PB_SpawnerBase
{
	States
	{
		Tier4:
			TNT1 A 0 PB_SpawnerSpawn("PB_MGSpawnerT4");
			Stop;
		Tier3:
			TNT1 A 0 PB_SpawnerSpawn("PB_MGSpawnerT3");
			Stop;
		Tier2:
			TNT1 A 0 PB_SpawnerSpawn("PB_MGSpawnerT2");
			Stop;
		Death:
			TNT1 A 0 A_Jump(64,"Tier2","Tier3","Tier4");
		Tier1:
			TNT1 A 0 PB_SpawnerSpawn("PB_MGSpawnerT1");
			Stop;
	}
}

class PB_MGSpawnerT1 : PB_WeaponSpawner
{
	Default
	{
		DropItem 'PB_Minigun', 255, 1;
	}
}

class PB_MGSpawnerT2 : PB_WeaponSpawner
{
	Default
	{
		PBRandomSpawner.Fallback 'PB_MGSpawnerT1';
		DropItem 'PB_Carbine', 255, 1;
	}
	
	override bool HandleSpawnExceptions(name toSpawn)
	{
		if(toSpawn == "PB_Carbine" && pb_chaingun_filter & DisablePB_Carbine)
			return false;
		return true;
	}
}

class PB_MGSpawnerT3 : PB_WeaponSpawner
{
	Default
	{
		PBRandomSpawner.Fallback 'PB_MGSpawnerT2';
		DropItem 'PB_Nailgun', 255, 1;
		DropItem 'PB_HDMRUpgrade', 255, 1;
		DropItem 'PB_MG42', 255, 1;
	}
	
	override bool HandleSpawnExceptions(name toSpawn)
	{
		if(toSpawn == "PB_Nailgun" && pb_chaingun_filter & DisablePB_Nailgun)
			return false;
		if(toSpawn == "PB_HDMRUpgrade" && pb_chaingun_filter & DisablePB_HDMRUpgrade)
			return false;
		//if we are in a mapset with a custom mg 42 spawn or there are no wolfss and the player has not enabled spawns on all maps, do not allow the mg 42
		if(toSpawn == "PB_MG42" && (pb_bfg_filter & DisablePB_MG42 || !pb_mg_42_chaingun_spawn && (!Handler.WSuSinMap || PB_EventHandler.GetPlayingWolfMaps())))
			return false;
		return true;
	}
}

class PB_MGSpawnerT4 : PB_WeaponSpawner
{
	Default
	{
		PBRandomSpawner.Fallback 'PB_MGSpawnerT3';
		DropItem 'PB_LMG', 255, 1;
		DropItem 'PB_MinigunUpgrade', 255, 1;
	}
	
	override bool HandleSpawnExceptions(name toSpawn)
	{
		if(toSpawn == "PB_LMG" && pb_chaingun_filter & DisablePB_LMG)
			return false;
		if(toSpawn == "PB_MinigunUpgrade" && pb_chaingun_filter & DisablePB_MinigunUpgrade)
			return false;
		return true;
	}
}