Class PBPlasmaRifleSpawner : PB_SpawnerBase replaces PlasmaRifle
{
	default
	{
	+LOOKALLAROUND;
	scale 0.45;
	-SHOOTABLE;
    -COUNTKILL; 
    -SOLID;
	+NOTIMEFREEZE;
    //CANPUSHWALLS;
    //-CANUSEWALLS;
    //-ACTIVATEMCROSS;
    //-CANPASS;
    //-ISMONSTER;
	//+NODAMAGE;
	//-NOMENU;
	Species "plasmariflespawner";
	}
	States
	{
		Spawn:
			TNT1 A 0;
		Spawn2:	
			TNT1 A 0;
		InitiateCheck:
			TNT1 A 1;
			TNT1 A 0
			{
				Stats = PB_GlobalStats.Get();
				int Count = Stats.Counters[PB_GlobalStats.Counter_LevelsCompleted];
				
				if(SpawnBalance==663)
				{
				{SetStateLabel("CHAOTICRANDOM");}
				}
				else if(SpawnBalance==666||SpawnBalance<=663&&SpawnBalance>=672)
				{
					//if(Count == 0) {SetStateLabel("Tier1");}
					
					if(Count < (levelsToPlay / 4)) {SetStateLabel("Tier1");}
					
					else if(Count == (levelsToPlay / 4)) {SetStateLabel("T2Random64");}
					else if(Count == ((levelsToPlay / 4) + 1)) {SetStateLabel("T2Random128");}
					else if(Count == ((levelsToPlay / 4) + 2)) {SetStateLabel("T2Random192");}
					
					else if(Count < ((levelsToPlay / 4) * 2)) {SetStateLabel("Tier2");}
					
					else if(Count == ((levelsToPlay / 4) * 2)) {SetStateLabel("T3Random64");}
					else if(Count == (((levelsToPlay / 4) * 2) + 1)) {SetStateLabel("T3Random128");}
					else if(Count == (((levelsToPlay / 4) * 2) + 2)) {SetStateLabel("T3Random192");}
					
					else if(Count < ((levelsToPlay / 4) * 3)) {SetStateLabel("Tier3");}
					
					else if(Count == ((levelsToPlay / 4) * 3)) {SetStateLabel("T4Random64");}
					else if(Count == (((levelsToPlay / 4) * 3) + 1)) {SetStateLabel("T4Random128");}
					else if(Count == (((levelsToPlay / 4) * 3) + 2)) {SetStateLabel("T4Random192");}
					
					else if(Count > (((levelsToPlay / 4) * 3) + 2)) {SetStateLabel("Tier4");}
				}
				else if(SpawnBalance==667)
				{
				{SetStateLabel("Tier1");}
				}
				else if(SpawnBalance==668)
				{
				{SetStateLabel("Tier2");}
				}
				else if(SpawnBalance==669)
				{
				{SetStateLabel("Tier3");}
				}
				else if(SpawnBalance==670||SpawnBalance==672)
				{
				{SetStateLabel("Tier4");}
				}
				else if(SpawnBalance==671)
				{
					//if(Count == 0) {SetStateLabel("Tier1");}
					if(Count <= (levelsToPlay / 4)) {SetStateLabel("Tier1");}
					else if(Count <= (levelsToPlay / 4 * 2)) {SetStateLabel("Tier2");}
					else if(Count <= (levelsToPlay / 4 * 3)) {SetStateLabel("Tier3");}
					else if(Count > (levelsToPlay / 4 * 3)) {SetStateLabel("Tier4");}
				}
			}
			Loop;
		T2Random64:
		    TNT1 A 0 A_Jump(64,"Tier2");
		    TNT1 A 0 A_Jump(256,"Tier1");
		T2Random128:
		    TNT1 A 0 A_Jump(128,"Tier2");
			TNT1 A 0 A_Jump(256,"Tier1");
		T2Random192:
		    TNT1 A 0 A_Jump(192,"Tier2");
			TNT1 A 0 A_Jump(256,"Tier1");
		T3Random64:
		    TNT1 A 0 A_Jump(64,"Tier3");
			TNT1 A 0 A_Jump(256,"Tier2");
		T3Random128:
		    TNT1 A 0 A_Jump(128,"Tier3");
			TNT1 A 0 A_Jump(256,"Tier2");
		T3Random192:
		    TNT1 A 0 A_Jump(192,"Tier3");
			TNT1 A 0 A_Jump(256,"Tier2");
		T4Random64:
		    TNT1 A 0 A_Jump(64,"Tier4");
			TNT1 A 0 A_Jump(256,"Tier3");
		T4Random128:
		    TNT1 A 0 A_Jump(128,"Tier4");
			TNT1 A 0 A_Jump(256,"Tier3");
		T4Random192:
		    TNT1 A 0 A_Jump(192,"Tier4");
			TNT1 A 0 A_Jump(256,"Tier3");
		CHAOTICRANDOM:
		    TNT1 A 0 A_Jump(256, "Tier4","Tier3", "Tier2", "Tier1");
			Stop;
		Tier4:
		SpawnM2Upgrade: 
		   TNT1 A 0;
		   TNT1 A 0
		   {
		    if(DisablePB_M2Upgrade==true)
		    {
		    SetStateLabel("Tier3");
		    }
		   }
			TNT1 A 0 A_SpawnItemEx("SpawnedM2U",flags:SXF_TRANSFERSPECIAL|SXF_TRANSFERAMBUSHFLAG|SXF_TRANSFERPOINTERS|288,tid:tid);
			Stop;
		Tier3:
		TNT1 A 0 A_Jump(256, "PB_CryoRifle","PB_Railgun");
		PB_CryoRifle:
		   TNT1 A 0;
		   TNT1 A 0
		   {
		    if(DisablePB_CryoRifle==true)
		    {
		    SetStateLabel("PB_Railgun");
		    }
		   }
			TNT1 A 0 A_SpawnItemEx("SpawnedCR",flags:SXF_TRANSFERSPECIAL|SXF_TRANSFERAMBUSHFLAG|SXF_TRANSFERPOINTERS|288,tid:tid);
			Stop;
		PB_Railgun:
		   TNT1 A 0;
		   TNT1 A 0
		   {
		    if(DisablePB_Railgun==true)
		    {
		    SetStateLabel("Tier2");
		    }
		   }
			TNT1 A 0 A_SpawnItemEx("SpawnedRailgun",flags:SXF_TRANSFERSPECIAL|SXF_TRANSFERAMBUSHFLAG|SXF_TRANSFERPOINTERS|288,tid:tid);
			Stop;
		Tier2:
		SpawnM2:
		   TNT1 A 0;
		   TNT1 A 0
		   {
		    if(DisablePB_M2Plasma==true)
		    {
		    SetStateLabel("Tier1");
		    }
		   }
			TNT1 A 0 A_SpawnItemEx("SpawnedM2",flags:SXF_TRANSFERSPECIAL|SXF_TRANSFERAMBUSHFLAG|SXF_TRANSFERPOINTERS|288,tid:tid);
			Stop;
		Tier1:
		SpawnM1:	
			TNT1 A 0 A_SpawnItemEx("SpawnedM1",flags:SXF_TRANSFERSPECIAL|SXF_TRANSFERAMBUSHFLAG|SXF_TRANSFERPOINTERS|288,tid:tid);
			Stop;
		Death:
		    TNT1 A 0;
			Goto Spawn;
	}
}

CLASS SpawnedM2U:droppedbase
{
    States
    {
    Spawn:
		//TNT1 AA 1
		TNT1 AA 0;
		TNT1 A 0 A_SpawnItemEx("PB_M2Upgrade",0,0,0,0,0,0,0,SXF_TRANSFERSPECIAL | SXF_NOCHECKPOSITION | 288);
	Spawn2:	
	    TNT1 A 1;
        Loop;
	Pickup:
		TNT1 A 0 A_GiveInventory("PlayerHasM2UPermanent",1);
		Stop;
    }
}

CLASS SpawnedCR:droppedbase
{
    States
    {
    Spawn:
		//TNT1 AA 1
		TNT1 AA 0;
		TNT1 A 0 A_SpawnItemEx("PB_CryoRifle",0,0,0,0,0,0,0,SXF_TRANSFERSPECIAL | SXF_NOCHECKPOSITION | 288);
	Spawn2:	
	    TNT1 A 1;
        Loop;
	Pickup:
		TNT1 A 0 A_GiveInventory("PlayerHasCryoPermanent",1);
		Stop;
    }
}

CLASS SpawnedRailgun:droppedbase
{
    States
    {
    Spawn:
		//TNT1 AA 1
		TNT1 AA 0;
		TNT1 A 0 A_SpawnItemEx("PB_Railgun",0,0,0,0,0,0,0,SXF_TRANSFERSPECIAL | SXF_NOCHECKPOSITION | 288);
	Spawn2:	
	    TNT1 A 1;
        Loop;
	Pickup:
		TNT1 A 0 A_GiveInventory("PlayerHasRGPermanent",1);
		Stop;
    }
}

CLASS SpawnedM2:droppedbase
{
    States
    {
    Spawn:
		//TNT1 AA 1
		TNT1 AA 0;
		TNT1 A 0 A_SpawnItemEx("M2Plasma",0,0,0,0,0,0,0,SXF_TRANSFERSPECIAL | SXF_NOCHECKPOSITION | 288);
	Spawn2:	
	    TNT1 A 1;
        Loop;
	Pickup:
		TNT1 A 0 A_GiveInventory("PlayerHasM2PlasmaPermanent",1);
		Stop;
    }
}

CLASS SpawnedM1:droppedbase
{
    States
    {
    Spawn:
		//TNT1 AA 1
		TNT1 AA 0;
		TNT1 A 0 A_SpawnItemEx("PB_M1PlasmaPickup",0,0,0,0,0,0,0,SXF_TRANSFERSPECIAL | SXF_NOCHECKPOSITION | 288);
	Spawn2:	
	    TNT1 A 1;
        Loop;
	Pickup:
		TNT1 A 0 A_GiveInventory("PlayerHasM1PlasmaPermanent",1);
		Stop;
    }
}