Class PBPlasmaRifleSpawner : PB_SpawnerBase replaces PlasmaRifle
{
	default
	{
	+LOOKALLAROUND;
	scale 0.45;
	-SHOOTABLE;
    -COUNTKILL; 
    -SOLID;
	+NOTIMEFREEZE;
    //CANPUSHWALLS;
    //-CANUSEWALLS;
    //-ACTIVATEMCROSS;
    //-CANPASS;
    //-ISMONSTER;
	//+NODAMAGE;
	//-NOMENU;
	Species "plasmariflespawner";
	}
	States
	{
		Spawn:
			TNT1 A 0;
		Spawn2:	
			TNT1 A 0;
		InitiateCheck:
			TNT1 A 1;
			TNT1 A 0
			{
				if(SpawnBalance==663)
				{
				{SetStateLabel("CHAOTICRANDOM");}
				}
				else if(SpawnBalance==666||SpawnBalance<=663&&SpawnBalance>=672)
				{
				 if(SMO >= 27)  {SetStateLabel("Tier4");}
				 else if(SMO == 26) {SetStateLabel("T4Random192");}
				 else if(SMO == 25) {SetStateLabel("T4Random128");}
				 else if(SMO == 24) {SetStateLabel("T4Random64");}
				 else if(SMO >= 19)  {SetStateLabel("Tier3");}
				 else if(SMO == 18) {SetStateLabel("T3Random192");}
				 else if(SMO == 17) {SetStateLabel("T3Random128");}
				 else if(SMO == 16) {SetStateLabel("T3Random64");}
				 else if(SMO >= 11)  {SetStateLabel("Tier2");}
				 else if(SMO == 10) {SetStateLabel("T2Random192");}
				 else if(SMO == 9) {SetStateLabel("T2Random128");}
				 else if(SMO == 8)  {SetStateLabel("T2Random64");}
				 else if(SMO >= 1)  {SetStateLabel("Tier1");}
				 else if(SMO == 0)  {SetStateLabel("Tier1");}
				}
				else if(SpawnBalance==667)
				{
				{SetStateLabel("Tier1");}
				}
				else if(SpawnBalance==668)
				{
				{SetStateLabel("Tier2");}
				}
				else if(SpawnBalance==669)
				{
				{SetStateLabel("Tier3");}
				}
				else if(SpawnBalance==670||SpawnBalance==672)
				{
				{SetStateLabel("Tier4");}
				}
				else if(SpawnBalance==671)
				{
				 if(SMO >= 25) {SetStateLabel("Tier4");}
				 else if(SMO >= 17) {SetStateLabel("Tier3");}
				 else if(SMO >= 9)  {SetStateLabel("Tier2");}
				 else if(SMO >= 1)  {SetStateLabel("Tier1");}
				 else if(SMO == 0)  {SetStateLabel("Tier1");}
				}
			}
			Loop;
		T2Random64:
		    TNT1 A 0 A_Jump(64,"Tier2");
		    TNT1 A 0 A_Jump(256,"Tier1");
		T2Random128:
		    TNT1 A 0 A_Jump(128,"Tier2");
			TNT1 A 0 A_Jump(256,"Tier1");
		T2Random192:
		    TNT1 A 0 A_Jump(192,"Tier2");
			TNT1 A 0 A_Jump(256,"Tier1");
		T3Random64:
		    TNT1 A 0 A_Jump(64,"Tier3");
			TNT1 A 0 A_Jump(256,"Tier2");
		T3Random128:
		    TNT1 A 0 A_Jump(128,"Tier3");
			TNT1 A 0 A_Jump(256,"Tier2");
		T3Random192:
		    TNT1 A 0 A_Jump(192,"Tier3");
			TNT1 A 0 A_Jump(256,"Tier2");
		T4Random64:
		    TNT1 A 0 A_Jump(64,"Tier4");
			TNT1 A 0 A_Jump(256,"Tier3");
		T4Random128:
		    TNT1 A 0 A_Jump(128,"Tier4");
			TNT1 A 0 A_Jump(256,"Tier3");
		T4Random192:
		    TNT1 A 0 A_Jump(192,"Tier4");
			TNT1 A 0 A_Jump(256,"Tier3");
		CHAOTICRANDOM:
		    TNT1 A 0 A_Jump(256, "Tier4","Tier3", "Tier2", "Tier1");
			Stop;
		Tier4:
		   TNT1 A 0
		   {
		    if(DisablePB_M2Upgrade==true)
		    {
		    SetStateLabel("Tier3");
		    }
		   }
			TNT1 A 0 A_SpawnItemEx("PB_M2Upgrade",flags:SXF_TRANSFERSPECIAL|SXF_TRANSFERAMBUSHFLAG|SXF_TRANSFERPOINTERS|288,tid:tid);
			Stop;
		Tier3:
		TNT1 A 0 A_Jump(256, "PB_CryoRifle","PB_Railgun");
		PB_CryoRifle:
		   TNT1 A 0
		   {
		    if(DisablePB_CryoRifle==true)
		    {
		    SetStateLabel("PB_Railgun");
		    }
		   }
			TNT1 A 0 A_SpawnItemEx("PB_CryoRifle",flags:SXF_TRANSFERSPECIAL|SXF_TRANSFERAMBUSHFLAG|SXF_TRANSFERPOINTERS|288,tid:tid);
			Stop;
		PB_Railgun:
		   TNT1 A 0
		   {
		    if(DisablePB_Railgun==true)
		    {
		    SetStateLabel("Tier2");
		    }
		   }
			TNT1 A 0 A_SpawnItemEx("PB_Railgun",flags:SXF_TRANSFERSPECIAL|SXF_TRANSFERAMBUSHFLAG|SXF_TRANSFERPOINTERS|288,tid:tid);
			Stop;
		Tier2:
		   TNT1 A 0
		   {
		    if(DisablePB_M2Plasma==true)
		    {
		    SetStateLabel("Tier1");
		    }
		   }
			TNT1 A 0 A_SpawnItemEx("M2Plasma",flags:SXF_TRANSFERSPECIAL|SXF_TRANSFERAMBUSHFLAG|SXF_TRANSFERPOINTERS|288,tid:tid);
			Stop;
		Tier1:
			TNT1 A 0 A_SpawnItemEx("PB_M1PlasmaPickup",flags:SXF_TRANSFERSPECIAL|SXF_TRANSFERAMBUSHFLAG|SXF_TRANSFERPOINTERS|288,tid:tid);
			Stop;
		Death:
		    TNT1 A 0;
			Goto Spawn;
	}
}