class PB_DTech : PB_Ammo replaces demonpickup
{
	Default
	{
		Scale 0.15;
		Tag "Demon Energy";
		Inventory.Amount 10;
		Inventory.MaxAmount 300;
		Inventory.PickupSound "demonsoulpickup";
		Ammo.BackpackAmount 60;
		Ammo.BackpackMaxAmount 666;
		PB_Ammo.ammotype "dtech";
		PB_Ammo.HUDGraphics "BARBACZ1", "BARBACZ2", "BARBACZ3", "BARBACZ4", "ABAR7", "AMMOIC7", "PB_DTech";
		+FLOATBOB
		floatbobstrength .4;
		+INVENTORY.ALWAYSPICKUP
	}
	
	override void DoPickupSpecial(actor toucher)
	{
		toucher.GiveInventory("PB_DemonAPBonus",1);
		Super.DoPickupSpecial(toucher);
	}
	override string PickupMessage()
	{
		if(!res) return "Demon Energy (+2 HP)";
		return Super.PickupMessage();
	}
}

class PB_DTechLarge : PB_DTech replaces demonpickup2
{
	Default
	{
		Scale 0.25;
		Inventory.Amount 20;
	}
	
	override void DoPickupSpecial(actor toucher)
	{
		toucher.GiveInventory("PB_DemonAPBonus",1);
		toucher.GiveInventory("PB_DemonHPBonus",2);
		Super.DoPickupSpecial(toucher);
	}
}

class PB_PermaDTech : PB_DTech
{
	Default
	{
		//$Title Demonic Energy
		//$Category Project Brutality - Ammunition
		//$Sprite DB61A0
		PB_Ammo.ammotype "permadtech";
	}
}

class PB_PermaDTechLarge : PB_DTechLarge
{
	Default
	{
		//$Title Large Demonic Energy
		//$Category Project Brutality - Ammunition
		//$Sprite DB61A0
		PB_Ammo.ammotype "permadtech";
	}
}

// Leech Grenade
Class PB_LeechPickup : PB_Ammo 
{
	Default
	{
		//$Title Leech
		//$Category Project Brutality - Weapons/Equipment
		Scale 0.35;
		Tag "Leech Grenade";
		Inventory.PickupSound "SiphonGrowl";
		PB_Ammo.AmmoType "leechnade";
		Inventory.Amount 1;
		Ammo.BackpackAmount 0;
	}
	
	override string PickupMessage()
	{
		return "What the hell is this thing..?";
	}
	
	override void AttachToOwner(actor other)
	{
		if(amount > 0)
		{
			other.GiveInventory("PB_LeechToken",1);
			other.GiveInventory("PB_DTech",20);
			Super.AttachToOwner(other);
		}
		else
		{
			Destroy();
		}
	}
}

class PB_LeechToken : PB_EquipToken {}