class PB_Cell : PB_Ammo
{
	Default
	{
		//$Title Energy Cell
		//$Category Project Brutality/Ammunition
		//$Sprite CEL1E0
		//Scale 0.4;
		Tag "$PB_CELL_TAG";
		Inventory.Amount 20;
		Inventory.MaxAmount 300;
		Inventory.PickupSound "misc/cell_PickUp";
		Ammo.BackpackAmount 20;
		Ammo.BackpackMaxAmount 600;
		PB_Ammo.ammotype "cell";
		PB_Ammo.HUDGraphics "BARBACP1", "BARBACP2", "BARBACP3", "BARBACP4", "ABAR5", "AMMOIC5", "Purple";
	}
}

class PB_CellPack : PB_CelL
{
	Default
	{
		//$Title Energy Cell Pack
		//$Category Project Brutality/Ammunition
		//$Sprite YELPF0
		//Scale 0.4;
		Inventory.Amount 100;
		Inventory.PickupSound "misc/bulkcell_PickUp";
		PB_Ammo.ammotype "cellpack";
	}
}