class PB_Fuel : PB_Ammo
{
	Default
	{
		//$Title Gas Can
		//$Category Project Brutality - Ammunition
		//$Sprite GSLNA0
		Scale 0.4;
		Tag "Fuel";
		Inventory.Amount 50;
		Inventory.MaxAmount 300;
		Inventory.PickupSound "CSAWGAS";
		Ammo.BackpackAmount 150;
		Ammo.BackpackMaxAmount 600;
		PB_Ammo.ammotype "fuel";
		PB_Ammo.HUDGraphics "BARBACD1", "BARBACD2", "BARBACD3", "BARBACD4", "ABAR6", "AMMOIC6", "PB_Fuel";
	}
}

class PB_FlamethrowerMancubusGas : PB_Fuel {
	Default {
		Scale 1.0;
		Inventory.Amount 50;
		Inventory.PickupSound "FLMDRAW";
		PB_Ammo.ammotype "mancfuel";
	}
}