class PB_RocketAmmo : PB_Ammo
{
	Default
	{
		//$Category Project Brutality - Ammunition
		//$Sprite R0CKA0
		//Scale 0.45;
		Tag "Explosive Round";
		Inventory.Amount 1;
		Inventory.MaxAmount 50;
		Inventory.PickupSound "misc/rocket_PickUp";
		Ammo.BackpackAmount 1;
		Ammo.BackpackMaxAmount 100;
		PB_Ammo.ammotype "exp";
	}
}

class PB_RocketBox : PB_RocketAmmo
{
	Default
	{
		//$Title Box of Explosives
		//$Category Project Brutality - Ammunition
		//$Sprite BROKA0
		//Scale 0.4;
		Inventory.Amount 6;
		Inventory.PickupSound "misc/rockboxa";
		PB_Ammo.AmmoType "expbox";
	}
}

class PB_GrenadeAmmo : PB_Ammo
{
	Default
	{
		//$Title UAC-M26 Frag Grenade
		//$Category Project Brutality - Weapons/Equipment
		//$Sprite PGRNA0
		Scale 0.45;
		Tag "Frag Grenade";
		Inventory.Amount 1;
		Inventory.MaxAmount 6;
		Inventory.PickupSound "GRNPIN";
		Inventory.Icon "PGRND0";
		Ammo.BackpackAmount 1;
		Ammo.BackpackMaxAmount 12;
		PB_Ammo.AmmoType "nade";
	}
}

class PB_StunGrenadeAmmo : PB_Ammo
{
	Default
	{
		//$Title Stun Grenade
		//$Category Project Brutality - Weapons/Equipment
		//$Sprite STNGA0
		Scale 0.6;
		Tag "Stun Grenade";
		Inventory.Amount 1;
		Inventory.MaxAmount 6;
		Inventory.PickupSound "StunGrenadePickup";
		Inventory.Icon "STNGA0";
		Ammo.BackpackAmount 1;
		Ammo.BackpackMaxAmount 12;
		PB_Ammo.ammotype "nadestun";
	}
}

class PB_ProxMineAmmo : PB_Ammo
{
	Default
	{
		//$Title Proximity Mine
		//$Category Project Brutality - Weapons/Equipment
		//$Sprite XPFPA0
		Scale 0.35;
		Tag "Proximity Mine";
		Inventory.Amount 1;
		Inventory.MaxAmount 6;
		Inventory.PickupSound "GRNPIN";
		Ammo.BackpackAmount 3;
		Ammo.BackpackMaxAmount 12;
		PB_Ammo.ammotype "proxmine";
	}
}

class PB_QuickLauncherAmmo : PB_Ammo
{
	Default
	{
		//$Title Quick Launcher
		//$Category Project Brutality - Weapons/Equipment
		//$Sprite FATBD0
		Tag "Quick Launcher";
		Inventory.Amount 4;
		Inventory.MaxAmount 60;
		Inventory.PickupSound "REVUP";
		Inventory.Icon "HREVCY";
		Ammo.BackpackAmount 4;
		Ammo.BackpackMaxAmount 120;
		PB_Ammo.ammotype "ql";
	}
	
	override bool TryPickup(in out actor toucher)
	{
		toucher.GiveInventory("HasRevGun",1) ;
		return Super.TryPickup(toucher);
	}
}