class PB_DTech : PB_Ammo replaces demonpickup
{
	Default
	{
		Scale 0.15;
		RenderStyle "Add";
		Tag "Demon Energy";
		Inventory.Amount 10;
		Inventory.MaxAmount 300;
		Inventory.PickupSound "demonsoulpickup";
		Ammo.BackpackAmount 60;
		Ammo.BackpackMaxAmount 666;
		PB_Ammo.ammotype "dtech";
		+FLOATBOB
		floatbobstrength .4;
		+INVENTORY.ALWAYSPICKUP
	}
	
	override void DoPickupSpecial(actor toucher)
	{
		toucher.GiveInventory("PB_DemonAPBonus",1);
		Super.DoPickupSpecial(toucher);
	}
	override string PickupMessage()
	{
		if(!res) return "";
		return Super.PickupMessage();
	}
}

class PB_DTechLarge : PB_DTech replaces demonpickup2
{
	Default
	{
		Scale 0.25;
		Inventory.Amount 20;
	}
	
	override void DoPickupSpecial(actor toucher)
	{
		toucher.GiveInventory("PB_DemonAPBonus",1);
		toucher.GiveInventory("PB_DemonHPBonus",2);
		Super.DoPickupSpecial(toucher);
	}
}

class PB_PermaDTech : PB_DTech
{
	Default
	{
		//$Title Demonic Energy
		//$Category Project Brutality - Ammunition
		//$Sprite DB61A0
		PB_Ammo.ammotype "permadtech";
	}
}

class PB_PermaDTechLarge : PB_DTechLarge
{
	Default
	{
		//$Title Large Demonic Energy
		//$Category Project Brutality - Ammunition
		//$Sprite DB61A0
		PB_Ammo.ammotype "permadtech";
	}
}

// Leech Grenade and Token
Class HasLeech : Inventory
{
	Default
	{
		inventory.maxamount 1;
	}
}

Class PB_LeechGrenadeAmmo : PB_Ammo 
{
	Default
	{
		//$Title Leech Grenade
		//$Category Project Brutality - Weapons/Equipment
		Scale 0.15;
		Tag "Leech Grenade";
		Inventory.PickupSound "SiphonGrowl";
		PB_Ammo.AmmoType "leechnade";
	}

	override bool TryPickup(in out actor toucher)
	{
		toucher.GiveInventory("HasLeech",1) ;
		return Super.TryPickup(toucher);
	}
}
