class PB_RocketAmmo : PB_Ammo
{
	Default
	{
		//$Category Project Brutality - Ammunition
		//$Sprite R0CKA0
		//Scale 0.45;
		Tag "Explosive Round";
		Inventory.Amount 1;
		Inventory.MaxAmount 50;
		Inventory.PickupSound "misc/rocket_PickUp";
		Ammo.BackpackAmount 1;
		Ammo.BackpackMaxAmount 100;
		PB_Ammo.ammotype "exp";
		PB_Ammo.HUDGraphics "BARBACR1", "BARBACR2", "BARBACR3", "BARBACR4", "ABAR4", "AMMOIC4", "Red";
	}
}

class PB_RocketBox : PB_RocketAmmo
{
	Default
	{
		//$Title Box of Explosives
		//$Category Project Brutality - Ammunition
		//$Sprite BR0KA0
		//Scale 0.4;
		Inventory.Amount 6;
		Inventory.PickupSound "misc/rockboxa";
		PB_Ammo.AmmoType "expbox";
	}
}

class PB_SGLAmmo : PB_RocketAmmo
{
	Default
	{
		PB_Ammo.ammotype "impactnade";
	}
}

class PB_SGLAmmoAcid : PB_RocketAmmo
{
	Default
	{
		PB_Ammo.ammotype "acidnade";
	}
}

class PB_SGLAmmoCryo : PB_RocketAmmo
{
	Default
	{
		PB_Ammo.ammotype "cryonade";
	}
}

class PB_SGLAmmoFire : PB_RocketAmmo
{
	Default
	{
		PB_Ammo.ammotype "firenade";
	}
}

class PB_SGLAmmoSticky : PB_RocketAmmo
{
	Default
	{
		PB_Ammo.ammotype "stickynade";
	}
}

class PB_EquipToken : Inventory
{
	Default
	{
		inventory.maxamount 1;
		+INVENTORY.UNDROPPABLE
	}
}

class PB_GrenadeAmmo : PB_Ammo
{
	Default
	{
		//$Title UAC-M26 Frag Grenade
		//$Category Project Brutality - Weapons/Equipment
		//$Sprite PGRNA0
		Scale 0.45;
		Tag "Frag Grenade";
		Inventory.Amount 1;
		Inventory.MaxAmount 6;
		Inventory.PickupSound "GRNPIN";
		Inventory.Icon "PGRND0";
		Ammo.BackpackAmount 1;
		Ammo.BackpackMaxAmount 12;
		PB_Ammo.AmmoType "nade";
	}
	
	override void AttachToOwner(actor other) //we have to do this here so that cheats will give the tokens
	{
		other.GiveInventory("PB_GrenadeToken",1);
		Super.AttachToOwner(other);
	}
}

class PB_GrenadeToken : PB_EquipToken {}

class PB_StunGrenadeAmmo : PB_Ammo
{
	Default
	{
		//$Title Stun Grenade
		//$Category Project Brutality - Weapons/Equipment
		//$Sprite STNGA0
		Scale 0.6;
		Tag "Stun Grenade";
		Inventory.Amount 1;
		Inventory.MaxAmount 6;
		Inventory.PickupSound "StunGrenadePickup";
		Inventory.Icon "STNGA0";
		Ammo.BackpackAmount 1;
		Ammo.BackpackMaxAmount 12;
		PB_Ammo.ammotype "nadestun";
	}
	
	override void AttachToOwner(actor other)
	{
		other.GiveInventory("PB_StunGrenadeToken",1);
		Super.AttachToOwner(other);
	}
}

class PB_StunGrenadeToken : PB_EquipToken {}

class PB_ProxMineAmmo : PB_Ammo
{
	Default
	{
		//$Title Proximity Mine
		//$Category Project Brutality - Weapons/Equipment
		//$Sprite XPFPA0
		Scale 0.35;
		Tag "Proximity Mine";
		Inventory.Amount 1;
		Inventory.MaxAmount 6;
		Inventory.PickupSound "GRNPIN";
		Ammo.BackpackAmount 1;
		Ammo.BackpackMaxAmount 12;
		PB_Ammo.ammotype "proxmine";
	}
	
	override void AttachToOwner(actor other)
	{
		other.GiveInventory("PB_ProxMineToken",1);
		Super.AttachToOwner(other);
	}
}

class PB_ProxMineToken : PB_EquipToken {}

class PB_QuickLauncherAmmo : PB_Ammo
{
	Default
	{
		//$Title Quick Launcher
		//$Category Project Brutality - Weapons/Equipment
		//$Sprite FATBD0
		Tag "Quick Launcher Missile";
		Inventory.Amount 4;
		Inventory.MaxAmount 60;
		Inventory.PickupSound "REVUP";
		Inventory.Icon "HREVCY";
		Ammo.BackpackAmount 4;
		Ammo.BackpackMaxAmount 120;
		PB_Ammo.ammotype "ql";
	}
	
	override void AttachToOwner(actor other)
	{
		other.GiveInventory("PB_QuickLauncherToken",1);
		Super.AttachToOwner(other);
	}
}

class PB_QuickLauncherToken : PB_EquipToken {}