class PB_Ammo : Ammo
{
	int cap,ca,res; name ammotype,s; string p;
	property ammotype : ammotype;
	
	mixin PB_BetterPickupSound;
	
	Default
	{
		+FLOORCLIP
		+DONTGIB
		+INVENTORY.IGNORESKILL
	}

	override void PostBeginPlay()
	{
		Super.PostBeginPlay();
		PB_SetAmmoSprite();
	}

	override class<Ammo> GetParentAmmo()
	{
		class<Object> type = GetClass();
		while(type.GetParentClass()!= "PB_Ammo"&&type.GetParentClass()!=null) type = type.GetParentClass();
		return(class<Ammo>)(type);
	}

	override bool TryPickup(in out actor toucher)
	{
		class<Ammo> type = GetParentAmmo();
		double factor = G_SkillPropertyFloat(SKILLP_AmmoFactor)*(bDROPPED?-G_SkillPropertyFloat(SKILLP_DropAmmoFactor):1);
		int aa = self.amount*factor;
		if(toucher && toucher is "PlayerPawn")
		{
			if (!toucher.FindInventory(self.GetParentAmmo(),true)){
				cap = toucher.FindInventory("Backpack",true)?self.BackpackMaxAmount:self.MaxAmount;
			}
			else{
				cap = toucher.FindInventory(self.GetParentAmmo(),true).MaxAmount;
			}
			ca = toucher.CountInv(type);
		}
		res = cap-ca;
		if(res<aa) AmmoCheck();
		else { res = aa; AmmoCheck(); }
		return Super.TryPickup(toucher);
	}

	void AmmoCheck() { if(res==1 || ammotype == "fuel" || ammotype == "dtech" || ammotype == "permadtech" ) p = "+%d %s"; else p = "+%d %ss"; }
	
	override string PickupMessage() { return string.format(p,res,GetTag()); }
	
	void PB_SetAmmoSprite()
	{
		switch(ammotype)
		{
			case 'lowcal': s = "MBLK"; break;
			case 'lowcalbox': s = "AMOK"; break;
			case 'highcal': s = "CLIP"; break;
			case 'highcalbox': s = "AMMO"; break;
			case 'shell': s = "SHEL"; break;
			case 'shellbox': s = "SBOX"; break;
			case 'exp': s = "R0CK"; break;
			case 'expbox': s = "BROK"; break;
			case 'cell' : s = "CELL"; SetStateLabel("SpawnCell"); break;
			case 'cellpack' : s = "YELP"; SetStateLabel("SpawnCellPack"); break;
			case 'fuel': s = "GSLN"; break;
			case 'dtech': s = "DB61"; SetStateLabel("SpawnDTech"); break;
			case 'permadtech': s = "DB61"; SetStateLabel("SpawnPermaDTech"); break;
			case 'leechnade': s = "FLSP"; SetStateLabel("SpawnLeechNade"); break;
			case 'nade': s = "PGRN"; SetStateLabel("SpawnNade"); break;
			case 'nadestun': s = "STNG"; break;
			case 'proxmine': s = "XPFP"; break;
			case 'ql': s = "FATB"; SetStateLabel("SpawnQL"); break;
		}
		sprite = GetSpriteIndex(s);
	}

	States
	{
	Spawn:
		TNT1 A 1 PB_SetAmmoSprite;
		#### A -1;
		stop;
	SpawnCell:
		CELL ABCDEFGH 2;
		loop;
	SpawnCellPack:
		YELP ABCDEFGHIJ 2;
		loop;
	SpawnDTech:
	SpawnLeechNade:
		DB61 ABCDEFGH 2 bright A_FadeOut(.01 * (0.085 / Scale.X), FTF_REMOVE | FTF_CLAMP );
		loop;
	SpawnPermaDTech:
		DB61 ABCDEFGH 2 bright;
		loop;
	SpawnNade:
		PGRN D -1;
		stop;
	SpawnQL:
		FATB D -1;
		stop;
	LoadSprites:
		MBLK A 0; AMOK A 0; CLIP A 0; AMMO A 0; SHEL A 0; SBOX A 0; ROCK A 0; BROK A 0; GSLN A 0; STNG A 0; XPFP A 0;
		CELL ABCDEFGH 0; YELP ABCDEFGHIJ 0; DB61 ABCDEFGH 0; PGRN D 0; FATB D 0; 
	}
}