class PB_Health : Health abstract
{
	mixin PB_BetterPickupSound;
	Default
	{
		+FORCEXYBILLBOARD
	}
}

class PB_Armor : BasicArmorPickup abstract
{
	mixin PB_BetterPickupSound;
	
	Default
	{
		+INVENTORY.AUTOACTIVATE;
		Inventory.MaxAmount 0;
		+FORCEXYBILLBOARD
	}
}

class PB_Armor2 : BasicArmorBonus abstract
{
	mixin PB_BetterPickupSound;
	
	Default
	{
		+INVENTORY.AUTOACTIVATE;
		+FORCEXYBILLBOARD;
	}
}
