Class DeadFlemoid_NoHeadFront: DeadZombieMan_NoArm
{
	
	Default
	{
		Health 300;
	}
	States
	{

		Spawn:
			POSH H -1;
			Stop;
			
		Death:
			TNT1 A 0 A_NoBlocking();
			TNT1 AA 0 A_SpawnProjectile ("PB_XDeath1", 15, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH, random (0, 180));
			TNT1 A 0 A_SpawnProjectile ("PB_XDeathArm1", 15, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH, random (0, 180));
			TNT1 AAAA 0 A_SpawnProjectile ("PB_BloodMist", 15, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH, random (0, 180));
			TNT1 A 0 A_SpawnItem ("DeadZombieman_NoHeadNoArm");
			Stop;
			
		Death.Fatality:
		Death.Melee:
		Death.Kick:
		Death.ExplosiveImpact:
			 TNT1 A 0 {
				A_NoBlocking();
				ThrustThingZ(0,15,0,1);
				A_FaceTarget();
				A_Recoil(1);
			}
			//ID11 EF 8;
			TNT1 A 1; //A_SpawnItem ("DeadZombieMan1", 5);
			Stop;
	}
}