class PB_MicroMissileProjectile : PB_ProjectileAlt
{
	double weavenum;
	Default
	{
		Radius 6;
		Height 6;
		Speed 45;
		DamageType "Explosive";
		Gravity 0.1;
		Scale 0.25;
		Decal "Scorch";
		SeeSound "weapons/RLL";
		Obituary "$OB_MPROCKET";
		-NOGRAVITY;
		
		PB_Projectile.BaseDamage 35;
	}
	
	States
	{
		Spawn:
			MICR A 0 NoDelay A_StartSound("weapons/rocketloop",105,CHANF_LOOP);
		Fly:
			MICR ABC 1 Bright Light("PB_ROCKET")
			{
				if(weavenum < 10) weavenum += 0.2;
				if(weavenum > 5) A_Weave(3,3,frandom(-(weavenum - 5),(weavenum - 5)),frandom(-(weavenum - 5),(weavenum - 5)));
				if(waterlevel < 1)
					A_SpawnItemEx("RocketTrailSparks",-10,0,0,-5,0,0);
			}
			loop;
		Crash:
		XDeath:
		Death:
			TNT1 A 0 {
				A_Stop();
				bNOINTERACTION = true;
				bNOGRAVITY = true;
			}
			TNT1 A 0;
			TNT1 A 0
			{
				A_Explode((90), 60);
				A_StopSound(105);
				A_StartSound("FAREXPL", CHAN_AUTO,CHANF_OVERLAP,0.5,0,1.1);
				Radius_Quake (2, 4, 0, 7, 0);
				A_SpawnItemEx ("DetectFloorCrater",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
				A_SpawnItemEx ("DetectCeilCrater",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
				A_SpawnItemEx ("ExplosionFlareSpawner",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
				A_SpawnItemEx ("LiquidExplosionEffectSpawner",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
				A_SpawnProjectile ("ExplosionSmokeFast22", 0, 0, random (0, 360), 2, random (0, 360));
				A_SpawnProjectile ("MediumExplosionFlames", 0, 0, random (0, 360), 2, random (0, 360));
				A_SpawnProjectile ("PBExplosionparticles", 0, 0, random (0, 360), 2, random (40, 90));
				A_SpawnProjectile ("PBExplosionparticles2", 0, 0, random (0, 360), 2, random (40, 90));
				A_SpawnProjectile ("PBExplosionparticles3", 10, 0, random (0, 360), 2, random (40, 90));
			}
			TNT1 A 0 A_Jump(256, "Spawn1", "Spawn2", "Spawn3");
		Spawn1:
			X004 ABCDE 1 bright Light("EXPLOSIONFLASH");
			X004 FGHIJKLMNOPQ 1 bright;
			stop;
		Spawn2:
			X003 ABCDE 1 bright Light("EXPLOSIONFLASH");
			X003 FGHIJKLMNOPQRSTUVWXYZ 1 bright;
			stop;
		Spawn3:
			X125 ABCDE 1 bright Light("EXPLOSIONFLASH");
			X125 FGHIJKLMNOPQR 1 bright;
			Stop;
	}
}
