class PB_MGNail : PB_Projectile
{
	Default
	{
		PB_Projectile.BaseDamage 20;
		PB_Projectile.RipperCount 5;
		Damagetype "Nail";
		DeathSound "Weapons/NailHit";
		Scale 0.5;
		Speed 100;
		RenderStyle "Normal";
		
		Obituary "%o was filled with nails by %k.";
	}
	
	States
	{
		Spawn:
			TNT1 A 0;
			NLPJ A 1 A_StartSound("Weapons/NailFlight", CHAN_BODY, CHANF_LOOP, 1.0 );
			Goto Fly;
		Fly:
			TNT1 A 0;
			NLPJ A 1;
			Loop;
		Crash:
		Death:
			TNT1 A 0 A_StopSound(CHAN_BODY);
			TNT1 A 0 A_SpawnItemEx("HitPuff");
			TNT1 A 0 A_Stop();
			NLPJ A 70 ;
			NLPJ A 4200;
			NLPJ AAAAA 1  A_FadeOut(0.2,FTF_REMOVE | FTF_CLAMP);
			Stop;
		XDeath:
			TNT1 A 0 A_StopSound(CHAN_BODY);
			NLPJ B 0 A_StartSound("Weapons/NailHitBleed");
			Stop;
	}
}

class PB_MGNailHot : PB_MGNail
{
	Default
	{
		PB_Projectile.BaseDamage 25;
		PB_Projectile.RipperCount 6;
		
		Damagetype "Nail";
		Speed 120;
		Obituary "%o was filled with hot nails by %k.";
	}
	
	States
	{
		Spawn:
			TNT1 A 0;
			NLPJ B 1 BRIGHT A_StartSound("Weapons/NailFlight", CHAN_BODY, CHANF_LOOP, 1.0 );
			Goto Fly;
		Fly:
			TNT1 A 0;
			NLPJ B 1 BRIGHT A_SpawnItemEx("GunFireSmoke",0,0,-2,-7);
			Loop;
		Crash:
		Death:
			TNT1 A 0 A_StopSound(CHAN_BODY);
			TNT1 A 0 A_SpawnItemEx("HitPuff");
			TNT1 A 0 A_SpawnItemEx("TinyBurningPiece", random (-45, 45), random (-45, 45));
			TNT1 A 0 A_SpawnItem("ExplosionParticleSpawner");
			TNT1 A 0 A_Stop();
			NLPJ B 70 BRIGHT A_SpawnItemEx("GunFireSmoke",0,0,-2,-7);
			TNT1 A 0 A_SpawnItemEx("GunFireSmoke",0,0,-2,-7);
			NLPJ A 4200;
			NLPJ AAAAA 1  A_FadeOut(0.2,FTF_REMOVE | FTF_CLAMP);
			Stop;
		XDeath:
			TNT1 A 0 A_StopSound(CHAN_BODY);
			NLPJ B 0 A_StartSound("Weapons/NailHitBleed");
			Stop;
	}
}

class PB_JavelinProjectile : PB_Projectile
{
	Default
	{
		PB_Projectile.BaseDamage 360;
		PB_Projectile.RipperCount 4;
		
		Damagetype "Blast";
		DeathSound "Weapons/NailHit";
		Scale 1.2;
		Speed 75;
		Radius 6;
		Height 6;
		RenderStyle "Normal";
		Gravity 0.14;
		
		Obituary "%o was filled with bullets by %k.";
	}
	
	States
	{
		Spawn:
			TNT1 A 0;
			NAIL B 1 BRIGHT A_StartSound("Weapons/NailFlight", CHAN_BODY,CHANF_LOOP, 1.0);
			Goto Fly;
		Fly:
			TNT1 A 0;
			NAIL B 1;
			Loop;
		Crash:
		Death:
			TNT1 A 0
			{
				A_StopSound(CHAN_BODY);
				bNOGRAVITY = true;
				A_SpawnItemEx("HitPuff");
				A_Stop();
				
				for(int i = 0; i < 4; i++)
				{
					A_SpawnProjectile ("HitSpark", 2, 0, frandom(0,1)*frandom (0, 360), 2, frandom(0,1)*frandom (30, 360));
					A_SpawnProjectile ("HitSpark22", 2, 0, frandom(0,1)*frandom (0, 360), 2, frandom(0,1)*frandom (30, 360));
					A_SpawnProjectile ("HitSpark23", 2, 0, frandom(0,1)*frandom (0, 360), 2, frandom(0,1)*frandom (30, 360));
				}
			}
			NAIL B 70 ;
			NAIL BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB 1 A_FadeOut(0.02);
			Stop;
		XDeath:
			TNT1 A 0 A_StopSound(CHAN_BODY);
			NAIL B 0 A_StartSound("Weapons/NailHitBleed");
			Stop;
	}
}

class PB_JavelinProjectile_Hot : PB_Projectile
{
	Default
	{
		PB_Projectile.BaseDamage 420;
		PB_Projectile.RipperCount 7;
		
		Damagetype "Blast";
		DeathSound "Weapons/NailHit";
		Scale 1.2;
		Speed 100;
		Radius 6;
		Height 6;
		RenderStyle "Normal";
		Gravity 0.14;
		
		Obituary "%o was filled with bullets by %k.";
	}
	
	States
	{
		Spawn:
			TNT1 A 0;
			NAIL A 1 BRIGHT A_StartSound("Weapons/NailFlight", CHAN_BODY, CHANF_LOOP, 1.0);
			Goto Fly;
		Fly:
			TNT1 A 0;
			NAIL A 1;
			Loop;
		Crash:
		Death:
			TNT1 A 0
			{
				A_StopSound(CHAN_BODY);
				bNOGRAVITY = true;
				A_SpawnItem("HitPuff");
				A_Stop();
				
				for(int i = 0; i < 4; i++)
				{
					A_SpawnProjectile ("HitSpark", 2, 0, frandom(0,1)*frandom (0, 360), 2, frandom(0,1)*frandom (30, 360));
					A_SpawnProjectile ("HitSpark22", 2, 0, frandom(0,1)*frandom (0, 360), 2, frandom(0,1)*frandom (30, 360));
					A_SpawnProjectile ("HitSpark23", 2, 0, frandom(0,1)*frandom (0, 360), 2, frandom(0,1)*frandom (30, 360));
					A_SpawnItemEx("TinyBurningPiece", random (-45, 45), random (-45, 45));
				}
			}
			TNT1 A 0 A_SpawnItemEx ("RedFlare",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
			TNT1 A 0 A_SpawnItem("ExplosionParticleSpawner");
			NAIL B 70 ;
			NAIL BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB 1 A_FadeOut(0.02);
			Stop;
		XDeath:
			TNT1 A 0 A_StopSound(CHAN_BODY);
			NAIL A 0 A_StartSound("Weapons/NailHitBleed");
			Stop;
	}
}

class PB_MicroMissileProjectile : PB_Projectile
{
	Default
	{
		Radius 6;
		Height 6;
		Speed 45;
		DamageType "Explosive";
		Gravity 1;
		Scale 0.38;
		Decal "Scorch";
		SeeSound "weapons/RLL";
		Obituary "$OB_MPROCKET";
		
		PB_Projectile.BaseDamage 35;
		PB_Projectile.RipperCount 0;
	}
	
	States
	{
		Spawn:
			MICR A 1 BRIGHT;
			MICR A 1 BRIGHT A_StartSound("weapons/rocketloop",105,CHANF_LOOP);
		Fly:
			MICR AAAABBBBCCCCAAAABBBBCCCC 1 Bright Light("ROCKET")
			{
				if(waterlevel < 1) {
					A_SpawnItemEx("RocketTrailSparks",-10,0,0,-5,0,0);
				}
			}
		Fly2: //for makin it fly off in different directions
			MICR AAABBBCCC 1 Bright Light("ROCKET")
			{
				A_Weave(3,3,frandom(-5,5),frandom(-5,5));
				if(waterlevel < 1)
				{
					A_SpawnItemEx("RocketTrailSparks",-10,0,0,-5,0,0);
				}
			}
			loop;
		Crash:
		XDeath:
		Death:
			TNT1 A 0;
			TNT1 A 0
			{
				A_Explode((70), 50);
				A_StopSound(105);
				A_StartSound("FAREXPL", CHAN_AUTO,CHANF_OVERLAP,0.5,0,1.1);
				Radius_Quake (2, 4, 0, 7, 0);
				A_SpawnItemEx ("DetectFloorCrater",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
				A_SpawnItemEx ("DetectCeilCrater",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
				A_SpawnItemEx ("ExplosionFlareSpawner",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
				A_SpawnItemEx ("LiquidExplosionEffectSpawner",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
				A_SpawnProjectile ("ExplosionSmokeFast22", 0, 0, random (0, 360), 2, random (0, 360));
				A_SpawnProjectile ("MediumExplosionFlames", 0, 0, random (0, 360), 2, random (0, 360));
				A_SpawnProjectile ("PBExplosionparticles", 0, 0, random (0, 360), 2, random (40, 90));
				A_SpawnProjectile ("PBExplosionparticles2", 0, 0, random (0, 360), 2, random (40, 90));
				A_SpawnProjectile ("PBExplosionparticles3", 10, 0, random (0, 360), 2, random (40, 90));
			}
			TNT1 A 0 A_Jump(256, "Spawn1", "Spawn2", "Spawn3");
		Spawn1:
			X004 ABCDE 1 bright Light("EXPLOSIONFLASH");
			X004 FGHIJKLMNOPQ 1 bright;
			stop;
		Spawn2:
			X003 ABCDE 1 bright Light("EXPLOSIONFLASH");
			X003 FGHIJKLMNOPQRSTUVWXYZ 1 bright;
			stop;
		Spawn3:
			X125 ABCDE 1 bright Light("EXPLOSIONFLASH");
			X125 FGHIJKLMNOPQR 1 bright;
			Stop;
	}
}