//[inkoalawetrust]: Make the ripping nailgun projectiles stick on the last actor they rip.
//NOTE: This uses the tracer pointer because PB_Projectile has +HITTRACER on by default.

class PB_NailgunGlue : PB_ProjectileAlt abstract //this needs to be an inherited class rather than a mixin so that the handler can properly check for it (see PBHandler.zc)
{
	int lifetime;
	
	Override Void OnExplode (Int Type)
	{
		Super.OnExplode (Type);
		
		//IDEA: Maybe for bleeding actors have the nail spawn the actors' blood occasionally on the spot it landed at ? Especially for larger ones like javelins.
		//BUG: Due to Brutal Spaghetti, this will often lead to nails sticking on those stupid headshot targets that immediately despawn. No way around it.
		If ((Type == EType_Actor || Type == EType_BleedingActor))
		{
			StickOnVictim = True;
			HitOffsets = Level.Vec3Diff (Tracer.Pos,Pos);
			If (GetClassName() != "PB_MGNailHot" && GetClassName() != "PB_JavelinProjectile_Hot")
				BleedAmount = Random (16,32);
		}
	}
	
	override int Handle_MissileHit(Actor Victim)
	{
		stuckVictim = Victim;
		return Super.Handle_MissileHit(Victim);
	}
	
	Bool StickOnVictim;
	Vector3 HitOffsets;
	Int BleedAmount; //How many times the final victim of the nail should bleed. Only appears on standard nails and javelins.
	Actor stuckVictim;
	
	//wall-sticking is modified from painslayer, by agent_ash (gplv3). see painslayer-license
		protected transient F3DFloor hit_3dfloor;
		protected Line hit_line;
		protected int hitplane; //0: none, 1: floor, 2: ceiling
		protected actor stickobject; //a non-monster object that was hit
		protected transient SecPlane stickplane; //a plane to stick to (has to be transient, can't be recorded into savegames)
		protected vector2 sticklocation; //the point at the line the stake collided with
		protected double stickoffset; //how far the stake is from the nearest ceiling or floor (depending on whether it hit top or bottom part of the line)
		protected double topz; //ZAtPoint below stake
		protected double botz; //ZAtPoint above stake
		bool stuckToSecPlane; //a non-transient way to record whether it stuck to a wall. Used by PK_StakeStickHandler
	
	Override Void Tick()
	{
		Super.Tick();
		
		//If you are supposed to stick on victims, check if you hit (No longer a missile), and if you have a pointer to the victim.
		If ((!IsFrozen() || Tracer && Tracer.bNoTimeFreeze) && StickOnVictim && !bMissile && Tracer && Tracer.bSolid)
		{
			SetOrigin (PB_Math.Vec3OffsetRelative (Tracer,HitOffsets),True); //https://www.youtube.com/watch?v=EXjfvx-k1Ms
			If (stuckVictim && stuckVictim.bISMONSTER && !stuckVictim.bNOBLOOD && BleedAmount && Random (0, 255) < 16)
			{
				BleedAmount--;
				stuckVictim.SpawnBlood (Pos,AngleTo (Tracer),20);
			}
		}
		
		If (bNoGravity && StickOnVictim && (!tracer || tracer && !tracer.bSOLID)) //Victim died and fell, fall down too now that you're unstuck.
		{
			bNoGravity = StickOnVictim = False;
			Gravity = 1.0;
		}
		
		if (bTHRUACTORS) {
			topz = CurSector.ceilingplane.ZAtPoint(pos.xy);
			botz = CurSector.floorplane.ZAtPoint(pos.xy);
			/*	Destroy the stake if it's run into ceiling/floor by a moving sector 
				(e.g. a door opened, pulled the stake up and pushed it into the ceiling). 
				Only do this if the stake didn't actually hit a plane before that:
			*/
			if (!hitplane && (pos.z >= topz-height || pos.z <= botz)) {
				Destroy();
				return;
			}
			//attached to floor/ceiling:
			if (hitplane > 0) {
				FindFloorCeiling();
				if (hitplane > 1)
					SetZ(ceilingz);
				else
					SetZ(floorz);
			}
			//attached to a plane (hit a door/lift earlier)
			else if (stickplane) {
				SetZ(stickplane.ZAtPoint(sticklocation) - stickoffset);
			}
			//otherwise attach it to the solid object it hit earlier:
			else if (stickobject)
				SetZ(stickobject.pos.z + stickoffset);
		}
	}
	
	override void PostBeginPlay() {
		super.PostBeginPlay();
		lifetime = CVar.GetCVar("pb_naillifetime").GetInt() * 35;
		pitch = target.pitch;
	}
	
	//this function is called when the projectile dies and checks if it hit something
	virtual void StickToWall() {
		string myclass = GetClassName();
		bTHRUACTORS = true;
		bNOGRAVITY = true;
		A_Stop();
		
		if (stickobject) {
			stickoffset = pos.z - stickobject.pos.z;
			//if (pk_debugmessages > 2)
				//console.printf("%s hit %s at at %d,%d,%d",myclass,stickobject.GetClassName(),pos.x,pos.y,pos.z);
			return;
		}
		
		//use linetrace to get information about what we hit
		FLineTraceData trac;
		LineTrace(angle,64,pitch,TRF_NOSKY|TRF_THRUACTORS|TRF_BLOCKSELF,data:trac);
			hit_3dfloor = trac.Hit3DFloor;
			hit_Line = trac.HitLine;
			sticklocation = trac.HitLocation.xy;
		topz = CurSector.ceilingplane.ZatPoint(sticklocation);
		botz = CurSector.floorplane.ZatPoint(sticklocation);
		
		//if hit floor/ceiling, we'll attach to them:
		if (trac.HitLocation.z >= topz) {
			hitplane = 2;
			//if (pk_debugmessages > 2)
				//console.printf("%s hit ceiling at at %d,%d,%d",myclass,pos.x,pos.y,pos.z);
		}
		else if (trac.HitLocation.z <= botz) {
			hitplane = 1;
			//if (pk_debugmessages > 2)
				//console.printf("%s hit floor at at %d,%d,%d",myclass,pos.x,pos.y,pos.z);
		}
		if (hitplane > 0)
			return;
			
		//3D floor is easiest, so we start with it:
		if (hit_3dfloor) {
			stuckToSecPlane = true;
			//we simply attach the stake to the 3D floor's top plane, nothing else
			F3DFloor flr = trac.Hit3DFloor;
			stickplane = flr.top;
			stickoffset = stickplane.ZAtPoint(sticklocation) - pos.z;
			//if (pk_debugmessages > 2)
				//console.printf("%s hit a 3D floor at %d,%d,%d",myclass,pos.x,pos.y,pos.z);
			return;
		}
		//otherwise see if we hit a line:
		if (hit_Line) {
			//check if the line is two-sided first:
			let tline = hit_Line;
			//if it's one-sided, it can't be a door/lift, so don't do anything else:
			if (!tline.backsector) {
				//if (pk_debugmessages > 2)
					//console.printf("%s hit one-sided line, not doing anything else",myclass);
				return;
			}
			stuckToSecPlane = true;
			//if it's two-sided:
			//check which side we're on:
			int lside = LevelLocals.PointOnLineSide(pos.xy, tline);
			string sside = (lside == 0) ? "front" : "back";
			//we'll attach the stake to the sector on the other side:
			let targetsector = (lside == 0 && tline.backsector) ? tline.backsector : tline.frontsector;
			let floorHitZ = targetsector.floorplane.ZatPoint (sticklocation);
			let ceilHitZ = targetsector.ceilingplane.ZatPoint (sticklocation);
			string secpart = "middle";
			//check if we hit top or bottom floor (i.e. door or lift):
			if (pos.z <= floorHitZ) {
				secpart = "lower";
				stickplane = targetsector.floorplane;
				stickoffset = floorHitZ - pos.z;
			}
			else if (pos.z >= ceilHitZ) {
				secpart = "top";
				stickplane = targetsector.ceilingplane;
				stickoffset = ceilHitZ - pos.z;
			}
			//if (pk_debugmessages > 2)
				//console.printf("%s hit the %s %s part of the line at %d,%d,%d",myclass,secpart,sside,pos.x,pos.y,pos.z);
		}
	}
}

class PB_MGNail : PB_NailgunGlue {
	Default {
		PB_Projectile.BaseDamage 20;
		PB_Projectile.RipperCount 5;
		PB_Projectile.PenetrationCount 1;
        +PB_Projectile.SMALLIMPACT
		+SQUAREPIXELS
		+ROLLSPRITE
		+RIPPER
		-NOGRAVITY
		Damagetype "Nail";
		DeathSound "Weapons/NailHit";
		Scale 0.5;
		Gravity 0.75;
		Speed 100;
		
		Obituary "%o was filled with nails by %k.";
	}
	
	States {
	Spawn:
		NLPJ A 0 NoDelay A_StartSound("Weapons/NailFlight", CHAN_BODY, CHANF_LOOP, 1.0 );
	Fly:
		NLPJ A 1;
		Loop;
	XDeath:
		TNT1 A 0 {
			A_StopSound(CHAN_BODY);
			A_StartSound("Weapons/NailHitBleed");
		}
		Goto DeathLoop;
	Death:
		NLPJ A 1 { 
			A_StopSound(CHAN_BODY);
			A_SpawnItemEx("HitPuff");
			StickToWall();
		}
		Goto DeathLoop;
	DeathLoop:
		NLPJ A 35 {
			tics = lifetime;
			roll = random(15, -15);
			if(hitplane > 0) { //floor
				bXFLIP = random(0, 1);
				frame = 2;
				if(hitplane > 1) //ceiling
					roll += 180;
			}
		}
	Fade:
		#### # 1 A_FadeOut(0.05);
		Loop;
	}
}

class PB_MGNailHot : PB_MGNail {
	Default 	{
		PB_Projectile.BaseDamage 25;
		PB_Projectile.RipperCount 6;
		+USEBOUNCESTATE
		+BOUNCEONWALLS
		+BOUNCEONFLOORS
		+BOUNCEONCEILINGS
		+BRIGHT
		BounceCount 2;
		
		Speed 120;
		Obituary "%o was filled with hot nails by %k.";
	}
	
	States {
	Spawn:
		NLPJ B 0 NoDelay A_StartSound("Weapons/NailFlight", CHAN_BODY, CHANF_LOOP, 1.0);
	Fly:
		NLPJ B 1 BRIGHT A_SpawnItemEx("GunFireSmoke",0,0,-2,-7);
		Loop;
	Bounce:
		NLPJ B 1 { 
			A_SpawnItemEx("HitPuff");
			A_SpawnItemEx("TinyBurningPiece", random (-45, 45), random (-45, 45));
			A_SpawnItem("ExplosionParticleSpawner");
		}
		Goto Fly;
	XDeath:
		NLPJ B 1 {
			A_StopSound(CHAN_BODY);
			A_StartSound("Weapons/NailHitBleed");
		}
		Goto DeathLoop;
	Death:
		NLPJ B 1 { 
			A_StopSound(CHAN_BODY);
			A_SpawnItemEx("HitPuff");
			A_SpawnItemEx("TinyBurningPiece", random (-45, 45), random (-45, 45));
			A_SpawnItem("ExplosionParticleSpawner");
			StickToWall();
		}
		Goto DeathLoop;
	DeathLoop:
		NLPJ B 35 {
			tics = lifetime;
			roll = random(15, -15);
			if(hitplane > 0) { //floor
				bXFLIP = random(0, 1);
				frame = 3;
				if(hitplane > 1) //ceiling
					roll += 180;
			}
		}
		Goto Fade;
	}
}

class PB_JavelinProjectile : PB_NailgunGlue {
	Default {
		PB_Projectile.BaseDamage 360;
		PB_Projectile.RipperCount 4;
		PB_Projectile.PenetrationCount 1;
		+PB_Projectile.NOWHIZBY;
		+SQUAREPIXELS
		+ROLLSPRITE
		+RIPPER
		-NOGRAVITY
		
		Damagetype "Blast";
		DeathSound "Weapons/NailHit";
		Scale 0.5;
		Speed 75;
		Radius 6;
		Height 6;
		Gravity 0.10;
		
		Obituary "%o was nailed by %k.";
	}
	
	States {
	Spawn:
		NAIL A 0 NoDelay A_StartSound("Weapons/NailFlight", CHAN_BODY, CHANF_LOOP, 1.0);
	Fly:
		NAIL A 1;
		Loop;
	XDeath:
		TNT1 A 0 {
			A_StopSound(CHAN_BODY);
			A_StartSound("Weapons/NailHitBleed");
		}
		Goto DeathLoop;
	Death:
		NAIL A 1 { 
			A_StopSound(CHAN_BODY);
			A_SpawnItemEx("HitPuff");
			for(int i = 0; i < 4; i++) {
				A_SpawnProjectile ("HitSpark", 2, 0, frandom(0,1)*frandom (0, 360), 2, frandom(0,1)*frandom (30, 360));
				A_SpawnProjectile ("HitSpark22", 2, 0, frandom(0,1)*frandom (0, 360), 2, frandom(0,1)*frandom (30, 360));
				A_SpawnProjectile ("HitSpark23", 2, 0, frandom(0,1)*frandom (0, 360), 2, frandom(0,1)*frandom (30, 360));
			}
			StickToWall();
		}
		Goto DeathLoop;
	DeathLoop:
		NAIL A 35 {
			tics = lifetime;
			if(hitplane > 0) { //floor
				frame = 5;
				if(hitplane > 1) //ceiling
					roll += 180;
			}
		}
	Fade:
		#### # 1 A_FadeOut(0.05);
		Loop;
	}
}

class PB_JavelinProjectile_Hot : PB_JavelinProjectile {
	Default {
		PB_Projectile.BaseDamage 420; //Extra devious blunt.
		PB_Projectile.RipperCount 7;
		PB_Projectile.PenetrationCount 1;
		
		+USEBOUNCESTATE
		+BOUNCEONWALLS
		+BOUNCEONFLOORS
		+BOUNCEONCEILINGS
		+RIPPER
		-NOGRAVITY
		BounceCount 2;
		Damagetype "Blast";
		DeathSound "Weapons/NailHit";
		Scale 0.5;
		Speed 100;
		Radius 6;
		Height 6;
		Gravity 0.10;
		
		Obituary "%o was crucified by %k.";
	}
	
	States {
	Spawn:
		TNT1 A 0;
		NAIL B 1 BRIGHT A_StartSound("Weapons/NailFlight", CHAN_BODY, CHANF_LOOP, 1.0);
		Goto Fly;
	Bounce:
		TNT1 A 0 {
			A_SpawnItem("HitPuff");
			for(int i = 0; i < 4; i++)
			{
				A_SpawnProjectile ("HitSpark", 2, 0, frandom(0,1)*frandom (0, 360), 2, frandom(0,1)*frandom (30, 360));
				A_SpawnProjectile ("HitSpark22", 2, 0, frandom(0,1)*frandom (0, 360), 2, frandom(0,1)*frandom (30, 360));
				A_SpawnProjectile ("HitSpark23", 2, 0, frandom(0,1)*frandom (0, 360), 2, frandom(0,1)*frandom (30, 360));
				A_SpawnItemEx("TinyBurningPiece", random (-45, 45), random (-45, 45));
			}
		}
	Fly:
		TNT1 A 0;
		NAIL B 1 BRIGHT A_SpawnItemEx("GunFireSmoke",0,0,-2,-7);
		Loop;
	XDeath:
		TNT1 A 0 {
			A_StopSound(CHAN_BODY);
			A_StartSound("Weapons/NailHitBleed");
		}
		Goto DeathLoop;
	Death:
		NAIL A 1 { 
			A_StopSound(CHAN_BODY);
			A_SpawnItemEx("HitPuff");
			for(int i = 0; i < 4; i++) {
				A_SpawnProjectile ("HitSpark", 2, 0, frandom(0,1)*frandom (0, 360), 2, frandom(0,1)*frandom (30, 360));
				A_SpawnProjectile ("HitSpark22", 2, 0, frandom(0,1)*frandom (0, 360), 2, frandom(0,1)*frandom (30, 360));
				A_SpawnProjectile ("HitSpark23", 2, 0, frandom(0,1)*frandom (0, 360), 2, frandom(0,1)*frandom (30, 360));
				A_SpawnItemEx("TinyBurningPiece", random (-45, 45), random (-45, 45));
				A_SpawnItemEx ("RedFlare");
				A_SpawnItemEx("ExplosionParticleSpawner");
			}
			StickToWall();
		}
	DeathLoop:
		NAIL # 0 {
			if(hitplane > 0) { //floor
				frame = 5;
				if(hitplane > 1) //ceiling
					roll = 180;
			}
		}
		NAIL #### 35 {
			if(lifetime <= 0) return resolvestate("FadeOut");
			lifetime -= 35;
			frame++;
			return resolvestate(null);
		}
		NAIL A 35 {
			tics = lifetime;
			if(hitplane > 0)
				frame = 5;
		}
		Goto Fade;
	}
}