class PB_MGNail : PB_Projectile
{
	Default
	{
		PB_Projectile.BaseDamage 10;
		PB_Projectile.RipperCount 2;
		
		Damagetype "Nailgun";
		DeathSound "Weapons/NailHit";
		Scale 0.5;
		Speed 60;
		RenderStyle "Normal";
		
		Obituary "%o was filled with bullets by %k.";
	}
	
	States
	{
		Spawn:
			TNT1 A 0;
			NLPJ A 1 A_PlaySound("Weapons/NailFlight", CHAN_BODY,1.0,True);
			Goto Fly;
		Fly:
			TNT1 A 0;
			NLPJ A 1 A_SpawnItemEx("NailBlur", 0, 0, 0, 1, 0, 0, 180, 128);
			Loop;
		Crash:
		Death:
			TNT1 A 0 A_StopSound(CHAN_BODY);
			TNT1 A 0 A_SpawnItem("HitPuff");
			TNT1 A 0 A_Stop();
			NLPJ A 70 ;
			NLPJ AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA 1 A_FadeOut(0.02);
			Stop;
		XDeath:
			TNT1 A 0 A_StopSound(CHAN_BODY);
			NLPJ B 0 A_PlaySound("Weapons/NailHitBleed");
			Stop;
	}
}

class PB_JavelinProjectile : PB_Projectile
{
	Default
	{
		PB_Projectile.BaseDamage 60;
		PB_Projectile.RipperCount 4;
		
		Damagetype "Blast";
		DeathSound "Weapons/NailHit";
		Scale 1.2;
		Speed 75;
		Radius 6;
		Height 6;
		RenderStyle "Normal";
		Gravity 0.14;
		
		Obituary "%o was filled with bullets by %k.";
	}
	
	States
	{
		Spawn:
			TNT1 A 0;
			NAIL B 1 BRIGHT A_PlaySound("Weapons/NailFlight", CHAN_BODY,1.0,True);
			Goto Fly;
		Fly:
			TNT1 A 0;
			NAIL B 1;
			Loop;
		Crash:
		Death:
			TNT1 A 0
			{
				A_StopSound(CHAN_BODY);
				A_ChangeFlag("NOGRAVITY",1);
				A_SpawnItem("HitPuff");
				A_Stop();
				
				for(int i = 0; i < 4; i++)
				{
					A_CustomMissile ("HitSpark", 2, 0, frandom(0,1)*frandom (0, 360), 2, frandom(0,1)*frandom (30, 360));
					A_CustomMissile ("HitSpark22", 2, 0, frandom(0,1)*frandom (0, 360), 2, frandom(0,1)*frandom (30, 360));
					A_CustomMissile ("HitSpark23", 2, 0, frandom(0,1)*frandom (0, 360), 2, frandom(0,1)*frandom (30, 360));
				}
			}
			NAIL B 70 ;
			NAIL BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB 1 A_FadeOut(0.02);
			Stop;
		XDeath:
			TNT1 A 0 A_StopSound(CHAN_BODY);
			NAIL B 0 A_PlaySound("Weapons/NailHitBleed");
			Stop;
	}
}

class PB_JavelinProjectile_Hot : PB_Projectile
{
	Default
	{
		PB_Projectile.BaseDamage 90;
		PB_Projectile.RipperCount 4;
		
		Damagetype "Blast";
		DeathSound "Weapons/NailHit";
		Scale 1.2;
		Speed 100;
		Radius 6;
		Height 6;
		RenderStyle "Normal";
		Gravity 0.14;
		
		Obituary "%o was filled with bullets by %k.";
	}
	
	States
	{
		Spawn:
			TNT1 A 0;
			NAIL A 1 BRIGHT A_PlaySound("Weapons/NailFlight", CHAN_BODY,1.0,True);
			Goto Fly;
		Fly:
			TNT1 A 0;
			NAIL A 1;
			Loop;
		Crash:
		Death:
			TNT1 A 0
			{
				A_StopSound(CHAN_BODY);
				A_ChangeFlag("NOGRAVITY",1);
				A_SpawnItem("HitPuff");
				A_Stop();
				
				for(int i = 0; i < 4; i++)
				{
					A_CustomMissile ("HitSpark", 2, 0, frandom(0,1)*frandom (0, 360), 2, frandom(0,1)*frandom (30, 360));
					A_CustomMissile ("HitSpark22", 2, 0, frandom(0,1)*frandom (0, 360), 2, frandom(0,1)*frandom (30, 360));
					A_CustomMissile ("HitSpark23", 2, 0, frandom(0,1)*frandom (0, 360), 2, frandom(0,1)*frandom (30, 360));
					A_SpawnItemEx("TinyBurningPiece", random (-45, 45), random (-45, 45));
				}
			}
			TNT1 A 0 A_SpawnItemEx ("RedFlare",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
			TNT1 A 0 A_SpawnItem("ExplosionParticleSpawner");
			NAIL B 70 ;
			NAIL BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB 1 A_FadeOut(0.02);
			Stop;
		XDeath:
			TNT1 A 0 A_StopSound(CHAN_BODY);
			NAIL A 0 A_PlaySound("Weapons/NailHitBleed");
			Stop;
	}
}