//[nV] the lmg's sprites use the same 7.62x51mm cartridge as the heavy dmr, but it actually fires this.
class PB_556x45mm : PB_Projectile //carbine, dmr, lmg
{
	Default
	{
		PB_Projectile.BaseDamage 22;
		PB_Projectile.RipperCount 3;
		PB_Projectile.PenetrationCount 3;
		//[nV] in reality this should be higher and the 7.62x51mm should be lower, but for balance reasons they have to be like this. despite this both should technically be possible with the right gun and ammo.
		PB_Projectile.SpeedFPS 2790;
		+PB_Projectile.WHIZCRACK;
		Obituary "%o was filled with holes by %k.";
	}
}

//[nV] interestingly, this seems to imply the minigun is a descendant of the ill-fated xm214 microgun.
class PB_556x45mmAP : PB_Projectile //minigun
{
	Default
	{
		PB_Projectile.BaseDamage 25;
		PB_Projectile.RipperCount 1;
		PB_Projectile.PenetrationCount 3;
		PB_Projectile.SpeedFPS 3250;
		-RIPPER;
		+PB_Projectile.WHIZCRACK;
		+PB_Projectile.SMALLIMPACT;
		Obituary "%o was torn to shreds by %k.";
		Damagetype "Cutless";
	}
}

class PB_762x51mm : PB_Projectile //hdmr
{
	Default
	{
		PB_Projectile.BaseDamage 35;
		PB_Projectile.RipperCount 4;
		PB_Projectile.PenetrationCount 3;
		PB_Projectile.SpeedFPS 2810;
		+PB_Projectile.WHIZCRACK;
		Obituary "%o was shredded by %k.";
	}
}

class PB_762x51mmAP : PB_Projectile //hdmr sniper
{
	Default
	{
		PB_Projectile.BaseDamage 165;
		PB_Projectile.RipperCount 8;
		PB_Projectile.PenetrationCount 3;
		PB_Projectile.SpeedFPS 2880;
		RipperLevel 1;
		+PB_Projectile.WHIZCRACK;
		Obituary "%o was shredded by %k.";
	}
}

class PB_792x57mm : PB_Projectile //mg 42
{
	Default
	{
		PB_Projectile.BaseDamage 40;
		PB_Projectile.RipperCount 5;
		PB_Projectile.PenetrationCount 3;
		PB_Projectile.SpeedFPS 2428;
		+PB_Projectile.WHIZCRACK;
		+PB_Projectile.SMALLIMPACT;
		Obituary "%k forced %o to read Mein Kampf.";
	}
}
