//////Imp Actor//////

Class PB_Imp : PB_Monster
{
	Default
		{
		Monster;
		Radius 16;
		Height 48;
		Speed 9;
		FastSpeed 10;
		MaxStepHeight 24;
		MaxDropOffHeight 48;
		Mass 120;
		SeeSound "imp/sight";
		PainSound "imp/pain";
		DeathSound "imp/death";
		ActiveSound "imp/active";
		BloodType "NashGoreBlood", "NashGoreBlood", "NashGoreBlood";
		Health 140;
		PainChance 200;
		PainChance "Avoid", 64;
		PainChance "Head", 255;
		PainChance "Kick", 255;
		PainChance "ExtremePunches", 255;
		PainChance "Melee", 255;
		PainChance "Taunt", 255;
		PainChance "MonsterKnocked", 255;
		PainChance "ExplosiveImpact", 255;
		PainChance "Trample", 255;
		PainChance "Stun", 255;
		PainChance "Siphon", 255;
		PainChance "Fire", 12;
		PainChance "Flames", 12;
		PainChance "Burn", 12;
		PainChance "Ice", 255;
		PainChance "Freeze", 255;
		damagefactor "Fire", 0.4;
		damagefactor "Flames", 0.4;
		damagefactor "Burn", 0.4;
		damagefactor "Ice", 1.6;
		damagefactor "Freeze", 1.6;
		damagefactor "Crush", 5.0;
		damagefactor "Avoid", 1.0;
		damagefactor "GibRemoving", 0.0;
		damagefactor "DontCallTheBaron", 0.0;
		damagefactor "Blood", 0.0; damagefactor "BlueBlood", 0.0; damagefactor "GreenBlood", 0.0;
		damagefactor "Kick", 0.4;
		damagefactor "Shrapnel", 0.4;
		damagefactor "ExplosiveImpact", 0.6;
		damagefactor "killme", 0.0;
		damagefactor "Taunt", 1.0;
		DamageFactor "CauseObjectsToSplash", 0.0;
		damagefactor "TeleportRemover", 0.0;
		damagefactor "SSG", 50.0;
		damagefactor "Shotgun", 1.2;
		damagefactor "Saw", 0.5;
		damagefactor "Cut", 0.75;
		damagefactor "Tear", 0.25;
		DropItem "DemonStrengthRune", 1;
		DropItem "DemonPickup", 60;
		HitObituary "$OB_IMPHIT";
		Obituary "$OB_IMPHIT";
		+FLOORCLIP;
		+SLIDESONWALLS;
		+DOHARMSPECIES;
		+HARMFRIENDS;
		Species "Imp";
		}
		
		int movement_direction;
		
		override void PostBeginPlay() {
			Super.PostBeginPlay(); // call the super function for virtual functions so we don't break shit if GZdoom update.
			HitBoxSpawned = False;
		
		}
		
		override void Tick()
		{
			Super.Tick();
			
			// Update recognition if pouncing
			if(self.InStateSequence(self.Curstate, self.ResolveState("Pounce"))) {
				self.Height = 28;
			}
			else {
				self.Height = 58;
			}
			
			//Handle Hitbox system
			HitboxerHandler();
			
		}
		
	States
		{
//////Base States//////
	Spawn:
		TROO A 1;
		TNT1 A 0 A_GiveInventory("SKImp", 1);
		TNT1 A 0 A_JumpIf(waterlevel == 2, "Swim");
		TNT1 A 0 A_JumpIf(waterlevel == 3, "Swim");
        TNT1 A 0 A_JumpIfInventory("Fatality_Marine", 1, "FatalityMarine");
	
	Stand:	
		TROS AB 10 A_Look();
	Loop;
	
	See:
		TNT1 A 0 {
				A_TakeInventory("SKImp", 1);
				EnemyLastSighted = Level.MapTime;
			}
		TROT A 2 A_faceTarget();
		TROT B 2;
		TROT C 2;
	
	SeeContinue:
        TNT1 A 0 A_JumpIfInventory("Fatality_Marine", 1, "FatalityMarine");
        TNT1 A 0 A_JumpIf(waterlevel == 2, "Swim");
		TNT1 A 0 A_JumpIf(waterlevel == 3, "Swim");
		TROO AA 2 A_SmartChase();
		TNT1 A 0 A_Recoil(-1);
		TROO AA 2 A_SmartChase();
		TNT1 A 0 A_PlaySound("flesh/step",4);
        TNT1 A 0 A_TakeInventory("SKImp", 1);
		TROO BB 2 A_SmartChase();
		TROO BB 2 A_SmartChase();
		TROO CC 2 A_SmartChase();
		TROO CC 2 A_SmartChase();
		TNT1 A 0 A_PlaySound("flesh/step",4);
		TROO DD 2 A_SmartChase();
		TROO DD 2 A_SmartChase();
	Loop;
	
	Idle:
	LookingForPlayer:
	    TNT1 A 0 A_GiveInventory("SKImp", 1);
		TROO B 10 A_Look();
		TROS B 10 A_Look();
		TROO B 10 A_Look();
		TNT1 A 0 A_SetAngle(angle - 40);
		TROO B 10 A_Look();
		TROS B 10 A_Look();
		TROO B 10 A_Look();
		TNT1 A 0 A_SetAngle(angle + 40);
		TROS B 10 A_Look();
		TROO B 10 A_Look();
		TROS B 10 A_Look();
		TROO A 0 A_Wander();
		TROO AA 2 A_Look();
		TNT1 A 0 A_PlaySound("flesh/step",4);
		TNT1 A 0 A_Recoil(-2);
		TROO B 0 A_Wander();
		TROO BB 2 A_Look();
		TNT1 A 0 A_Recoil(-2);
		TROO C 0 A_Wander();
		TROO CC 2 A_Look();
		TNT1 A 0 A_PlaySound("flesh/step",4);
		TNT1 A 0 A_Recoil(-2);
		TROO D 0 A_Wander();
		TROO DD 2 A_Look();
		TNT1 A 0 A_jump(128, "LookingForPlayer");
		TNT1 A 0 A_Recoil(-2);
		TROO A 0 A_Wander();
		TROO AA 2 A_Look();
		TNT1 A 0 A_PlaySound("flesh/step",4);
		TNT1 A 0 A_Recoil(-2);
		TROO B 0 A_Wander();
		TROO BB 2 A_Look();
		TNT1 A 0 A_jump(128, "LookingForPlayer");
		TNT1 A 0 A_Recoil(-2);
		TROO C 0 A_Wander();
		TROO CC 2 A_Look();
		TNT1 A 0 A_PlaySound("flesh/step",4);
		TNT1 A 0 A_Recoil(-2);
		TROO D 0 A_Wander();
		TROO DD 2 A_Look();
		TNT1 A 0 A_Recoil(-2);
	Goto LookingForPlayer;
	
	Advancing:	
		TNT1 A 0 {
				A_TakeInventory("CantFire", 1);
				return A_JumpIfInventory("EnemyMemory", 20, "ForgetTarget");
			}
		TROO AA 4 A_SmartChase();
        TNT1 A 0 A_TakeInventory("SKImp", 1);
		TROO BB 4 A_SmartChase();
		TROO CC 4 A_SmartChase();
		TROO DD 4 A_SmartChase();
	Loop;
	
	FallBack:
	Goto Melee;
	
	GetUp:
		TNT1 A 0 {
				A_SpawnItem("LargeMassWaterImpact");
				A_SpawnItem("SmallUnderwaterExplosion");
				return A_JumpIf(waterlevel == 2, "Swim");
				return A_JumpIf(waterlevel == 3, "Swim");
				{bGHOST = true;}
				{bNOPAIN = false;}
				{bSOLID = false;}
				{bFORCEXYBILLBOARD = true;}
				A_GiveInventory("ISDOWN", 1);
				return A_JumpIfInventory ("FallingHeight", 12, "FallingDie");
			}
		IZD4 MMMMMMMM 5 A_JumpIf(Vel.Z < 0, "FallingAfterImpact");
		TNT1 A 0 {
				{bSOLID = true;}
				{bFORCEXYBILLBOARD = false;}
				A_TakeInventory("ISDOWN", 1);
				A_TakeInventory("FallingHeight", 100);
				A_TakeInventory("IsDown", 1);
			}
		IZD4 NO 7;
         Goto SeeContinue;
	
	FallingAfterImpact:
		IZD4 L 1 {
				{bNOGRAVITY = false;}
				{bTHRUSPECIES = false;}
				{bCEILINGHUGGER = false;}
				A_GiveInventory ("FallingHeight", 1);
				return A_JumpIf(waterlevel == 2, "Swim");
				return A_JumpIf(waterlevel == 3, "Swim");
			}
		NULL A 0 A_CheckFloor ("GetUp");
		NULL A 0 A_JumpIf (Vel.Z == 0, "GetUp");
	Loop;
	
	Possession:
		TNT1 A 0 A_SetInvulnerable();
		TROO H 3;
		TROO H 3 A_Pain();
		"####" "#" 35 ACS_NamedExecuteAlways("Pos - Flicker effect");
		TNT1 A 0 A_UnSetInvulnerable();
	Goto See;
	
	Raise:
		TROO MLKJI 8;
	Goto See;
	
	Swim:
	TNT1 A 0 {
			A_NoBlocking();
			A_Fall();
			A_SpawnItem("ImpFish");
		}
	Stop;
	
//////Attacks//////
	
	Melee:
		TNT1 A 0 A_JumpIfCloser(50, "Claw");
		TNT1 A 0 A_Jump(72, "JumpSlash");
		TNT1 A 0 A_Jump(132, "Pounce");
	GoTo JumpSlash;
	
	Claw:
        TROO EF 4 A_FaceTarget();
        TROO G 4 A_SpawnProjectile("ImpAttack",10,0,0,0);
        TROO FE 4;
		TNT1 A 0 A_JumpIfCloser(50, "Claw");
	Goto SeeContinue;
	
	JumpSlash:
		TROO E 1 {
				A_FaceTarget();
				return A_JumpIfCloser(50, "Claw");
			}
		TROT CD 4 {
				ThrustThingZ(0,20,0,1);
				A_FaceTarget();
				A_Recoil (-10);
			}
		TROT E 2;
		TROT F 2 {
				A_GiveInventory ("IsJumping");
				A_StartSound("weapons/fistwhoosh");
				A_FaceTarget();
			}
        TROT F 6 {
				A_SpawnProjectile("ImpAttack2",10,0,0,0);
				A_TakeInventory ("IsJumping");
				return A_JumpIfInventory("Fatality_Marine", 1, "FatalityMarine");
			}
		TROT G 6 { 
				A_SpawnProjectile("ImpAttack2",10,0,0,0);
				return A_JumpIfInventory("Fatality_Marine", 1, "FatalityMarine");
			}
		TROT H 6 A_JumpIfInventory("Fatality_Marine", 1, "FatalityMarine");
	Goto SeeContinue;
	
	Pounce:
	TNT1 A 0 {
				A_FaceTarget();
				A_StartSound("imp/sight",6);
			}
        1M40 ABCD 4 A_Recoil (-1);
		TNT1 A 0 A_JumpIfCloser(50, "Claw");
		1M40 A 5 {
				A_FaceTarget();
				ThrustThingZ(0,25,0,1);
				A_FaceTarget();
				A_Recoil (-10);
			}
		1M40 E 6 {
				A_GiveInventory ("IsJumping");
				A_StartSound("weapons/fistwhoosh");
				A_FaceTarget();
			}
        1M40 E 4 {
				A_SpawnProjectile("ImpAttack2",10,0,0,0);
				A_TakeInventory ("IsJumping");
				return A_JumpIfInventory("Fatality_Marine", 1, "FatalityMarine");
			}
		1M40 A 4 {
				A_SpawnProjectile("ImpAttack2",10,0,0,0);
				return A_JumpIfInventory("Fatality_Marine", 1, "FatalityMarine");
			}
			
	Goto SeeContinue;

	Missile:
		TNT1 A 0 {
				A_SpawnProjectile("MonsterTargetCheck", 34, 0, 0, 0);
				A_SpawnProjectile("MonsterTargetCheckFaster", 34, 0, 0, 0);
				return A_JumpIfCloser(150, "Melee");
				return A_JumpIfCloser(1200, 3);
			}
		TROO E 4 {
				A_FaceTarget();
				A_Playsound ("IMPCHARG");
				A_SpawnProjectile ("SmallFlameTrails", 35, 30, random (0, 40), 2, random (0, 160));
				A_SpawnProjectile ("ImBallGettingReady", 35, 30, random (0, 140), 2, random (0, 160));
				return A_JumpIfInventory("CantFire",1, "Advancing");
				return A_JumpIfCloser(170, "Melee");
			}
		TROO E 2 {
				A_FaceTarget();
				A_SpawnProjectile ("SmallFlameTrails", 35, 30, random (0, 40), 2, random (0, 160));
				A_SpawnProjectile ("ImBallGettingReady", 35, 30, random (0, 140), 2, random (0, 160));
			}
		TROO E 2 {
				A_FaceTarget();
				A_SpawnProjectile ("SmallFlameTrails", 35, 30, random (0, 40), 2, random (0, 160));
				A_SpawnProjectile ("ImBallGettingReady", 35, 30, random (0, 140), 2, random (0, 160));
			}
		TROO E 2 {
				A_FaceTarget();
		        A_SpawnProjectile ("SmallFlameTrails", 35, 30, random (0, 40), 2, random (0, 160));
				A_SpawnProjectile ("ImBallGettingReady", 35, 30, random (0, 140), 2, random (0, 160));
			}
		TROO E 2 {
				A_FaceTarget();
		        A_SpawnProjectile ("SmallFlameTrails", 35, 30, random (0, 40), 2, random (0, 160));
				A_SpawnProjectile ("ImBallGettingReady", 35, 30, random (0, 140), 2, random (0, 160));
			}
		TROO E 2 {
				A_FaceTarget();
				A_SpawnProjectile ("SmallFlameTrails", 35, 30, random (0, 40), 2, random (0, 160));
				A_SpawnProjectile ("ImBallGettingReady", 35, 30, random (0, 140), 2, random (0, 160));
			}
		TROO F 2 A_FaceTarget();
		TROO G 6 A_SpawnProjectile("FireBall_", 34, 0, 0, 0);
		TROO F 4;
	Goto SeeContinue;
	
	FatalityMarine:
		TNT1 A 0 A_SetInvulnerable();
        IPFP ABCD 4;
        TNT1 A 0 A_SpawnItemEx("FootStep5", 0, 0, 40, 0, 0);
        IPFP EE 6;
		IPFP F 8;
	    TNT1 A 0 A_PlaySound("DSFDTHE");	    
		IPFP G 8;
		TNT1 AA 0 A_SpawnProjectile ("PB_XDeath1", 1, 0, random (0, 360), 2, random (0, 160));
        TNT1 AAAAA 0 A_SpawnProjectile ("NashGoreBloodSpurt", 25, 0, random (0, 360), 2, random (0, 160));
        IPFP H 8;
        IPFP I 8;
		TNT1 AA 0 A_SpawnProjectile ("PB_XDeath1", 1, 0, random (0, 360), 2, random (0, 160));
        TNT1 AAAAA 0 A_SpawnProjectile ("NashGoreBloodSpurt", 25, 0, random (0, 360), 2, random (0, 160));
        IPFP J 8;
        IPFP K 8;
		TNT1 AA 0 A_SpawnProjectile ("PB_XDeath1", 1, 0, random (0, 360), 2, random (0, 160));
        TNT1 AAAAA 0 A_SpawnProjectile ("NashGoreBloodSpurt", 25, 0, random (0, 360), 2, random (0, 160));
        IPFP H 8;
        IPFP I 8;
		TNT1 AA 0 A_SpawnProjectile ("PB_XDeath1", 1, 0, random (0, 360), 2, random (0, 160));
        TNT1 AAAAA 0 A_SpawnProjectile ("NashGoreBloodSpurt", 25, 0, random (0, 360), 2, random (0, 160));
        IPFP J 8;
        IPFP K 8;
		TNT1 AA 0 A_SpawnProjectile ("PB_XDeath1", 1, 0, random (0, 360), 2, random (0, 160));
        TNT1 AAAAA 0 A_SpawnProjectile ("NashGoreBloodSpurt", 25, 0, random (0, 360), 2, random (0, 160));
        IPFP H 8;
        IPFP I 8;
		TNT1 AA 0 A_SpawnProjectile ("PB_XDeath1", 1, 0, random (0, 360), 2, random (0, 160));
        TNT1 AAAAA 0 A_SpawnProjectile ("NashGoreBloodSpurt", 25, 0, random (0, 360), 2, random (0, 160));
        IPFP J 8;	   
	    IPFP L 8;
		TNT1 AA 0 A_SpawnProjectile ("PB_XDeath1", 1, 0, random (0, 360), 2, random (0, 160));
        TNT1 AAAAA 0 A_SpawnProjectile ("NashGoreBloodSpurt", 25, 0, random (0, 360), 2, random (0, 160));
        IPFP M 8;
	    TNT1 A 0 A_SpawnProjectile ("PB_Intestine", 12, 0, random (0, 360), 2, random (0, 40));
        IPFP N 8;
		TNT1 AA 0 A_SpawnProjectile ("PB_XDeath1", 1, 0, random (0, 360), 2, random (0, 160));
        TNT1 AAAAA 0 A_SpawnProjectile ("NashGoreBloodSpurt", 25, 0, random (0, 360), 2, random (0, 160));
        IPFP O 8;
	    TNT1 A 0 A_SpawnProjectile ("PB_Intestine", 12, 0, random (0, 360), 2, random (0, 40));	   
	    IPFP L 8;
		TNT1 AA 0 A_SpawnProjectile ("PB_XDeath1", 1, 0, random (0, 360), 2, random (0, 160));
        TNT1 AAAAA 0 A_SpawnProjectile ("NashGoreBloodSpurt", 25, 0, random (0, 360), 2, random (0, 160));
        IPFP M 8;
	    TNT1 A 0 A_SpawnProjectile ("PB_Intestine", 12, 0, random (0, 360), 2, random (0, 40));
        IPFP N 8;
		TNT1 AA 0 A_SpawnProjectile ("PB_XDeath1", 1, 0, random (0, 360), 2, random (0, 160));
        TNT1 AAAAA 0 A_SpawnProjectile ("NashGoreBloodSpurt", 25, 0, random (0, 360), 2, random (0, 160));
        IPFP O 8;
	    TNT1 A 0 A_SpawnProjectile ("PB_Intestine", 12, 0, random (0, 360), 2, random (0, 40));
        TNT1 A 0 {
				A_TakeInventory("Fatality_Marine",1);
				A_SpawnItem ("GrowingBloodPool");
				A_UnSetInvulnerable();
				A_SpawnItem ("MarineGotOwnedByImp", 1);
			}
	Goto See;
	
//////Painstates//////
	
	Pain.Avoid:
		TNT1 A 0 A_Jump(255, "AvoidLeft", "AvoidRight");
	Goto AvoidLeft;
	  
	AvoidLeft:
	    TROO E 1 A_FaceTarget();
		TNT1 A 0 {
				{bNOGRAVITY = false;}
				{bTHRUSPECIES = false;}
				{bCEILINGHUGGER = false;}
				ThrustThingZ(0,30,0,1);
				ThrustThing(angle*256/360+192, 10, 0, 0);
			}
        TROO NNNOOO 2 A_FaceTarget();
    Goto Missile+26;
	
	AvoidRight:
	    TROO E 1 A_FaceTarget();
		TNT1 A 0 {
				{bNOGRAVITY = false;}
				{bTHRUSPECIES = false;}
				{bCEILINGHUGGER = false;}
				ThrustThingZ(0,30,0,1);
				ThrustThing(angle*256/360+64, 10, 0, 0);
			}
        TROO NNNOOO 2 A_FaceTarget();
    Goto Missile+26;
		
	Pain:
		TNT1 A 0 {
				{bNOGRAVITY = false;}
				{bTHRUSPECIES = false;}
				{bCEILINGHUGGER = false;}
				return A_JumpIfInventory("IsDown", 1, "Pain.IsDown");
			}
		TROO H 6 A_Pain();
	Goto SeeContinue;
	
	Pain.Melee:
		TNT1 A 0 {
				{bNOGRAVITY = false;}
				{bTHRUSPECIES = false;}
				{bCEILINGHUGGER = false;}
			}
		TROO A 2;
		TNT1 A 0 A_JumpIfInventory ("SKImp", 1, "GotoStealthKill");
		TROO A 2 A_Pain();
	Goto SeeContinue;
		
	GotoStealthKill:
		TNT1 A 0 {
				A_GiveToTarget("SKImp");
				A_GiveToTarget("GoFatality", 1);
				A_Die("Stealthy");
			}
	Stop;
	
	Pain.Stun:
		TNT1 A 0 {
				{bNOGRAVITY = false;}
				{bTHRUSPECIES = false;}
				{bCEILINGHUGGER = false;}
				A_SpawnItemEx ("StunElectrocute", random (-4, 4), random (-4, 4),  random (16, 32), 0, 0);
			}
		TROO H 1 A_Pain();
		TROO HHHHHHHHHH 3 A_SpawnItemEx ("StunElectrocute", random (-12, 12), random (-12, 12),  random (16, 52), 0, 0);
		TROO H 1 A_Pain();
		TROO HHHHHHHHHH 3 A_SpawnItemEx ("StunElectrocute", random (-12, 12), random (-12, 12),  random (16, 52), 0, 0);
		TROO H 1 A_Pain();
		TROO HHHHHHHHHH 3 A_SpawnItemEx ("StunElectrocute", random (-12, 12), random (-12, 12),  random (16, 52), 0, 0);
		TROO H 1 A_Pain();
		TROO HHHHHHHHHH 3 A_SpawnItemEx ("StunElectrocute", random (-12, 12), random (-12, 12),  random (16, 52), 0, 0);
		TROO H 1 A_Pain();
	Goto See;
	
	Pain.Siphon:
		TNT1 AAA 0 A_SpawnItemEx ("RedLightning_Small", random (-12, 12), random (-12, 12), random (16, 52), 0, 0);
		TROO H 1 
		{
			{bNOGRAVITY = false;}
			{bTHRUSPECIES = false;}
			{bCEILINGHUGGER = false;}
			A_FaceTarget();
			A_GiveToTarget("HealthBonus",4);
		}
		TROO H 5 A_FaceTarget();
		TNT1 A 0 A_Pain();
	Goto See;
	
	Pain.BlackHole:
		TNT1 A 0 {
				{bNOGRAVITY = false;}
				{bTHRUSPECIES = false;}
				{bCEILINGHUGGER = false;}
			}
        IZD4 K 1 A_Pain();
        TNT1 A 0 {
				A_GiveInventory("IsDown", 1);
				ThrustThingZ(0,6,0,1);
			}
		IZD4 K 1 A_facetarget;
        IZD4 K 6 ThrustThing(angle*256/360+128, 5, 0, 0);
        IZD4 L 8;
	Goto FallingAfterImpact;
	
	Pain.head:
	Pain.minorhead:
		TNT1 A 0 {
				{bNOGRAVITY = false;}
				{bTHRUSPECIES = false;}
				{bCEILINGHUGGER = false;}
			}
		TROO H 6;
		TROO H 6 A_Pain();
	Goto SeeContinue;

	Pain.ExplosiveImpact:
	Pain.Explosive:
		TNT1 A 0 A_JumpIfInventory ("IsDown", 1, "Pain");
			IZD4 K 1 {
					{bNOGRAVITY = false;}
					{bTHRUSPECIES = false;}
					{bCEILINGHUGGER = false;}
					{bNODROPOFF = False;}
					{bFORCEXYBILLBOARD = True;}
					A_TakeInventory("SKImp", 1);
					A_GiveInventory("IsDown", 1);
					A_Pain();
					ThrustThingZ(0,30,0,1);
			}
			IZD4 K 2 A_facetarget();
			IZD4 K 1 A_Recoil(15);
			SPO4 L 8;
	Goto FallingAfterImpact;
	
    Pain.Kick:
	Pain.ExtremePunches:
         TNT1 A 0 A_JumpIfInventory ("IsDown", 1, "Pain");
			IZD4 K 1 {
					{bNOGRAVITY = false;}
					{bTHRUSPECIES = false;}
					{bCEILINGHUGGER = false;}
					{bNODROPOFF = False;}
					{bFORCEXYBILLBOARD = True;}
					A_TakeInventory("SKImp", 1);
					A_GiveInventory("IsDown", 1);
					A_Pain();
					A_facetarget();
					ThrustThingZ(0,20,0,1);
			}
			IZD4 K 1 A_facetarget();
			IZD4 K 6 A_Recoil(15);
			IZD4 L 8;
	Goto FallingAfterImpact;
	
	Pain.IsDown:
	    TNT1 A 0 {
				{bNOGRAVITY = false;}
				{bTHRUSPECIES = false;}
				{bCEILINGHUGGER = false;}
			}
	    ID11 B 1;
	    ID11 B 5 A_Pain();
	Goto GetUp;
	    
	Pain.KillMe:
    Pain.Taunt:
        TNT1 A 0;
    Goto Missile;
	
//////Basic Death States//////
  
  Death:
    TNT1 A 0 {
			{bNOGRAVITY = false;}
			{bTHRUSPECIES = false;}
			{bCEILINGHUGGER = false;}
		}
		TNT1 A 0 A_JumpIfInventory("IsJumping", 1, "DeathJump");
		TNT1 A 0 A_Jump(32, "Death.Arm");
		TNT1 A 0 A_Jump(24,"DeathNoGuts");
		TNT1 A 0 A_Jump(32,"Death20alt");
		TNT1 A 0 A_Jump(128, "DeathMirror");
		TR97 A 8 ;
		TR97 B 8 A_Scream();
		TR97 C 6;
		TR97 D 6 A_NoBlocking();
		TNT1 A 0 {
				A_SpawnItem ("GrowingBloodPool");
				A_SpawnItem("DeadImp1");
			}
	Stop;
	
	DeathMirror:
		TROO V 8;
		TROO W 8 A_Scream();
		TROO X 7 A_NoBlocking();
		TROO Y 7;
		TNT1 A 0 A_SpawnItem ("GrowingBloodPool");
		TNT1 A 0 A_SpawnItem ("DeadImpTROOY");
	Stop;
	
	StealthKill:
	TNT1 A 0 A_JumpIfInTargetInventory("FistsSelected", 1, 1);
	Goto Death;
	TNT1 A 0 {
			A_GiveToTarget("GoFatality", 1);
			A_GiveToTarget("SKImp", 1);
			A_NoBlocking();
			A_Fall();
			A_Die("Stealthy");
		}
	Stop;
	
	Death.Stealthy:	
		TNT1 A 0 A_NoBlocking();
	Stop;
	
	Death20alt:
        TNT1 A 0 {
				{bNOGRAVITY = false;}
				{bTHRUSPECIES = false;}
				{bCEILINGHUGGER = false;}
				A_Scream();
				A_NoBlocking();
			}
		TROD ABCD 6;
		TNT1 A 0 {
				A_SpawnItem ("GrowingBloodPool");
				A_SpawnItemEx ("ImpDyingOfBloodLoss", 0,0,7,0,0,0,0,SXF_NOCHECKPOSITION,0);
			}
      Stop;
	
	Death.Arm:
		TNT1 A 0 {
				{bNOGRAVITY = false;}
				{bTHRUSPECIES = false;}
				{bCEILINGHUGGER = false;}
				A_SpawnProjectile ("XDeathImpArm", 35, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH  , random (0, 160));
				A_Scream();
				A_NoBlocking();
				A_SpawnProjectile ("PB_SmallGib", 35, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH  , random (0, 160));
				A_SpawnProjectile ("PB_SmallGib", 35, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH  , random (0, 160));
				A_SpawnProjectile ("PB_MuchBlood2", 35, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH  , random (0, 160));
				A_SpawnItem ("DyingImpNoArm", 2);
			}
		TNT1 A 0 A_Jump(110, "Arm2");
	Stop;
	
	Arm2:
		T408 A 8; 
		TNT1 A 0 { 
				A_SpawnProjectile ("PB_SmallGib", 35, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH  , random (0, 160));
				A_SpawnProjectile ("PB_SmallGib", 35, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH  , random (0, 160));
				A_SpawnProjectile ("PB_MuchBlood2", 35, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH  , random (0, 160));
				A_SpawnItem ("DyingImpNoArm2", 2);
			}
	Stop;

    Death.Leg:
		TNT1 A 0 {
				{bNOGRAVITY = false;}
				{bTHRUSPECIES = false;}
				{bCEILINGHUGGER = false;}
				A_SpawnProjectile ("XDeathImpLeg", 35, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH  , random (0, 160));
				A_SpawnProjectile ("PB_MuchBlood2", 15, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH  , random (0, 160));
				A_SpawnProjectile ("PB_XDeath1", 15, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH  , random (0, 160));
				A_SpawnProjectile ("PB_SmallGib", 15, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH  , random (0, 160));
				A_SpawnProjectile ("PB_SmallGib", 15, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH  , random (0, 160));
				A_SpawnItem ("GrowingBloodPool");
				A_Scream();
			}
		TNT1 A 0 A_Jump(64, "DeathLeg2");
		TNT1 A 0 A_JumpIfInventory("IsJumping", 1, "Death.LegInTheAir");
		TR09 A 9;
		TR09 A 3 A_SpawnProjectile ("PB_XDeath1", 15, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH  , random (0, 160));
		TR09 B 3 A_Scream();
		TR09 C 3 A_NoBlocking();
        TNT1 A 0 A_SpawnItem ("DyingImpNoLeg", 5);
	Stop;
	
	DeathLeg2:
		TNT1 A 0 {
				A_NoBlocking();
				A_Fall();
				A_SpawnProjectile ("XDeathImpLeg", 35, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH  , random (0, 160));
				A_SpawnProjectile ("PB_MuchBlood2", 15, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH  , random (0, 160));
				A_SpawnProjectile ("PB_XDeath1", 15, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH  , random (0, 160));
				A_SpawnProjectile ("PB_SmallGib", 15, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH  , random (0, 160));
				A_SpawnProjectile ("PB_SmallGib", 15, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH  , random (0, 160));
				A_SpawnItem("ImpSaciLol");
			}
	Stop;
	
	Death.LegMassacre:
		TNT1 A 0 {
				{bNOGRAVITY = false;}
				{bTHRUSPECIES = false;}
				{bCEILINGHUGGER = false;}
			}
		TNT1 A 0 A_SpawnProjectile ("XDeathImpLeg", 35, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnProjectile ("PB_MuchBlood", 50, 0, random (0, 360), 2, random (0, 160));
		TR09 A 8 A_SpawnProjectile ("PB_Xdeath1", 40, 0, random (0, 360), 2, random (0, 160));
		TR09 B 8 A_Scream();
		TNT1 A 0 A_NoBlocking();
        TNT1 A 0 A_SpawnItem ("ImpBrutalizedWithNoLeg");
	Stop;

    DeathJump:
		 TNT1 A 0 {
				{bNOGRAVITY = false;}
				{bTHRUSPECIES = false;}
				{bCEILINGHUGGER = false;}
				{bNODROPOFF = false;}
				{bSLIDESONWALLS = false;}
				A_Scream();
				A_NoBlocking();
				A_Stop();
				ThrustThingZ(0,30,0,1);
				A_FaceTarget();
				A_Recoil (10);
			}
        ID11 A 4 {
				A_SpawnProjectile ("Brutal_LiquidBlood3", 15, 0, random (0, 360), 2, random (0, 40));
			}
		TNT1 A 0 A_JumpIf((Vel.Y == 0), "TakeASit");
		ID11 A 4 {
				A_SpawnProjectile ("Brutal_LiquidBlood3", 15, 0, random (0, 360), 2, random (0, 40));
			}
		TNT1 A 0 A_JumpIf((Vel.Y == 0), "TakeASit");
		ID11 B 4 {
				A_SpawnProjectile ("Brutal_LiquidBlood3", 15, 0, random (0, 360), 2, random (0, 40));
			}
		TNT1 A 0 A_JumpIf((Vel.Y == 0), "TakeASit");
		ID11 A 4 {
				A_SpawnProjectile ("Brutal_LiquidBlood3", 15, 0, random (0, 360), 2, random (0, 40));
			}
		TNT1 A 0 A_JumpIf((Vel.Y == 0), "TakeASit");
		ID11 C 4 {
				A_SpawnProjectile ("Brutal_LiquidBlood3", 15, 0, random (0, 360), 2, random (0, 40));
			}
		TNT1 A 0 A_JumpIf((Vel.Y == 0), "TakeASit");
		ID11 C 4 {
				A_SpawnProjectile ("Brutal_LiquidBlood3", 15, 0, random (0, 360), 2, random (0, 40));
			}
		TNT1 A 0 A_JumpIf((Vel.Y == 0), "TakeASit");
		ID11 D 4 {
				A_SpawnProjectile ("Brutal_LiquidBlood3", 15, 0, random (0, 360), 2, random (0, 40));
			}
		TNT1 A 0 A_JumpIf((Vel.Y == 0), "TakeASit");
		ID11 D 4 {
				A_SpawnProjectile ("Brutal_LiquidBlood3", 15, 0, random (0, 360), 2, random (0, 40));
			}
		TNT1 A 0 A_JumpIf((Vel.Y == 0), "TakeASit");
		TNT1 A 0 {
				A_SpawnItem ("GrowingBloodPool");
				A_SpawnItem("DeadImp1");
			}
	Stop;

	TakeASit:
	    TNT1 AAAA 0 A_SpawnProjectile ("PB_SuperWallRedBlood", 32, 0, random (170, 190), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH  , random (0, 40));
	    ID11 B 5;
	    TNT1 A 0 {
				A_SpawnItem("GrowingBloodPool");
				A_SpawnItemEx("DeadImp_Slumped", 10);
			}
	Stop;
	
	DeathNoGuts:
		TNT1 A 0 {
				A_SpawnProjectile ("PB_Intestine", 24, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH  , random (0, 160));
				A_SpawnProjectile ("PB_Intestine", 24, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH  , random (0, 160));
				A_SpawnProjectile ("PB_Intestine", 24, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH  , random (0, 160));
				A_SpawnProjectile ("PB_SmallGib", 24, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH  , random (0, 160));
				A_SpawnProjectile ("PB_SmallGib", 24, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH  , random (0, 160));
				A_SpawnProjectile ("PB_MuchBlood2", 24, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH  , random (0, 160));
			}
		IMPC A 8 A_Scream();
        IMPC B 8 A_NoBlocking();
        IMPC C 8;
		TNT1 A 0 {
				A_SpawnItem ("GrowingBloodPool");
				A_SpawnItem ("DyingImp", 2);
			}
	Stop;
	
	Death.Shotgun:
	    TNT1 A 0 {
				{bNOGRAVITY = false;}
				{bTHRUSPECIES = false;}
				{bCEILINGHUGGER = false;}
				{bSLIDESONWALLS = false;}
			}
		TNT1 A 0 A_Jump(42, "Death.Shotgunontheface");
		TNT1 A 0 A_JumpIfCloser(80, "Death.Blast");
		TNT1 A 0 A_JumpIfCloser(320, "Death.Shotgunontheface");
	Goto Death;
		
	Death.Shotgunontheface:	
	    TNT1 A 0 {
				A_Stop();
				A_NoBlocking();
				{bNOBLOCKMONST = true;}
				A_Stop();
				A_Pain();
			}
		TNT1 A 0 A_Jump(128, "DeathJump");
		TNT1 A 0 A_Jump(32, "Death.ARm");
		TNT1 A 0 A_Jump(96, "DeathNoGuts");
		TNT1 A 0 A_Jump(128, "DeathShotgunontheface2");
		TROO H 1 A_FaceTarget();
		TNT1 A 0 {
				A_Recoil(13);
				ThrustThingZ(0,20,0,1);
				A_Scream();
				A_SpawnProjectile ("PB_MuchBlood2", 35, 0, random (0, 360), 2, random (0, 160));
				A_SpawnProjectile ("PB_XDeath1", 35, 0, random (0, 360), 2, random (0, 160));
				A_SpawnProjectile ("PB_XDeath1", 35, 0, random (0, 360), 2, random (0, 160));
			}
        TR06 ABCDE 4 A_SpawnProjectile ("Brutal_LiquidBlood3", 15, 0, random (0, 360), 2, random (0, 40));
		TR06 FGHIJK 4 A_JumpIf((Vel.Y == 0), "DSFStop");
	Goto DSFStop+1;
		
	DSFStop:
		TNT1 A 0 {
				A_SpawnItem("Ploft3");
				A_SpawnItem ("GrowingBloodPool");
				A_SpawnProjectile ("PB_SuperWallRedBlood", 2, 0, random (170, 190), 2, random (0, 0));
				A_SpawnItem ("DeadImpTR06K") ;
			}
	Stop;
	
	DeathShotgunontheface2:	
		TNT1 A 0 {
				{bNOBLOCKMONST = true;}
				A_Stop();
				A_Pain();
			}
		TROO H 1 A_FaceTarget();
		TNT1 A 0 {
				A_Scream();
				A_Recoil(13);
				ThrustThingZ(0,20,0,1);
				A_SpawnProjectile ("PB_MuchBlood2", 35, 0, random (0, 360), 2, random (0, 160));
				A_SpawnProjectile ("PB_Xdeath1", 35, 0, random (0, 360), 2, random (0, 160));
				A_SpawnProjectile ("PB_Xdeath1", 35, 0, random (0, 360), 2, random (0, 160));
			}
        TR06 LMNO 4 A_SpawnProjectile ("Brutal_LiquidBlood3", 15, 0, random (0, 360), 2, random (0, 40));
		TR06 QRSTU 4 A_JumpIf((Vel.Y == 0), "DSFStop2");
	Goto DSFStop2+1;
		
	DSFStop2:
		TNT1 A 0 {
				A_SpawnItem("Ploft3");
				A_SpawnItem ("GrowingBloodPool");
				A_SpawnProjectile ("PB_SuperWallRedBlood", 2, 0, random (170, 190), 2, random (0, 0));
				A_SpawnItem ("DeadImpTR06V");
			}
	Stop;
	
	Death.Minigun:
        TNT1 A 0 {
				A_FaceTarget();
				A_Scream();
				A_NoBlocking();
				A_SpawnItem ("BrutalizedImp1", 1);
			}
		TNT1 A 0 A_Jump(128, "DeathMinigun2");
	Stop;
		
	DeathMinigun2:
        TNT1 A 0 A_SpawnItem ("BrutalizedImp4", 1);
	Stop;
	
	Death.cut:
	Death.HKFT:
	Death.Saw:
        TNT1 A 0 {
				{bNOGRAVITY = false;}
				{bTHRUSPECIES = false;}
				{bCEILINGHUGGER = false;}
			}
		TNT1 A 0 A_Jump(48, "Death.Arm", "Death");
		TNT1 A 0 A_Jump(64,"DeathNoGuts");
    Goto Death.Tear;
	
	Death.Tear:
		TNT1 A 0 {
				{bNOGRAVITY = false;}
				{bTHRUSPECIES = false;}
				{bCEILINGHUGGER = false;}
			}
		TNT1 A 0 A_Jump(128, "Tear2", "Tear3", "Tear4");
		TNT1 A 0 {
				A_XScream();
				A_NoBlocking();
				A_SpawnProjectile ("PB_XDeath1", 40, 0, random (0, 360), 2, random (0, 160));
			}
		TROG A 2 A_SpawnProjectile ("RipImp", 0, 0, random (0, 360), 2, random (0, 160));
        TROG AAA 4 A_SpawnItem ("PB_MuchBlood2", 0, 30);
	    TROG BCDEFGH 8; 
		TNT1 A 1 A_SpawnItem ("DeadImp_Half", 5);
	Stop;
		
	Tear2:
		TNT1 A 0 A_XScream();
		TNT1 A 0 A_NoBlocking();
		T5SW A 3;
		T5SW A 1 A_PlaySound("misc/xdeath4f", 9);
		T5SW BBB 2 A_SpawnProjectile ("Blood", 10, 0, random (0, 360), 2, random (0, 160));
		TNT1 AA 0 A_SpawnProjectile ("PB_XDeath1", 40, 0, random (0, 360), 2, random (0, 160));
		T5SW CCC 2 A_SpawnProjectile ("Blood", 10, 0, random (0, 360), 2, random (0, 160));
		TNT1 AA 0 A_SpawnProjectile ("PB_XDeath1", 40, 0, random (0, 360), 2, random (0, 160));
		TNT1 AAAA 0 A_SpawnProjectile ("MuchBlood", 50, 0, random (0, 360), 2, random (0, 160));
		TNT1 AA 0 A_SpawnProjectile ("PB_XDeath2", 40, 0, random (0, 360), 2, random (0, 160));
		TNT1 AA 0 A_SpawnProjectile ("PB_XDeath2", 32, 0, random (0, 360), 2, random (0, 160));
		TNT1 AAA 0 A_SpawnProjectile ("PB_XDeath2", 32, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnProjectile ("LivingHeart", 32, 0, random (170, 190), 2, random (0, 40));
		T5SW DDD 2 A_SpawnProjectile ("Blood", 10, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnProjectile ("PB_XDeath3", 32, 0, random (170, 190), 2, random (0, 40));
		TNT1 AAAAAA 0 A_SpawnProjectile ("Instestin", 32, 0, random (150, 210), 2, random (0, 40));
		TNT1 AAAA 0 A_SpawnProjectile ("NashGoreBloodSpurt", 32, 0, random (170, 190), 2, random (0, 40));
		T5SW EEE 2 A_SpawnProjectile ("Blood", 10, 0, random (0, 360), 2, random (0, 160));
		TNT1 AAA 0 A_SpawnProjectile ("Instestin", 32, 0, random (150, 210), 2, random (0, 40));
		TNT1 AAAA 0 A_SpawnProjectile ("NashGoreBloodSpurt", 32, 0, random (170, 190), 2, random (0, 40));
		T5SW FFF 2 A_SpawnProjectile ("Blood", 10, 0, random (0, 360), 2, random (0, 160));
		T5SW GGG 2 A_SpawnProjectile ("Blood", 10, 0, random (0, 360), 2, random (0, 160));
        TNT1 A 0 A_SpawnItem ("DeadImpT5SWG");
	Stop;
		
	Tear3:
		TNT1 A 0 A_XScream();
		TNT1 A 0 A_NoBlocking();
		IXD1 ABC 4 A_SpawnProjectile ("MuchBlood", 45, 0, random (0, 360), 2, random (0, 160));
		TNT1 AA 0 A_SpawnProjectile ("PB_XDeath2", 32, 0, random (0, 360), 2, random (0, 160));
		TNT1 AA 0 A_SpawnProjectile ("PB_XDeath2", 32, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnProjectile ("LivingHeart", 32, 0, random (170, 190), 2, random (0, 40));
		IXD1 DDDDDDDDDD 1 A_SpawnProjectile ("Brutal_LiquidBlood2", 35, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnProjectile ("RipImp", 0, 0, random (0, 360), 2, random (0, 160));
		IXD1 EEEEEEEEEE 1 A_SpawnProjectile ("Brutal_LiquidBlood2", 26, 0, random (0, 360), 2, random (0, 160));
		IXD1 FFFFFFFFFF 1 A_SpawnProjectile ("Brutal_LiquidBlood2", 26, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnProjectile ("PB_XDeath3", 8, 0, random (170, 190), 2, random (0, 40));
		TNT1 AAA 0 A_SpawnProjectile ("Instestin", 8, 0, random (150, 210), 2, random (0, 40));
		IXD1 GGGGGGGG 1 A_SpawnProjectile ("Brutal_LiquidBlood2", 9, 0, random (0, 360), 2, random (0, 160));
		IXD1 HHHHHHHHHHHHH 1 A_SpawnProjectile ("Brutal_LiquidBlood2", 6, 0, random (0, 360), 2, random (0, 160));
        TNT1 A 0 A_SpawnItem ("DeadImpIXD1H");
	Stop;
		
	Tear4:
		TNT1 A 0 A_XScream();
		TNT1 O 0 A_NoBlocking();
		TNT1 AA 0 A_SpawnProjectile ("PB_XDeath2", 32, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnProjectile ("LivingHeart", 32, 0, random (170, 190), 2, random (0, 40));
		TNT1 AAA 0 A_SpawnProjectile ("MuchBlood", 45, 0, random (0, 360), 2, random (0, 160));
		TNT1 AAA 0 A_SpawnProjectile ("PB_XDeath3", 16, 0, random (170, 190), 2, random (0, 40));
		TNT1 AA 0 A_SpawnProjectile ("NashGoreBloodSpurt", 32, 0, random (170, 190), 2, random (0, 40));
		TNT1 AAA 0 A_SpawnProjectile ("NashGoreBloodSpurt", 32, 0, random (170, 190), 2, random (0, 40));
		TNT1 AAA 0 A_SpawnProjectile ("PB_SquirtingBloodTrail", 32, 0, random (170, 190), 2, random (0, 40));
		TNT1 AAA 0 A_SpawnProjectile ("SuperWallRedBlood", 32, 0, random (170, 190), 2, random (0, 40));
		TNT1 AA 0 A_SpawnProjectile ("BloodMistBig", 40, 0, random (0, 360), 2, random (30, 90));
		TNT1 A 0 A_SpawnProjectile ("RipImp", 0, 0, random (0, 360), 2, random (0, 160));
		IXD4 AAAGGGGHHH 1 A_SpawnProjectile ("Brutal_LiquidBlood2", 35, 0, random (0, 360), 2, random (0, 160));
		
		TNT1 A 0 A_SpawnProjectile ("NashGoreBloodSpurt", 32, 0, random (170, 190), 2, random (0, 40));
		IXD4 I 2 A_SpawnProjectile ("Brutal_LiquidBlood2", 32, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnProjectile ("NashGoreBloodSpurt", 32, 0, random (170, 190), 2, random (0, 40));
		TNT1 A 0 A_SpawnProjectile ("NashGoreBloodSpurt", 32, 0, random (170, 190), 2, random (0, 40));
		IXD4 I 2 A_SpawnProjectile ("Brutal_LiquidBlood2", 32, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnProjectile ("NashGoreBloodSpurt", 32, 0, random (170, 190), 2, random (0, 40));
		TNT1 A 0 A_SpawnProjectile ("NashGoreBloodSpurt", 32, 0, random (170, 190), 2, random (0, 40));
		IXD4 I 2 A_SpawnProjectile ("Brutal_LiquidBlood2", 32, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnProjectile ("NashGoreBloodSpurt", 32, 0, random (170, 190), 2, random (0, 40));
		TNT1 A 0 A_SpawnProjectile ("NashGoreBloodSpurt", 32, 0, random (170, 190), 2, random (0, 40));
		IXD4 I 2 A_SpawnProjectile ("Brutal_LiquidBlood2", 32, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnProjectile ("NashGoreBloodSpurt", 32, 0, random (170, 190), 2, random (0, 40));
		TNT1 A 0 A_SpawnProjectile ("NashGoreBloodSpurt", 32, 0, random (170, 190), 2, random (0, 40));
		IXD4 I 2 A_SpawnProjectile ("Brutal_LiquidBlood2", 32, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnProjectile ("NashGoreBloodSpurt", 32, 0, random (170, 190), 2, random (0, 40));
		TNT1 A 0 A_SpawnProjectile ("NashGoreBloodSpurt", 32, 0, random (170, 190), 2, random (0, 40));
		IXD4 I 2 A_SpawnProjectile ("Brutal_LiquidBlood2", 32, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnProjectile ("NashGoreBloodSpurt", 32, 0, random (170, 190), 2, random (0, 40));
		TNT1 A 0 A_SpawnProjectile ("NashGoreBloodSpurt", 32, 0, random (170, 190), 2, random (0, 40));
		IXD4 I 2 A_SpawnProjectile ("Brutal_LiquidBlood2", 32, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnProjectile ("NashGoreBloodSpurt", 32, 0, random (170, 190), 2, random (0, 40));
		TNT1 A 0 A_SpawnProjectile ("NashGoreBloodSpurt", 32, 0, random (170, 190), 2, random (0, 40));
		IXD4 I 2 A_SpawnProjectile ("Brutal_LiquidBlood2", 32, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnProjectile ("NashGoreBloodSpurt", 32, 0, random (170, 190), 2, random (0, 40));
		TNT1 A 0 A_SpawnProjectile ("NashGoreBloodSpurt", 32, 0, random (170, 190), 2, random (0, 40));
		IXD4 I 2 A_SpawnProjectile ("Brutal_LiquidBlood2", 32, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnProjectile ("NashGoreBloodSpurt", 32, 0, random (170, 190), 2, random (0, 40));
		TNT1 A 0 A_SpawnProjectile ("NashGoreBloodSpurt", 32, 0, random (170, 190), 2, random (0, 40));
		IXD4 I 2 A_SpawnProjectile ("Brutal_LiquidBlood2", 32, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnProjectile ("NashGoreBloodSpurt", 32, 0, random (170, 190), 2, random (0, 40));
		TNT1 A 0 A_SpawnProjectile ("NashGoreBloodSpurt", 32, 0, random (170, 190), 2, random (0, 40));
		IXD4 I 2 A_SpawnProjectile ("Brutal_LiquidBlood2", 32, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnProjectile ("NashGoreBloodSpurt", 32, 0, random (170, 190), 2, random (0, 40));
		TNT1 A 0 A_SpawnProjectile ("NashGoreBloodSpurt", 32, 0, random (170, 190), 2, random (0, 40));
		IXD4 I 1;
		IXD4 JJJJJ 1;
		IXD4 KKKKKKKKKK 1;
		IXD4 LLLLLL 1;
        TNT1 A 0 A_SpawnItem ("DeadImpIXD4L");
	Stop;
	
	Deat.Cut:
	Death.cutless:
        TNT1 A 0{
				{bNOGRAVITY = false;}
				{bTHRUSPECIES = false;}
				{bCEILINGHUGGER = false;}
			}
		TNT1 A 0 A_JumpIfInventory ("IsDown", 1, "Death.Down");
		TNT1 A 0 A_Jump(42,"DeathNoGuts");
		TNT1 A 0 A_Jump(16, "Death");
		TNT1 A 0 A_Jump(16, "Death.LegMassacre");
    Goto Death;
	
	Death.Blast:
	Death.Railgun:
	    TNT1 A 0 {
		        {bNOGRAVITY = false;}
				{bTHRUSPECIES = false;}
				{bCEILINGHUGGER = false;}
		        A_FaceTarget();
		        A_NoBlocking();
		        A_XScream();
		        A_SpawnProjectile ("XDeathImpArm", 32, 0, random (150, 210), 2, random (0, 40));
		        A_SpawnProjectile ("XDeathImpHead", 32, 0, random (150, 210), 2, random (0, 40));
			}
		TNT1 A 0 A_Jump(12, "Death.Arm");
		TNT1 A 0 A_Jump(128, "Death.Blast2", "DeathBlast3");
		TNT1 AAA 0 {
				A_SpawnProjectile ("PB_Xdeath3", 16, 0, random (170, 190), 2, random (0, 40));
				A_SpawnProjectile ("PB_Intestine", 32, 0, random (150, 210), 2, random (0, 40));
				A_SpawnProjectile ("PB_Xdeath1", 32, 0, random (150, 210), 2, random (0, 40));
				A_SpawnProjectile ("BloodMistBig", 40, 0, random (0, 360), 2, random (30, 90));
			}
		TNT1 AAAA 0 {
				A_SpawnProjectile ("NashGoreBloodSpurt", 32, 0, random (170, 190), 2, random (0, 40));
				A_SpawnProjectile ("NashGoreBloodSpurt", 32, 0, random (170, 190), 2, random (0, 40));
				A_SpawnProjectile ("PB_SquirtingBloodTrail", 32, 0, random (170, 190), 2, random (0, 40));
				A_SpawnProjectile ("PB_SuperWallRedBlood", 32, 0, random (170, 190), 2, random (0, 40));
			}
		TR03 A 6 A_Stop();
		TNT1 A 0 A_SpawnItem ("GrowingBloodPool");
		TR03 BBBBBBBBBB 3 A_SpawnProjectile ("Brutal_LiquidBlood2", 26, 0, random (0, 360), 2, random (30, 60));
		TR03 CCC 3 A_SpawnProjectile ("Brutal_LiquidBlood2", 26, 0, random (0, 360), 2, random (10, 40));
		TR03 DD 3 A_SpawnProjectile ("Brutal_LiquidBlood2", 6, 0, random (0, 360), 2, random (30, 60));
		TNT1 A 0 A_SpawnItem ("DeadImpTR03E");
	Stop;
	
	Death.Blast2:
		TNT1 A 0 {
		         A_XScream();
		         A_SpawnProjectile ("XDeathImpArm", 32, 0, random (150, 210), 2, random (0, 40));
		         A_SpawnProjectile ("XDeathImpHead", 32, 0, random (150, 210), 2, random (0, 40));
				}
		TNT1 AAA 0 {
				A_SpawnProjectile ("PB_Intestine", 32, 0, random (150, 210), 2, random (0, 40));
				A_SpawnProjectile ("PB_Xdeath1", 32, 0, random (150, 210), 2, random (0, 40));
				A_SpawnProjectile ("PB_Xdeath3", 16, 0, random (170, 190), 2, random (0, 40));
				A_SpawnProjectile ("BloodMistBig", 40, 0, random (0, 360), 2, random (30, 90));
			}
		TNT1 AAAA 0 {
				A_SpawnProjectile ("NashGoreBloodSpurt", 32, 0, random (170, 190), 2, random (0, 40));
				A_SpawnProjectile ("NashGoreBloodSpurt", 32, 0, random (170, 190), 2, random (0, 40));
				A_SpawnProjectile ("PB_SquirtingBloodTrail", 32, 0, random (170, 190), 2, random (0, 40));
				A_SpawnProjectile ("PB_SuperWallRedBlood", 32, 0, random (170, 190), 2, random (0, 40));
			}
		TR04 A 6 A_Stop();
		TNT1 A 0 A_SpawnItem ("GrowingBloodPool");
		TR04 BBBBBBBBBB 3 A_SpawnProjectile ("Brutal_LiquidBlood2", 26, 0, random (0, 360), 2, random (30, 60));
		TR04 CCC 3 A_SpawnProjectile ("Brutal_LiquidBlood2", 26, 0, random (0, 360), 2, random (10, 40));
		TR04 DD 3 A_SpawnProjectile ("Brutal_LiquidBlood2", 26, 0, random (0, 360), 2, random (30, 60));
		TNT1 A 0 A_SpawnItem ("DeadImpTR04E");
	Stop;
		
	DeathBlast3:
		TNT1 A 0 {
		         A_xScream();
				 A_SpawnProjectile ("PB_Xdeath3", 16, 0, random (170, 190), 2, random (0, 40));
			}
		TNT1 AA 0 A_SpawnProjectile ("PB_Xdeath2", 32, 0, random (150, 210), 2, random (0, 40));
		TNT1 AAA 0 A_SpawnProjectile ("PB_Xdeath1", 32, 0, random (150, 210), 2, random (0, 40));
		TNT1 AAAA 0 {
				A_SpawnProjectile ("NashGoreBloodSpurt", 32, 0, random (170, 190), 2, random (0, 40));
				A_SpawnProjectile ("NashGoreBloodSpurt", 32, 0, random (170, 190), 2, random (0, 40));
				A_SpawnProjectile ("PB_SquirtingBloodTrail", 32, 0, random (170, 190), 2, random (0, 40));
				A_SpawnProjectile ("PB_SuperWallRedBlood", 32, 0, random (170, 190), 2, random (0, 40));
				A_SpawnProjectile ("BloodMistBig", 40, 0, random (0, 360), 2, random (30, 90));
				A_SpawnProjectile ("PB_Intestine", 32, 0, random (150, 210), 2, random (0, 40));
			}
		TR04 F 6 A_Stop();
		TR04 G 2 A_Scream();
		TNT1 A 0 A_SpawnItem ("GrowingBloodPool");
		TR04 GGGG 2 A_SpawnProjectile ("Brutal_LiquidBlood2", 26, 0, random (0, 360), 2, random (30, 60));
		TR04 H 3 A_SpawnProjectile ("Brutal_LiquidBlood2", 26, 0, random (0, 360), 2, random (10, 40));
		TR04 I 3 A_SpawnProjectile ("Brutal_LiquidBlood2", 6, 0, random (0, 360), 2, random (30, 60));
		TNT1 A 0 A_SpawnItem ("DeadImpTR04J");
	Stop;
		
	Death.SSG:
	Death.SuperPunch:
		TNT1 A 0 {
		        {bNOGRAVITY = false;}
				{bTHRUSPECIES = false;}
				{bCEILINGHUGGER = false;}
			}
	    IZD1 E 1 A_Pain();
		IZD1 E 1 A_FaceTarget();
		TNT1 A 0 {
				A_SpawnItem("BloodSplasher2");
				A_SpawnProjectile ("PB_Xdeath2", 32, 0, random (170, 190), 2, random (0, 40));
		        A_SpawnProjectile ("PB_Xdeath3", 32, 0, random (170, 190), 2, random (0, 40));
				A_SpawnProjectile ("XDeathImpHead", 32, 0, random (170, 190), 2, random (0, 40));
                A_XScream();
		        A_NoBlocking();
			}
		TNT1 AA 0 {
				A_SpawnProjectile ("PB_Xdeath1", 32, 0, random (170, 190), 2, random (0, 40));
				A_SpawnProjectile ("XDeathImpArm", 32, 0, random (170, 190), 2, random (0, 40));
			}         
		TNT1 AAA 0 {
				A_SpawnProjectile ("PB_Intestine", 32, 0, random (150, 210), 2, random (0, 40));
				A_SpawnProjectile ("BloodMistBig", 40, 0, random (0, 360), 2, random (30, 90));
				A_SpawnProjectile ("SuperGoreSpawner", 35, 0, random (170, 190), 2, random (0, 40));
			}
		TNT1 AAAA 0 {
				A_SpawnProjectile ("NashGoreBloodSpurt", 32, 0, random (170, 190), 2, random (0, 40));
				A_SpawnProjectile ("NashGoreBloodSpurt", 32, 0, random (170, 190), 2, random (0, 40));
				A_SpawnProjectile ("PB_SquirtingBloodTrail", 32, 0, random (170, 190), 2, random (0, 40));
				A_SpawnProjectile ("PB_SuperWallRedBlood", 32, 0, random (170, 190), 2, random (0, 40));
				A_SpawnProjectile ("PB_SuperWallRedBlood", 46, 0, random (170, 190), 2, random (0, 40)); 
		    }
		IZD1 EEFFGH 6;
		TNT1 A 0 {
		         A_SpawnItem ("GrowingBloodPool");
		         A_SpawnItem ("DeadImpJustLegsAreLeft");
			}
    Stop;
	
	Crush:
	Death.Stomp:
		TNT1 A 0 {
				A_SpawnItem ("GrowingBloodPool");
				A_SpawnItem ("CrushedRemains");
				A_XScream();
				A_NoBlocking();
			}
	    TNT1 AAAAAAAAAAAAAAAAAAAAAAAAA 0 A_SpawnProjectile ("NashGoreBloodSpurt", 0, 0, random (0, 360), 2, random (0, 360));
		TNT1 AAAAAA 0 bright A_SpawnProjectile ("SuperGoreSpawner", 5, 0, random (0, 360), 2, random (30, 180));
		TNT1 AAAAAA 0 bright A_SpawnProjectile ("XDeath1", 5, 0, random (0, 360), 2, random (30, 180));
		TNT1 AA 0 bright A_SpawnProjectile ("XDeath2", 55, 0, random (0, 360), 2, random (30, 180));
		TNT1 AA 0 bright A_SpawnProjectile ("XDeath3", 55, 0, random (0, 360), 2, random (30, 180));
	Stop;
	
	Death.Nailgun:
		 TNT1 A 0 {
				{bNODROPOFF = false;}
				{bSLIDESONWALLS = false;}
				ThrustThingZ(0,random(22,30),0,1);
				A_Scream();
				A_NoBlocking();
				A_FaceTarget();
				A_Recoil (30);
			}
         ID11 A 4 A_SpawnProjectile ("Brutal_LiquidBlood3", 15, 0, random (0, 360), 2, random (0, 40));
		 TNT1 A 0 A_JumpIf((Vel.Y == 0), "PinToWall");
		 ID11 A 4 A_SpawnProjectile ("Brutal_LiquidBlood3", 15, 0, random (0, 360), 2, random (0, 40));
		 TNT1 A 0 A_JumpIf((Vel.Y == 0), "PinToWall");
		 ID11 B 4 A_SpawnProjectile ("Brutal_LiquidBlood3", 15, 0, random (0, 360), 2, random (0, 40));
		 TNT1 A 0 A_JumpIf((Vel.Y == 0), "PinToWall");
		 ID11 B 4 A_SpawnProjectile ("Brutal_LiquidBlood3", 15, 0, random (0, 360), 2, random (0, 40));
		 TNT1 A 0 A_JumpIf((Vel.Y == 0), "PinToWall");
		 ID11 C 4 A_SpawnProjectile ("Brutal_LiquidBlood3", 15, 0, random (0, 360), 2, random (0, 40));
		 TNT1 A 0 A_JumpIf((Vel.Y == 0), "PinToWall");
		 ID11 C 4 A_SpawnProjectile ("Brutal_LiquidBlood3", 15, 0, random (0, 360), 2, random (0, 40));
		 TNT1 A 0 A_JumpIf((Vel.Y == 0), "PinToWall");
		 ID11 D 4 A_SpawnProjectile ("Brutal_LiquidBlood3", 15, 0, random (0, 360), 2, random (0, 40));
		 TNT1 A 0 A_JumpIf((Vel.Y == 0), "PinToWall");
		 ID11 D 4 A_SpawnProjectile ("Brutal_LiquidBlood3", 15, 0, random (0, 360), 2, random (0, 40));
		 TNT1 A 0 A_JumpIf((Vel.Y == 0), "PinToWall");
		 TNT1 A 0 A_SpawnItem ("GrowingBloodPool");
		 TNT1 A 0 A_SpawnItem("DeadImp1");
    Stop;
	
	PinToWall:
		TNT1 A 0 {
				A_SpawnProjectile ("PB_MuchBlood2", 35, 0, random (0, 360), 2, random (0, 160));
				A_SpawnProjectile ("PB_Xdeath1", 35, 0, random (0, 360), 2, random (0, 160));
				A_SpawnProjectile ("PB_Xdeath1", 35, 0, random (0, 360), 2, random (0, 160));
				A_SpawnProjectile ("PB_Xdeath2", 32, 0, random (150, 210), 2, random (0, 40));
				A_PlaySound("Weapons/NailHitBleed", 6);
			}
	    TNT1 AAAA 0 A_SpawnProjectile ("PB_SuperWallRedBlood", 6, 0, random (170, 190), 2, random (0, 40));
	    PIN6 A 5;
	    TNT1 A 0 A_SpawnItem("GrowingBloodPool");
		TNT1 A 0 A_SpawnItemEx("DeadImp_Pinned", 10, 0, 10);
	Stop;
	
	Death.Melee:
		TNT1 A 0 A_JumpIfInventory ("SKImp", 1, "StealthKill");
    
	Death.Kick: 
		 TNT1 A 0 {
				{bNOGRAVITY = false;}
				{bTHRUSPECIES = false;}
				{bCEILINGHUGGER = false;}
				A_Scream();
				A_NoBlocking();
				ThrustThingZ(0,20,0,1);
				A_FaceTarget();
				A_Recoil (8);
			}
         ID30 ABCD 8;
         TNT1 A 1 A_SpawnItem ("DeadImp1MeleeDeath", 5);
	Stop;
	
	FallingDie:
	TNT1 A 0 {
			{bSHOOTABLE = false;}
			{bCOUNTKILL = false;}
		}
	TNT1 A 0 A_JumpIfInventory ("FallingHeight", 30, "Death.Stomp");
	TNT1 A 0 A_JumpIfInventory ("FallingHeight", 20, "FallingSuperDeath");
	TNT1 A 0 A_JumpIfInventory ("FallingHeight", 6, "FallingDeath");
	
	FallingDeath:
	Death.FellFromALongFall: 
		TROO M 1;
		TNT1 A 0 {
				A_Scream();
				A_NoBlocking();
				A_SpawnItem ("GrowingBloodPool");
				A_SpawnItem("DeadImp1");
			}
		TNT1 AAAA 0 A_SpawnProjectile ("PB_Xdeath1", 32, 0, random (0, 360), 2, random (50, 130));
	Stop;
	
	FallingSuperDeath:
	TNT1 A 0 {
			A_XScream();
			A_NoBLocking();
			A_SpawnItem ("GrowingBloodPool");
		}
	Goto Death.ExplosiveImpact+1;
	
	Death.Eat:
	    TNT1 A 0 {
				A_NoBlocking();
				A_Scream();
				A_GiveToTarget("ImpFatality",1);
			}
        Stop;
	
	Death.HelperMarineFatallity:
	Death.RVFT:
		TNT1 A 0 {
				A_Pain();
				A_Scream();
				A_NoBlocking();
				A_GiveToTarget("ImpFatality3", 1);
				A_GiveToTarget("ImpFatality", 1);
			}
        Stop;
		
	Death.Fatality:
		TNT1 A 0 {
				A_Pain();
				A_NoBlocking();
				return A_JumpIfIntargetInventory("FistsSelected", 1, "Death.ExplosiveImpact");
				A_GiveToTarget("GoFatality", 1);
				return A_Jump(255, "Death.Fatality1", "Death.Fatality1", "Death.Fatality2", "Death.Fatality2", "Death.Fatality3", "Death.Fatality3", "Death.Fatality4", "Death.Fatality5");
			}
		Goto Death.Fatality1;
 
        Death.Fatality1:
			TNT1 A 0 A_GiveToTarget("ImpFatality", 1);
        Stop;
		
		Death.Fatality2:
			TNT1 A 0 A_GiveToTarget("ImpFatality2", 1);
		Stop;
		
		Death.Fatality3:
		Death.BHFT:
			TNT1 A 0 A_GiveToTarget("ImpFatality3", 1);
		Stop;
		
		Death.Fatality4:
			TNT1 A 0 A_GiveToTarget("ImpFatality4", 1);
		Stop;
		
		Death.Fatality5:
			TNT1 A 0 A_GiveToTarget("ImpFatality5", 1);
		Stop;
		
		Death.KillMe:
		Death.Taunt:
		Death.Avoid:
			TNT1 A 0 {
					{bSOLID = false;}
					A_SpawnItem("PB_Imp");
				}
        Stop;
		
//////XDeath States

	XDeath:
		TNT1 A 0 A_JumpIfInTargetInventory("SSGSelected", 1, "Death.SSG");
		TNT1 A 0 { 
			{bNOGRAVITY = false;}
			{bTHRUSPECIES = false;}
			{bCEILINGHUGGER = false;}
			NashGoreGibs.SpawnGibs(self);
			A_SpawnProjectile ("PB_XDeath1", 42, 0, random (0, 290), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH  , random (10, 60));
			A_SpawnProjectile ("PB_XDeath3", 42, 0, random (0, 290), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH  , random (10, 60));
			A_SpawnProjectile ("PB_XDeath3", 42, 0, random (0, 290), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH  , random (10, 60));
			A_SpawnProjectile ("PB_XDeath3", 42, 0, random (0, 290), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH  , random (10, 60));
			A_SpawnProjectile ("PB_XDeath2", 42, 0, random (0, 190), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH  , random (10, 60));
			A_SpawnProjectile ("PB_XDeath4", 42, 0, random (0, 190), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH  , random (10, 60));
			}
		TNT1 AAAAAA 0 A_SpawnProjectile ("PB_BloodmistLarge", 40, 0, random (0, 360), 2, random (30, 90));
        TNT1 A 1 {
			A_SpawnItemEx("ImpXDeath",0,0,2,Vel.X,Vel.Y,Vel.Z,angle,SXF_ABSOLUTEVELOCITY|SXF_ABSOLUTEANGLE|SXF_NOCHECKPOSITION,0);
			A_Recoil(2);
			A_XScream();
			A_NoBlocking();
		}
	Stop;
	
	Death.Explosive:
		TNT1 A 1 A_FaceTarget();
		TNT1 A 1 A_JumpIfInTargetInventory("RocketLauncherSelected", 1, "RocketMan");
	Goto XDeath;
	
	RocketMan:
		TNT1 A 0 A_JumpIfCloser(800, "RocketImp");
	Goto XDeath;
		
	RocketImp:
		TNT1 A 0 {
		        A_XScream();
		        A_NoBlocking();
			}
		TNT1 A 1 A_SpawnProjectile ("RocketImpVictim", 15, 0, 180, 2, 0);
	stop;
	
	Death.Fatality:
	Death.ExplosiveImpact:
	Death.ExtremePunches:
        TNT1 A 0 ThrustThingZ(0,15,0,1);
        TNT1 A 0 A_FaceTarget;
        ID11 ABC 6;
        TNT1 A 1 A_SpawnItem ("DeadImp1", 5);
    Stop;
		
	Dead.ExplosiveImpact:
			TNT1 A 0 {
				A_NoBlocking();
		        {bNOGRAVITY = false;}
				{bTHRUSPECIES = false;}
				{bCEILINGHUGGER = false;}
		        A_SpawnItem ("GrowingBloodPool");
		        A_SpawnItem ("ThisImpGotDestroyed");
		        A_SpawnItem ("Ploft");
			}
		TNT1 A 0 A_Jump(128, "Dead.ExplosiveImpact2");
		TNT1 AAAA 0 A_SpawnItem ("Blood");
	Stop;
		
		Dead.ExplosiveImpact2:
		TNT1 A 0 {
				A_NoBlocking();
		        {bNOGRAVITY = false;}
				{bTHRUSPECIES = false;}
				{bCEILINGHUGGER = false;}
		        A_SpawnItem ("GrowingBloodPool");
		        A_SpawnItem ("ThisImpGotDestroyed2");
		        A_SpawnItem ("Ploft");
			}
		TNT1 AAAA 0 A_SpawnItem ("Blood");
	Stop;
		
	Death.Landmine:
	Death.LandMine2:
		TNT1 A 0 {
				A_NoBlocking();
				{bNOGRAVITY = false;}
				{bTHRUSPECIES = false;}
				{bCEILINGHUGGER = false;}
				ThrustThingZ(0,15,0,1);
			}
	Death.LegInTheAir:
		TNT1 A 0 {
				{bNOGRAVITY = false;}
				{bTHRUSPECIES = false;}
				{bCEILINGHUGGER = false;}
			}
		TNT1 A 0 ThrustThingZ(0,35,0,1);
		TNT1 AA 0 A_SpawnProjectile ("PB_Xdeath1", 40, 0, random (0, 360), 2, random (0, 160));
		TNT1 AA 0 A_SpawnProjectile ("PB_SuperWallRedBlood", 46, 0, random (170, 190), 2, random (0, 40));
		TNT1 AAAAAA 0 A_SpawnProjectile ("BloodMistLarge", 40, 0, random (0, 360), 2, random (20, 90));
		TNT1 AAAAAAAAAAA 0 A_SpawnProjectile ("BrainBlood", 50, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnProjectile ("XDeathImpLeg", 32, 0, random (0, 360), 2, random (0, 160));
		TNT1 AA 0 A_SpawnProjectile ("PB_Xdeath1", 40, 0, random (0, 360), 2, random (0, 160));
		ID13 A 1 A_Scream();
	    ID17 HI 4;
		ID17 JKLMN 4 A_CheckFloor ("Dead.Landmine");
		ID17 NNNNNNNN 4 A_CheckFloor ("Dead.Landmine");
		TNT1 A 0 A_SpawnItem ("DeadImp_NoLeg");
	Stop;
	
	Dead.Landmine:
		TNT1 A 0 {
				A_NoBlocking();
				A_SpawnItem ("GrowingBloodPool");
				A_SpawnItem ("Ploft");
				A_SpawnItem ("DeadImp_NoLeg");
			}
		TNT1 AAAA 0 A_SpawnItem ("Blood"); 
		TR09 E 1;
	Stop;	

//////Headshot Death States//////

	Death.head:
		TNT1 A 0 {
				{bNOGRAVITY = false;}
				{bTHRUSPECIES = false;}
				{bCEILINGHUGGER = false;}
			}
		TNT1 A 0 A_JumpIfInTargetInventory("HasIncendiaryWeapon",1,"Death.Incinerate");
		TNT1 A 0 A_JumpIfInTargetInventory("HasPlasmaWeapon", 1, "Death.Plasma");
		TNT1 A 0 A_JumpIfInTargetInventory("HasCutingWeapon", 1, "Death.Decapitate");
		TNT1 A 0 A_JumpIfHealthLower(-50, "Death.HeadExplode");
		TNT1 A 0 A_JumpIfInTargetInventory("RandomHeadExploder", 1, "HeadExploder");
	
	Death.HeadMinor:
		TNT1 A 0 {
				A_Playsound("MinorHeadshot", 0);
				A_SpawnProjectile ("PB_Brains1", 50, 0, random (0, 360), 2, random (0, 160));
				A_SpawnProjectile ("PB_Brains1", 50, 0, random (0, 360), 2, random (0, 160));
				A_SpawnProjectile ("PB_Brains3", 50, 0, random (0, 360), 2, random (0, 160));
				A_SpawnProjectile ("PB_Brains6", 50, 0, random (0, 360), 2, random (0, 160));
				A_SpawnProjectile ("PB_SmallBrainPieceFast", random (45, 55), random (5, -5), random (170, 190), 2, random (-10, 10));
				A_SpawnProjectile ("PB_SmallBrainPieceFast", random (45, 55), random (5, -5), random (170, 190), 2, random (-10, 10));
				A_SpawnProjectile ("PB_SmallBrainPiece", 50, 0, random (0, 360), 2, random (0, 160));
				A_SpawnProjectile ("PB_SmallBrainPiece", 50, 0, random (0, 360), 2, random (0, 160));
				A_SpawnProjectile ("PB_SuperWallRedBlood", 46, 0, random (170, 190), 2, random (0, 40));
			}
		TNT1 A 0 A_Jump(150, "MinorHead1", "MinorHead2");
		TROH K 9 A_SpawnProjectile ("PB_SquirtingBloodTrail", 40, 0, 120, 2, random (0, 60));
		TNT1 A 0 A_NoBlocking();
		TROH L 9 A_SpawnProjectile ("PB_SquirtingBloodTrail", 30, 0, 120, 2, random (0, 60));
		TNT1 A 0 A_Scream();
		TROH M 8 A_SpawnProjectile ("PB_SquirtingBloodTrail", 20, 0, 120, 2, random (0, 60));
		TROH N 8;
		TNT1 A 0 A_SpawnItem ("GrowingBloodPool");
		TNT1 A 0 A_SpawnItem ("DeadImp_MinorHeadDeadFront");
	Stop;
		
	MinorHead1:
	    TNT1 A 0 {
				A_XScream();
				A_NoBlocking();
				A_SpawnProjectile ("PB_Brains2", 50, 0, random (0, 360), 2, random (0, 160));
				A_SpawnProjectile ("PB_Brains5", 50, 0, random (0, 360), 2, random (0, 160));
			}
		T6SW ABC 8;
		T6SW DDD 2 A_SpawnProjectile ("PB_SquirtingBloodTrail", 20, 0, 120, 2, random (0, 60));
		T6SW E 2 A_Scream();
		T6SW EEEDDD 2 A_SpawnProjectile ("PB_SquirtingBloodTrail", 26, 0, 120, 2, random (0, 60));
		TNT1 A 0 A_SpawnItem ("GrowingBloodPool");
		T6SW F 6;
        TNT1 A 0 A_SpawnItem ("DeadImpT6SWG");
	Stop;
		
	MinorHead2:
	    TNT1 A 0 {
				A_XScream();
				A_NoBlocking();
				A_SpawnProjectile ("PB_Brains2", 50, 0, random (0, 360), 2, random (0, 160));
				A_SpawnProjectile ("PB_Brains5", 50, 0, random (0, 360), 2, random (0, 160));
			}
		T6SW HIJ 8;
		T6SW KKK 2 A_SpawnProjectile ("PB_SquirtingBloodTrail", 25, 0, 120, 2, random (0, 60));
		T6SW L 2 A_Scream();
		T6SW LLLKKK 2 A_SpawnProjectile ("PB_SquirtingBloodTrail", 26, 0, 120, 2, random (0, 60)); 
		TNT1 A 0 A_SpawnItem ("GrowingBloodPool");
        T6SW M 6;
        TNT1 A 0 A_SpawnItem ("DeadImpT6SWn");
	Stop;
	
		Death.headExplode:
			TNT1 A 0 {
				A_Stop();
				A_StartSound("gore/headshot", CHAN_BODY);
				A_SpawnItem("ImpHeadExplode", 0, 50);
				A_XScream();
				A_SpawnItem("BloodSplasher2");
				A_NoBlocking();
			}
			TROH AAAABBBB 2 {
				A_SpawnProjectile ("PB_SquirtingBloodTrail", 30, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH  , random (60, 120));
				A_SpawnItemEx("NashGoreBloodSpurt",
				frandom(-5, 5), frandom(-5, 5), frandom(30, 32),
				frandom(-2, 2), frandom(-2, 2), frandom(4, 8),
				frandom(0, 360));
			}
			TNT1 A 0 A_Jump(32, "Deathchickenhead");
			TROH CCCCCCCC 2 {
				A_SpawnProjectile ("PB_SquirtingBloodTrail", 30, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH  , random (60, 120));
				A_SpawnItemEx("NashGoreBloodSpurt",
				frandom(-5, 5), frandom(-5, 5), frandom(30, 32),
				frandom(-2, 2), frandom(-2, 2), frandom(4, 8),
				frandom(0, 360));
			}
			TNT1 A 0 {
				A_SpawnItem("GrowingBloodPool");
				A_StartSound("BODYF",CHAN_AUTO);
				}
			TROH DDDDEEEEEEEEEEEEEEEE 2 A_SpawnProjectile ("PB_SquirtingBloodTrail", 10, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH  , random (10, 40));
			TNT1 A 0 A_SpawnItem ("DeadImp_NoHead");
	Stop;
	
	Deathchickenhead:
        TNT1 A 0 A_PlaySound("misc/xdeath2c");
		TROH FFFGGGHHHIII 2 A_SpawnProjectile ("Brutal_LiquidBlood2", 30, 0, random (0, 360), 2, random (10, 90));
		TNT1 A 0 A_PlaySound("misc/xdeath2c");
		TROH FFFGGGHHHIII 2 A_SpawnProjectile ("Brutal_LiquidBlood2", 30, 0, random (0, 360), 2, random (10, 90));
		TNT1 A 0 A_PlaySound("misc/xdeath2c");
		TROH FFFGGGHHHIII 2 A_SpawnProjectile ("Brutal_LiquidBlood2", 30, 0, random (0, 360), 2, random (10, 90));
		TNT1 A 0 A_PlaySound("misc/xdeath2c");
		TROH FFFGGGHHHIII 2 A_SpawnProjectile ("Brutal_LiquidBlood2", 30, 0, random (0, 360), 2, random (10, 90));
		TNT1 A 0 A_PlaySound("misc/xdeath2c");
		TROH FFFGGGHHHIII 2 A_SpawnProjectile ("Brutal_LiquidBlood2", 30, 0, random (0, 360), 2, random (10, 90));
		TNT1 A 0 A_PlaySound("misc/xdeath2c");
		TROH FFFGGGHHHIII 2 A_SpawnProjectile ("Brutal_LiquidBlood2", 30, 0, random (0, 360), 2, random (10, 90));
		TROH CCCCCCCC 2 A_SpawnProjectile ("Brutal_LiquidBlood2", 30, 0, random (0, 360), 2, random (60, 120));
		TROH DDD 2 A_SpawnProjectile ("Brutal_LiquidBlood2", 20, 0, random (0, 360), 2, random (60, 120)) ;
		TNT1 A 0 A_SpawnItem ("GrowingBloodPool");
		TROH EEEEEEEEEEEEEEEEEEEEEEEEEEEEE 2 A_SpawnProjectile ("Brutal_LiquidBlood2", 15, 0, random (0, 360), 2, random (15, 40));
        TNT1 A 0 A_SpawnItem ("DeadImp_NoHead");
	Stop;
	
	HeadExploder:
		TNT1 A 0 A_Jump(72, "Death.HeadExplode");
	Goto Death.HeadMinor;
	
	Death.Decapitate:
        TNT1 A 0 {
				A_Stop();
				A_FaceTarget();
				A_NoBlocking();
				A_SpawnProjectile ("XDeathImpHeadBeheaded", 50, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH  , random (40, 90));
				A_SpawnProjectile ("PB_MuchBlood", 40, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH  , random (0, 160));
			}
		TROH AABBBBC 8 {
				A_SpawnProjectile ("PB_SquirtingBloodTrail", 30, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH  , random (60, 120));
				A_SpawnItemEx("NashGoreBloodSpurt",
				frandom(-5, 5), frandom(-5, 5), frandom(30, 32),
				frandom(-2, 2), frandom(-2, 2), frandom(4, 8),
				frandom(0, 360));
			}
		TNT1 A 0 {
				A_SpawnItem ("GrowingBloodPool");
				A_SpawnItem ("DeadImp_NoHead");
			}
	Stop;
	
//////Elemental Deaths//////

	Death.fire:
	Death.Flames:
	Death.Burn:
		TNT1 A 0 {
				{bNOGRAVITY = false;}
				{bTHRUSPECIES = false;}
				{bCEILINGHUGGER = false;}
				A_Scream();
				A_NoBlocking();
				A_SpawnItemEx("BurningImpRunning",0,0,0,0,0,0,0,288);
			}
		TNT1 A 0 A_JumpIfInTargetInventory("HasIncendiaryWeapon",1,"Death.Incinerate");
    Stop;

	Death.Plasma: 
	Death.Plasma2:
		TNT1 A 0 {
				{bNOGRAVITY = false;}
				{bTHRUSPECIES = false;}
				{bCEILINGHUGGER = false;}
			}
		TNT1 A 0 A_Jump(96, "OtherPlasmaDeath");
		TNT1 A 0 {
				A_Stop();
				A_StartSound("plasmaflesh");
				A_SpawnItemEx("RealisticFireSparks1Blue",random(-2,2),random(-2,2),18,0,0,0,0,SXF_NOCHECKPOSITION  ,0);
			}
		TNT1 AAAA 0 {
				A_SpawnProjectile("BluePlasmaFireNonStatic", 42, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH  , random (0, 180));
				A_SpawnProjectile("PB_BloodmistLarge", 32, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH  , random (0, 180));
				A_SpawnProjectile("NashgoreBlood", 32, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH  , random (0, 180));
			}
		PBR1 B 6 A_NoBlocking();
		TNT1 A 0 {
				A_SpawnItemEx ("RealisticFireSparks1Blue",random(-2,2),random(-2,2),10,0,0,0,0,SXF_NOCHECKPOSITION  ,0);
				A_SpawnItemEx ("DetectFloorCraterSmall",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
				A_SpawnItem("BarrelExplosionSmokeColumn");
				A_SpawnItemEx("TinyBurningPiece", random (-15, 15), random (-15, 15));
				A_SpawnItemEx("TinyBurningPiece2", random (-35, 35), random (-35, 35));
				A_SpawnItemEx("TinyBurningPiece3", random (-45, 45), random (-45, 35));
			}
		PBR1 CCDD 3 A_SpawnProjectile ("BluePlasmaFireNonStatic", 32, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH  , random (0, 180));
		PBR1 EEFF 3;
		PBR1 GG 3;
		PBR1 H -1;
	Stop;
	
	OtherPlasmaDeath:
		IMPP A 6 A_PlaySound("plasmaflesh");
		TNT1 AAAAAAAAAAAAAAAAAAAAAAAA 0 A_SpawnProjectile ("Ashes1", 33, 0, random (0, 360), 2, random (0, 180));
		TNT1 AAAAAA 0 A_SpawnProjectile ("BluePlasmaFire", 32, 0, random (0, 360), 2, random (0, 180));
		TNT1 AAAAAAAAAAAAAAAAAAA 0 A_SpawnProjectile ("Ashes2", 31, 0, random (0, 360), 2, random (0, 180));
		IMPP B 6 A_NoBlocking();
		TNT1 AAAAAAA 0 A_SpawnProjectile ("SmallBrainPiece", 50, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_PlaySound("misc/xdeath4");
		TNT1 AAAAA 0 A_SpawnProjectile ("Brains1", 48, 0, random (0, 360), 2, random (0, 160));
		TNT1 AAAA 0 A_SpawnProjectile ("SmallBrainPieceFast", random (45, 55), random (5, -5), random (170, 190), 2, random (-10, 10));
		TNT1 AAA 0 A_SpawnProjectile ("Brains7", 52, 0, random (0, 360), 2, random (0, 160));
		TNT1 AA 0 A_SpawnProjectile ("SuperWallRedBlood", 46, 0, random (170, 190), 2, random (0, 40));
		TNT1 AAAAAAAAAAA 0 A_SpawnProjectile ("NashGoreBloodSpurt", 50, 0, random (0, 360), 2, random (0, 160));
		IMPP CDE 6;
		IMPP FFFFFFFFFFFFFFFFFFFFFFFFFFFFF 8 A_SpawnProjectile ("PlasmaSmoke", 10, 0, random (0, 360), 2, random (0, 160));
		IMPP F -1;
	stop;
	
	Death.SuperPlasma:
        TNT1 A 0 {
				{bNOGRAVITY = false;}
				{bTHRUSPECIES = false;}
				{bCEILINGHUGGER = false;}
				A_XScream();
				A_NoBlocking();
			}
		XBRN AA 2 BRIGHT A_SpawnItem("BlueFlare",0,43);
        TNT1 AAAA 0 A_SpawnProjectile ("NashGoreBloodSpurt", 30, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 {
				A_SpawnProjectile ("XDeathBurnedImpArm", 32, 0, random (0, 360), 2, random (0, 160));
				A_SpawnProjectile ("XDeathBurnedImpLeg", 32, 0, random (0, 360), 2, random (0, 160));
				A_SpawnProjectile ("XDeathBurnedMeat", 32, 0, random (0, 360), 2, random (0, 160));
				A_SpawnProjectile ("XDeathBurnedMeat2", 32, 0, random (0, 360), 2, random (0, 160));
				A_SpawnProjectile ("XDeathBurnedMeat3", 32, 0, random (0, 360), 2, random (0, 160));
			}
		XBRN BB 2 BRIGHT A_SpawnItem("BlueFlare",0,43);
        TNT1 A 0 A_SpawnProjectile ("NashGoreBloodSpurt", 30, 0, random (0, 360), 2, random (0, 160));
		XBRN CC 2 BRIGHT A_SpawnItem("BlueFlare",0,43);
		TNT1 AAAAA 0 A_SpawnProjectile ("PlasmaParticleX", 48, 0, random (0, 360), 2, random (0, 360));
		TNT1 AAA 0 A_SpawnProjectile ("BigPlasmaParticleX", 42, 0, random (0, 360), 2, random (0, 360));
    Stop;
	
	Death.GreenFire:
        TNT1 A 0 {
				{bNOGRAVITY = false;}
				{bTHRUSPECIES = false;}
				{bCEILINGHUGGER = false;}
				A_XScream();
				A_NoBlocking();
				A_SpawnProjectile ("NashGoreBloodSpurt", 30, 0, random (0, 360), 2, random (0, 160));
				A_SpawnProjectile ("NashGoreBloodSpurt", 30, 0, random (0, 360), 2, random (0, 160));
				A_SpawnProjectile ("NashGoreBloodSpurt", 30, 0, random (0, 360), 2, random (0, 160));
				A_SpawnProjectile ("NashGoreBloodSpurt", 30, 0, random (0, 360), 2, random (0, 160));
				A_SpawnProjectile ("XDeathBurnedImpLeg", 32, 0, random (0, 360), 2, random (0, 160));
				A_SpawnProjectile ("XDeathBurnedMeat", 32, 0, random (0, 360), 2, random (0, 160));
				A_SpawnProjectile ("XDeathBurnedMeat", 32, 0, random (0, 360), 2, random (0, 160));
				A_SpawnProjectile ("XDeathBurnedMeat2", 32, 0, random (0, 360), 2, random (0, 160));
				A_SpawnProjectile ("XDeathBurnedMeat3", 32, 0, random (0, 360), 2, random (0, 160));
			}
		EXPL AAAAAAAAAAAAAAAAAAAAAAAA 0 A_SpawnProjectile ("GreenFlameTrails", 50, 0, random (0, 360), 2, random (0, 360));
		XBRN AAAA 2 BRIGHT A_SpawnItem("GreenFlare",0,43);
    Stop;
	
	Death.Incinerate:
		TNT1 A 0 {
				A_Stop();
				A_Playsound("MELT");
				A_NoBlocking();
				A_SpawnItemEx ("ExplosionFlareSpawner",0,0,32,0,0,0,0,SXF_NOCHECKPOSITION,0);
				A_SpawnItemEx("TinyBurningPiece", random (-15, 15), random (-15, 15));
				A_SpawnItemEx("TinyBurningPiece2", random (-35, 35), random (-35, 35));
				A_SpawnItemEx("TinyBurningPiece3", random (-45, 45), random (-45, 35));
			}
        TNT1 AAAAAA 0 { 
				A_SpawnProjectile ("ExplosionParticleHeavy", 32, 0, random (0, 360), 2, random (0, 360));
				A_SpawnProjectile ("ExplosionParticleVeryFast", 32, 0, random (0, 360), 2, random (0, 360));
			}
		TNT1 AAAAAAAAAAAA 0 {
				A_SpawnProjectile ("Ashes1", 28, 0, random (0, 360), 2, random (0, 180));
				A_SpawnProjectile ("Ashes2", 40, 0, random (0, 360), 2, random (0, 180));
			}
		TNT1 A 0 A_SpawnItemEx ("RealisticFireSparks1",random(-2,2),random(-2,2),32,0,0,0,0,SXF_NOCHECKPOSITION  ,0);
		T6SB AAAAA 1 BRIGHT Light("IncinerationGlow") A_SpawnProjectile ("BurningEmberParticlesFloating_Bigger", 36, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnItemEx ("RealisticFireSparks1",random(-2,2),random(-2,2),28,0,0,0,0,SXF_NOCHECKPOSITION  ,0);
		T6SB BBBBB 1 BRIGHT Light("IncinerationGlow") A_SpawnProjectile ("BurningEmberParticlesFloating_Bigger", 32, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnItemEx ("RealisticFireSparks1",random(-2,2),random(-2,2),24,0,0,0,0,SXF_NOCHECKPOSITION  ,0);
		T6SB CCCCC 1 BRIGHT Light("IncinerationGlow") A_SpawnProjectile ("BurningEmberParticlesFloating_Bigger", 28, 0, random (0, 360), 2, random (0, 160));
        TNT1 A 0 A_Playsound("SZZLL", 3);
		TNT1 A 0 A_SpawnItemEx ("RealisticFireSparks1",random(-2,2),random(-2,2),20,0,0,0,0,SXF_NOCHECKPOSITION  ,0);
		T6SB DDDDD 1 BRIGHT Light("IncinerationGlow") A_SpawnProjectile ("BurningEmberParticlesFloating_Bigger", 20, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnItemEx ("RealisticFireSparks1",random(-2,2),random(-2,2),16,0,0,0,0,SXF_NOCHECKPOSITION  ,0);
		T6SB EEEEE 1 BRIGHT Light("IncinerationGlow") A_SpawnProjectile ("BurningEmberParticlesFloating_Bigger", 12, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnItemEx ("RealisticFireSparks1",random(-2,2),random(-2,2),12,0,0,0,0,SXF_NOCHECKPOSITION  ,0);
		T6SB FFFFF 1 BRIGHT Light("IncinerationGlow") A_SpawnProjectile ("BurningEmberParticlesFloating_Bigger", 10, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnItemEx ("RealisticFireSparks1",random(-2,2),random(-2,2),8,0,0,0,0,SXF_NOCHECKPOSITION  ,0);
		TNT1 A 0 A_SpawnItem("BarrelExplosionSmokeColumn");
		T6SB GGGG 2 BRIGHT Light("IncinerationGlow");
		TNT1 A 0 A_SpawnItemEx ("RealisticFireSparks1",random(-2,2),random(-2,2),8,0,0,0,0,SXF_NOCHECKPOSITION  ,0);
		T6SB HHIIHHIIHHIIHHII 2 BRIGHT Light("IncinerationGlow") A_SpawnProjectile ("PlasmaSmoke", 14, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnItemEx ("RealisticFireSparks1",random(-2,2),random(-2,2),8,0,0,0,0,SXF_NOCHECKPOSITION  ,0);
		T6SB HHIIHHIIHHIIHHII 2 Light("IncinerationGlow") A_SpawnProjectile ("PlasmaSmoke", 14, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnItemEx ("RealisticFireSparks1",random(-2,2),random(-2,2),8,0,0,0,0,SXF_NOCHECKPOSITION  ,0);
		T6SB HHIIHHIIHHIIHHII 2;
		T6SB JJJJJJJ 12 A_SpawnProjectile ("PlasmaSmoke", 14, 0, random (0, 360), 2, random (0, 160));
		T6SB J -1;
	Stop;
	
	Death.Shrink:
		TNT1 A 0 A_PlaySound("Shrink", 3);
		TNT1 A 1 A_SpawnItemEx ("ImpShrinkFX1", 0, 0,  5, 0, 0);
		TNT1 A 1 A_SpawnItemEx ("ImpShrinkFX2", 0, 0, 5, 0, 0);
		TNT1 A 1 A_SpawnItemEx ("ImpShrinkFX3", 0, 0, 5, 0, 0);
		TNT1 A 1 A_SpawnItemEx ("ImpShrinkFX4", 0, 0, 5, 0, 0);
		TNT1 A 1 A_SpawnItemEx ("ImpShrinkFX5", 0, 0, 5, 0, 0);
		TNT1 A 1 A_SpawnItemEx ("ImpShrinkFX6", 0, 0, 5, 0, 0);
		TNT1 A 1 A_SpawnItemEx ("ImpShrinkFX7", 0, 0, 5, 0, 0);
		TNT1 A 1 A_SpawnItemEx ("LilImp", 1);
	stop;
		
	Death.Blackhole:
        TNT1 A 0 {
				A_Scream();
				A_NoBlocking();
				A_SpawnItem("BlackHoledHuman");
			}
    Stop;
	
	Death.Ice:
	Death.Freeze:
	Death.Frost:
	TNT1 A 0 {
			{bSHOOTABLE = false;}
			{bSOLID = false;}
			A_SpawnItem("FrozenImp");
		}
	Stop;
	}
}