class PB_ArmorBonus : PB_Armor2
{
	mixin PB_BetterPickupSound;
	
	Default
	{
		//$Category Project Brutality - Health and Armor
		//$Sprite BON2A0
		Tag "Armor Bonus";
		Armor.SaveAmount 2;
		Armor.MaxSaveAmount 500;
		Inventory.PickUpSound "misc/abonus_PickUp";
		Inventory.PickupMessage "Armor Bonus (+%a AP)";
		//Scale .34;
		+COUNTITEM;
	}
	States
	{
		Spawn:
			BON2 A 16 BRIGHT;
			BON2 BCDEFGH 2 BRIGHT; 
			loop;
	}
}

class PB_ArmorBonusDropped : PB_ArmorBonus
{
	Default
	{
		//Dropped version that doesnt count towards item total
		-COUNTITEM;
		-INVENTORY.ALWAYSPICKUP;
	}
}

class PB_DemonAPBonus : PB_ArmorBonusDropped {}

class PB_GreenArmor : PB_Armor
{
	Default
	{
		//$Category Project Brutality - Health and Armor
		//$Sprite 4RM1A0
		Tag "Light Recon Armor";
		Radius 20;
		Height 16;
		Armor.SavePercent 40;
		Armor.SaveAmount 100;
		Inventory.PickupMessage "Light Recon Armor";
		Inventory.PickupSound "ARMOR";
		//Scale .28;
	}

	States
	{
		Spawn:
			4RM1 A -1;
			stop;
	}
}

class PB_BlueArmor : PB_Armor
{
	Default
	{
		//$Category Project Brutality - Health and Armor
		//$Sprite 4RM2A0
		Tag "Heavy Assault Armor";
		Radius 20;
		Height 16;
		Armor.SavePercent 70;
		Armor.SaveAmount 200;
		Inventory.PickupMessage "Heavy Assault Armor";
		Inventory.PickupSound "ARMOR";
		//Scale .28;
	}

	States
	{
		Spawn:
			4RM2 A -1;
			stop;
	}
}