class PB_FlamethrowerUpgrade : PB_UpgradeItem
{
	//$Title Flamethrower Upgrade
	//$Category Project Brutality - Weapon Upgrades
	Default {
		Inventory.PickupSound "FLMDRAW";
		Scale 0.5;
		Inventory.PickupMessage "$PB_FLAMER_UPGRADE_PICKUP";
		Tag "UAC-M3 Flamethrower";
	}
	
	override bool TryPickup(in out Actor toucher) {
		if(!toucher.FindInventory("PB_FLamethrower") && !toucher.FindInventory("FlamerUpgraded") && toucher.CountInv("PB_Fuel") < toucher.GetAmmoCapacity("PB_Fuel")) {
			toucher.GiveInventory("PB_Flamethrower", 1);
			return true;
		}
		return false;
	}
	
	override void AttachToOwner(Actor other) {
		let weap = PB_Weapon(FindInventory("PB_Flamethrower"));
		if(weap) {
			weap.showSecondary = false;
		}
		owner.SetInventory("FlamerUpgraded", 1);
		owner.SetInventory("FlamerTankNotInserted", 1);
	}
	
	States
	{
		Spawn:
			FSPW B -1;
			Stop;
	}
}