class PB_FlamethrowerUpgrade : PB_UpgradeItem
{
	//$Title Flamethrower Upgrade
	//$Category Project Brutality - Weapon Upgrades
	Default {
		Inventory.PickupSound "FLMDRAW";
		Scale 0.5;
		Inventory.PickupMessage "$PB_FLAMER_UPGRADE_PICKUP";
		Tag "UAC-M3 Flamethrower";
	}
	States
	{
		Spawn:
			FSPW B -1;
			Stop;
		Pickup:
			TNT1 A 0 A_JumpIf(!FindInventory("PB_Flamethrower") || !FindInventory("FlamerUpgraded") || CountInv("PB_Fuel") < GetAmmoCapacity("PB_Fuel"),1);
			Fail;
			TNT1 A 0 {
				A_GiveInventory("PB_Flamethrower");
				let weap = PB_Weapon(FindInventory("PB_Flamethrower"));
				if(weap) {
					weap.ammo1 = Ammo(FindInventory("PB_Fuel"));
					weap.ammo2 = null;
				}
				if(!FindInventory("FlamerUpgraded")) {
					A_SetInventory("FlamerUpgraded",1);
					A_SetInventory("FlamerTankNotInserted",1);
				}
			}
			Stop;
	}
}