class PB_FlamethrowerUpgrade : PB_UpgradeItem
{
	//$Title Flamethrower Upgrade
	//$Category Project Brutality - Weapon Upgrades
	Default {
		Inventory.PickupSound "FLMDRAW";
		Scale 0.5;
		Inventory.PickupMessage "$PB_FLAMER_UPGRADE_PICKUP";
		Tag "UAC-M3 Flamethrower";
	}
	
	override bool TryPickup(in out Actor toucher) {
		if(toucher.FindInventory("PB_Flamethrower") && toucher.FindInventory("FlamerUpgraded") && toucher.CountInv("PB_Fuel") == toucher.GetAmmoCapacity("PB_Fuel")) {
			return false;
		}
		return super.TryPickup(toucher);
	}
	
	States
	{
		Spawn:
			FSPW B -1;
			Stop;
		Pickup:
			TNT1 A 0 {
				A_GiveInventory("PB_Flamethrower");
				let weap = PB_Weapon(FindInventory("PB_Flamethrower"));
				if(weap) {
					weap.showSecondary = false;
				}
				if(!FindInventory("FlamerUpgraded")) {
					A_SetInventory("FlamerUpgraded",1);
					A_SetInventory("FlamerTankNotInserted",1);
				}
			}
			Stop;
	}
}