class PB_MonsterSpawner : PBRandomSpawner abstract
{
	Default
	{
	}
}

class PB_WeaponSpawner : PBRandomSpawner abstract
{
	Default
	{
	}
}

class PB_AmmoSpawner : PBRandomSpawner abstract
{
	Default
	{
	}
}

class PB_HealthSpawner : PBRandomSpawner abstract
{
	Default
	{
	}
}

class PB_ArmorSpawner : PBRandomSpawner abstract
{
	Default
	{
	}
}

class PB_PowerUpSpawner : PBRandomSpawner abstract
{
	default
	{
	}
}