class PB_BarrelBase : Actor {
	Default {
		Health 20;
		Radius 10;
		Height 42;
		PainChance 255;
		BloodType "PB_BulletImpactSheetMetal";
		+SOLID
		+SHOOTABLE
		+NOBLOODDECALS
		+ACTIVATEMCROSS
		+DONTGIB
		+NOICEDEATH
	}
	
	enum barrelTypes {
		TYPE_EXPLOSIVE,
		TYPE_BURNING,
		TYPE_FROZEN
	}
	
	const FLAME_OFFSET = 32;
	
	int barrelType;
	bool bloodstained, holes, cut, dented, drained;
	bool electricDeath;
	
	override bool Used (Actor user) {
		if(health < 1) return false;
		user.SetInventory("PB_BarrelToken", 1);
		let token = PB_BarrelToken(user.FindInventory("PB_BarrelToken"));
		if(token) {
			token.barrelType = barrelType;
			token.bloodstained = bloodstained;
		}
		Destroy();
		return true;
	}
	
	override int TakeSpecialDamage(Actor inflictor, Actor source, int damage, Name damagetype) {
		if(damagetype == "Disintegrate") {
			if(barrelType != TYPE_EXPLOSIVE) {
				A_StartSound("IceMelt");
				barrelType = TYPE_EXPLOSIVE;
				SetStateLabel("Spawn");
			}
			return 0;
		}
		if(damagetype == "Fire" || damagetype == "Burn" || damagetype == "Flames") {
			if(barrelType != TYPE_BURNING) {
				if(barrelType == TYPE_FROZEN) A_StartSound("IceMelt");
				A_StartSound("barrel/flameon");
				barrelType = TYPE_BURNING;
				SetStateLabel("Spawn");
			}
			return 0;
		}
		if(damagetype == "Ice" || damagetype == "Freeze" || damagetype == "Frost") {
			if(barrelType != TYPE_FROZEN) {
				A_StartSound("weapons/CryoRifle/freezeobject");
				barrelType = TYPE_FROZEN;
				SetStateLabel("Spawn");
			}
			return 0;
		}
		return super.TakeSpecialDamage(inflictor, source, damage, damagetype);
	}
	
	state PB_BarrelJump(statelabel explosive, statelabel burning, statelabel frozen) {
		switch(barrelType) {
		case TYPE_EXPLOSIVE:
			return resolvestate(explosive);
			break;
		case TYPE_BURNING:
			return resolvestate(burning);
			break;
		case TYPE_FROZEN:
			return resolvestate(frozen);
			break;
		}
		return resolvestate(null);
	}
	
	States {
	Spawn:
		BA11 A 0 NoDelay {
			if(barrelType == TYPE_BURNING) {
				A_SpawnItemEx("PB_BarrelFire", zofs:PB_BarrelBase.FLAME_OFFSET, flags:SXF_SETMASTER);
				A_SpawnItemEx("PB_BarrelSparks", zofs:PB_BarrelBase.FLAME_OFFSET, flags:SXF_SETMASTER);
			}
			return PB_BarrelJump("SpawnExplosive", "SpawnBurning", "SpawnFrozen");
		}
	SpawnExplosive:
		BA11 ABCDEFGHIJKLM 3;
		Loop;
	SpawnBurning:
		BFR1 A 7 A_CustomMissile ("BigBlackSmokePillarShort", FLAME_OFFSET, 0, random (40, 180), 2, random (60, 120));
		Loop;
	SpawnFrozen:
		BIR1 A 6 A_SpawnItemEx("PB_BarrelCryoSmoke", frandom(-2.0, 2.0), frandom(-2.0, 2.0), frandom(3.0, 7.0), frandom(-1.0, 1.0), frandom(-1.0, 1.0), frandom(-1.0, 0));
		Loop;
	Pain:
		TNT1 A 0 {
			A_StartSound("barrel/pain");
			return PB_BarrelJump("SpawnExplosive", "SpawnBurning", "SpawnFrozen");
		}
		Goto Spawn;
	KnockedOverBurning:
		TNT1 A 0 {
			A_FaceTarget();
			A_SpawnItemEx ("KickedBarrelFlame", zofs:15, -5);
			A_StartSound("barrel/flameon");
			for(int i = 0; i < 5; i++) {
				A_CustomMissile ("Flames", 24, 0, random (150, 210), 2, random (0, 40));
			}
			for(int i = 0; i < 11; i++) {
				A_CustomMissile ("BarrelFireSpawner", 12, 0, random (150, 210), 2, random (0, 40));
				A_CustomMissile ("BarrelFireSpawner", 24, 0, random (150, 210), 2, random (0, 40));
				A_CustomMissile ("BarrelFireSpawner", 24, 0, random (150, 210), 2, random (0, 40));
			}
		}
		Stop;
	Death.Kick:
		TNT1 A 0 PB_BarrelJump("Death", "KnockedOverBurning", "Death");
		Goto Death;
	Death.Plasma:
	Death.Electric:
		TNT1 A 0 {
			electricDeath = true;
		}
	Death:
		TNT1 A 0 {
			A_StartSound("barrel/pain");
			return PB_BarrelJump("DeathExplosive", "DeathBurning", "DeathFrozen");
		}
	DeathExplosive:
		BBLA AAA 3;
		BBLA B 3 {
			if(electricDeath) A_SpawnItemEx("PB_StunGrenadeExplosion", zofs:10);
		}
		BBLA C 3;
		TNT1 A 0 {
			A_Explode(128, 128, damagetype:"ExplosiveImpact");
			A_Explode(128, 192, XF_THRUSTLESS, damagetype:"ExplosiveImpact");
			A_Stop();
			A_AlertMonsters();
			A_StartSound("Nukage/Explosion");
			A_StartSound("FAREXPL", 3);
			A_SpawnItemEx("NewBarrelExploFX", 15, 0, 20);
			A_SpawnItemEx("TinyBurningPiece", random (-15, 15), random (-15, 15));
			A_SpawnItemEx("TinyBurningPiece2", random (-35, 35), random (-35, 35));
			A_SpawnItemEx("TinyBurningPiece3", random (-45, 45), random (-45, 35));
			A_SpawnItemEx("BarrelShrapnel1", 0, 0, 5, random (8, -8), random (8, -8), random (6, 10), 0, SXF_SETMASTER);
			A_SpawnItemEx("BarrelShrapnel2", 0, 0, 5, random (8, -8), random (8, -8), random (6, 10), 0, SXF_SETMASTER);
			A_SpawnItemEx("BarrelShrapnel3", 0, 0, 5, random (8, -8), random (8, -8), random (6, 10), 0, SXF_SETMASTER);
			A_SpawnProjectile("PBExplosionparticles3", 64, 0, random (0, 360), 2, random (-40, -90));
			A_SpawnProjectile("FireworkSFXType2", 64, 0, random (0, 360), 2, random (8, -8));
			A_SpawnProjectile("Shrapnel", 64, 0, random (0, 360), 2, random (8, -8));
		}
		Stop;
	DeathBurning:
		BFEX AAA 3;
		BFEX B 3 {
			if(electricDeath) A_SpawnItemEx("PB_StunGrenadeExplosion", zofs:10);
		}
		BFEX C 3;
		TNT1 A 0 {
			A_Explode(128, 128, damagetype:"FireExplosion");
			A_Stop();
			A_AlertMonsters();
			A_StartSound("EXPLFI");
			A_StartSound("FAREXPL", 3);
			A_SpawnItemEx ("DetectFloorCrater",0,0,0);
			A_SpawnItemEx ("DetectCeilCrater",0,0,0);
			A_SpawnItemEx ("IncendiaryGrenadeFX", 0, 0, 0);
			A_CustomMissile ("BarrelFireSpawner", 8, 0, random (0, 360), 2, random (40, 65));
			A_CustomMissile ("BarrelFireSpawner", 8, 0, random (0, 360), 2, random (40, 65));
			A_CustomMissile ("BarrelFireSpawner", 8, 0, random (0, 360), 2, random (40, 65));
			for(int i = 0; i < 10; i++)
				A_CustomMissile ("FT_GroundFireSpawner", 12, 0, random (0, 360), 2, random (50, 130));
			A_CustomMissile ("FireworkSFXType2", 64, 0, random (0, 360), 2, random (30, 60));
			A_CustomMissile ("FireworkSFXType2", 64, 0, random (0, 360), 2, random (30, 60));
			A_CustomMissile ("FireworkSFXType2", 64, 0, random (0, 360), 2, random (30, 60));
			A_CustomMissile ("FireworkSFXType2", 64, 0, random (0, 360), 2, random (30, 60));
			A_CustomMissile ("FireballExplosionFlamesBig", 6, 0, random (0, 360), 2, random (0, 360));
			A_CustomMissile ("FireballExplosionFlamesBig", 6, 0, random (0, 360), 2, random (0, 360));
			A_SpawnItemEx("BarrelShrapnel1", 0, 0, 5, random (8, -8), random (8, -8), random (6, 10), 0, SXF_SETMASTER);
			A_SpawnItemEx("BarrelShrapnel2", 0, 0, 5, random (8, -8), random (8, -8), random (6, 10), 0, SXF_SETMASTER);
			A_SpawnItemEx("BarrelShrapnel3", 0, 0, 5, random (8, -8), random (8, -8), random (6, 10), 0, SXF_SETMASTER);
		}
		Stop;
	DeathFrozen:
		BBLA DDD 3;
		BBLA E 3 {
			if(electricDeath) A_SpawnItemEx("PB_StunGrenadeExplosion", zofs:10);
		}
		BBLA F 3;
		TNT1 A 0 {
			A_Explode(128, 128, damagetype:"IceExplosion");
			A_Explode(128, 320, XF_THRUSTLESS, damagetype:"IceExplosion");
			A_Stop();
			A_AlertMonsters();
			A_StartSound("EXPLIC");
			A_StartSound("FAREXPL", 3);
			Radius_Quake (2, 24, 0, 15, 0);
			A_SpawnItemEx("IceExplosionImpact", random(-2,2), random(-2,2), random(-2,2), 0, 0, 0, random(1,360), SXF_NOCHECKPOSITION);
			for(int i = 0; i < 3; i++) {
				A_SpawnItemEx("CryoSmoke", 0, 0, 0, random(8, -8)*0.1, 0, random(8, -8)*0.1, random(1,360), SXF_NOCHECKPOSITION);
				A_SpawnItemEx("CryoSmoke2", 0, 0, 0, random(8, -8)*0.04, 0, random(8, -8)*0.04, random(1,360), SXF_NOCHECKPOSITION,64);
				A_SpawnItemEx ("RandomSmallIcecrystal",random(8, -8), random(8, -8),random(1,10));
				A_SpawnItemEx ("RandomSmallIcecrystal",random(8, -8), random(8, -8),random(1,10));
				A_SpawnItemEx ("RandomSmallIcecrystal",random(8, -8), random(8, -8),random(1,10));
				A_SpawnItemEx ("RandomMediumIcecrystal",random(8, -8), random(8, -8),random(1,20));
				A_SpawnItemEx ("RandomMediumIcecrystal",random(8, -8), random(8, -8),random(1,20));
				A_SpawnItemEx ("RandomMediumIcecrystal",random(8, -8), random(8, -8),random(1,20));
				A_SpawnItemEx ("RandomMediumIcecrystal",random(8, -8), random(8, -8),random(1,20));
				A_SpawnItemEx ("RandomMediumIcecrystal",random(8, -8), random(8, -8),random(1,45));
				A_SpawnItemEx ("RandomLargeIcecrystal",random(8, -8), random(8, -8),random(1,30));
				A_SpawnItemEx ("RandomLargeIcecrystal",random(8, -8), random(8, -8),random(1,30));
			}
		}
		Stop;
	}
}

class PB_ExplosiveBarrel : PB_BarrelBase {
	override void PostBeginPlay() {
		barrelType = TYPE_EXPLOSIVE;
		super.PostBeginPlay();
	}
}

class PB_BurningBarrel : PB_BarrelBase {
	override void PostBeginPlay() {
		barrelType = TYPE_BURNING;
		super.PostBeginPlay();
	}
}

class PB_FrozenBarrel : PB_BarrelBase {
	Default {
		//$Title Frozen Barrel
		//$Category Project Brutality/Decorations
		//$Sprite BIR1A0
	}
	override void PostBeginPlay() {
		barrelType = TYPE_FROZEN;
		super.PostBeginPlay();
	}
}

class PB_ThrownBarrel : Actor {
	Default {
	Radius 12;
	Height 24;
	Speed 22;
	Damage 55;
	Health 10;
	Gravity 0.5;
	Scale 1.0;
	DamageType "ExplosiveImpact";
	BloodType "PB_BulletImpactSheetMetal";
	+MISSILE
	+SHOOTABLE
	+FORCEXYBILLBOARD
	+ROLLSPRITE
	+ROLLCENTER
	+NOBLOODDECALS
	}
	
	States {
	Spawn:
		BAR1 A 1 A_SetRoll(roll+22.5, SPF_INTERPOLATE);
		Loop;
	Death:
		TNT1 A 0 {
			A_Explode(128, 128, damagetype:"ExplosiveImpact");
			A_Explode(128, 192, XF_THRUSTLESS, damagetype:"ExplosiveImpact");
			A_Stop();
			A_AlertMonsters();
			A_StartSound("Nukage/Explosion");
			A_StartSound("FAREXPL", 3);
			A_SpawnItemEx("NewBarrelExploFX", 15, 0, 20);
			A_SpawnItemEx("TinyBurningPiece", random (-15, 15), random (-15, 15));
			A_SpawnItemEx("TinyBurningPiece2", random (-35, 35), random (-35, 35));
			A_SpawnItemEx("TinyBurningPiece3", random (-45, 45), random (-45, 35));
			A_SpawnItemEx("BarrelShrapnel1", 0, 0, 5, random (8, -8), random (8, -8), random (6, 10), 0, SXF_SETMASTER);
			A_SpawnItemEx("BarrelShrapnel2", 0, 0, 5, random (8, -8), random (8, -8), random (6, 10), 0, SXF_SETMASTER);
			A_SpawnItemEx("BarrelShrapnel3", 0, 0, 5, random (8, -8), random (8, -8), random (6, 10), 0, SXF_SETMASTER);
			A_SpawnProjectile("PBExplosionparticles3", 64, 0, random (0, 360), 2, random (-40, -90));
			A_SpawnProjectile("FireworkSFXType2", 64, 0, random (0, 360), 2, random (8, -8));
			A_SpawnProjectile("Shrapnel", 64, 0, random (0, 360), 2, random (8, -8));
		}
		Stop;
	}
}

class PB_ThrownBurningBarrel : PB_ThrownBarrel {
	States {
	Spawn:
		BFR1 A 1 A_SetRoll(roll+22.5, SPF_INTERPOLATE);
		Loop;
	Death:
		TNT1 A 0 {
			A_Explode(128, 128, damagetype:"FireExplosion");
			A_Stop();
			A_AlertMonsters();
			A_StartSound("EXPLFI");
			A_StartSound("FAREXPL", 3);
			A_SpawnItemEx ("DetectFloorCrater",0,0,0);
			A_SpawnItemEx ("DetectCeilCrater",0,0,0);
			A_SpawnItemEx ("IncendiaryGrenadeFX", 0, 0, 0);
			A_CustomMissile ("BarrelFireSpawner", 8, 0, random (0, 360), 2, random (40, 65));
			A_CustomMissile ("BarrelFireSpawner", 8, 0, random (0, 360), 2, random (40, 65));
			A_CustomMissile ("BarrelFireSpawner", 8, 0, random (0, 360), 2, random (40, 65));
			for(int i = 0; i < 10; i++)
				A_CustomMissile ("FT_GroundFireSpawner", 12, 0, random (0, 360), 2, random (50, 130));
			A_CustomMissile ("FireworkSFXType2", 64, 0, random (0, 360), 2, random (30, 60));
			A_CustomMissile ("FireworkSFXType2", 64, 0, random (0, 360), 2, random (30, 60));
			A_CustomMissile ("FireworkSFXType2", 64, 0, random (0, 360), 2, random (30, 60));
			A_CustomMissile ("FireworkSFXType2", 64, 0, random (0, 360), 2, random (30, 60));
			A_CustomMissile ("FireballExplosionFlamesBig", 6, 0, random (0, 360), 2, random (0, 360));
			A_CustomMissile ("FireballExplosionFlamesBig", 6, 0, random (0, 360), 2, random (0, 360));
			A_SpawnItemEx("BarrelShrapnel1", 0, 0, 5, random (8, -8), random (8, -8), random (6, 10), 0, SXF_SETMASTER);
			A_SpawnItemEx("BarrelShrapnel2", 0, 0, 5, random (8, -8), random (8, -8), random (6, 10), 0, SXF_SETMASTER);
			A_SpawnItemEx("BarrelShrapnel3", 0, 0, 5, random (8, -8), random (8, -8), random (6, 10), 0, SXF_SETMASTER);
		}
		Stop;
	}
}

class PB_ThrownFrozenBarrel : PB_ThrownBarrel {
	States {
	Spawn:
		BIR1 A 1 A_SetRoll(roll+22.5, SPF_INTERPOLATE);
		Loop;
	Death:
		TNT1 A 0 {
			A_Explode(128, 128, damagetype:"IceExplosion");
			A_Explode(128, 320, XF_THRUSTLESS, damagetype:"IceExplosion");
			A_Stop();
			A_AlertMonsters();
			A_StartSound("EXPLIC");
			A_StartSound("FAREXPL", 3);
			Radius_Quake (2, 24, 0, 15, 0);
			A_SpawnItemEx("IceExplosionImpact", random(-2,2), random(-2,2), random(-2,2), 0, 0, 0, random(1,360), SXF_NOCHECKPOSITION);
			for(int i = 0; i < 3; i++) {
				A_SpawnItemEx("CryoSmoke", 0, 0, 0, random(8, -8)*0.1, 0, random(8, -8)*0.1, random(1,360), SXF_NOCHECKPOSITION);
				A_SpawnItemEx("CryoSmoke2", 0, 0, 0, random(8, -8)*0.04, 0, random(8, -8)*0.04, random(1,360), SXF_NOCHECKPOSITION,64);
				A_SpawnItemEx ("RandomSmallIcecrystal",random(8, -8), random(8, -8),random(1,10));
				A_SpawnItemEx ("RandomSmallIcecrystal",random(8, -8), random(8, -8),random(1,10));
				A_SpawnItemEx ("RandomSmallIcecrystal",random(8, -8), random(8, -8),random(1,10));
				A_SpawnItemEx ("RandomMediumIcecrystal",random(8, -8), random(8, -8),random(1,20));
				A_SpawnItemEx ("RandomMediumIcecrystal",random(8, -8), random(8, -8),random(1,20));
				A_SpawnItemEx ("RandomMediumIcecrystal",random(8, -8), random(8, -8),random(1,20));
				A_SpawnItemEx ("RandomMediumIcecrystal",random(8, -8), random(8, -8),random(1,20));
				A_SpawnItemEx ("RandomMediumIcecrystal",random(8, -8), random(8, -8),random(1,45));
				A_SpawnItemEx ("RandomLargeIcecrystal",random(8, -8), random(8, -8),random(1,30));
				A_SpawnItemEx ("RandomLargeIcecrystal",random(8, -8), random(8, -8),random(1,30));
			}
		}
		Stop;
	}
}

class PB_BarrelToken : Inventory {
	Default {
		Inventory.MaxAmount 1;
	}

	enum barrelTypes {
		TYPE_EXPLOSIVE,
		TYPE_BURNING,
		TYPE_FROZEN
	}
	
	int barrelType;
	bool bloodstained;
}

class BarrelFire : Actor {
	Default {
		RenderStyle "Add";
		Scale 0.25;
		+NOINTERACTION
		+BRIGHT
	}
	States {
	Spawn:
		X053 ABCDEFGHIJKLMNOPQRSTU 1 NoDelay A_AttachLightDef('FlamethrowerLight', 'BarrelFire');
		Stop;
	}
}

class PB_BarrelFire : Actor {
	Default {
		Radius 0;
		Height 0;
		Scale 0.5;
		RenderStyle "Add";
		+NOINTERACTION
		+NOGRAVITY
		+BRIGHT
	}
	
	override void Tick() {
		let barrel = PB_BarrelBase(master);
		if(barrel && barrel.barrelType == PB_BarrelBase.TYPE_BURNING) {
			SetOrigin((barrel.pos.xy, barrel.pos.z + PB_BarrelBase.FLAME_OFFSET), true);
		}
		else Destroy();
		super.Tick();
	}
	
	States {
	Spawn:
		FLME ABCDEFGHIJKLMN 1;
		Loop;
	}
}

class BarrelTopFire2 : PB_BarrelFire {}
class PB_BarrelSparks : Actor {
	Default {
		RenderStyle "Add";
		+NOINTERACTION
		+BRIGHT
	}
	
	override void Tick() {
		let barrel = PB_BarrelBase(master);
		if(barrel && barrel.barrelType == PB_BarrelBase.TYPE_BURNING) {
			SetOrigin((barrel.pos.xy, barrel.pos.z + PB_BarrelBase.FLAME_OFFSET), true);
		}
		else Destroy();
		super.Tick();
	}
	
	States {
	Spawn:
        SPFN ABCDEFGHIJKLMNOPQRSTUVWXYZ 1;
		SPFM ABCDEFG 1;
		Loop;
	}
}

class PB_BarrelCryoSmoke : CryoSmoke
{
	Default {
		Alpha 0.5;
		+ROLLSPRITE
		+ROLLCENTER
	}
	States {
	Spawn:
		SMK2 A 0 NoDelay {
			roll = random(0, 359);
			scale *= frandom(0.8, 1.2);
		}
		SMK2 A 2 A_FadeOut (0.02);
		Wait;
	}
}