Class PBArachnotronSpawner : PB_SpawnerBase
{
	States
	{
		Death:
			TNT1 A 0 PB_SpawnerSpawn("PB_Arachspawner_DW");
			Stop;
		Tier4:
			TNT1 A 0 PB_SpawnerSpawn("PB_Arachspawner_T4");
			Stop;
		Tier3:
			TNT1 A 0 PB_SpawnerSpawn("PB_Arachspawner_T3");
			Stop;
		Tier2:
			TNT1 A 0 PB_SpawnerSpawn("PB_Arachspawner_T2");
			Stop;
		Tier1:
			TNT1 A 0 PB_SpawnerSpawn("PB_Arachspawner_T1");
			Stop;
	}
}

Class PB_Arachspawner_T1 : PB_MonsterSpawner
{
    default
    {
		PBRandomSpawner.SpawnOverride "pb_arachnotron_override";
        dropitem "PB_Arachnotron1",255,1;
    }
}

Class PB_Arachspawner_T2 : PB_MonsterSpawner
{
    default
    {
		PBRandomSpawner.Fallback "PB_Arachspawner_T1";
		PBRandomSpawner.SpawnOverride "pb_arachnotron_override";
        dropitem "PB_InfernalArachnotron",255,1;
    }
	
	override bool HandleSpawnExceptions(name toSpawn)
	{
		if(toSpawn == "PB_InfernalArachnotron" && pb_arachnotron_filter & DisablePB_InfernalArachnotron)
			return false;
		return true;
	}
}

Class PB_Arachspawner_T3 : PB_MonsterSpawner
{
    default
    {
		PBRandomSpawner.Fallback "PB_Arachspawner_T2";
		PBRandomSpawner.SpawnOverride "pb_arachnotron_override";
        dropitem "PB_Arachnophyte",255,1;
    }
	
	override bool HandleSpawnExceptions(name toSpawn)
	{
		if(toSpawn == "PB_Arachnophyte" && pb_arachnotron_filter & DisablePB_Arachnophyte)
			return false;
		return true;
	}
}

Class PB_Arachspawner_T4 : PB_MonsterSpawner
{
    default
    {
		PBRandomSpawner.Fallback "PB_Arachspawner_T3";
		PBRandomSpawner.SpawnOverride "pb_arachnotron_override";
        dropitem "PB_EliteArachnotron",255,1;
    }
	
	override bool HandleSpawnExceptions(name toSpawn)
	{
		if(toSpawn == "PB_EliteArachnotron" && pb_arachnotron_filter & DisablePB_EliteArachnotron)
			return false;
		return true;
	}
}

Class PB_Arachspawner_DW : PB_MonsterSpawner
{
    default
    {
		PBRandomSpawner.SpawnOverride "pb_arachnotron_override";
        dropitem "PB_Arachnotron1",255,31;
        dropitem "PB_InfernalArachnotron",255,22;
        dropitem "PB_Arachnophyte",255,9;
        dropitem "PB_EliteArachnotron",255,38;
    }
	
	override bool HandleSpawnExceptions(name toSpawn)
	{
		if(toSpawn == "PB_InfernalArachnotron" && pb_arachnotron_filter & DisablePB_InfernalArachnotron)
			return false;
		if(toSpawn == "PB_Arachnophyte" && pb_arachnotron_filter & DisablePB_Arachnophyte)
			return false;
		if(toSpawn == "PB_EliteArachnotron" && pb_arachnotron_filter & DisablePB_EliteArachnotron)
			return false;
		return true;
	}
}
