Class PBBOHSpawner : PB_SpawnerBase
{
	States
	{
		Death:
			TNT1 A 0 PB_SpawnerSpawn("PB_BaronSpawner_DW");
			Stop;
		Tier4:
			TNT1 A 0 PB_SpawnerSpawn("PB_BaronSpawner_T4");
			Stop;
		Tier3:
			TNT1 A 0 PB_SpawnerSpawn("PB_BaronSpawner_T3");
			Stop;
		Tier2:
			TNT1 A 0 PB_SpawnerSpawn("PB_BaronSpawner_T2");
			Stop;
		Tier1:
			TNT1 A 0 PB_SpawnerSpawn("PB_BaronSpawner_T1");
			Stop;
	}
}

Class PB_BaronSpawner_T1 : PB_MonsterSpawner
{
	default
	{
		PBRandomSpawner.SpawnOverride "pb_baronofhell_override";
		dropitem "PB_Baron1",255,1;
	}
}

Class PB_BaronSpawner_T2 : PB_MonsterSpawner
{
	default
	{
		PBRandomSpawner.Fallback "PB_BaronSpawner_T1";
		PBRandomSpawner.SpawnOverride "pb_baronofhell_override";
		dropitem "PB_CyberBaron",255,1;
	}
	
	override bool HandleSpawnExceptions(name toSpawn)
	{
		if(toSpawn == "PB_CyberBaron" && pb_baronofhell_filter & DisablePB_CyberBaron)
			return false;
		return true;
	}
}

Class PB_BaronSpawner_T3 : PB_MonsterSpawner
{
	default
	{
		PBRandomSpawner.Fallback "PB_BaronSpawner_T2";
		PBRandomSpawner.SpawnOverride "pb_baronofhell_override";
		dropitem "PB_Infernus",255,1;
	}
	
	override bool HandleSpawnExceptions(name toSpawn)
	{
		if(toSpawn == "PB_Infernus" && pb_baronofhell_filter & DisablePB_Infernus)
			return false;
		return true;
	}
}

Class PB_BaronSpawner_T4 : PB_MonsterSpawner
{
	default
	{
		PBRandomSpawner.Fallback "PB_BaronSpawner_T3";
		PBRandomSpawner.SpawnOverride "pb_baronofhell_override";
		dropitem "PB_Belphegor",255,1;
	}
	
	override bool HandleSpawnExceptions(name toSpawn)
	{
		if(toSpawn == "PB_Belphegor" && pb_baronofhell_filter & DisablePB_Belphegor)
			return false;
		return true;
	}
}

Class PB_BaronSpawner_DW : PB_MonsterSpawner
{
	default
	{
		PBRandomSpawner.SpawnOverride "pb_baronofhell_override";
		dropitem "PB_Baron1",255,42;
		dropitem "PB_CyberBaron",255,10;
		dropitem "PB_Infernus",255,27;
		dropitem "PB_Belphegor",255,21;
	}
	
	override bool HandleSpawnExceptions(name toSpawn)
	{
		if(toSpawn == "PB_CyberBaron" && pb_baronofhell_filter & DisablePB_CyberBaron)
			return false;
		if(toSpawn == "PB_Infernus" && pb_baronofhell_filter & DisablePB_Infernus)
			return false;
		if(toSpawn == "PB_Belphegor" && pb_baronofhell_filter & DisablePB_Belphegor)
			return false;
		return true;
	}
}
