Class PBCyberDemonSpawner : PB_SpawnerBase
{
	States
	{
		Death:
			TNT1 A 0 PB_SpawnerSpawn("PB_CyberDSpawner_DW");
			Stop;
		Tier4:
			TNT1 A 0 PB_SpawnerSpawn("PB_CyberDSpawner_T4");
			Stop;
		Tier3:
			TNT1 A 0 PB_SpawnerSpawn("PB_CyberDSpawner_T3");
			Stop;
		Tier2:
			TNT1 A 0 PB_SpawnerSpawn("PB_CyberDSpawner_T2");
			Stop;
		Tier1:
			TNT1 A 0 PB_SpawnerSpawn("PB_CyberDSpawner_T1");
			Stop;
	}
}

Class PB_CyberDSpawner_T1 : PB_MonsterSpawner
{
	default
	{
		PBRandomSpawner.SpawnOverride "pb_cyberdemon_override";
		dropitem "PB_Cyberdemon1",255,1;
	}
}

Class PB_CyberDSpawner_T2 : PB_MonsterSpawner
{
	default
	{
		PBRandomSpawner.Fallback "PB_CyberDSpawner_T1";
		PBRandomSpawner.SpawnOverride "pb_cyberdemon_override";
		dropitem "PB_Annihilator",255,1;
	}
	
	override bool HandleSpawnExceptions(name toSpawn)
	{
		if(toSpawn == "PB_Annihilator" && pb_cyberdemon_filter & DisablePB_Annihilator)
			return false;
		return true;
	}
}

Class PB_CyberDSpawner_T3 : PB_MonsterSpawner
{
	default
	{
		PBRandomSpawner.Fallback "PB_CyberDSpawner_T2";
		PBRandomSpawner.SpawnOverride "pb_cyberdemon_override";
		dropitem "PB_Annihilator",255,1;
	}
	
	override bool HandleSpawnExceptions(name toSpawn)
	{
		if(toSpawn == "PB_Annihilator" && pb_cyberdemon_filter & DisablePB_Annihilator)
			return false;
		return true;
	}
}

Class PB_CyberDSpawner_T4 : PB_MonsterSpawner
{
	default
	{
		PBRandomSpawner.Fallback "PB_CyberDSpawner_T3";
		PBRandomSpawner.SpawnOverride "pb_cyberdemon_override";
		dropitem "PB_Annihilator",255,1;
	}
	
	override bool HandleSpawnExceptions(name toSpawn)
	{
		if(toSpawn == "PB_Annihilator" && pb_cyberdemon_filter & DisablePB_Annihilator)
			return false;
		return true;
	}
}

Class PB_CyberDSpawner_DW : PB_MonsterSpawner
{
	default
	{
		PBRandomSpawner.SpawnOverride "pb_cyberdemon_override";
		dropitem "PB_Cyberdemon1",255,1;
		dropitem "PB_Annihilator",255,1;
	}
	
	override bool HandleSpawnExceptions(name toSpawn)
	{
		if(toSpawn == "PB_Annihilator" && pb_cyberdemon_filter & DisablePB_Annihilator)
			return false;
		return true;
	}
}
