Class PBCyberDemonSpawner : PB_SpawnerBase //replaces Cyberdemon
{
	default
	{
		+LOOKALLAROUND;
		scale 0.45;
		-SHOOTABLE;
		-COUNTKILL; 
		-SOLID;
		+NOTIMEFREEZE;
		//CANPUSHWALLS;
		//-CANUSEWALLS;
		//-ACTIVATEMCROSS;
		//-CANPASS;
		//-ISMONSTER;
		//+NODAMAGE;
		//-NOMENU;
		Species "CyberDspawner";
	}
	States
	{
		Tier4:
			TNT1 A 0;
			TNT1 A 0 PB_SpawnerSpawn("PB_CyberDSpawner_T4");//,0,0,0,0,0,0,0,SXF_TRANSFERSPECIAL | SXF_TRANSFERAMBUSHFLAG | SXF_TRANSFERPOINTERS | 288,0,tid);
			Stop;
		Tier3:
			TNT1 A 0;
			TNT1 A 0 PB_SpawnerSpawn("PB_CyberDSpawner_T3");//,0,0,0,0,0,0,0,SXF_TRANSFERSPECIAL | SXF_TRANSFERAMBUSHFLAG | SXF_TRANSFERPOINTERS | 288,0,tid);
			Stop;
		Tier2:
		Annihilator:
			TNT1 A 0;
			TNT1 A 0 PB_SpawnerSpawn("PB_CyberDSpawner_T2");//,0,0,0,0,0,0,0,SXF_TRANSFERSPECIAL | SXF_TRANSFERAMBUSHFLAG | SXF_TRANSFERPOINTERS | 288,0,tid);
			Stop;
		Tier1:
		SpawnCyberDemon:
				TNT1 A 0;
				TNT1 A 0 PB_SpawnerSpawn("PB_CyberDSpawner_T1");//,0,0,0,0,0,0,0,SXF_TRANSFERSPECIAL | SXF_TRANSFERAMBUSHFLAG | SXF_TRANSFERPOINTERS | 288,0,tid);
				Stop;
		Death:
			TNT1 A 0;
			Goto Spawn;
	}
}


Class PB_CyberDSpawner_T1 : PB_MonsterSpawner
{
	default
	{
		dropitem "PB_Cyberdemon1",255,1;
	}
	override void HandleSpawnExeptions(in out name toSpawn)
	{
		if(pb_cyberdemon_override != "Disabled") {
			toSpawn = pb_cyberdemon_override;
			return;
		}
	}
	
}

Class PB_CyberDSpawner_T2 : PB_MonsterSpawner
{
	default
	{
		dropitem "PB_Annihilator",255,1;
	}
	override void HandleSpawnExeptions(in out name toSpawn)
	{
		if(pb_cyberdemon_override != "Disabled") {
			toSpawn = pb_cyberdemon_override;
			return;
		}
		if(pb_NoAnnihilator && toSpawn == "PB_Annihilator")
			toSpawn = "PB_Cyberdemon1";
	}
}

Class PB_CyberDSpawner_T3 : PB_MonsterSpawner
{
	default
	{
		dropitem "PB_Annihilator",255,1;
	}
	override void HandleSpawnExeptions(in out name toSpawn)
	{
		if(pb_cyberdemon_override != "Disabled") {
			toSpawn = pb_cyberdemon_override;
			return;
		}
		if(pb_NoAnnihilator && toSpawn == "PB_Annihilator")
			toSpawn = "PB_Cyberdemon1";
	}
}

Class PB_CyberDSpawner_T4 : PB_MonsterSpawner
{
	default
	{
		dropitem "PB_Annihilator",255,1;
	}
	override void HandleSpawnExeptions(in out name toSpawn)
	{
		if(pb_cyberdemon_override != "Disabled") {
			toSpawn = pb_cyberdemon_override;
			return;
		}
		if(pb_NoAnnihilator && toSpawn == "PB_Annihilator")
			toSpawn = "PB_Cyberdemon1";
	}
}