Class PBImpSpawner : PB_SpawnerBase
{
	States
	{
		Death:
			TNT1 A 0 PB_SpawnerSpawn("PB_ImpSpawner_DW");
			Stop;
		Tier4:
			TNT1 A 0 PB_SpawnerSpawn("PB_ImpSpawner_T4");
			Stop;
		Tier3:
			TNT1 A 0 PB_SpawnerSpawn("PB_ImpSpawner_T3");
			Stop;
		Tier2:
			TNT1 A 0 PB_SpawnerSpawn("PB_ImpSpawner_T2");
			Stop;
		Tier1:
			TNT1 A 0 PB_SpawnerSpawn("PB_ImpSpawner_T1");
			stop;
	}
}

Class PB_ImpSpawner_T1 : PB_MonsterSpawner
{
	default
	{
		PBRandomSpawner.SpawnOverride "pb_imp_override";
		dropitem "DNImpVariant1",255,1;
		dropitem "DNImpVariant2",255,1;
		dropitem "DNImpVariant3",255,1;
		dropitem "PB_Imp1",255,1;
	}
	
	override bool HandleSpawnExceptions(name toSpawn)
	{
		if((toSpawn == "DNImpVariant1" || toSpawn == "DNImpVariant2" || toSpawn == "DNImpVariant3") && pb_imp_filter & DisableDNImpVariants)
			return false;
		return true;
	}
}

Class PB_ImpSpawner_T2 : PB_MonsterSpawner
{
	default
	{
		PBRandomSpawner.Fallback "PB_ImpSpawner_T1";
		PBRandomSpawner.SpawnOverride "pb_imp_override";
		dropitem "PB_InfectedImp",255,1;
	}
	
	override bool HandleSpawnExceptions(name toSpawn)
	{
		if(toSpawn == "PB_InfectedImp" && pb_imp_filter & DisablePB_InfectedImp)
			return false;
		return true;
	}
}

Class PB_ImpSpawner_T3 : PB_MonsterSpawner
{
	default
	{
		PBRandomSpawner.Fallback "PB_ImpSpawner_T2";
		PBRandomSpawner.SpawnOverride "pb_imp_override";
		dropitem "PB_DarkImpNether",255,1;
		dropitem "PB_DarkImpVoid",255,1;
		dropitem "PB_DarkImpNami",255,1;
		dropitem "PB_DarkImpST",255,1;
	}
	
	override bool HandleSpawnExceptions(name toSpawn)
	{
		if((toSpawn == "PB_DarkImpNether" || toSpawn == "PB_DarkImpVoid" || toSpawn == "PB_DarkImpNami" || toSpawn == "PB_DarkImpST") && pb_imp_filter & DisablePB_DarkImps)
			return false;
		return true;
	}
}

Class PB_ImpSpawner_T4 : PB_MonsterSpawner
{
	default
	{
		PBRandomSpawner.Fallback "PB_ImpSpawner_T3";
		PBRandomSpawner.SpawnOverride "pb_imp_override";
		dropitem "PB_DarkImpNether",255,1;
		dropitem "PB_DarkImpVoid",255,1;
		dropitem "PB_DarkImpNami",255,1;
		dropitem "PB_DarkImpST",255,1;
	}
	
	override bool HandleSpawnExceptions(name toSpawn)
	{
		if((toSpawn == "PB_DarkImpNether" || toSpawn == "PB_DarkImpVoid" || toSpawn == "PB_DarkImpNami" || toSpawn == "PB_DarkImpST") && pb_imp_filter & DisablePB_DarkImps)
			return false;
		return true;
	}
}

Class PB_ImpSpawner_DW : PB_MonsterSpawner
{
	default
	{
		PBRandomSpawner.SpawnOverride "pb_imp_override";
		dropitem "DNImpVariant1",255,5;
		dropitem "DNImpVariant2",255,4;
		dropitem "DNImpVariant3",255,3;
		dropitem "PB_Imp1",255,6;
		dropitem "PB_InfectedImp",255,10;
		dropitem "PB_DarkImpNether",255,24;
		dropitem "PB_DarkImpVoid",255,21;
		dropitem "PB_DarkImpNami",255,19;
		dropitem "PB_DarkImpST",255,7;
	}
	
	override bool HandleSpawnExceptions(name toSpawn)
	{
		if((toSpawn == "DNImpVariant1" || toSpawn == "DNImpVariant2" || toSpawn == "DNImpVariant3") && pb_imp_filter & DisableDNImpVariants)
			return false;
		if(toSpawn == "PB_InfectedImp" && pb_imp_filter & DisablePB_InfectedImp)
			return false;
		if((toSpawn == "PB_DarkImpNether" || toSpawn == "PB_DarkImpVoid" || toSpawn == "PB_DarkImpNami" || toSpawn == "PB_DarkImpST") && pb_imp_filter & DisablePB_DarkImps)
			return false;
		return true;
	}
}
