Class PBMancubusSpawner : PB_SpawnerBase
{
	States
	{
		Death:
			TNT1 A 0 PB_SpawnerSpawn("PB_MancubiSpawner_DW");
			Stop;
		Tier4:
			TNT1 A 0 PB_SpawnerSpawn("PB_MancubiSpawner_T4");
			Stop;
		Tier3:
			TNT1 A 0 PB_SpawnerSpawn("PB_MancubiSpawner_T3");
			Stop;
		Tier2:
			TNT1 A 0 PB_SpawnerSpawn("PB_MancubiSpawner_T2");
			Stop;
		Tier1:
			TNT1 A 0 PB_SpawnerSpawn("PB_MancubiSpawner_T1");
			Stop;
	}
}

Class PB_MancubiSpawner_T1 : PB_MonsterSpawner
{
	default
	{
		PBRandomSpawner.SpawnOverride "pb_mancubus_override";
		dropitem "PB_Mancubus1",255,1;
	}
}

Class PB_MancubiSpawner_T2 : PB_MonsterSpawner
{
	default
	{
		PBRandomSpawner.Fallback "PB_MancubiSpawner_T1";
		PBRandomSpawner.SpawnOverride "pb_mancubus_override";
		dropitem "PB_Daedabus",255,1;
	}
	
	override bool HandleSpawnExceptions(name toSpawn)
	{
		if(toSpawn == "PB_Daedabus" && pb_mancubus_filter & DisablePB_Daedabus)
			return false;
		return true;
	}
}

Class PB_MancubiSpawner_T3 : PB_MonsterSpawner
{
	default
	{
		PBRandomSpawner.Fallback "PB_MancubiSpawner_T2";
		PBRandomSpawner.SpawnOverride "pb_mancubus_override";
		dropitem "PB_Volcabus",255,1;
	}
	
	override bool HandleSpawnExceptions(name toSpawn)
	{
		if(toSpawn == "PB_Volcabus" && pb_mancubus_filter & DisablePB_Volcabus)
			return false;
		return true;
	}
}

Class PB_MancubiSpawner_T4 : PB_MonsterSpawner
{
	default
	{
		PBRandomSpawner.Fallback "PB_MancubiSpawner_T3";
		PBRandomSpawner.SpawnOverride "pb_mancubus_override";
		dropitem "PB_Volcabus",255,1;
	}
	
	override bool HandleSpawnExceptions(name toSpawn)
	{
		if(toSpawn == "PB_Volcabus" && pb_mancubus_filter & DisablePB_Volcabus)
			return false;
		return true;
	}
}

Class PB_MancubiSpawner_DW : PB_MonsterSpawner
{
	default
	{
		PBRandomSpawner.SpawnOverride "pb_mancubus_override";
		dropitem "PB_Mancubus1",255,38;
		dropitem "PB_Daedabus",255,28;
		dropitem "PB_Volcabus",255,34;
	}
	
	override bool HandleSpawnExceptions(name toSpawn)
	{
		if(toSpawn == "PB_Daedabus" && pb_mancubus_filter & DisablePB_Daedabus)
			return false;
		if(toSpawn == "PB_Volcabus" && pb_mancubus_filter & DisablePB_Volcabus)
			return false;
		return true;
	}
}
