Class PBSpectreSpawner : PB_SpawnerBase //replaces Spectre
{
	default
	{
		+LOOKALLAROUND;
		scale 0.45;
		-SHOOTABLE;
		-COUNTKILL; 
		-SOLID;
		+NOTIMEFREEZE;
		//CANPUSHWALLS;
		//-CANUSEWALLS;
		//-ACTIVATEMCROSS;
		//-CANPASS;
		//-ISMONSTER;
		//+NODAMAGE;
		//-NOMENU;
		Species "spectrespawner";
	}
	States
	{
		Tier4:
			TNT1 A 0;
			TNT1 A 0 PB_SpawnerSpawn("PB_SpectreSpawner_T4");//,0,0,0,0,0,0,0,SXF_TRANSFERSPECIAL | SXF_TRANSFERAMBUSHFLAG | SXF_TRANSFERPOINTERS | 288,0,tid);
			Stop;
		Tier3:
			TNT1 A 0;
			TNT1 A 0 PB_SpawnerSpawn("PB_SpectreSpawner_T3");//,0,0,0,0,0,0,0,SXF_TRANSFERSPECIAL | SXF_TRANSFERAMBUSHFLAG | SXF_TRANSFERPOINTERS | 288,0,tid);
			Stop;
		Tier2:
		SpawnVoidS:
			TNT1 A 0;
			TNT1 A 0 PB_SpawnerSpawn("PB_SpectreSpawner_T2");//,0,0,0,0,0,0,0,SXF_TRANSFERSPECIAL | SXF_TRANSFERAMBUSHFLAG | SXF_TRANSFERPOINTERS | 288,0,tid);
			Stop;
		Tier1:
		SpawnSpectre:
			TNT1 A 0;
			TNT1 A 0 PB_SpawnerSpawn("PB_SpectreSpawner_T1");//,0,0,0,0,0,0,0,SXF_TRANSFERSPECIAL | SXF_TRANSFERAMBUSHFLAG | SXF_TRANSFERPOINTERS | 288,0,tid);
			Stop;
		Death:
			 TNT1 A 0;
			Goto Spawn;
	}
}


Class PB_SpectreSpawner_T1 : PB_MonsterSpawner
{
	default
	{
		dropitem "PB_Spectre",255,1;
	}
	override void HandleSpawnExeptions(in out name toSpawn)
	{
		if(pb_spectre_override != "Disabled") {
				toSpawn = pb_spectre_override;
				return;
		}
	}
	
	
}

Class PB_SpectreSpawner_T2 : PB_MonsterSpawner
{
	default
	{
		dropitem "PB_VoidSpectre",255,1;
	}
	override void HandleSpawnExeptions(in out name toSpawn)
	{
		if(pb_spectre_override != "Disabled") {
				toSpawn = pb_spectre_override;
				return;
		}
		if(pb_VoidSpectre && toSpawn == "PB_VoidSpectre")
				toSpawn = "PB_Spectre";
				
	}
}

Class PB_SpectreSpawner_T3 : PB_MonsterSpawner
{
	default
	{
		dropitem "PB_VoidSpectre",255,1;
	}
	override void HandleSpawnExeptions(in out name toSpawn)
	{
		if(pb_spectre_override != "Disabled") {
				toSpawn = pb_spectre_override;
				return;
		}
		if(pb_VoidSpectre && toSpawn == "PB_VoidSpectre")
			toSpawn = "PB_Spectre";
	}
}

Class PB_SpectreSpawner_T4 : PB_MonsterSpawner
{
	default
	{
		dropitem "PB_VoidSpectre",255,1;
	}
	override void HandleSpawnExeptions(in out name toSpawn)
	{
		if(pb_spectre_override != "Disabled") {
				toSpawn = pb_spectre_override;
				return;
		}
		if(pb_VoidSpectre && toSpawn == "PB_VoidSpectre")
			toSpawn = "PB_Spectre";
	}
}