Class PBSpectreSpawner : PB_SpawnerBase replaces Spectre
{
	default
	{
		+LOOKALLAROUND;
		scale 0.45;
		-SHOOTABLE;
		-COUNTKILL; 
		-SOLID;
		+NOTIMEFREEZE;
		//CANPUSHWALLS;
		//-CANUSEWALLS;
		//-ACTIVATEMCROSS;
		//-CANPASS;
		//-ISMONSTER;
		//+NODAMAGE;
		//-NOMENU;
		Species "spectrespawner";
	}
	States
	{
	Tier4:
	Tier3:
	Tier2:
	SpawnVoidS:
	    TNT1 A 0;
		TNT1 A 0
		   {
		    if(pb_VoidSpectre==1)
		    {
		    SetStateLabel("Tier1");
		    }
		   }
		TNT1 A 0 A_SpawnItemEx("PB_VoidSpectre",0,0,0,0,0,0,0,SXF_TRANSFERSPECIAL | SXF_TRANSFERAMBUSHFLAG | SXF_TRANSFERPOINTERS | 288,0,tid);
		Stop;
	Tier1:
	SpawnSpectre:
		TNT1 A 0;
		TNT1 A 0 A_SpawnItemEx("PB_Spectre",0,0,0,0,0,0,0,SXF_TRANSFERSPECIAL | SXF_TRANSFERAMBUSHFLAG | SXF_TRANSFERPOINTERS | 288,0,tid);
		Stop;
		Death:
		    TNT1 A 0;
			Goto Spawn;
	}
}