extend class PB_WeaponBase //Barrels. Pope, why's your code so jank? It looks fucking wretched. -AD
{
	string b;

	action void PB_RaiseBarrel() {
		A_SetInventory("CantWeaponSpecial", 1);
		A_ClearOverlays(-10,65);
		A_StopSound(1);
		A_StopSounds(4, 6);
		A_TakeInventory("Zoomed", 1);
		A_ZoomFactor(1.0);
		A_SetCrosshair(-1);
		PB_SetReloading(false);
		A_StartSound("barrel/pain");
	}
	
	action void PB_BarrelThrow(string b1)
	{
		A_FireProjectile("PB_Thrown"..b1, 0, 1, 0, 0, FPF_NOAUTOAIM);
		SetInventory("PB_BarrelToken", 0);
		invoker.hasBarrel = false;
	}
	
	action void PB_SetBarrelSprites(string explosive, string burning, string frozen) {
		let token = PB_BarrelToken(FindInventory("PB_BarrelToken"));
		if(token) {
			switch(token.barrelType) {
			case PB_BarrelToken.TYPE_EXPLOSIVE:
				A_SetWeaponSprite(explosive);
				break;
			case PB_BarrelToken.TYPE_BURNING:
				A_SetWeaponSprite(burning);
				break;
			case PB_BarrelToken.TYPE_FROZEN:
				A_SetWeaponSprite(frozen);
				break;
			}
		}
	}
	
	action state PB_BarrelJump(statelabel explosive, statelabel burning, statelabel frozen) {
		let token = PB_BarrelToken(FindInventory("PB_BarrelToken"));
		switch(token.barrelType) {
		case PB_BarrelToken.TYPE_EXPLOSIVE:
			return resolvestate(explosive);
			break;
		case PB_BarrelToken.TYPE_BURNING:
			return resolvestate(burning);
			break;
		case PB_BarrelToken.TYPE_FROZEN:
			return resolvestate(frozen);
			break;
		}
		return resolvestate(null);
	}
	
	States
	{
	CacheSprites:
		BANE A 0;
		BAFE A 0;
		BAIE A 0;
	RaiseBarrel:
		TNT1 A 0 PB_RaiseBarrel();
		BANE ABCDEFG 1 PB_SetBarrelSprites("BANE", "BAFE", "BAIE");
	ReadyBarrel:
		TNT1 A 0 PB_BarrelJump("ReadyExplosiveBarrel", "ReadyBurningBarrel", "ReadyFrozenBarrel");
	//Idle
	ReadyExplosiveBarrel:
		THRG LKJIHHIJKL 2 A_DoPBWeaponAction(0, PB_NOUNLOAD);
		Loop;
	ReadyBurningBarrel:
		THRG DEFGFED 2 A_DoPBWeaponAction(0, PB_NOUNLOAD);
		Loop;
	ReadyFrozenBarrel:
		THRG M 1 A_DoPBWeaponAction(0, PB_NOUNLOAD);
		Loop;
	//Throw
	ThrowBarrel:
		TNT1 A 0 {
			if(!FindInventory("PB_PowerStrength")) return resolvestate("PlaceBarrel");
			return PB_BarrelJump("ThrowExplosiveBarrel", "ThrowBurningBarrel", "ThrowFrozenBarrel");
		}
	ThrowExplosiveBarrel:
		BANE HIJKLMN 1;
		TNT1 A 0 A_StartSound("weapons/fistwhoosh");
		BANE ONLJH 1;
		TNT1 A 0 PB_BarrelThrow("Barrel");
		THRF ABCDEF 2;
		TNT1 A 0 A_SetInventory("CantWeaponSpecial",0);
		goto GoingToReady2;
	ThrowBurningBarrel:
		BAFE HIJKLMN 1;
		TNT1 A 0 A_StartSound("weapons/fistwhoosh");
		BAFE ONLJH 1;
		TNT1 A 0 PB_BarrelThrow("BurningBarrel");
		THRF ABCDEF 2;
		TNT1 A 0 A_SetInventory("CantWeaponSpecial",0);
		goto GoingToReady2;
	ThrowFrozenBarrel:
		BAIE HIJKLMN 1;
		TNT1 A 0 A_StartSound("weapons/fistwhoosh");
		BAIE ONLJH 1;
		TNT1 A 0 PB_BarrelThrow("FrozenBarrel");
		THRF ABCDEF 2;
		TNT1 A 0 A_SetInventory("CantWeaponSpecial",0);
		Goto GoingToReady2;
	//Place
	PlaceBarrel:
		BANE GFEDCBA 1 PB_SetBarrelSprites("BANE", "BAFE", "BAIE");
		TNT1 A 0 {
			if(CountInv("Grab1")) invoker.b = "PB_NukageBarrel";
			else if(CountInv("Grab2")) invoker.b = "PB_NukageBarrelHoles";
			else if(CountInv("Grab3")) invoker.b = "PB_NukageBarrelCut";
			else if(CountInv("Grab4")) invoker.b = "PB_NukageBarrelDented";
			else if(CountInv("Grab5")) invoker.b = "PB_NukageBarrel_RedBlood";
			else if(CountInv("Grab6")) invoker.b = "PB_NukageBarrelHoles_RedBlood";
			else if(CountInv("Grab7")) invoker.b = "PB_NukageBarrelCut_RedBlood";
			else if(CountInv("Grab8")) invoker.b = "PB_NukageBarrelDented_RedBlood";
			let token = PB_BarrelToken(FindInventory("PB_BarrelToken"));
			string barrelType;
			switch(token.barrelType) {
			case PB_BarrelToken.TYPE_EXPLOSIVE:
				barreltype = "PB_ExplosiveBarrel";
				break;
			case PB_BarrelToken.TYPE_BURNING:
				barreltype = "PB_BurningBarrel";
				break;
			case PB_BarrelToken.TYPE_FROZEN:
				barreltype = "PB_FrozenBarrel";
				break;
			}
			bool success;
			Actor spawnedbarrel;
			[success, spawnedbarrel] = A_SpawnItemEx(barrelType, 17, xvel:12);
			let barrel = PB_BarrelBase(spawnedbarrel);
			if(barrel && token) {
				barrel.bloodstained = token.bloodstained;
			}
			SetInventory("PB_BarrelToken", 0);
			invoker.hasBarrel = false;
			A_StartSound("barrel/pain");
		}
		PKPB HGFEDCBA 1;
		TNT1 A 2;
		TNT1 A 0 A_SetInventory("CantWeaponSpecial",0);
		TNT1 A 0 A_JumpIf(player.PendingWeapon != WP_NOCHANGE,1);
		Goto GoingToReady2;
		TNT1 A 0 A_Lower();
		Wait;
	//Flashes
	FlashBarrelKicking:
		BAIE A 0 A_JumpIfInventory("GrabbedIceBarrel",1,3);
		BAFE A 0 A_JumpIfInventory("GrabbedFlameBarrel",1,2);
		BANE A 0;
		"####" IJKLMNOONMLKJI 1 A_DoPBWeaponAction(WRF_NOFIRE|WRF_NOSWITCH);
		TNT1 A 0
		{
			if(CountInv("GrabbedBarrel")) return ResolveState("IdleBarrel");
			else if(CountInv("GrabbedIceBarrel")) return ResolveState("IdleIceBarrel");
			else if(CountInv("GrabbedFlameBarrel")) return ResolveState("IdleFlameBarrel");
			else return ResolveState(null);
		}
		Stop;
	FlashBarrelPunching: 
		BAIQ I 0 A_JumpIfInventory("GrabbedIceBarrel",1,3);
		BAFQ I 0 A_JumpIfInventory("GrabbedFlameBarrel",1,2);
		BANQ I 0;
		"####" IJKL 1 A_DoPBWeaponAction(WRF_NOFIRE|WRF_NOSWITCH);
		"####" M 6 A_DoPBWeaponAction(WRF_NOFIRE|WRF_NOSWITCH);
		"####" LKJI 1 A_DoPBWeaponAction(WRF_NOFIRE|WRF_NOSWITCH);
		Stop;
	FlashBarrelAirKicking:
		BAIE A 0 A_JumpIfInventory("GrabbedIceBarrel",1,3);
		BAFE A 0 A_JumpIfInventory("GrabbedFlameBarrel",1,2);
		BANE A 0;
		"####" IJKLMNOOOOONMLKJI 1 A_DoPBWeaponAction(WRF_NOFIRE|WRF_NOSWITCH);
		TNT1 A 0
		{
			if(CountInv("GrabbedBarrel")) return ResolveState("IdleBarrel");
			else if(CountInv("GrabbedIceBarrel")) return ResolveState("IdleIceBarrel");
			else if(CountInv("GrabbedFlameBarrel")) return ResolveState("IdleFlameBarrel");
			else return ResolveState(null);
		}
		Stop;
	FlashBarrelSlideKicking:
		BAIE A 0 A_JumpIfInventory("GrabbedIceBarrel",1,3);
		BAFE A 0 A_JumpIfInventory("GrabbedFlameBarrel",1,2);
		BANE A 0;
		"####" IJKLMNOOOOOOOOOOOOOOOOOOOO 1 A_DoPBWeaponAction(WRF_NOFIRE|WRF_NOSWITCH);
		TNT1 A 0
		{
			if(CountInv("GrabbedBarrel")) return ResolveState("IdleBarrel");
			else if(CountInv("GrabbedIceBarrel")) return ResolveState("IdleIceBarrel");
			else if(CountInv("GrabbedFlameBarrel")) return ResolveState("IdleFlameBarrel");
			else return ResolveState(null);
		}
		Stop;
	FlashBarrelSlideKickingStop:
		BAIE A 0 A_JumpIfInventory("GrabbedIceBarrel",1,3);
		BAFE A 0 A_JumpIfInventory("GrabbedFlameBarrel",1,2);
		BANE A 0;
		"####" ONMLKJI 1 A_DoPBWeaponAction(WRF_NOFIRE|WRF_NOSWITCH);
		TNT1 A 0
		{
			if(CountInv("GrabbedBarrel")) return ResolveState("IdleBarrel");
			else if(CountInv("GrabbedIceBarrel")) return ResolveState("IdleIceBarrel");
			else if(CountInv("GrabbedFlameBarrel")) return ResolveState("IdleFlameBarrel");
			else return ResolveState(null);
		}
		Stop;
	}
}