class PB_RevLauncherFireCount : Inventory{Default{Inventory.MaxAmount 3;}}
extend class PB_WeaponBase
{
	States
	{
		UseEquipment:
			TNT1 A 0 A_JumpIfInventory("CantDoAction", 1, "FailOverlay");
			TNT1 A 0 A_JumpIf(health <= 0, "FailOverlay");
			TNT1 A 0 {
				A_ClearOverlays(-80,80);
				A_TakeInventory("RailgunInfrared", 1);
				A_StopSound(CHAN_WEAPON);
				A_StopSound(CHAN_VOICE);
				A_StopSound(CHAN_6);
				A_StopSound(CHAN_7);
				A_TakeInventory("UseEquipment", 1);
			}
			TNT1 A 0 A_JumpIfInventory ("GrabbedBarrel", 1, "IdleBarrel");
			TNT1 A 0 A_JumpIfInventory ("GrabbedFlameBarrel", 1, "IdleFlameBarrel");
			TNT1 A 0 A_JumpIfInventory ("GrabbedIceBarrel", 1, "IdleIceBarrel");
			TNT1 A 0 A_JumpIfInventory("FragGrenadeSelected", 1, "ThrowGrenade");
			TNT1 A 0 A_JumpIfInventory("ProximityMineSelected", 1, "ThrowMine");
			TNT1 A 0 A_JumpIfInventory("StunGrenadeSelected", 1, "ThrowStun");
			TNT1 A 0 A_JumpIfInventory("LeechSelected", 1, "ThrowLeech");
			//TNT1 A 0 A_JumpIfInventory("RevGunSelected", 1, "FireRevGun");
			//More stuff to come.....
			Goto GoingToReady;
		WheelCancelEquipment:
			TNT1 A 0
				{
				A_SetInventory("WW_ProximityMineSelected",0);
				A_SetInventory("WW_StunGrenadeSelected",0);
				A_SetInventory("WW_LeechSelected",0);
				A_SetInventory("WW_FragGrenadeSelected",0);
				A_SetInventory("WW_RevGunSelected",0);
				A_SetInventory("CantWeaponSpecial",0);
				}
			goto Equipment_Toggle_Handler_Overlay;
		SwitchEquipment:	
			TNT1 A 0 A_TakeInventory("ToggleEquipment", 1);
			TNT1 A 0 {
				if(
					CountInv("WW_ProximityMineSelected") && CountInv("ProximityMineSelected") >=1 ||
					CountInv("WW_StunGrenadeSelected") && CountInv("StunGrenadeSelected") >=1 ||
					CountInv("WW_LeechSelected") && CountInv("LeechSelected") >=1 ||
					CountInv("WW_RevGunSelected") && CountInv("RevGunSelected") >=1 ||
					CountInv("WW_FragGrenadeSelected") && CountInv("FragGrenadeSelected") >=1)
					{A_Print("$PB_ALREADYSELECTED"); return ResolveState("WheelCancelEquipment");}
				return ResolveState(null);
				}
			TNT1 A 0 
				{
					if(CountInv("WW_ProximityMineSelected") >=1)
						{ 
							A_Print("Equipment Selected: \ctProximity Mine"); 
							A_SetInventory("ProximityMineSelected",1);
							A_SetInventory("StunGrenadeSelected",0);
							A_SetInventory("LeechSelected",0);
							A_SetInventory("RevGunSelected",0);
							A_SetInventory("FragGrenadeSelected",0);
							A_StartSound("GRNPIN", 3);
							return ResolveState("WheelCancelEquipment");
						}
					if(CountInv("WW_StunGrenadeSelected") >=1)
						{ 
							A_Print("Equipment Selected: \cvStun Grenade"); 
							A_SetInventory("ProximityMineSelected",0);
							A_SetInventory("StunGrenadeSelected",1);
							A_SetInventory("LeechSelected",0);
							A_SetInventory("RevGunSelected",0);
							A_SetInventory("FragGrenadeSelected",0);
							A_StartSound("StunGrenadePickup", 3);
							return ResolveState("WheelCancelEquipment");
						}
					if(CountInv("WW_LeechSelected") >=1)
						{ 
							A_Print("Equipment Selected: \c[PB_DTech]Leech"); 
							A_SetInventory("ProximityMineSelected",0);
							A_SetInventory("StunGrenadeSelected",0);
							A_SetInventory("LeechSelected",1);
							A_SetInventory("RevGunSelected",0);
							A_SetInventory("FragGrenadeSelected",0);
							A_StartSound("SiphonGrowl", 3);
							return ResolveState("WheelCancelEquipment");
						}
					if(CountInv("WW_RevGunSelected") >=1)
						{ 
							A_Print("Equipment Selected: \cnQuick Launcher"); 
							A_SetInventory("ProximityMineSelected",0);
							A_SetInventory("StunGrenadeSelected",0);
							A_SetInventory("LeechSelected",0);
							A_SetInventory("RevGunSelected",1);
							A_SetInventory("FragGrenadeSelected",0);
							A_StartSound("REVUP", 3);
							return ResolveState("WheelCancelEquipment");
						}
					if(CountInv("WW_FragGrenadeSelected") >=1)
						{ 
							A_Print("Equipment Selected: \cdFrag Grenade"); 
							A_SetInventory("ProximityMineSelected",0);
							A_SetInventory("StunGrenadeSelected",0);
							A_SetInventory("LeechSelected",0);
							A_SetInventory("RevGunSelected",0);
							A_SetInventory("FragGrenadeSelected",1);
							A_StartSound("GRNPIN", 3);
							return ResolveState("WheelCancelEquipment");
						}
				return ResolveState(null);
				}
			goto Equipment_Toggle_Handler_Overlay;
		LeechBeam:
			SYNP WXYZWXYZWXYZ 1 BRIGHT;
			Loop;
		ThrowLeech:
			TNT1 A 0 {
				A_TakeInventory("ADSMode", 1);
				A_TakeInventory("UseEquipment", 1);
				PB_SetReloading(false);
			}
			TNT1 A 0 A_JumpIfInventory("PB_Dtech", 4, 2);
			TNT1 A 0 A_Print("Insufficient Demon Energy");
			Goto GoingToReady;
			TNT1 A 0 {
				A_SetInventory("Zoomed", 0);
				A_ZoomFactor(1.0);
			}
			TNT1 A 1 A_StartSound("SiphonActive", 3);
			SYNP KLMNO 1 A_WeaponOffset(0,32);
			TNT1 A 0 {
				A_StopSound(3);
				A_Overlay(-5, "LeechBeam");
			}
		HoldLeech:
			SYNP ABCDEF 2 {
				A_StartSound("SiphonHold",3,CHANF_LOOPING);
				A_FireBullets(0, 0, -1, 3, "SiphonPuff", FBF_NORANDOM|FBF_NOFLASH);
				A_TakeInventory("PB_Dtech", 4, TIF_NOTAKEINFINITE);
			}
			TNT1 A 0 A_JumpIf(CountInv("PB_Dtech") > 4 && PressingUser1(), "HoldLeech");
			TNT1 A 0 {
				A_StopSound(3);
				A_ClearOverlays(-5,-5);
				if(CountInv("PB_Dtech") < 4 && PressingUser1()) {
					A_Print("Insufficient Demon Energy");
				}
			}
			SYNP ONMLK 1;
			TNT1 A 0 {
				A_WeaponOffset(0,32);
				A_TakeInventory("UseEquipment", 1);
				A_TakeInventory("ToggleEquipment", 1);
			}
			TNT1 A 0 A_JumpIf(PressingUser1(), "UseEquipment");
			Goto GoingToReady2;
		ThrowStun:
			TNT1 A 0 {
				A_TakeInventory("ADSMode", 1);
				A_TakeInventory("UseEquipment", 1);
				PB_SetReloading(false);
			}
			TNT1 A 0 A_JumpIfInventory("PB_StunGrenadeAmmo", 1, 2);
			TNT1 A 0 A_Print("No Stun Grenades Left");
			Goto GoingToReady;
			TNT1 A 0 {
				A_SetInventory("Zoomed", 0);
				A_ZoomFactor(1.0);
			}
			STNG BCDEF 1;
			STNG F 1 Offset(-2,34);
			TNT1 A 0 A_StartSound("StunGrenadeArm", 2);
			STNG GIJJJIHGKLMNOP 1;
			
			HND1 I 1 A_StartSound("THRGRN", 1);
			TNT1 A 0 A_TakeInventory("PB_StunGrenadeAmmo", 1, TIF_NOTAKEINFINITE);
			HND1 J 1 A_FireProjectile("PB_ThrownStunGrenade",0,0,0,0,0,0);
			HND1 KLMNOPQ 1;
			TNT1 A 0 {
				A_TakeInventory("UseEquipment", 1);
				A_TakeInventory("ToggleEquipment", 1);
			}
			TNT1 A 0 A_JumpIf(PressingUser1(), "UseEquipment");
			Goto GoingToReady2;
			FireRevGun:
				TNT1 A 0 {
					A_TakeInventory("ADSMode", 1);
					A_TakeInventory("UseEquipment", 1);
				}
				TNT1 A 0 A_JumpIfInventory("PB_QuickLauncherAmmo", 1, 2);
				TNT1 A 0 A_Print("No Quick Launcher Missiles Left");
				stop;
				TNT1 A 0 {A_StartSound("revup", CHAN_AUTO, CHANF_OVERLAP);}
				RVCA ABCDEFGHIJK 1;
				RVCF AB 1;
			FiringRevGun:
				TNT1 A 0 {if (player.FindPSprite(PSP_WEAPON) && InStateSequence(player.FindPSprite(PSP_WEAPON).curstate, ResolveState("Deselect"))){return ResolveState("FireRevGunDeselect");} return ResolveState(null);}
				RVCF C 1 BRIGHT {
					A_AlertMonsters();
					A_TakeInventory("PB_QuickLauncherAmmo", 1, TIF_NOTAKEINFINITE);
					/*
					if(!FindInventory("PB_RevLauncherFireCount")){A_AlertMonsters();}
					if(CountInv("PB_RevLauncherFireCount")<3){A_GiveInventory("PB_RevLauncherFireCount",1);
					}else{A_TakeInventory("PB_QuickLauncherAmmo", 1);A_SetInventory("PB_RevLauncherFireCount",0);}
					*/
					A_FireProjectile("Alerter",0,0,-1,0);
					A_FireProjectile("DoomerRevenantSeeker3", random(4, -4), 0, -16, 8);
					A_StartSound("hellishmissle/fire",CHAN_AUTO, CHANF_OVERLAP, 0.5, pitch:frandom(0.95, 1.05));
					if(JustPressed(BT_USER1) && CVar.GetCVar("pb_toggle_launchers", player).GetBool()) {
						SetInventory("UseEquipment",1);
					}
				}
				RVCF D 1 BRIGHT {
					A_StartSound("hellishmissle/fire", CHAN_AUTO, CHANF_OVERLAP, 0.5, pitch:frandom(0.95, 1.05));
					A_FireProjectile("ShakeYourAss",0,0,0,0,0,0);
					A_FireProjectile("DoomerRevenantSeeker2", random(4, -4), 0, 16, 8);
					if(JustPressed(BT_USER1) && CVar.GetCVar("pb_toggle_launchers", player).GetBool()) {
						SetInventory("UseEquipment",1);
					}
				}
				RVCF EFG 1 BRIGHT {
					if(player.FindPSprite(PSP_WEAPON) && InStateSequence(player.FindPSprite(PSP_WEAPON).curstate, ResolveState("Deselect"))) {
						return ResolveState("FireRevGunDeselect");
					}
					if((JustPressed(BT_USER1) || FindInventory("UseEquipment")) && CVar.GetCVar("pb_toggle_launchers", player).GetBool()) {
						return ResolveState("FireRevGunFinish");
					}
					return ResolveState(null);
				}
				RVCF HI 1 {
					if(player.FindPSprite(PSP_WEAPON) && InStateSequence(player.FindPSprite(PSP_WEAPON).curstate, ResolveState("Deselect"))) {
						return ResolveState("FireRevGunDeselect");
					}
					if((JustPressed(BT_USER1) || FindInventory("UseEquipment")) && CVar.GetCVar("pb_toggle_launchers", player).GetBool()) {
						return ResolveState("FireRevGunFinish");
					}
					return ResolveState(null);
				}
				TNT1 A 0 A_JumpIf(CountInv("PB_QuickLauncherAmmo") > 0 && (PressingUser1() || CVar.GetCVar("pb_toggle_launchers", player).GetBool()), "FiringRevGun");
				goto FireRevGunFinish;
			FireRevGunFinish:
				TNT1 A 0 {
					if(CountInv("PB_QuickLauncherAmmo") < 1 && (PressingUser1() || CVar.GetCVar("pb_toggle_launchers", player).GetBool() && !FindInventory("UseEquipment"))) {
						A_Print("No Quick Launcher Missiles Left");
					}
					A_TakeInventory("UseEquipment", 1);
					A_TakeInventory("ToggleEquipment", 1);
				}
				RVCF BA 1;
				RVCA K 1 A_StartSound("revcyc", CHAN_AUTO, CHANF_OVERLAP);
				RVCA JIHGFEDCB 1;
				RVCA A 1 {
					A_TakeInventory("UseEquipment", 1);
					A_TakeInventory("ToggleEquipment", 1);
				}
				stop;
			FireRevGunDeselect:
				RVCA H 1 {
					A_TakeInventory("UseEquipment", 1);
					A_TakeInventory("ToggleEquipment", 1);
					A_StartSound("revcyc", CHAN_AUTO, CHANF_OVERLAP);
				}
				RVCA FDCB 1;
				stop;
		ThrowGrenade:
			TNT1 A 0 {
				A_StopSound(6);
				A_StopSound(CHAN_VOICE);
				A_TakeInventory("ADSMode", 1);
				A_TakeInventory("UseEquipment", 1);
				PB_SetReloading(false);
			}
			TNT1 A 0 A_JumpIfInventory("PB_GrenadeAmmo", 1, 2);
			TNT1 A 0 A_Print("No Frag Grenades Left");
			Goto GoingToReady;
			TNT1 A 0 {
				A_SetInventory("Zoomed", 0);
				A_ZoomFactor(1.0);
			}
			TNT1 A 0 A_Giveinventory("PlayerIsThrowingAGrenade",1);
			HNDF ABCDE 1 A_SetRoll(roll+2.0, SPF_INTERPOLATE);
			HNDF FGHI 1 {
				A_SetRoll(roll+2.0, SPF_INTERPOLATE);
				if(JustPressed(BT_USER1)) A_GiveInventory("UseEquipment",1);
				}
			TNT1 A 0 A_StartSound("OPNGRN",0);
			HNDF JKLMNOPQR 1 {
				A_SetRoll(roll+2.0, SPF_INTERPOLATE);
				if(JustPressed(BT_USER1)) A_GiveInventory("UseEquipment",1);
				}
			TNT1 A 0 A_JumpIfInventory("UseEquipment", 1, "TossGrenade");
			TNT1 A 1 A_SetRoll(roll-18.0);
			HND1 I 1 A_StartSound("THRGRN",0);
			HND1 J 1 {
				A_FireProjectile("PB_ThrownGrenade",0,0,0,0,0,0);
				A_TakeInventory("PB_GrenadeAmmo", 1, TIF_NOTAKEINFINITE);
				A_FireProjectile("Alerter",0,0,0,0,0,0);
			}
			HND1 KLMNOPQ 1 A_SetRoll(roll-5.0);
			TNT1 A 0 {
			A_SetRoll(0, SPF_INTERPOLATE);
			A_TakeInventory("UseEquipment", 1);
			A_TakeInventory("ToggleEquipment", 1);
			A_TakeInventory("PlayerIsThrowingAGrenade", 1);
			}
			TNT1 A 0 A_JumpIf(PressingUser1(), "UseEquipment");
			Goto GoingToReady2;
		TossGrenade:
			TNT1 A 1;
			HND1 RSTU 1 A_SetRoll(roll-1.5, SPF_INTERPOLATE);
			TNT1 A 0 {
				A_StartSound("THRGRN", 1);
				A_TakeInventory("PB_GrenadeAmmo", 1, TIF_NOTAKEINFINITE);
				A_FireProjectile("Alerter",0,0,0,0,0,0);
				A_FireProjectile("ThrownGrenade15", 0,0,0,-2,0,3);
			}
			HND1 VWXY 1 A_SetRoll(roll-1.5, SPF_INTERPOLATE);
			TNT1 A 0 {
				A_SetRoll(0);
				A_TakeInventory("PB_LockScreenTilt",1);
				A_TakeInventory("UseEquipment", 1);
				A_TakeInventory("ToggleEquipment", 1);
				A_TakeInventory("PlayerIsThrowingAGrenade", 1);
			}
			TNT1 A 0 A_JumpIf(PressingUser1(), "UseEquipment");
			Goto GoingToReady2;
		ThrowMine:
			TNT1 A 0 {
				A_TakeInventory("ADSMode", 1);
				A_TakeInventory("UseEquipment", 1);
				PB_SetReloading(false);
			}
			TNT1 A 0 A_JumpIfInventory("PB_ProxMineAmmo", 1, 2);
			TNT1 A 0 A_Print("No Proximity Mines Left");
			Goto GoingToReady;
			TNT1 A 0 {
				A_SetInventory("Zoomed", 0);
				A_ZoomFactor(1.0);
			}
			XPFF FEDCBA 1;
			XPFS B 4 A_StartSound("weapons/pbarm", 2);
			XHFF A 0 {
				A_StartSound("MINE002", 3);
				A_ThrowGrenade("PB_ThrownProxMine",4,11,1,0);
				A_TakeInventory("PB_ProxMineAmmo", 1, TIF_NOTAKEINFINITE);
			}
			XHFF MNOPQRSTUVWXYZ 1;
			TNT1 A 0 {
				A_TakeInventory("UseEquipment", 1);
				A_TakeInventory("ToggleEquipment", 1);
			}
			TNT1 A 0 A_JumpIf(PressingUser1(), "UseEquipment");
			Goto GoingToReady2;
	}
}